### ISSUE TITLE
SynthDef graph building fails under certain circumstances with additions of identical objects  

### ISSUE THREAD

**Issue by dkmayer** [supercollider/supercollider#5405] opened 2021-03-29 21:53 UTC
SC 3.11.2
OS 10.15.7

```
// (1) ok

(
{
	var x = SinOsc.ar(mul: 0.1);
	x
}.play
)

(
SynthDef(\test_1, {
	var x = SinOsc.ar(mul: 0.1);
	Out.ar(0, x)
}).play
)

// (2) silent !

(
{
	var x = SinOsc.ar(mul: 0.1);
	x + x
}.play
)


(
SynthDef(\test_2, {
	var x = SinOsc.ar(mul: 0.1);
	Out.ar(0, x + x)
}).play
)


// (3) again sound !!

(
{
	var x = SinOsc.ar(mul: 0.1);
	x * x
}.play
)

(
SynthDef(\test_3, {
	var x = SinOsc.ar(mul: 0.1);
	Out.ar(0, x * x)
}).play
)

// (4) and here also sound !
// result multiplied with 0.1 only to avoid loud output

(
{
	var x = SinOsc.ar();
	x + x * 0.1
}.play
)

(
SynthDef(\test_4, {
	var x = SinOsc.ar();
	Out.ar(0, x + x * 0.1)
}).play
)
```

The behaviour was initially detected with unexpected silence coming from Mix:

https://scsynth.org/t/help-for-incomprehensible-mix-behavior/3510

**Comment by jamshark70** [comment] 2021-03-30 03:57
Interesting optimizer edge case.

x is a unique instance of `BinaryOpUGen(*)` (inputs: SinOsc and 0.1).

This one instance is going into both inputs of a `BinaryOpUGen(+)` -- let's call it y.

optimizeToMulAdd looks for a `+` operator, one of whose inputs is a `*` operator (checking the left input first). We match that condition.

The optimization is valid only if x's result is not used anywhere else: `this.descendants.size == 1`. We *should* fail this test because x is used in two separate inputs.

The problem is that `descendants` is a Set of *UGens*. x feeds into two inputs, but they belong to the same UGen, so y is represented only once -- the set size is 1 -- so the optimizer proceeds to delete x, and replace y by a MulAdd.

The MulAdd inputs should be SinOsc, 0.1 and x -- but x has been deleted. So now the MulAdd is invalid and disappears from the graph -- and Out has no source, so it disappears from the graph too.

I guess the proper fix for this case would be to count inputs rather than UGens as descendants. That could have a ripple effect, requiring changes to optimization and to the topo sort.

Or perhaps `descendants` could be a Dictionary, adding 1 for each input where the UGen appears. Then the topo sort could use `descendants.keys` (should be the same as we have now), and the optimizer could use `descendants.sum` instead of `descendants.size`. That might be a little slower.

**Comment by jamshark70** [comment] 2021-03-30 04:34
Here are two more reproducers, for different optimizations, demonstrating that a fix local to optimizeToMulAdd would not be sufficient. It really has to be fixed in the descendants collection.

```
(
SynthDef(\optimizeToSum4SameProblem, {
	var x = SinOsc.ar([100, 200, 300]).sum;
	Out.ar(0, x + x);
}).dumpUGens;

SynthDef(\optimizeAddNegSameProblem, {
	var x = SinOsc.ar(100).neg;
	Out.ar(0, x + x);
}).dumpUGens;
)

optimizeToSum4SameProblem
[ 0_SinOsc, audio, [ 100, 0.0 ] ]
[ 1_SinOsc, audio, [ 200, 0.0 ] ]
[ 2_SinOsc, audio, [ 300, 0.0 ] ]

optimizeAddNegSameProblem
[ 0_SinOsc, audio, [ 100, 0.0 ] ]
```

**Comment by smrg-lm** [comment] 2021-04-12 23:27
Since they are all binaryop optimizations that fail under identity, wouldn't it be enough to check that inputs a and b are not the same object and return nil as first test in each function?

**Comment by smrg-lm** [comment] 2021-04-14 06:32
I was investigating this matter for some hours now...

For optimizeToSum4, optimizeToMulAdd, optimizeAddNeg the fix could be to check if a !== b to perform buildSynthDef.removeUGen, the issue is that the wrapper op ugen should not be removed when a === b because the chain cuts for the other branch. In this way, the results are also optimized following the pre-existing logic. 

Note: optimizeSub is working fine because the case passes through optimizeAddNeg immediately after.

```
// optimizeToSum4
x = SinOsc.ar([100, 200, 300]).sum();
x + x

['0_SinOsc', 'audio', [100, 0.0]]
['1_SinOsc', 'audio', [200, 0.0]]
['2_SinOsc', 'audio', [300, 0.0]]
['3_Sum3', 'audio', ['0_SinOsc', '1_SinOsc', '2_SinOsc']]
['4_Sum4', 'audio', ['0_SinOsc', '1_SinOsc', '2_SinOsc', '3_Sum3']]
['5_Out', 'audio', [0, '4_Sum4']]
```

// optimizeToMulAdd
x = SinOsc.ar(100) * 0.1;
x + x

['0_SinOsc', 'audio', [100, 0.0]]
['1_*', 'audio', ['0_SinOsc', 0.1]]
['2_MulAdd', 'audio', ['0_SinOsc', 0.1, '1_*']]
['3_Out', 'audio', [0, '2_MulAdd']]

// optimizeAddNeg
x = SinOsc.ar(100).neg;
x + x

['0_SinOsc', 'audio', [100, 0.0]]
['1_neg', 'audio', ['0_SinOsc']]
['2_-', 'audio', ['1_neg', '0_SinOsc']]
['3_Out', 'audio', [0, '2_-']]

// optimizeSub (the same without the check)
x = SinOsc.ar(100).neg;
x - x

['0_SinOsc', 'audio', [100, 0.0]]
['1_-', 'audio', ['0_SinOsc', '0_SinOsc']]
['2_Out', 'audio', [0, '1_-']]
```

**Comment by jamshark70** [comment] 2021-04-19 14:33
> Since they are all binaryop optimizations that fail under identity, wouldn't it be enough to check that inputs a and b are not the same object and return nil as first test in each function?

That would be an expedient way, sure, and less risky than messing around with the internal data structures. There may not be a need to make 'descendants' formally 100% correct at this time, if we detect these edge cases using a simple identity check.

> It may need another pair of eyes, things get really messy down there.

Do you have a branch I could try out?

**Comment by smrg-lm** [comment] 2021-04-20 16:46
@jamshark70 I made a pull request with the patch. I think is less risky too. To revisit the implementation is possible but it touches many related details and requires some work.

**Comment by JordanHendersonMusic** [comment] 2024-08-17 18:03
The above PR fixes this issue.

**Closed by JordanHendersonMusic** 2024-08-17 18:03 UTC
Labels: bug, comp: class library
