### ISSUE TITLE
scide: command not found, raspbian buster install issue

### ISSUE THREAD

**Issue by socalledsound** [supercollider/supercollider#4517] opened 2019-07-30 19:46 UTC
## Environment

* SuperCollider version: 3.9.3
* Operating system: raspbian buster

Trying to install scide on Raspberry Pi 4.
After what seems like a successful build I get "scide: command not found".
scide is created as an executable during the build process.
sclang works.
there is no supercoll;ider icon added to the start menu.

Any insight or suggestions would be appreciated!

**Comment by snappizz** [comment] 2019-07-31 01:04
what are the steps you used to install SC?

please try to fill out the issue template if possible, since it's there to ask you to share steps to reproduce etc.

**Comment by socalledsound** [comment] 2019-08-02 14:30
I used the building for raspberry pi page from this repo to install, the build succeeded.
one maybe salient error message was that when installing qt, qtwebengine5-dev was not found.
I noticed that several other people had had that problem as well and there had been some talk about making that an optional dependency or something.  
fwiw I did the same build a few days ago on an r pi 3 (debian stretch, not buster) and it works flawlessly.  
thanks!

**Comment by redFrik** [comment] 2019-08-02 14:37
the build instructions for scide are a bit outdated and stuck with 3.9.3+stretch until the qtwebengine issue is fixed (you can build 3.10 for headless without any issues though).
one thing to try if you can't wait and need 3.9.3+buster is to `sudo apt-get install qttools5-dev`

**Comment by socalledsound** [comment] 2019-08-02 16:45
thanks for this!  will try later when I'm at that machine again.  

one quick dumb question, if I'm running headless is there a command to send the contents of a document to the sc server?  for instance if I use an editor like vim or nano to write a doc can I do something like 
sclang myDoc.txt

as I would with bash?

I know there's an emacs client and maybe a vim client but haven't tried to muddle through that process yet.

thanks in advance

**Comment by redFrik** [comment] 2019-08-02 21:50
sure, you can run code from a document at startup with `sclang mycode.scd`.
or you start sclang headless with `sclang`and that'll give you a readline prompt from where you can run other code documents with `"folder/someothercode.scd".load`

**Comment by jamshark70** [comment] 2019-08-02 23:25
> until the qtwebengine issue is fixed

[scide] [sclang] Make QtWebEngine optional #4328 has been merged, by the way, it's done.

**Closed** 2020-05-05 01:31 UTC
Labels: bug, comp: build, os: Linux, waiting for information
