### ISSUE TITLE
adding supercollider 3.8/3.9 ? - stable - to latest version of debian package manager - apt-get

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [supercollider/supercollider#3385] opened 2018-01-04 15:18 UTC
## adding supercollider 3.8/3.9 ? - stable - to latest version of debian package manager - apt-get

# greetings

latest version of debian only features 3.7 in the default package manager. I would like to recommend you guys to

- <i>add the version 3.8/3.9 to debian package manager apt-get</i>

<b><sub>kind regards</sub></b>

**Comment by snappizz** [comment] 2018-01-04 15:20
hi tiago, this is currently in progress. sorry we have been so slow with this.

closing as duplicate of #2917.

**Closed by snappizz** 2018-01-04 15:20 UTC

**Comment by tiagomoraismorgado88** [comment] 2018-01-04 15:48
i see. thank you so much
