### ISSUE TITLE
sclang: Bizarre interaction between exceptions, Arrays and return values in nested calls

### ISSUE THREAD

**Issue by wasamasa** [supercollider/supercollider#3652] opened 2018-04-07 23:46 UTC
```sc
var x = { |in| in };
var y = { |in| try { ["foo".xxx] } { |err| in } };
var z;

y.(42).postln; // prints 42
x.(y.(42)).postln; // prints empty array instead of 42
z = y.(42); x.(z).postln; // prints 42
exit(0);
```

I use the last line as workaround. What is going on here?

OS: Arch Linux.
Reproducible with "sclang 3.9.2" and "sclang 3.9dev (Built from branch 'develop' [2b6c724d5])".
Plugins: No plugins whatsoever.

**Comment by brianlheim** [comment] 2018-04-08 00:27
Huh, this is a pretty interesting bug in the interpreter. At a very crude glance, it looks like when there's an exception thrown the stack isn't wound back up properly, and a partially constructed object is accidentally passed:

```supercollider
x = _.postln;
y = { |i| try { [3, 3.meow] } { i } };
x.(y.(42).postln).postln; // prints 42, then [ 3 ]
```

Other notes:
- it's not due to tail call optimization

**Comment by wasamasa** [comment] 2018-04-08 09:42
At least it's not TCO, the actual code exhibiting the bug relies on it being enabled.

**Comment by jamshark70** [comment] 2018-04-08 10:54
Or:

```
x = _.postln;
y = { |i| try { [3, 3.meow] } { i } };
x.(y.(42).debug("y result")).debug("x result"); // prints 42, then [ 3 ]

y result: 42
x result: [ 3 ]
-> [ 3 ]
```

The `x = _.postln` never posts.

It does look like some kind of stack corruption.

**Comment by wasamasa** [comment] 2018-04-18 20:34
Do any of you have pointers where to start digging?

**Comment by brianlheim** [comment] 2018-04-18 20:37
The compiler code is in lang/LangSource. I would start by stepping through the interpreter's execution of the bytecodes of the example you posted

**Comment by brianlheim** [comment] 2018-08-31 07:01
Duplicate of #232

**Closed by brianlheim** 2018-08-31 07:01 UTC
Labels: comp: sclang
