### ISSUE TITLE
With gcc >= 4.9 Release and RelWithDebInfo builds SC broken at startup. Observed on 32-bit machines on Windows, Linux i686 and Raspbian (ARM)

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1450] opened 2015-05-05 09:50 UTC
Failure during startup and *initClassTree

```
init_OSC
empty
compiling class library...
    NumPrimitives = 690
    compiling dir: 'C:\Program Files (x86)\SuperCollider-3.7alpha0\SCClassLibrary'
    pass 1 done
    numentries = 812407 / 11206560 = 0.072
    5048 method selectors, 2220 classes
    method table size 6155080 bytes, big table size 44826240
    Number of Symbols 11532
    Byte Code Size 347777
    compiled 315 files in 0.41 seconds

Info: 2 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
ERROR: Message 'atIdentityHash' not understood.
RECEIVER:
Instance of Array {    (0a1f08f0, gc=08, fmt=01, flg=00, set=03)
  indexed slots [4]
      0 : nil
      1 : nil
      2 : nil
      3 : nil
}
ARGS:
class AppClock (0a05c9a0) {
  instance variables [19]
    name : Symbol 'AppClock'
    nextclass : instance of Meta_Archive (09F154E0, size=19, set=5)
    superclass : Symbol 'Clock'
    subclasses : nil
    methods : nil
    instVarNames : nil
    classVarNames : instance of SymbolArray (0A05CA60, size=1, set=3)
    iprototype : nil
    cprototype : instance of Array (0A05CAE0, size=1, set=3)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 41
    classFlags : Integer 0
    maxSubclassIndex : Integer 41
    filenameSymbol : Symbol 'C:\Program Files (x86)\SuperCollider-3.7alpha0\SCClassLibrary\Common\Core\Clock.sc'
    charPos : Integer 980
    classVarIndex : Integer 332
}
CALL STACK:
    DoesNotUnderstandError:reportError   0a1f0df0
        arg this = <instance of DoesNotUnderstandError>
    Nil:handleError   0a1f0d90
        arg this = nil
        arg error = <instance of DoesNotUnderstandError>
    Thread:handleError   0a1f0d30
        arg this = <instance of Thread>
        arg error = <instance of DoesNotUnderstandError>
    Object:throw   0a1f0cd0
        arg this = <instance of DoesNotUnderstandError>
    Object:doesNotUnderstand   0a1f09b0
        arg this = [*4]
        arg selector = 'atIdentityHash'
        arg args = [*1]
    Set:includes   0a1f0950
        arg this = <instance of IdentitySet>
        arg item = <instance of Meta_AppClock>
    Meta_Class:initClassTree   0a1f0770
        arg this = <instance of Meta_Class>
        arg aClass = <instance of Meta_AppClock>
        var implementsInitClass = nil
    Process:startup   0a1f0710
        arg this = <instance of Main>
        var time = nil
    Main:startup   0a1ef3d0
        arg this = <instance of Main>
        var didWarnOverwrite = false
^^ The preceding error dump is for ERROR: Message 'atIdentityHash' not understood.
RECEIVER: [ nil, nil, nil, nil ]
```

All the rest of these errors here are because the class tree did not initialize correctly and there are variables that should have been set.

```
ERROR: Message 'volume' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
    DoesNotUnderstandError:reportError   0a1f0290
        arg this = <instance of DoesNotUnderstandError>
    Nil:handleError   0a1f0350
        arg this = nil
        arg error = <instance of DoesNotUnderstandError>
    Thread:handleError   0a1f03b0
        arg this = <instance of Thread>
        arg error = <instance of DoesNotUnderstandError>
    Object:throw   0a1f04d0
        arg this = <instance of DoesNotUnderstandError>
    Object:doesNotUnderstand   0a1f0f10
        arg this = nil
        arg selector = 'volume'
        arg args = [*0]
    Meta_ScIDE:defaultServer_   0a1f05f0
        arg this = <instance of Meta_ScIDE>
        arg server = nil
    Meta_ScIDE:handshake   0a1f07d0
        arg this = <instance of Meta_ScIDE>
    Function:defer   0a1f0b10
        arg this = <instance of Function>
        arg delta = nil
    Meta_ScIDE:connect   0a1f0c10
        arg this = <instance of Meta_ScIDE>
        arg ideName = "SCIde_4948"
    Process:interpretCmdLine   0a1f1150
        arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'volume' not understood.
RECEIVER: nil


ERROR: Message 'sched' not understood.
RECEIVER:
   nil
ARGS:
   Integer 0
Instance of Routine {    (0a1f2130, gc=10, fmt=00, flg=00, set=05)
  instance variables [27]
    state : Integer 0
    func : instance of Function (0A1F2070, size=2, set=3)
    stack : instance of Array (0880B6A0, size=0, set=9)
    method : nil
    block : nil
    frame : nil
    ip : RawPointer 00000000
    sp : RawPointer 00000000
    numpop : Integer 0
    receiver : nil
    numArgsPushed : Integer 0
    parent : nil
    terminalValue : nil
    primitiveError : Integer 0
    primitiveIndex : Integer 0
    randData : instance of Int32Array (0A1EF1F0, size=4, set=3)
    beats : Float 0.423379   A713D5A0 3FDB18A4
    seconds : Float 0.423379   A713D5A0 3FDB18A4
    clock : instance of Meta_SystemClock (0A04FAA0, size=19, set=5)
    nextBeat : nil
    endBeat : nil
    endValue : nil
    environment : nil
    exceptionHandler : nil
    threadPlayer : nil
    executingPath : nil
    oldExecutingPath : nil
}
CALL STACK:
    DoesNotUnderstandError:reportError   0a1f04d0
        arg this = <instance of DoesNotUnderstandError>
    Nil:handleError   0a1f0590
        arg this = nil
        arg error = <instance of DoesNotUnderstandError>
    Thread:handleError   0a1f03b0
        arg this = <instance of Thread>
        arg error = <instance of DoesNotUnderstandError>
    Object:throw   0a1f0350
        arg this = <instance of DoesNotUnderstandError>
    Object:doesNotUnderstand   0a1f1b50
        arg this = nil
        arg selector = 'sched'
        arg args = [*2]
    Meta_AppClock:sched   0a1f1bb0
        arg this = <instance of Meta_AppClock>
        arg delta = 0
        arg item = <instance of Routine>
    Meta_Clock:play   0a1f1c10
        arg this = <instance of Meta_AppClock>
        arg task = <instance of Routine>
    Stream:play   0a1f2010
        arg this = <instance of Routine>
        arg clock = <instance of Meta_AppClock>
        arg quant = nil
    Meta_ScIDE:processUrl   0a1f1e50
        arg this = <instance of Meta_ScIDE>
        arg urlString = nil
        arg doneAction = <instance of Function>
        var url = <instance of URI>
        var brokenFunc = <instance of Function>
    Meta_ScIDE:openHelpUrl   0a1f1d90
        arg this = <instance of Meta_ScIDE>
        arg url = nil
    Meta_HelpBrowser:goTo   0a1f1d30
        arg this = <instance of Meta_HelpBrowser>
        arg url = nil
        var ideClass = <instance of Meta_ScIDE>
    Meta_HelpBrowser:goHome   0a1f1cd0
        arg this = <instance of Meta_HelpBrowser>
    Process:interpretCmdLine   0a1f19f0
        arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'sched' not understood.
RECEIVER: nil
```

edited by @crucialfelix

**Comment by bagong** [comment] 2015-05-10 10:07
The problem goes away when compiler optimizations are switched off with -O0. This also enhances sclang stability. The frequent crashes triggered by typing and dragging the mouse are reduced significantly (but not gone)

**Comment by bagong** [comment] 2015-05-22 09:49
Ubuntu 15.04 which uses gcc-4.9 is not affected

**Comment by timblechmann** [comment] 2015-05-24 11:59
bugs like this are not related to the toolchain, but most likely due to a bug in the code. a backtrace might help: start a debugger, attach it to the crashing process, post the backtrace. line numbers might help. speculating doesn't

**Comment by xavriley** [comment] 2015-11-02 10:19
This probably shouldn't have the `os:Windows` tag given that it's about Ubuntu...

**Comment by jamshark70** [comment] 2015-11-02 10:54
@xavriley look at the file paths in the initial error dump, with backslashes. This *is* about Windows.

**Comment by xavriley** [comment] 2015-11-02 11:00
Sorry my bad, stupid mistake on my part. The MinGW in the issue title is also a giveaway!

That said, I came to this issue because the same error is happening on the Raspbian build of SuperCollider which tallies with Tim's comment about this probably being a bug in the code rather than the toolchain. If I get time to investigate that I'll report back here.

**Comment by gogobd** [comment] 2015-11-02 14:36
Hello, every 01! I was having the same issue with the current raspbian (Jessie): SuperCollider installed via apt-get is currently not working. It would be great to have a working package "shipped" with Jessie.

**Comment by crucialfelix** [comment] 2015-11-02 17:03
This is strange.

```supercollider
    Object:doesNotUnderstand   0a1f09b0
        arg this = [*4]
        arg selector = 'atIdentityHash'
        arg args = [*1]
    Set:includes   0a1f0950
        arg this = <instance of IdentitySet>
        arg item = <instance of Meta_AppClock>
    Meta_Class:initClassTree   0a1f0770
        arg this = <instance of Meta_Class>
        arg aClass = <instance of Meta_AppClock>
        var implementsInitClass = nil
```

Array certainly does understand atIdentityHash

```supercollider
	// IdentitySet support
	atIdentityHash { arg argKey;
		_Array_AtIdentityHash
		^this.primitiveFailed
	}
```

and even if that primitive failed it would throw a primitive failed, not a does not understand.

and why would changing the compiler optimization settings change this ?  something is rotten.

**Comment by gogobd** [comment] 2015-11-04 09:51
This bug is labeled "os: Windows", but I have the same Problem on plain Raspbian Jessie.

**Comment by crucialfelix** [comment] 2015-11-04 19:01
Fredrik mentioned last night that he's seen this quite a bit, in particular on Raspbian. It has something to do with the order that the class files are processed in. 

On different OS they are read differently. If you change the folder structure then sometimes it works.

Not that that is a solution, its more of a clue to the problem.

**Comment by telephon** [comment] 2015-11-05 19:11
```
compile done
ERROR: Message 'atIdentityHash' not understood.
RECEIVER:
Instance of Array {    (0a1f08f0, gc=08, fmt=01, flg=00, set=03)
```
This seems as if the ```startup``` method were called before the method table is fully initialized.

**Comment by crucialfelix** [comment] 2015-11-05 19:29
yeah, it looks really strange. but it is a runtime error during class init.

maybe some class like Document does not exist and its causing something strange by being nil.

**Comment by telephon** [comment] 2015-11-05 20:18
In the above case, nil is not involved.

**Comment by gogobd** [comment] 2015-11-16 10:23
I just re-built SuperCollider from source (following http://supercollider.github.io/development/building-raspberrypi.html with deviations) and I can confirm: a "Release" build crashes with 'atIdentityHash', a "Debug" build works.
Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux
gcc (Raspbian 4.9.2-10) 4.9.2

**Comment by telephon** [comment] 2015-11-16 16:48
If there is any way to call ```Process.startup``` a little bit later.


The method is called here in PyrLexer, if I see this correctly:

```
void compileSucceeded();
void compileSucceeded()
{
	compiledOK = !(parseFailed || compileErrors);
	if (compiledOK) {
		compiledOK = true;

		compiledOK = initRuntime(gMainVMGlobals, 128*1024, pyr_pool_runtime);

		if (compiledOK) {
			VMGlobals *g = gMainVMGlobals;

			g->canCallOS = true;
			//++g->sp; SetObject(g->sp, g->process);
			//runInterpreter(g, s_hardwaresetup, 1);

			++g->sp; SetObject(g->sp, g->process);
			runInterpreter(g, s_startup, 1);
			g->canCallOS = false;

			schedRun();
		}
		flushPostBuf();
	}
}
``

**Comment by crucialfelix** [comment] 2015-11-16 22:04
ok, why would that make a difference ?

**Comment by passivist** [comment] 2015-11-18 09:18
I had this problem on a variety of Linux Distros (xubuntu + lubuntu 15.10 and Debian 8.2). All of them 32-bit on a Lenovo G50-70. The problem disappeared when I installed a 64-bit xubuntu 14.04.

So maybe the problem could have something to do with 32-bit?

**Comment by muzikantonk** [comment] 2015-12-10 15:16
I'm experiencing this issue in Raspbian Jessie on my Raspberry Pi Zero. Really want to get SC up and running on the little guy. Any suggestions on what to try?

**Comment by miczac** [comment] 2015-12-11 02:52
FWIW, pre-packed SC 3.6.6 on Jessie on the original R-Pi has the same problem. 
I don't think that's R-Pi model specific.

**Comment by miczac** [comment] 2015-12-13 19:28
@telephon, delaying didn't change anything. So I started poking around and can't even bisect since in my setup *) I just keep getting the error. 
*)  
Linux scdeb 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) i686 GNU/Linux

**Comment by miczac** [comment] 2015-12-13 19:35
compiler issue?

**Comment by miczac** [comment] 2015-12-15 04:28
BTW, title of this issue should be gcc >= 4.9. ;)
Stepping back to gcc 4.8.4 seems to be working on a Debian  8  like described above.
On Raspbian Jessie  I seem to have trouble to exchange the compiler properly, 
because it's stalling after some while when compiling. Also when returning to 4.9.
I've yet to find out what's wrong.

**Comment by wtkns** [comment] 2016-01-18 19:44
i was able to get 'Release' to build without this error on arch, gcc 5.3.0-3  using fredrik's code from the list, http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/sc-master-desktop-headless-on-rpi2-with-raspbian-jessie-tt7622564.html

particularly:
`sed -i 's/UL, numSubclasses/UL, (long unsigned int)numSubclasses/g' lang/LangSource/PyrObject.cpp`

**Comment by gogobd** [comment] 2016-01-26 05:14
I just built 3.7alpha1 on my raspberry pi, debug build works, release doesn't, due to the issues described here.

**Comment by the-drunk-coder** [comment] 2016-02-02 23:48
Same error here, on raspi 2. 

When i try to start sclang without x, i get a segfault. In scide, i get the errors described above.

I tried using Frederik's fix, but it doesn't change anything at all. If you change it to
```
sed -i 's/ULL, numSubclasses/ULL, (long unsigned int)numSubclasses/g' lang/LangSource/PyrObject.cpp
```
then there's actually one typecast added, but that didn't fix anything for me. 

Trying with the beta1 now ...

**Comment by the-drunk-coder** [comment] 2016-02-03 01:01
Beta1 isn't working as well.

**Comment by gogobd** [comment] 2016-02-03 11:58
For the record: I just compiled a Release build of SuperCollider on a Raspberry Pi with gcc-4.8 (https://github.com/supercollider/supercollider/tree/3.7.0) (2016-01-18) As the title of this issue suggests the problems just occur with gcc>=4.9

**Comment by scztt** [comment] 2016-02-03 17:37
This is somewhat orthogonal but - as far as I know, GCC is not a great compiler to be using for ARM regardless of the version. Last I checked, it's not at the point where it's producing fully ARM-optimized code anyway, and there are enough code gen bugs to muddy the waters for issues like this. What about grabbing a trial license of the official ARM toolchain and building 3.7.0 binaries for the major raspberry distributions? A drop-in SuperCollider, even if it only worked on a narrow range of distributions / circumstances, would be absolutely huge for anyone doing raspberry pi work, and building with the ARM toolchain would probably net a significant performance boost. Trials versions of the toolchain only last 30 days I think, but we've got enough people to make that stretch for quite a while. :)

**Comment by miczac** [comment] 2016-02-05 03:59
@scztt - I am just wondering, the OP reported this problem from a Windows system.
nevertheless, you're having a point here - would be worth a shot, IMHO.

**Comment by fcuro** [comment] 2016-03-16 15:17
Perhaps a clue?
Ubuntu difficulty: 1 toshiba laptop and 1 dell desktop, both running 15.10.
SC runs on the laptop and not the desktop.
'system info' shows:
ubuntu 15.10 ... (x86-64) on the laptop (works)
but
ubuntu 15.10 ... (i686) on the desktop (doesn't)
----------
question: compiling from source with make, how to switch off compiler optimizations (a suggested above)?

**Comment by fcuro** [comment] 2016-03-16 17:14
compiling with CMakeCache.txt altered to say 
... CMAKE_C_FLAGS:STRING=-O0
produces a new build of 7.0 with the same startup error messages.

**Comment by miczac** [comment] 2016-03-16 17:36
what compiler version are you using? (see above)

**Comment by bagong** [comment] 2016-03-16 18:53
I think you should make the settings build type (configuration, Release/Debug) specific. If you didn't specify a build type, you get the default, which is RelWithDebInfo. Look out for variables like these:

CMAKE_CXX_FLAGS_RELEASE
CMAKE_CXX_FLAGS_RELWITHDEBINFO
CMAKE_C_FLAGS_RELEASE
CMAKE_C_FLAGS_RELWITHDEBINFO

Pick the ones that fit your case (your CMAKE_BUILD_TYPE) and set them to -O0 -DNDEBUG for the sledgehammer method ;)

Would be great if this problem could be fixed somehow, it moved from a niche problem into something pretty mainstream... If I knew how to approach it I'd invest a bit of time. Not being able to build Windows with 4.9.2 is a major drawback, but now the linux distros (incl. ARM) are also getting there (while Windows is heading to gcc 5.3 ;) )

**Comment by fcuro** [comment] 2016-03-16 22:05
miczac:
gcc --version
gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
--------
bagong,
I don't know whether the DEBUG stuff's output would run slower(?) -- 
or is that only if you put the results through a debugger afterwards.
---------
Maybe I'll go compile csound instead.... Patience; I want patience & I want it now!
(Thanks for suggestions!)

**Comment by bagong** [comment] 2016-03-16 22:58
To me you sounded like you just wanted a build you could use. Have you tried what I suggested?

And you might want to try this:

http://lmgtfy.com/?q=gcc+optimization+ndebug

Best
.r.

**Comment by fcuro** [comment] 2016-03-16 23:39
I just did, time for a long nap... and looking through the terminal output, lots of 'warning, blah blah is depreciated', but actually 

It worked!!!! 
---
(Thanks. I expect the actual dsp stuff runs fast enough, & it was the sclang routines that were fnurgled up anyway!)

**Comment by bagong** [comment] 2016-03-16 23:45
Well, if you're on gcc 5.2, that's pretty interesting and edgy ;) ! When I tried with gcc 5.3 on Windows some time ago, the IDE wouldn't even come up ;)

**Comment by fcuro** [comment] 2016-03-17 03:37
I also wonder if this might have (I'm not going to try it, but someone may want to) 
worked with only these two lines changed in CMakeCache.txt :
CMAKE_C_FLAGS:STRING=-O0
_and_
CMAKE_CXX_FLAGS:STRING=-O0
?
if the significant thing was to get rid of mistaken optimizations from any compiler used(?)

**Comment by bagong** [comment] 2016-03-17 08:58
@fcuro, if I am not wrong, those settings you wonder about would have been overwritten by the more specific build type related ones. 

Yes, creating a debug build does take out the optimizations, but it didn't sound like you wanted to debug. If you just want to use SC, you don't want to be burdened with a very slow install of several hundred MB that will crash a loooot easier than a release build.

If I am not mistaken, "-DNDEBUG" does not trigger a debug build, rather to the opposite, it switches off *some* mechanisms in the code that can play a role in debugging (Google can help). 

The -O settings are not architecture specific. Even if it is true that this problem only exists on 32-bit systems the problem is likely to be a different one.

Note, all this is not about *solving* the problem, but just about finding workarounds in situations where you have no other choice. I guess to help you on with your particular needs, you should state with quite a bit of detail, what kind of systems you are using, why you use a different compiler than the one provided by the distribution, how you manage to mix different architectures on one system, and you should post the errors you see.

**Comment by fcuro** [comment] 2016-03-17 14:41
Hmm, I see... Certainly I can be mistaken; it seems to be one of the things I do best. Since I had the debugger-fodder distinction backasswards, I've got no idea why DNDEBUG would help.

Something in those mechanisms it switches off may be befurngling the connections between different modules in the result?

The problem wouldn't be with the 32-bit architecture -- but with what the compiler does trying to optimise code for it? [It's the standard version with ubuntu 15.10 at the moment, by the way.]

How the compiler keeps track of addresses? -- If a class can't find the right location for classes it needs (as does seem to be what's making the normal code not work), what the compiler has done to specify the address (whether for a 64-bit machine or a 32 bitter with some 64-bit extras) ought to be a key place to look. Something about the difference between a 64 bit address and a 32 bit?

Wikipedia (re i686) has it that:
"Some techniques first used in the x86 space in the P6 core include:
...
    PAE and wider 36-bit address bus to support 64 GB of physical memory (the linear address space of a process was still limited to 4 GB)."
so maybe the optimizations stumble in how they deal with that on a machine with less than 4G?

Thanks much for your help!

**Comment by bagong** [comment] 2016-03-17 17:32
Ah, sorry, I thought Ubuntu was still on 4.9, my bad... Hmm, after rereading the thread I should maybe adjust the title: >= 4.9 32-bit only? Unfortunately I cannot try it out on Windows as the 64-bit MinGW build doesn't get through....

**Comment by bagong** [comment] 2016-03-19 01:04
I think I got a significant step further with this, and would appreciate a lot comments, as it is quite relevant for the Windows version of the upcoming release:

As I don't understand of the technical implications of this kind of problem, and I also do not understand how using gdb could help here (I am happy to press buttons if somebody tells me what to do). So I tried a brute force approach.

- First I found that the error also does not occur with -O1, but it does with -O2
- Then I kind of bisected the flags that -O2 adds to -O1, and after quite some time I arrived at a single flag: -fstrict-aliasing. If I add -fno-strict-aliasing to the c- and cxx-flags it even works with -O3, so one can keep the default flags set by cmake and just add -fno-strict-aliasing.

At that point I have two questons:

- do people agree that it is better to use gcc/MinGW 4.9 with that flag, rather than 4.8 for the SC build? The two considerations here: a) Qt uses 4.9 b) somewhere I read using the strict aliasing optimization with code that seems to have issues in that respect isn't recommendable anyways (msvc and clang seem not to use strict-aliasing).
- how should I add that flag to the build? I take it that it should be there for anybody who tries to compile with MinGW, but which scope should I define? Just MinGW 32-bit, compiler-version from 4.9 upwards, or more generic, like generally for MinGW (and MSYS), or maybe even GCC in general?

Thanks for input!

**Comment by jamshark70** [comment] 2016-03-19 04:31
That's a huge finding!

I just glanced over http://cellperformance.beyond3d.com/articles/2006/06/understanding-strict-aliasing.html -- enough to know that I'm in no position to offer any advice on compiler settings or C++ tweaks.

If I had to guess, I'd say that the dodgy aliasing is occurring in the part of sclang that builds the method lookup table. I suppose it's theoretically possible for it to be in the method lookup code, but I would be very surprised if so, because the former is a complex process while the latter needs to be streamlined for performance (as simple as possible). So I'd look in the former area first (though I admit I would have no idea what to look for, apart from pointers with different types).

**Comment by jamshark70** [comment] 2016-03-19 08:27
https://github.com/supercollider/supercollider/blob/master/lang/LangSource/PyrObject.cpp#L1172

```
void buildBigMethodMatrix()
```

Start there, perhaps.

**Comment by bagong** [comment] 2016-03-19 11:03
You are talking to me, right? I would be great, if somebody looked into that, that actually understood the underlying code ;)
I've since tried to do one more thing that seems rational. Have gcc tell, where it thinks problems with strict aliasing might occur. There is a warning dedicated to this: -Wstrict-aliasing which can be set to different levels of precision. On the highest level (3, few wrong positives, likely many cases missed) I don't see a reference to sclang. On the lowest level (1 many wrong positives, little missed) there is a lot referring to sclang.  And a lot referring to boost asio and interprocess, quite a bit Windows specific, but much of it generic too.

The output of -Wstrict-aliasing=3 is here:

https://gist.github.com/bagong/0b7edf01117ffc55bda2

The output of -Wstrict-aliasing=1 is here:

https://gist.github.com/bagong/7787e8a383cb55c9ecda

**Comment by jamshark70** [comment] 2016-03-19 11:21
I'm talking to any dev who knows enough about C++ aliasing rules to review the code competently. I'm guessing that's maybe Tim and nobody else :p

**Comment by bagong** [comment] 2016-03-19 11:24
Hahaha, I had similar thoughts ;)

This seems to be a quite far reaching issue, outside of the scope of 3.7. I would still like to keep this question in sight as well:

For the Windows 3.7 release, is it better to build with MinGW 4.8 and the given compiler flags, or (which I strongly tend to) use MinGW 4.9.2 and add -fno-strict-aliasing?

**Comment by jamshark70** [comment] 2016-03-19 14:51
As for compiler flags, I suppose if "no-strict-aliasing" is good enough for Linus Torvalds, it could be good enough for us. http://lkml.org/lkml/2003/2/26/158 -- at least temporarily. IMO losing an optimization is less objectionable than the software not working at all.

**Comment by bagong** [comment] 2016-03-19 16:44
Yea, from the bit I vaguely understand in those discussions it seems that even people who mutually respect each other as being in the know can come to opposite conclusions.
@jamshark70  I tried to step through the code from that starting point on you suggested. It's a faar way, and most goes through boost land. The problem I have is that you can only step in debug mode, but in debug mode the error doesn't occur (even if you combine -O3 and -g). So I never get to the spot where it actually breaks... If you have an idea how to approach this...

Coming back to the black-box thinking I depend on a lot: it seems to me that if an optimization can turn code that can actually work into something that doesn't work, it shouldn't be used. So even building with 4.8.2 might be affected by this problem, only in a way that doesn't show as obviously... So from that blackbox logic the question would rather be: shouldn't avoiding that optimization be a more generally applied precaution for SC builds?

**Comment by sensestage** [comment] 2016-05-11 20:31
also confirmed for building on BeagleBone (BeLa) with gcc-4.9.2/g++-4.9.2

**Comment by telephon** [comment] 2016-05-12 05:36
> shouldn't avoiding that optimization be a more generally applied precaution for SC builds?

Compilers always translate, and Traduttore, Traditore.  I don't know much about these kinds of optimisations, but it seems that we should keep things simple indeed. Better not optimise and be safe. This is just my 2 cents.

**Comment by bagong** [comment] 2016-05-12 05:52
Well, on the Raspberry Pi we observed that removing the optimization and using 4.9.2 still doesn't result in a well working build. So just from experience, for the combination Rasbian Jessie and Raspberry Pi 1/2/3 it is still better to use 4.8. With 4.8 the optimization seems not to matter and results in a slightly faster SC. Might be the similar for bela (interesting development!)? As long as we don't understand the underlying matter we depend on this kind of blind experimentation...

**Comment by gusano** [comment] 2016-05-30 11:54
I get this error on a rpi-3 `Raspbian 8.0 jessie` and `gcc-4.8`

**Comment by timblechmann** [comment] 2016-05-30 15:24
maybe someone could try #2115

**Comment by bagong** [comment] 2016-05-30 16:36
I have very little time atm, serious personal stuff. But: I built #2115 with my default configuration on a RPi-3 and could start sclang in readline mode without errors. I have not cross-checked @gusano 's observation that current master also solves the problem. So maybe somebody else could cross-check. @timblechmann 's PR has serious implications that need to be cross-checked on all platforms, especially Windows.

**Comment by timblechmann** [comment] 2016-05-30 17:25
fwiw, if bugs show up in an optimized build it is quite likely that there are subtle underlying bugs. the wrong use of flexible array members might be one of them.

**Comment by bagong** [comment] 2016-05-30 21:32
@gusano, I do not get that error with vanilla master

**Comment by gusano** [comment] 2016-05-31 10:15
@bagong that's weird, I tested on a brand new rpi3 with everything up-to-date and current sc master.
@timblechmann I'm gonna give #2115 a try, although you closed it

**Comment by gusano** [comment] 2016-05-31 12:38
@bagong Sorry for the noise, I tried again today with latest master (still on rpi3) and it works fine when building with gcc-4.8.4
@timblechmann Using #2115 it builds fine on the rpi3 with gcc-4.9 but sclang woes (high cpu, jack freaks out with xruns, etc..)

**Comment by vivid-synth** [comment] 2016-12-10 04:18
Can someone summarize what the status of this is? It looks like maybe adding `-fno-strict-aliasing` fixes it but we don't know why? (And that might indicate a bug?) And that #2115 may fix it even with `-fstrict-aliasing`?

**Comment by dyfer** [comment] 2021-01-28 20:39
Does this issue still occur?

**Comment by dyfer** [comment] 2021-03-14 22:29
Closing as stale. Please reopen if the issue still occurs.

**Closed by dyfer** 2021-03-14 22:29 UTC
Labels: bug
