### ISSUE TITLE
Need updated Windows build instructions

### ISSUE THREAD

**Issue by dumbledad** [supercollider/supercollider#1763] opened 2015-12-11 08:13 UTC
[README.md](https://github.com/supercollider/supercollider/blob/master/README.md) states "Platform specific build and install instructions can be found in the following files". However [README_OS_X.md](https://github.com/supercollider/supercollider/blob/master/README_OS_X.md) contains build instructions (not install instructions) and [README_WINDOWS.md](https://github.com/supercollider/supercollider/blob/master/README_WINDOWS.md) only contains installation instructions, I cannot see any build instructions there. In lieu of adding both sets of instructions to each file we could change the wording to "Platform specific build or install instructions can be found in the following files".

(N.B. Where would I find Windows build instructions?)

**Comment by crucialfelix** [comment] 2015-12-11 13:46
I would say that the issue isn't how the sentence is worded, but the fact that build instructions for windows are missing.

Install on OS X is "drag it to your app folder" which I think everybody knows. The sentence could be added.  More importantly the build instructions are talking about travis-ci which is irrelevant and confusing.

**Comment by jamshark70** [comment] 2015-12-11 14:35
Build instructions for Windows are missing because setting up a build environment in Windows requires a level of heroics somewhat beyond that of the Marvel Comics film franchise.

**Comment by dumbledad** [comment] 2015-12-11 14:40
Are they documented anywhere outside Stark Industries?

**Comment by davidstephengrant** [comment] 2016-01-17 11:44
I found this: https://www.snip2code.com/Snippet/412469/Windows-README-for-SuperCollider-3-7 - apparently from March 2015. Are these the most recent (known) build instructions for Windows, and has anyone tested them recently?

**Comment by bagong** [comment] 2016-01-17 12:20
It's a very brief version that can serve an informed reader as a starting point for building SC unixy style with mingw and msys. Problem here (among others) is that there is no well defined, easily installable msys environment. But if you're versed in this environment, it's certainly a possibility. I had been using msys2 for a while, which looked very promising, but they have a quick rolling release system, and at some point their versions used gcc versions that broke the sc-build.
Also efforts were made to make a VStudio build possible - which worked at some point.
A long text that describes both build systems is here:

https://github.com/supercollider/supercollider/blob/topic/scwin3.7/README_WINDOWS.md

Unfortunately editor-sclang communication doesn't work properly in recent builds, resulting SC is virtually unusable, although everything comes up quite well. Also some commits to master, after the topic/scwin3.7 branch was created, make it difficult to merge that branch with current master (or the 3.7 release branch).

**Comment by timblechmann** [comment] 2016-01-17 13:49
about the ide/lang communication "bug": 
* it is unknown which qt version had been used.
* i have suggested to file a bug report for qt.
* apparently there were no experiments about compiling qt with QT_LOCALSOCKET_TCP.

about the build system:
it would be great to update the cmake buildsystem to support msvc and make/ninja on windows. main obstacle is the integration of externally compiled libraries. i'm happy to help with code reviews.

**Comment by bagong** [comment] 2016-01-17 14:43
- 5.2 up to 5.41
- good idea, but it has to be done by somebody with enough understanding to be able to do so ;)
- likely ;) Compiling winSC is not exactly trivial... adding compiling QT on top would add another sweet challenge...

**Comment by timblechmann** [comment] 2016-01-17 14:57
the current stable version of qt is 5.5, 5.6 being released in a few weeks (betas are out). building qt is pretty straight forward, just that it takes a bit of time ...

**Comment by Jaaaaaa** [comment] 2016-01-26 22:40
Thank you very much for detail step by step descripted help on link
https://github.com/supercollider/supercollider/blob/topic/scwin3.7/README_WINDOWS.md. Finally sucessful built own supercollider on Win (except manualy copy of libsndfile-1.dll to install folder). I used branch scwin3.7-fix-conflicts, exist some newer, closer to current master branch than this one from june which is possible to build?

**Comment by bagong** [comment] 2016-01-26 22:55
Nice. Unfortunately I know of no other branch. Wanna give it a try? In which environment did you build?

**Comment by Jaaaaaa** [comment] 2016-01-27 07:37
cmake->vs2013 (qt5.4.1)

**Comment by bagong** [comment] 2016-01-27 07:55
Basically there are 3 blocks in the branch: changes that allow SC to be compiled with 64-bit windows toolchain, cmake changes to deal with Visual Studio, and a fix for the communication issues between the ide and sclang. The first block has been merged into master, but afaik nobody has checked on the details. The second block isn't generic yet, but shouldn't be difficult to bring to master. The third block is unfortunately not Windows specific. According to Tim those changes shouldn't be necessary, and there is a chance that a more recent Qt version, or a custom compile of Qt fixes things for Windows without those changes.

**Comment by bagong** [comment] 2016-02-05 02:27
@Jaaaaaa, could you try that pull request, or if you prefer the original branch on in my repo: https://github.com/bagong/supercollider.git. The branch is called 3.7win. It's based on the 3.7 release branch. Somehow the error behavious has changed. There are still phases where sclang is quite instable, but then there are others where it is solid over long time... I can copy past more than a million characters... I would like to find a pattern under which sclang get's unstable... haven't found anything reproducible yet...

**Comment by bagong** [comment] 2016-02-05 03:35
Hey @Jaaaaaa , one more thing: if you still get instability, try replacing that checkmark towards the end (line 618) of the file QuarksGui.sc in yourInstallFolder\SuperCollider\SCClassLibrary\Common\Quarks by a "normal" character. That checkmark could contribute to the instability... I am not sure yet...

**Comment by Jaaaaaa** [comment] 2016-02-05 10:26
So @bagong, i tried it, but I wasn't sucessful on the end. Cmake with default option has problem to found nova-simd and hidapi. I put it from scwin3.7-fix-conflicts into folder external_libraries (nova-tt  aren't there too). After this i built it. In build install folder scide didn't found libsndfile-1.dll, again manually added. But after that scide made some error, which i cant fix. Free translation of that msg mean something like "Entry point of procedure GetSystemTimeAsFileTime not sucessfuly found in dynamic linked library Kernel32.dll "??????

**Comment by bagong** [comment] 2016-02-05 10:50
Sorry for the frustration and thank you for trying! If we walk through this, it could help to improve the documentation (and you might get your build and a working environment). 

It would be good to identify the points where you get stuck and try to solve them in good way. Mixing different source trees and binaries is very error prone. Errors you get might be due to those workarounds rather than a problem with the build if it runs as planned. Btw, on which OS are you, Windows 8.1 64bit?

- I think the missing external libraries are fixed by saying "git submodule update" at the right point. If you tell me where you got that error message, I will add that info in the Readme.
- libsndfile-1.dll shouldn't be missing of course. Lucas and I don't have that problem, the file is added properly during install/bundle. Is there any error that could give a hint why it isn't copied in your case?
- that third error sounds like libraries are mixed that don't belong together (version, architecture, not sure) that would need a bit of inspection once the others are set right.

Do you use any instant messaging media, IRC or Gitter or Facebook? I could try to hold your hand while you go through it again, if you're still patient? We need people that build Windows, and you are already so far ;)

**Comment by bagong** [comment] 2016-02-19 11:00
There is a pull request now on the 3.7 branch containing a detailed description of the build system.

**Closed** 2016-03-06 13:23 UTC
Labels: fix proposed, needs documentation

**Comment by bagong** [comment] 2016-03-06 13:30
I am almost done with another update to Win build system and Readme. This contains a handful of needed fixes to the build system,  and the option to run various sc components in their respective target folders without the need to "install" (a ripoff of the Mac system), and an adjusted Readme. All doesn't interfere with the other OSes, so it shouldn't be problematic to merge for an RC or release, but I have to do some testing and commit editing before I offer a pull request. It'll happen next week.

**Comment by crucialfelix** [comment] 2016-03-06 13:49
as long as its just the build system - we can easily verify that that works (or doesn't). adjusted readme is fine too.

anything else is closed.  I really want to ship this now. like just tag it and release it.

**Comment by bagong** [comment] 2016-03-06 13:52
Sure. I didn't intend to sound like I was going against that.
