### ISSUE TITLE
"/*" is parsed incorrectly when it is within /* */

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6170] opened 2023-12-30 02:40 UTC
## Environment

* SuperCollider version: 3.14.0_dev
* Operating system: macOS, Windows, Linux

## Steps to reproduce
https://github.com/supercollider/supercollider/pull/6164

## Expected vs. actual behavior
`"/*"` should not be regarded as the start of a comment, even within a `/*` `*/` pair.

**Comment by JordanHendersonMusic** [comment] 2024-05-05 17:18
Closing as this is a duplicate of #5578

**Closed by JordanHendersonMusic** 2024-05-05 17:18 UTC
Labels: bug
