### ISSUE TITLE
failed to read Quark directory listing

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1585] opened 2015-07-01 13:55 UTC
With a fresh install on OS X the latest binary – trying Quarks.gui and "Check for updates" we get consistently:

"failed to read Quark directory listing"

**Comment by crucialfelix** [comment] 2015-07-01 14:03
Are you implying that there was no error posted ?  How is that possible:

```
("Failed to read quarks directory listing: % %".format(if(fetch, directoryUrl, dirTxtPath), err)).error;
```

What is the full error message ?

**Comment by telephon** [comment] 2015-07-01 14:09
ERROR: Failed to read quarks directory listing: https://github.com/supercollider-quarks/quarks.git a PrimitiveFailedError

**Comment by crucialfelix** [comment] 2015-07-02 14:06
Cannot reproduce.

You will have to investigate it and provide some more information.

what does "fresh install" mean exactly ? Did you remove Application Support ? do you have any sclang_conf ?

A primtive failed. What primitive ?

**Comment by telephon** [comment] 2015-07-02 18:34
>what does "fresh install" mean exactly ?

Three people in a workshop downloaded the latest alpha binary for OSX and had the same problem. This may be our network, but still, it were three cases in a row.

>Did you remove Application Support ?

You mean ````Application Support > SuperCollider ````? No. But any existing quarks folders.

>A primitive failed. What primitive ?

Unfortunately, I can't tell from the error message.

**Comment by crucialfelix** [comment] 2015-07-02 21:30
Stick some debugging in, locate the error please. What did you mean about
the network ? Is it possibly caused by not having network access ?

What does "no, but any existing quarks folder" mean?

It sounds like you have encountered a serious issue, but the bug report
needs more information.

**Comment by telephon** [comment] 2015-07-02 21:59
>Stick some debugging in, locate the error please. 

I cannot reproduce it myself. Also don't know how to stick debugging in.

>What did you mean about the network ? Is it possibly caused by not having network access ? 

It is possible. But we were able to use http as usual.

>What does "no, but any existing quarks folder" mean? 

>>>Did you remove Application Support ?
>>You mean Application Support > SuperCollider? No. But any existing quarks folders.

I meant that I didn't remove ````Application Support/SuperCollider/````, but only ````Application Support/SuperCollider/downloaded-quarks```` and ````Application Support/SuperCollider/quarks````.

>It sounds like you have encountered a serious issue, but the bug report needs more information.

I understand, but right now I have no access to the situation that caused it.

**Comment by crucialfelix** [comment] 2015-07-03 06:27
Do they have git installed ?

**Comment by telephon** [comment] 2015-07-03 23:07
No, they haven't. Should they?

**Comment by crucialfelix** [comment] 2015-07-04 10:31
Of course. It uses git.  

the readme here and in the help file are pretty clear I think:

https://github.com/supercollider-quarks/quarks

So this is perhaps the cause of the error.

**Comment by telephon** [comment] 2015-07-04 19:17
Ah ok - if that is the case then the fix would simply be a warning. I'll try on Tuesday.

**Comment by crucialfelix** [comment] 2015-07-08 16:43
fix is there

**Comment by miguel-negrao** [comment] 2015-09-13 17:22
Doesn't the fix solve the issue, such that it can be closed ?

**Comment by crucialfelix** [comment] 2015-09-16 09:34
because it hasn't been merged yet. which is my fault. I said I would rename *exec to *call and then merge it.

I had a really big 3 month work project, but that's now complete. I'll try to merge this in the next day or two.

**Closed** 2015-09-18 08:18 UTC
Labels: bug, os: Mac OS X, quarks
