### ISSUE TITLE
"WARNING: server 'localhost' not running." error message needs to be clearer

### ISSUE THREAD

**Issue by ryceg** [supercollider/supercollider#3969] opened 2018-08-10 02:36 UTC
Environment
-----------

* SuperCollider version: 3.9.3
* Operating system and version: Mac OSX

Expected Behavior
-----------------
Better description of the error message and steps to fix the issue (i.e. `Server.killAll;`), since it's such an easy issue to encounter.

Current Behavior
----------------
A dead synth server has been running in the background. Trying to play anything yields `WARNING: server 'localhost' not running.`. This is easily fixed by using `Server.killAll;`. 

Steps to reproduce (for bugs)
-----------------------------
1. Make Supercollider have a dead synth server running in the background.
2. `s.boot;`
3. `{SinOsc.ar}.play;` should yield 
```supercollider
localhost
booting server 'localhost' on address: 127.0.0.1:57110
Number of Devices: 3
   0 : "Built-in Microph"
   1 : "Built-in Output"
   2 : "AutoAggDevice"

"AutoAggDevice" Input Device
   Streams: 1
      0  channels 2

"Built-in Output" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 44100.000000, driver's block size = 512
Exception in World_OpenUDP: bind: Address already in use
RESULT = 1

WARNING: server 'localhost' not running.
nil
```

Error message (for bugs)
------------------------

```
localhost
booting server 'localhost' on address: 127.0.0.1:57110
Number of Devices: 3
   0 : "Built-in Microph"
   1 : "Built-in Output"
   2 : "AutoAggDevice"

"AutoAggDevice" Input Device
   Streams: 1
      0  channels 2

"Built-in Output" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 44100.000000, driver's block size = 512
Exception in World_OpenUDP: bind: Address already in use
RESULT = 1

WARNING: server 'localhost' not running.
nil
```

**Comment by jamshark70** [comment] 2018-08-10 22:54
The problem is that Function:play doesn't know why the server isn't running -- so it isn't certain that `Server.killAll` will fix it.

Function:play's error message shouldn't make guesses. If this error message stated confidently that it's because of a port conflict, then it would be misleading in cases where the server didn't boot because of a sample rate mismatch or (in Linux) if Jack's chosen audio device is unavailable.

In fact, the error dump you posted does show the cause:

```
Exception in World_OpenUDP: bind: Address already in use
```

*This* error message might perhaps be made clearer (though there may be valid reasons to have multiple sclang/scsynth pairs running at the same time, so it's not necessarily right to recommend `Server.killAll` as a blanket solution).

**Comment by dyfer** [comment] 2018-08-28 17:30
Would it be worthwhile to extend ```scsynth```'s error message? I know this is long, but maybe something like this? 
```
Exception in World_OpenUDP: bind: Address already in use
If you are trying to run a single server locally, it is likely that a stale server runs in the background.
SuperCollider language provides a convenience method to forcibly quit all servers:
Server.killAll
Waring: This will kill all server processes you might be running!
```
On one hand it's specific to sclang and over-verbose, but on the other the ```Exception in World_OpenUDP``` error tells the user almost nothing about what the possible cause is (not all users are familiar with networking caveats...)

**Comment by cdbzb** [comment] 2019-08-02 00:04
yep - google brought me here after seeing this error, the prolix message would have helped me...

**Comment by cdbzb** [comment] 2019-08-02 00:07
ahh never mind! Server.killAll not doing it for me. restart seems to be the answer but not clear why this is happening...

**Comment by brianlheim** [comment] 2019-12-27 22:23
i noticed this issue has been getting a lot of views according to our insights/traffic page, so i opened #4703 to resolve it

**Comment by fmiramar** [comment] 2020-03-28 16:53
> ahh never mind! Server.killAll not doing it for me. restart seems to be the answer but not clear why this is happening...

I'm on Mac osx 10.14.6 mojave, SC 3.10.4 and for me restarting the computer was the only solution( I was trying to boot on the system without any external device connected). The only different thing for me was that yesterday I turned off the computer using a focusrite scarlet 18i20 interface. I probably shut down SC before turning of the interface. Could this be an issue regarding audio interfaces ?

**Comment by brianlheim** [comment] 2020-05-05 02:00
Fixed in https://github.com/supercollider/supercollider/pull/4863!

@fmiramar this is not the right place to ask, sorry. please use the sc-users mailing list, scsynth.org, or the SC Slack chat for help debugging audio hardware issues.

**Closed by brianlheim** 2020-05-05 02:00 UTC
Labels: comp: class library
