### ISSUE TITLE
redraw error

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1408] opened 2015-04-06 10:21 UTC
Since the introduction of qt5, I get redraw-errors in the NdefMixer GUI. I assume this is a more general problem (though not tested...)

![screen shot 2015-04-06 at 13 18 30](https://cloud.githubusercontent.com/assets/75468/7003224/89cc945c-dc5f-11e4-8952-0260a084fb93.png)
(white areas should be sliders as well)
@adcxyz ,  do you have an idea?

**Comment by LFSaw** [comment] 2015-04-06 10:40
![screen shot 2015-04-06 at 13 18 30](https://cloud.githubusercontent.com/assets/75468/7003401/793c2672-dc62-11e4-9a1f-ceb98d86614b.png)

**Comment by adcxyz** [comment] 2015-04-06 11:01
hi till, 

just tested on my current debug build, looks good here with the NdefMixer helpfile example. 

There is some dodginess in the EnvirGui update method (using a defer { }) to do two update steps, 
maybe that is the culprit. let's take the discussion/fix offline to reduce noise, 

best adc

**Comment by sensestage** [comment] 2015-04-27 18:10
I can confirm the issue - on Linux it even draws the whole window black once I click on the "ed" button of one of the Ndefs to let the window expand. I then have to mouse over and at certain points click to get the child widgets to reappear.
A build from last week still had this bug.

**Comment by telephon** [comment] 2015-05-14 14:23
Hm, I can't reproduce on OS X 10.10. Maybe it has to do with the updating method?

**Comment by adcxyz** [comment] 2015-05-14 14:48
I also still get it too on my current dev build. 
resizing the window by hand seems force a complete refresh so everything appears properly. 
It is likely a timing thing between JITGui and Qt redraw/update methods. 
Will try to get a small reproducer that is independent from JITguis.

best adc

**Comment by telephon** [comment] 2015-06-14 18:57
have you found a small reproducer?

**Comment by adcxyz** [comment] 2015-06-17 12:34
no, it seems to be a general qt version issue. 
needs testing with build based on recommended qt version.
somewhat related : 
I have a fix for the dodgy updates in EnvirGui and subclasses, 
will make it a pull request soon so it makes it into 3.7

**Comment by adcxyz** [comment] 2016-10-09 09:14
This is gone with the update of EnvirGui etc to ParamView in 3.8, 
so I close this. 
just reopen if you still see this.

**Closed by adcxyz** 2016-10-09 09:14 UTC
Labels: bug, comp: Qt GUI, qt5, waiting for information
