### ISSUE TITLE
Incomplete Help files in help browser in 3.10.0 (Ubuntu 19.04)

### ISSUE THREAD

**Issue by mesjetiu** [supercollider/supercollider#4392] opened 2019-04-20 11:45 UTC
Bug description:
Some information in help files doesn't appear in Help Browser, like code examples in any page. Also some help pages appears empty in Help Browser, like "Document Browser".
In Ubuntu 19.04 and Kubuntu 19.04.
SC version: 3.10.0 from Ubuntu official repositories

Steps to reproduce:
1. Look up any UpGen help in Help Browser, like SinOsc
2. Code examples in page are empty.
3. If the same help file ("/usr/share/SuperCollider/HelpSource/Classes/SinOsc.schelp") is open out of Help Browser, code examples are there! 

Actual result:
Help Browser seems not to visualize all elements in help files, like code examples.

Expected result:
Help file should appear complete in Help Browser, with every code example.

**Comment by snappizz** [comment] 2019-04-20 17:49
hi, thanks for the report. this smells like a javascript issue. could you try launching SCIDE from the terminal and seeing if any errors are printed?

highly recommend upgrading to 3.10.2 if possible, 3.10.0 and 3.10.1 have a critical memory leak that causes sclang to get slower and slower over time.

**Comment by mesjetiu** [comment] 2019-04-21 18:42
The output Scide in terminal is:
`*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 215
* source ID: "file:///home/carlos/.local/share/SuperCollider/Help/scdoc.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: CodeMirror is not defined"
* line: 3
* source ID: "file:///home/carlos/.local/share/SuperCollider/Help/editor.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 157
* source ID: "file:///home/carlos/.local/share/SuperCollider/Help/scdoc.js"
`
Thanks for your advise. I will try to compile from source 2.10.2 since ubuntu 19.04 has 2.10.0... 
Anyway, do you think it is a problem that I can solve easely?

**Comment by snappizz** [comment] 2019-04-24 22:48
there's another report of this issue: #4367

unfortunately i don't know how to fix this right now since i can't reproduce it.

**Comment by gusano** [comment] 2019-04-25 02:54
@mesjetiu what's the output of the following command in your terminal?
`ls -l ~/.local/share/SuperCollider/Help`

**Comment by bartart3d** [comment] 2019-06-21 20:01
Hi, I've got the same issue here, I think.. so I'll add my version of 
`ls -l ~/.local/share/SuperCollider/Help/lib` 

```
lrwxrwxrwx 1 bart bart 44 jun 21 21:42 codemirror-5.39.2.min.js -> ../../../javascript/codemirror/codemirror.js
lrwxrwxrwx 1 bart bart 51 jun 21 21:42 codemirror-addon-simple-5.39.2.min.js -> ../../../javascript/codemirror/addon/mode/simple.js
lrwxrwxrwx 1 bart bart 40 jun 21 21:42 jquery.min.js -> ../../../javascript/jquery/jquery.min.js

```

**Comment by gusano** [comment] 2019-06-22 10:59
@bartart3d thanks. These should not be symlink although I'm not 100% sure..
What happens if you move the main jQuery file back into `lib`?

```
cp ~/.local/share/javascript/jquery.min.js ~/.local/share/SuperCollider/help/lib
```

**Comment by bartart3d** [comment] 2019-06-22 13:34
When entering  your command, copy pasting it, it says the directory 
`/home/bart/.local/share/javascript/jquery.min.js`
does not exist, should it?

grtz,
Bart

**Comment by gusano** [comment] 2019-06-22 13:48
@bartart3d yes.
I'll have a look at where this symlink comes from.
Thank you!

**Comment by bartart3d** [comment] 2019-06-22 13:50
great :-) As a test, I downloaded the git version of supercollider 3.10, unzipped, and copy pasted the javascript files you mentioned into 
`.local/share/SuperCollider/help/lib`
And now it works :+1:

**Comment by gusano** [comment] 2019-06-22 14:03
@snappizz who's packaging sc for Ubuntu? Seeing the comments above I'm pretty sure the folder `$HOME/.local/share/SuperCollider/Help/lib` generated by this package is empty..

**Comment by gusano** [comment] 2019-06-22 14:08
Closing this as a duplicate of #4367 cc @mesjetiu

**Closed by gusano** 2019-06-22 14:08 UTC
Labels: bug, comp: SCDoc

**Comment by mfcarcache** [comment] 2020-08-26 19:30
Thank You gusano. 
I've downloaded the last version and copied all files inside Help. That's worked with 3.10 in Ubuntustudio 20.04

**Comment by JordanHendersonMusic** [comment] 2021-06-29 11:50
Still having this issue on Pop_os in 2021....
Just remake the symbolic links (or copy and rename), the files are here:
```
codemirror-5.39.2.min.js -> /usr/share/javascript/codemirror/codemirror.js
codemirror-addon-simple-5.39.2.min.js -> /usr/share/javascript/codemirror/addon/mode/simple.js
jquery.min.js -> /usr/share/javascript/jquery/jquery.min.js
```
