### ISSUE TITLE
UGen.buildSynthDef is nil in {}.plot (this makes LocalBuf and {}.plot incompatible)

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#78] opened 2012-05-06 05:45 UTC
[Issue migrated from SourceForge | ID: 2612612 | Submitted by 'danstowell']
[http://sourceforge.net/support/tracker.php?aid=2612612]

{IFFT(FFT(LocalBuf(1024), PinkNoise.ar))}.play    // works

{IFFT(FFT(LocalBuf(1024), PinkNoise.ar))}.plot(1) // doesn't - buildSynthDef is nil

**Comment by Sciss** [comment] 2021-05-05 15:43
apologies for polluting multiple issues with automatic mentions from unrelated commits; I accidentally pushed non-overlapping ScalaCollider branches to my fork of SuperCollider (a wrongly set-url remote). I deleted those branches again, but seems the mentions are still in the ticket system, now pointing to orphaned commits.

**Comment by jamshark70** [comment] 2023-04-04 00:40
Reopening this issue: it is still a problem, and it was not fixed by the commit merged in August 2020 (which commit is totally irrelevant to this issue).

**Comment by telephon** [comment] 2023-04-10 17:00
Ah, it relies on `UGen.buildSynthDef` …

so that

```
(
a = {
	UGen.buildSynthDef.postln; // -> nil
	0.0
}.plot;
)
```

**Comment by telephon** [comment] 2023-04-10 17:22
So the problem is that the function is called a second time in https://github.com/supercollider/supercollider/blob/50d9927505d5a3b8a515b13b3c8fe7950dc022fa/SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc#L1319

Will need a little thinking how best to inform the call about the rate of the UGen in the function.

As a first thought, it could be either:
- more information passed through an extra argument (a dict whose values can be set in `asBuffer`).
- just convert the output into audio rate if it isn't.

Any opinions?

**Comment by telephon** [comment] 2023-04-13 21:11
> At the risk of pushing the discussion in a wrong direction: on some occasions I felt that a Buffer (both the language object and the server implementation) should have a settable sample rate parameter.

Yes, that was actually my thought as well when I read your comment. It is definitely a useful bit of information.

Going further down that road:

If a buffer has an optional sample rate, then this value should probably be accessible from the server side as well? Somehow `DiskIn` has such an internal info (should be somewhere here: https://github.com/supercollider/supercollider/blob/5c8e9440a1a42e0a5d3c8f06b3d52021884befb6/server/plugins/DiskIO_UGens.cpp#L280).

**Comment by jamshark70** [comment] 2024-04-18 03:31
Indeed, it's no longer reproducible.

There are a couple of relevant commits, about a month ago:

- https://github.com/supercollider/supercollider/commit/d5552c2a0c1bc373977080b690be2d08681752ef
- https://github.com/supercollider/supercollider/commit/0c3690af37ade255a9c0f92316586290b2e9a547

So I suppose this issue is addressed now.

**Closed** 2024-04-19 17:07 UTC
Labels: bug
