### ISSUE TITLE
Running "sclang foo.scd" hangs by default

### ISSUE THREAD

**Issue by aspiers** [supercollider/supercollider#3393] opened 2018-01-06 20:36 UTC
If I have a file `hello.scd` containing:

    "Hello, world!".postln;

and I invoke `sclang hello.scd` from the CLI, it will output a bunch of stuff ending in:

```
*** Welcome to SuperCollider 3.9dev. *** For help press Ctrl-D.
Hello, world!
```

and then it will hang.  The way to fix this is apparently to add `0.exit;` to the end of `hello.scd`, but that only works if there is no compilation error whilst compiling the classes.  If there is an error, apparently there is no way to avoid it hanging other than wrapping `sclang` in a timeout.  This is particularly problematic for `guard-sclang` which needs to spot when the developer has introduced (hopefully transient) compilation errors into the classes, and currently wrapping `sclang` in a timeout seems to be the only way to do that.  This issue is being tracked in https://github.com/aspiers/guard-sclang/issues/2.

Very preliminary analysis of `lang/LangSource/SC_TerminalClient.cpp` seems to suggest that it calls `commandLoop()` regardless of which options are chosen, e.g. `-D` for daemon mode has no effect on this, so that might explain why it's always hanging.

**Comment by patrickdupuis** [comment] 2018-01-06 22:58
This seems to be related to #3297

**Comment by jamshark70** [comment] 2018-01-06 23:55
I don't think it's related. #3297 is simply wrong behavior: sclang invoked without a script file, class library compiled successfully, but no way to use the interpreter. This issue is: sclang invoked with a script file, class library *failed* and we want an automatic exit from the process rather than entering an idle state.

I see three cases for library compilation failure:

- sclang invoked from an editor: sclang should wait for "recompile" or "exit" instructions from the editor.

- sclang invoked from the command line without a script: if library compilation succeeds, it would enter readline mode -- interactive use -- but if it fails, I'm not sure -- should the process just die, or wait for the user to force quit?

- sclang invoked from the command line with a script: if library compilation fails, there's no reason to keep sclang alive. We should just quit (with an error code), but we don't.
  - What should we do if the library is fine but the user script has a compilation error? I think it's justifiable to quit with an error code.
  - If the user script compiles but hits an unhandled exception...? Maybe in non-interactive mode, interpreter `halt` should quit the process too.

**Comment by aspiers** [comment] 2018-01-07 00:23
>This issue is: sclang invoked with a script file, class library failed and we want an automatic exit from the process rather than entering an idle state.

Yes, that's *part* of the problem here, but not the whole issue; it's also problematic that `sclang` hangs after compilation *succeeds* and a referenced script file is also successfully run but doesn't call `Integer.exit`.

Nevertheless I agree with the rest of your analysis.

> * sclang invoked from the command line without a script: if library compilation succeeds, it would enter readline mode -- interactive use -- but if it fails, I'm not sure -- should the process just die, or wait for the user to force quit?

It should die; what would be the value of waiting for the user to force quit?  You already seem to acknowlege that in the next case:

> * sclang invoked from the command line with a script: if library compilation fails, there's no reason to keep sclang alive. We should just quit (with an error code), but we don't.

I don't see why there would be any less reason to quit if a script is specified vs. if one isn't.

>   * What should we do if the library is fine but the user script has a compilation error? I think it's justifiable to quit with an error code.

Agreed.

>   * If the user script compiles but hits an unhandled exception...? Maybe in non-interactive mode, interpreter halt should quit the process too.

Agreed here too.

**Comment by jamshark70** [comment] 2018-01-07 02:07
> Yes, that's part of the problem here, but not the whole issue; it's also problematic that sclang hangs after compilation succeeds and a referenced script file is also successfully run but doesn't call Integer.exit.

I don't fully agree with you here. If your script is only `"Hello".postln`, then it makes sense to terminate. But if your script boots the server, starts some audio processes running, opens a GUI for user interaction (and it should terminate when the user clicks a button or closes the window), then it would be disastrous for sclang to assume "I got to the end of the script file, so, exit now."

If we're going to implement an automatic exit, then we have to be clear about the conditions that would disable the automatic exit. I tend to agree with you that it's confusing for the user to write a simple, linear script and sclang doesn't exit. In "conventional" languages, you can e.g. keep the process alive as long as it has threads open. But sclang doesn't have true threads -- only coroutines that happen to be scheduled on a clock, with a rescheduling mechanism. So, reasonable conditions might be:

- If we reached the end of the script *and* all clock queues are empty, exit. (Booting the server starts a routine to check server status, so that would automatically put something into one of the queues.)

- If we reached the end of the script *and* no GUI windows are open, exit. (But here, if the user closes the last window and schedulers are empty, should this automatically exit?)

E.g., Should this script terminate automatically? When, and how should sclang know that it's time to exit?

```
Routine {
	5.do { |i|
		i.postln;
		1.0.wait;
	};
}.play;
```

**Comment by jamshark70** [comment] 2018-01-07 02:53
Also, I just realized, a user might do `s.startAliveThread` in her startup.scd, or an extension class might schedule a repeating task, and that would prevent a script from exiting automatically, because we have no distinction between "this scheduled thing is important for user interaction and we need to wait for it" and "this is a background task that can terminate any time."

I think there would be good reasons to have an automatic exit from a script, but you can't guarantee success. As long as we're aware of the limitations and think them through, it's OK with me... I just want to be sure we aren't assuming that it's easy and foolproof.

**Comment by brianlheim** [comment] 2018-01-07 03:58
@jamshark70 A check on GUI threads and scheduler queues before terminating seems reasonable to me. That's similar to what Adam and I had discussed on Slack when he first brought this up.

**Comment by aspiers** [comment] 2018-01-07 10:17
@jamshark70 Thanks, excellent thoughts here and I'm in full agreement with everything you've written.

Successful compilation scenarios aside, are we all agreed that `sclang` should always immediately quit on compilation failures?

**Comment by jamshark70** [comment] 2018-01-08 02:03
> A check on GUI threads and scheduler queues before terminating seems reasonable to me. That's similar to what Adam and I had discussed on Slack when he first brought this up.

OK, I wasn't aware of that prior discussion. The enhancement request, as stated initially, suggested only that sclang should quit when finished, without defining what "finished" means.

I can see two ways to handle it, but first:

> ... are we all agreed that sclang should always immediately quit on compilation failures?

We need to distinguish between an *interactive mode* (either commandline without a script, presenting a readline prompt, or launched from an editor with a "-i" switch) and a *non-interactive mode* (with a script -- no prompts, no interaction with an editor). I agree that sclang should always immediately quit on compilation failures *if* it's launched non-interactively.

I apologize if it sounds pedantic, but without that distinction, "always immediately quit on compilation failures" would happen also when running sclang via the IDE. I wouldn't agree with that. (Sure, this enhancement assumes a non-interactive context, but we've gotten in trouble in the past by assuming too much -- no harm to make the boundaries explicit.)

OK. Two options. (In both cases, if there's no GUI or scheduler activity, sclang would exit.)

- Option A: At the moment when the main line of the script finishes, if there's a GUI window or any scheduled item, it's than the user's responsibility to do `0.exit`. That is, it's a one-time check: exit, or don't, and don't keep checking.

- Option B: If there's a GUI window or scheduled item, keep monitoring:
  - When a window closes, check for other windows or scheduled items, and exit only if everything is gone.
  - If a scheduled item wakes up and does *not* reschedule itself, exit if there's nothing else pending. (Probably could use a counter to avoid looping over the collection of all existing clocks for *every* scheduled event.)

TBH I'm leaning towards option A, because, as noted, a user's configuration could schedule a persistent task, preventing automatic exit, and this would be out of the script's control. That is, option B would work most of the time but it would be inherently unreliable, so the documentation would have to be "In most cases it will exit, but you can't be sure."

For that matter, option A is also unreliable (but at least option A makes it more the user's responsibility). I think it's easier for documentation to explain "you should explicitly `0.exit` in all but the simplest cases" rather than "sclang will try to exit for you, but several circumstances could prevent that."

**Comment by brianlheim** [comment] 2018-01-08 03:25
> I think it's easier for documentation to explain "you should explicitly 0.exit in all but the simplest cases" rather than "sclang will try to exit for you, but several circumstances could prevent that."

I think both are easy to document, but the second is by far more intuitive. The "several circumstances" are really just one - sclang should exit when all threads have finished executing. So, sclang is still running -> a thread is still running. That does not seem uncertain or unreliable to me. On the contrary, what seems unreliable to me is trying to make sure there's no order of thread/GUI interaction that could lead to `exit` not being called (e.g. if an exception is thrown).

> > ... are we all agreed that sclang should always immediately quit on compilation failures?
>
> We need to distinguish between an interactive mode (either commandline without a script, presenting a readline prompt, or launched from an editor with a "-i" switch) and a non-interactive mode (with a script -- no prompts, no interaction with an editor).

In both cases, I say that the process should quit on _library_ compilation failure.

**Comment by jamshark70** [comment] 2018-01-08 09:30
By "unreliable," I mean this:

1. I write a script that does something, finishes, and I expect it to exit by itself.
2. I send the script to someone else, who has put `s.startAliveThread` in the startup.scd file. (Or, they have an extension class that runs a thread.)
3. That user writes back to me saying, "You said it would exit but it doesn't exit."

Exiting, or not exiting, becomes partly dependent on the environment, and a script file can't control the environment. So the behavior is not actually deterministic based on the contents of the script.

In that sense, JMc might have been right to leave it in the user's hands. (With that comment, I'm playing devil's advocate and not seriously arguing against the proposal -- but, don't dismiss the point, either. Fact is, the only way to be sure a script will exit is to write an explicit exit. Otherwise, you're playing dice.)

> In both cases, I say that the process should quit on library compilation failure.

So, library compilation fails in the IDE, and it prints the message that the interpreter quit unexpectedly? I guess it's reasonable to ask the user to reboot the interpreter instead of recompiling the library, but at least the message needs to change in that case -- e.g. "Please resolve the issue and reboot the interpreter."

**Comment by miguel-negrao** [comment] 2018-01-08 11:26
> I think both are easy to document, but the second is by far more intuitive. The "several circumstances" are really just one - sclang should exit when all threads have finished executing.

I'm not familiar with the low-level sclang network, serial,MIDI, etc code, but what about the  call-backs related to these connections ? Do they also internally create sclang threads which will count towards deciding to quit sclang or not ? I'm thinking about a program that starts and just watches for some incoming message either via network, MIID, serial, etc. Those shouldn't be automatically exited while there are call-backs registered waiting for events.

Best,
Miguel Negrão

**Comment by jamshark70** [comment] 2018-01-08 12:22
> I'm not familiar with the low-level sclang network, serial,MIDI, etc code, but what about the call-backs related to these connections ? Do they also internally create sclang threads which will count towards deciding to quit sclang or not?

They aren't sclang Threads, so you're right, merely watching for scheduled items is not enough. I did think of that, but hadn't mentioned it yet.

I'm not sure of the best way to define whether we are waiting for an action to fire or not. In a way, it's the same problem that I was mentioning with the aliveThread: we don't have a way to specify whether a thread is critical (and should block exit) or background (and should not block exit). All threads block exit (as proposed), and there is no control over starting threads that block exit. Likewise, we don't have a distinction between "wait for osc messages until the process exits" (don't block exit) and "wait for a specific osc message which will end the process" (*do* block exit).

**Comment by cleary** [comment] 2020-06-25 23:53
Hi guys,
I've been battling with this process trying to manage interactions with [sclang from ansible](https://github.com/cleary/ansible-tidalcycles-base/blob/master/tasks/postinst.yml) - 

I see it's a far more complicated issue than I initially gave it credit for, but I'd like to add some thoughts:

In my scenario, I'm installing superdirt by passing an scd script to sclang using an ansible task which runs the `shell` module.

I didn't have any luck using `0.exit;` at the end of my scd file as recommended, so I've gone with a particularly ugly *wait-for-expected-output-then-have-the-shell-kill-itself* method. This is reliable when successful, but doesn't handle errors at all. 
I then have to follow up and check if there are any dangling sclang processes still running and kill them too - not ideal. 

Onto my thoughts for expected behaviour:

I think the key thing to determine is: **Were we started from an Interactive or non-Interactive terminal**?

- If non-interactive, and compilation succeeds, exit with a zero return code, terminate sclang processes
- If non-interactive, and compilation fails, exit with non-zero return code, terminate sclang processes

If started from a non-interactive terminal, and waiting for threads is desired behaviour then that could be something requested explicitly from the script? 

`wait.exit` (I don't know sc syntax :P )?

**Comment by jamshark70** [comment] 2020-06-26 05:02
> I didn't have any luck using 0.exit; at the end of my scd file as recommended

Can you say more about what is going wrong with `0.exit`?

**Comment by cleary** [comment] 2020-06-26 07:14
hi @jamshark70, 
Thanks for the follow up!

`0.exit` is problematic, because it seems to evaluate that line regardless what happens in the rest of the file. 

All I want to do is install superdirt:
```
Quarks.checkForUpdates({Quarks.install("SuperDirt", "v1.1.3"); thisProcess.recompile()});
```

but as an example, if the computer is offline or github is otherwise unavailable sclang throws a bunch of error text to the console, then proceeds to evaluate 0.exit; and exit with a 0 return code - as though nothing went wrong.

Am I able to set a variable conditionally on the result of the Quarks.check... command that I can then use as my return code?

PS as a side note, it looks like I may have previously been getting some other errors too due to a missing `;` at the end of the Quarks.check... command - the above issue still applies though

**Comment by jamshark70** [comment] 2020-06-26 15:11
> `0.exit` is problematic, because it seems to evaluate that line regardless what happens in the rest of the file.

I had thought it might be something like that.

"At the end of the file" is oversimplified. For one thing, if there are asynchronous operations being performed, it's the user's responsibility to wait until those are complete before calling `exit` (using a Routine and Condition, usually). It's also the user's responsibility to return the correct exit code for the situation.

```
Quarks.checkForUpdates({Quarks.install("SuperDirt", "v1.1.3"); 0.exit;});
1.exit;
```

I *think* Quarks operations are synchronous, but if not, that could explain why it's running the `1.exit` inappropriately.

One snag is that Quarks error reporting is not good presently.

But I think this is all not quite related to the bug report. Maybe continue this on the user forum? It strikes me as a usage question rather than a bug.

**Comment by cleary** [comment] 2020-06-26 19:36
> One snag is that Quarks error reporting is not good presently.
So after digging just enough last night, and a bit of experimentation, I've got a working sc conditional tied to the boolean returning `Quarks.isInstalled()` function - which means it no longer relies on the Quarks error reporting

``` 
Quarks.checkForUpdates({Quarks.install("SuperDirt", "v1.1.3"); if (Quarks.isInstalled("SuperDirt"), {0.exit;}, {1.exit;});});
```

> But I think this is all not quite related to the bug report. Maybe continue this on the user forum? It strikes me as a usage question rather than a bug.
Agree, thanks for your patience and once again, apologies for the noise -

**Comment by NightMachinary** [comment] 2020-10-23 22:06
[**@jamshark70**](https://github.com/jamshark70) commented on [Jun 26, 2020, 7:41 PM GMT+4:30](https://github.com/supercollider/supercollider/issues/3393#issuecomment-650232587 "2020-06-26T15:11:49Z - Replied by Github Reply Comments"):
> > `0.exit` is problematic, because it seems to evaluate that line regardless what happens in the rest of the file.
> 
> I had thought it might be something like that.
> 
> "At the end of the file" is oversimplified. For one thing, if there are asynchronous operations being performed, it's the user's responsibility to wait until those are complete before calling `exit` (using a Routine and Condition, usually). It's also the user's responsibility to return the correct exit code for the situation.

I want to exit from this file after the sound finishes. What should I do?

```
// https://en.wikibooks.org/wiki/Designing_Sound_in_SuperCollider/Print_version
// 26: DTMF dialling tones
(
fork {
	var cond, runResponder;

	Server.default = s = Server.remote(\remote, NetAddr("127.0.0.1", 57110));

	cond = Condition({ s.serverRunning });

	// 'signal' will allow the forked routine to advance
	// only when 'serverRunning' finally becomes true
	runResponder = SimpleController(s).put(\serverRunning, { cond.signal });

	cond.wait;

	runResponder.remove;

(
// This data structure (like a "hashtable" or "associative array" in other languages)
// maps from a phone key to a pair of frequencies in Hz.
// We can push these frequencies to a synth.
~tbl = IdentityDictionary[
	$1 -> [[697, 1209]],
	$2 -> [[770, 1209]],
	$3 -> [[852, 1209]],
	$4 -> [[697, 1336]],
	$5 -> [[770, 1336]],
	$6 -> [[852, 1336]],
	$7 -> [[697, 1477]],
	$8 -> [[770, 1477]],
	$9 -> [[852, 1477]],
	$* -> [[697, 1633]],
	$0 -> [[770, 1633]],
	$# -> [[852, 1633]],
	$A -> [[941, 1209]],
	$B -> [[941, 1336]],
	$C -> [[941, 1477]],
	$D -> [[941, 1633]]
];

// Here we define a SynthDef which plays a single "number" at a time.
// Note that our strategy here is a bit different from the PD code in the book:
//   there, a single pair of sine-wave oscillators was re-used for each number,
//   whereas here, we create (and later free) an individual synth for each number.
SynthDef(\dtmf, {|freq=#[770, 1633], out=0, amp=0.2, gate=1|
	var son, env;
	son = SinOsc.ar(freq, 0, amp).sum;
	env = EnvGen.ar(Env.asr(0.001, 1, 0.001), gate, doneAction: 2);
	Out.ar(out, Pan2.ar(son * env * amp));
}).add;
) ;

(
// This pattern generates a random "phone number" and dials it
Pbind(
	\instrument, \dtmf,
	\dur, 0.2, // or for more "human" timing, try   Pwhite(0.2, 0.5, inf)
	\sustain, 0.15,
	\amp, 0.3,
	\freq, Prand(~tbl.asArray, 13)
).play;
) ;
};
)
```

**Comment by jamshark70** [comment] 2020-10-24 01:21
Revised version:

```supercollider
(
fork {
	var cond, runResponder, player;
	
	// Server.default = s = Server.remote(\remote, NetAddr("127.0.0.1", 57110));
	Server.default.boot;
	
	cond = Condition({ s.serverRunning });
	
	// 'signal' will allow the forked routine to advance
	// only when 'serverRunning' finally becomes true
	runResponder = SimpleController(s).put(\serverRunning, { cond.signal });
	
	cond.wait;
	
	runResponder.remove;
	
	(
		// This data structure (like a "hashtable" or "associative array" in other languages)
		// maps from a phone key to a pair of frequencies in Hz.
		// We can push these frequencies to a synth.
		~tbl = IdentityDictionary[
			$1 -> [[697, 1209]],
			$2 -> [[770, 1209]],
			$3 -> [[852, 1209]],
			$4 -> [[697, 1336]],
			$5 -> [[770, 1336]],
			$6 -> [[852, 1336]],
			$7 -> [[697, 1477]],
			$8 -> [[770, 1477]],
			$9 -> [[852, 1477]],
			$* -> [[697, 1633]],
			$0 -> [[770, 1633]],
			$# -> [[852, 1633]],
			$A -> [[941, 1209]],
			$B -> [[941, 1336]],
			$C -> [[941, 1477]],
			$D -> [[941, 1633]]
		];
		
		// Here we define a SynthDef which plays a single "number" at a time.
		// Note that our strategy here is a bit different from the PD code in the book:
		//   there, a single pair of sine-wave oscillators was re-used for each number,
		//   whereas here, we create (and later free) an individual synth for each number.
		SynthDef(\dtmf, {|freq=#[770, 1633], out=0, amp=0.2, gate=1|
			var son, env;
			son = SinOsc.ar(freq, 0, amp).sum;
			env = EnvGen.ar(Env.asr(0.001, 1, 0.001), gate, doneAction: 2);
			Out.ar(out, Pan2.ar(son * env * amp));
		}).add;
	) ;
	
	// technically you should wait for the synthdef
	// to be received and processed
	// you're getting away without it because of events' messaging latency
	// but really you should...
	Server.default.sync;
	
	(
		// This pattern generates a random "phone number" and dials it
		player = Pbind(
			\instrument, \dtmf,
			\dur, 0.2, // or for more "human" timing, try   Pwhite(0.2, 0.5, inf)
			\sustain, 0.15,
			\amp, 0.3,
			\freq, Prand(~tbl.asArray, 13)
		).play;
	);

	// previously you watched for the server to be running
	// you can also watch for the pattern to end
	
	cond = Condition.new;
	
	runResponder = SimpleController(player)
	.put(\stopped, { cond.unhang });
	
	cond.hang;
	
	// maybe in your case you don't have to do this
	// (if the remote server remains running)
	Server.default.latency.wait;
	
	0.exit;
};
)
```

I will close this, as it is a usage question, not a bug/feature-request. Usage questions belong on the forum at scsynth.org.

**Closed by jamshark70** 2020-10-24 01:21 UTC
Labels: comp: sclang

**Comment by aspiers** [comment] 2020-10-24 17:40
@jamshark70 I'm a little confused now as this issue went in several directions and I'm still not sure how (or whether) the original problem is addressed.  My original report on this issue was motivated by the fact that:

> guard-sclang which needs to spot when the developer has introduced (hopefully transient) compilation errors into the classes, and currently wrapping sclang in a timeout seems to be the only way to do that. 

On [January 6, 2018 11:55 PM](https://github.com/supercollider/supercollider/issues/3393#issuecomment-355787284 "2018-01-06T23:55:39Z - Replied by Github Reply Comments") you wrote:
> I see three cases for library compilation failure:
>
> [...]
> *   sclang invoked from the command line with a script: if library compilation fails, there's no reason to keep sclang alive. We should just quit (with an error code), but we don't.
> 
>     *   What should we do if the library is fine but the user script has a compilation error? I think it's justifiable to quit with an error code.
>     *   If the user script compiles but hits an unhandled exception...? Maybe in non-interactive mode, interpreter `halt` should quit the process too.

and on [January 8, 2018 2:03 AM](https://github.com/supercollider/supercollider/issues/3393#issuecomment-355872216 "2018-01-08T02:03:39Z - Replied by Github Reply Comments") you wrote:
> I agree that sclang should always immediately quit on compilation failures _if_ it's launched non-interactively.

Are you saying that this behaviour is now fixed, so that non-interactive runs *do* now immediately quit on compilation failures?

**Comment by jamshark70** [comment] 2020-10-24 23:47
Ok, I forgot about those.

It seems this issue has become a bit diluted -- maybe the best course of action is to open a new issue with a specific feature to implement...? The issue title as given here doesn't really tell contributors what needs to be done. A new issue such as "Command-line sclang should exit with error code upon library compilation error" would also be less likely to attract usage questions.

As for quitting sclang when GUIs and threads are gone, I think my opinion hasn't changed much. It's not hard to imagine cases where any approach to automatic exit would fail to exit.

**Comment by aspiers** [comment] 2020-10-25 13:12
[**@jamshark70**](https://github.com/jamshark70) commented on [October 25, 2020 12:47 AM](https://github.com/supercollider/supercollider/issues/3393#issuecomment-716069937 "2020-10-24T23:47:47Z - Replied by Github Reply Comments"):
> Ok, I forgot about those.
> 
> It seems this issue has become a bit diluted -- maybe the best course of action is to open a new issue with a specific feature to implement...? The issue title as given here doesn't really tell contributors what needs to be done. A new issue such as "Command-line sclang should exit with error code upon library compilation error" would also be less likely to attract usage questions.

OK sure - filed as #5218.  Sorry about the somewhat vague title on this issue.

> As for quitting sclang when GUIs and threads are gone, I think my opinion hasn't changed much. It's not hard to imagine cases where any approach to automatic exit would fail to exit.

That's fair enough.  It's not the particular itch I'm trying to scratch so I have no complaints if there's no easy way to address that ;-)

Thanks a lot!
