### ISSUE TITLE
Rest objects in event streams are no longer interpreted as silent Events

### ISSUE THREAD

**Issue by davidgranstrom** [supercollider/supercollider#3447] opened 2018-01-19 16:16 UTC
Hi,

I just updated to 3.9 and read that `Rest` has changed behaviour (for the better IMHO). I stumbled upon this problem when trying out some code which was working in 3.8 but now breaks with this error [1]. 

Here is the reproducer. 

```supercollider
(
a = Pbind(
    \degree, 0,
);

b = Pbind(
    \degree, 4,
);

Ppar([
    a,
    Pseq([ Rest(4), b ])
    // Pseq([ (type: \rest, dur: 2), b ]) // <- work around
]).play;
)
```

The work around is quite simple, but I'm wondering if this is simply wrong usage of `Rest` from my side or if it is bug?  For instance, this works:

```supercollider
Pseq([
    Rest(1),
    Pbind(\dur, 1/2, \degree, Pwhite(0, 7, 2))
], inf).play;
```

I added this line in `Rest.sc` under the "Event Support" comment and it seems to work with a very quick test.. But maybe it is rather `Ppar` that needs attention, or my usage of `Rest` that needs to be updated!

`asEvent { ^(type: \rest, dur: value.value) }`

```
ERROR: Message 'asEvent' not understood.
RECEIVER:
Instance of Rest {    (0x11608d2c8, gc=FC, fmt=00, flg=00, set=02)
  instance variables [1]
    value : Integer 4
}
ARGS:
CALL STACK:
        DoesNotUnderstandError:reportError
                arg this = <instance of DoesNotUnderstandError>
        Nil:handleError
                arg this = nil
                arg error = <instance of DoesNotUnderstandError>
        Thread:handleError
                arg this = <instance of Thread>
                arg error = <instance of DoesNotUnderstandError>
        Thread:handleError
                arg this = <instance of Routine>
                arg error = <instance of DoesNotUnderstandError>
        Thread:handleError
                arg this = <instance of Routine>
                arg error = <instance of DoesNotUnderstandError>
        Object:throw
                arg this = <instance of DoesNotUnderstandError>
        Object:doesNotUnderstand
                arg this = <instance of Rest>
                arg selector = 'asEvent'
                arg args = [*0]
        < FunctionDef in Method Ppar:embedInStream >
                arg j = 0
                var outval = <instance of Event>
                var stream = <instance of Routine>
                var nexttime = 0
                var now = 0
        Integer:do
                arg this = 1
                arg function = <instance of Function>
                var i = 0
        Ppar:embedInStream
                arg this = <instance of Ppar>
                arg inval = <instance of Event>
                var assn = nil
                var priorityQ = <instance of PriorityQueue>
        Routine:prStart
                arg this = <instance of Routine>
                arg inval = <instance of Event>
^^ The preceding error dump is for ERROR: Message 'asEvent' not understood.
RECEIVER: Rest(4)
```

**Comment by jamshark70** [comment] 2018-01-19 18:45
To be really technically precise, you need the Ppar to yield silent events (`Event.silent`) rather than Rests. Formally, they aren't really interchangeable.

From a usability perspective, it's a pain in the ass that the current implementation is more strict.

To be honest, at this point, I don't remember if I argued for a more relaxed or a more strict standard. If the latter, I apologize... if the former, I apologize for losing the argument.

**Comment by jamshark70** [comment] 2018-01-20 02:40
For the example to have worked in 3.8, Rest must have implemented `asEvent` in the past, but I can find no evidence that it did. (And I noted that in the email thread last month: "Hmm, I just checked -- this didn't work in 3.8 either. AFAICS here, Rest never implemented asEvent.")

Here is the commit that added `asEvent`: https://github.com/supercollider/supercollider/commit/702cd0c1f4cff283f0d7fe5b95795fe86f24cd0b#diff-7e50aa4b4803fa9f0da0199787a0cfdc -- for SimpleNumber, Event and Nil, but *not* Rest.

@davidgranstrom Did you perhaps have an extension in your 3.8 environment providing `Rest:asEvent`?

I need to reread Ron's objections in the email thread. He's got a few good points, but at the same time, multiple users have found it intuitive to write `Rest(1)` in place of `Event.silent(1)` and I'm not sure the language should split this hair so finely.

**Comment by davidgranstrom** [comment] 2018-01-20 10:56
@jamshark70 I just went back to my previous 3.8 install, and there the example I posted earlier is working. I don't see any added methods for `Rest` in the HelpBrowser either. Any extension which adds methods to a class should show up in there I think? (I did regenerate the docs as well).

And thanks for pointing me to `Event.silent` I have missed that one, will probably use that in the future!

**Comment by jamshark70** [comment] 2018-01-20 13:28
Ohhhh, I get it now. It's tricky -- I really had to think about it.

3.8 doesn't need `Rest:asEvent` because `asEvent` is called on the return value from `someEventStream.next(inevent)` -- but, in the old implementation of Rest, we never return the Rest itself here. When the Rest pops up in the stream, it has the side effect of modifying inevent to be marked as a rest, and then it returns the rest object's value.

So the Pseq stream hits a Rest object, it goes into Rest:embedInStream, where the input event gets `\isRest -> true` put into it, and then embedInStream returns the value (4, in your example). So then the input event is thrown away, replaced by the number, and then SimpleNumber:asEvent redirects to `Event.silent(value)`.

(This, btw, is one reason why it was good to change the Rest implementation. This sort of invisible magic -- a Rest --> number --> Event.silent, without any explicit conversion method -- is really difficult to troubleshoot. I wrote the thing and I completely missed it, in two separate discussions.)

That makes it indeed a regression.

I'll review Ron's e-mail comments tomorrow. When I glanced it over them earlier today, it reminded me that his skepticism about asEvent here is justified on technical grounds. But, I think we need to find a way to make it transparent to the user.

**Comment by telephon** [comment] 2018-01-20 16:44
Since we are supporting `SimpleNumber::asEvent`, we should also support `Rest::asEvent`, I suppose. I find the whole `asEvent` stuff for Numbers a little problematic I have to admit.

**Comment by patrickdupuis** [comment] 2018-01-20 23:31
>That makes it indeed a regression.
We should try and get this fixed in `3.9.1` if possible (tentative release date Jan. 31st).

**Comment by jamshark70** [comment] 2018-01-21 01:55
But Ron is correct: Ppar isn't the only problem.

```
(
p = Pmul(
	\ffreq, 2,
	Pseq([
		Rest(1),
		Pbind(
			\instrument, \filteredsaw,
			\degree, Pwhite(0, 7, inf),
			\ffreq, Pexprand(1000, 4000, inf)
		)
	])
).play;
)

ERROR: Message 'at' not understood.
RECEIVER:
Instance of Rest
```

"OK," we think, "we need asEvent in a lot more places." So, in Pset:embedInStream (Pmul inherits this), `inEvent = evtStream.next(event).asEvent;`, and let's assume we've already added to Rest: `asEvent { ^Event.silent(value) }`. Then:

```
ERROR: Message '*' not understood.
RECEIVER:
   nil
ARGS:
   Integer 2
```

... because Pmul assumes not only that everything coming from the child stream will be an event, but also that every one of those events will include the key being modified. But an `Event.silent` doesn't necessarily include those. (In fact, I ran into this problem in ddwChucklib-livecode, where I had to wrap the event-filtering component in a Pif: https://github.com/jamshark70/ddwChucklib-livecode/blob/master/preprocessor.scd#L2338-L2342).

I guess there are two ways we could go:

- Rest objects should be basically interchangeable with Event.silent. Currently, Event.silent works with Ppar but Rest does not, so, fix that. (Seems to be the thrust of this issue report: narrowly fix something that slipped from 3.8.)

- Or: If we're going to support Rest objects as a drop-in replacement for events in streams, then it's inconsistent to support this for Ppar (maybe even Pspawner) but not support it for other types of filter patterns. (This is Ron's point from the e-mail thread: that this regression is a symptom of a deeper conceptual flaw, and that patching it for Ppar is only a band-aid.)

Probably we should fix the regression here, and open a separate issue for the bigger problem. But I think Ron's objection should be noted: We are assuming that you should be able to stream Rests alongside events transparently, and it may be difficult/impossible to make that assumption universally safe. It may not be helpful to underestimate those difficulties and just patch this one for the sake of expediency.

**Comment by telephon** [comment] 2018-01-21 14:21
I think we shouldn't use rests as synonyms for silent events unless we find a really easy solution

**Comment by telephon** [comment] 2018-01-21 14:30
... or unless a new standard (like calling `asEvent` everywhere) has other substantial advantages

**Comment by jamshark70** [comment] 2018-01-22 08:10
I have to admit, I'm unsure what to do here.

I think we need a review of filter patterns to see where events are expected. I made a quick pass. Most patterns expecting events don't access arbitrary keys, and a couple access keys that are populated in the default event prototype (e.g. `PfadeIn` and `PfadeOut` touch `\amp`). I think Rest objects or Event.silent would at least not produce an error with these.

AFAICS the main concerns are:

- The `Pset` constellation: Pset*, Padd*, Pmul* -- because the user specifies the key to modify, and there's no guarantee it will be in the default event.
- `Pbindf`, because you don't know which `Pkey()`s might appear.
- `Pcollect`, `Pselect`, `Preject`.

I think the options are:

- Leave them as is -- all return values from event streams get passed into these filter patterns. If a user mixes Rest/Event.silent into the stream, there's no guarantee that any specific arbitrary key will always be populated, so it's at the user's own risk. The user is responsible for checking keys.

- Or, change the semantics so that an incoming event where `isRest` is true skips the filter pattern's processing. E.g., where Pset now says `this.filterEvent(inEvent, val);`, it could say `if(inEvent.isRest.not) { this.filterEvent(inEvent, val) };`. I think there's a good case for doing this in Pset* and Pbindf because the user's options are limited to add logic checking for rests. But I would *not* do this for Pcollect etc. because the user can account for it, and we often use Pcollect for bookkeeping side effects and it may be important to know that a rest happened.

If we decide the former is the better approach, then it weakens the case to "fix" Rests in Ppar.

@snappizz, @davidgranstrom -- your thoughts?

```
| Class          | Events? | Notes                                 |
|----------------+---------+---------------------------------------|
| PAbstractGroup | y       | Only puts into inevent                |
| Padd           | y       |                                       |
| Paddp          | y       |                                       |
| Paddpre        | y       |                                       |
| Pbindf         | y       |                                       |
| Pbus           | y       | No processing of stream.next          |
| PfadeIn        | y       |                                       |
| PfadeOut       | y       |                                       |
| Pfin           | y       | No processing                         |
| Pfindur        | y       |                                       |
| Pfset          | y       | No processing                         |
| Pfx            | y       | No processing                         |
| Pfxb           | y       | Delegates to Pbus                     |
| Pgroup         | y       | PAbstractGroup                        |
| Plag           | y       | No processing                         |
| Plambda        | y       | \eventScope                           |
| Pmul           | y       |                                       |
| Pmulp          | y       |                                       |
| Pmulpre        | y       |                                       |
| PparGroup      | y       | PAbstractGroup                        |
| Pplayer        | y       | Only touches parent                   |
| Pset           | y       |                                       |
| Psetp          | y       |                                       |
| Psetpre        | y       |                                       |
| Pspawn         | y       | Could handle Rest; doesn't            |
| Pstretch       | y       | Delta/dur only (ok with Event.silent) |
| Pstretchp      | y       | Delta/dur only (ok with Event.silent) |
| Psym           | y       | No processing                         |
| Psym1          | y       | No processing                         |
| Psync          | y       |                                       |
| Ptsym          | y       | No processing                         |
```

**Comment by telephon** [comment] 2018-03-16 12:30
I'd propose to leave this as it is for now. We should try to avoid conversions like `asEvent` if they don't give us a substantial benefit. E.g. this would be justified where we could combine two rich categories of objects in only this way: `asStream` is a good example.

Use `Event.silent` instead of `Rest`, where an event is expected.

In the future, we could have a look what interface we want an object to fulfill that is passed as Event through an event stream. Then we can document and fix that.

**Comment by davidgranstrom** [comment] 2018-03-18 20:25
Agreed. `Event.silent` is probably what I should have used in the first place. Should I close the issue?

**Comment by telephon** [comment] 2018-03-18 22:04
yes, please - thanks for the report!

**Closed** 2018-03-21 15:26 UTC
Labels: bug, comp: class library
