### ISSUE TITLE
Error with drum pattern code causing server to crash?

### ISSUE THREAD

**Issue by javieryturriaga** [supercollider/supercollider#6325] opened 2024-05-26 16:57 UTC
Bug description: Server crashing upon trying to execute this code:

Steps to reproduce:
1. SynthDef(\drums, {|freq|
	var env = Env.perc(level: 0.1, releaseTime: 0.2).kr(doneAction: Done.freeSelf);
	var sig = WhiteNoise.ar * env;
	var trigger = Impulse.ar(freq);
	sig = Latch.ar(sig, trigger);
	Out.ar(0, [sig, sig])
}).add;
2. Synth(\drums, [\freq, 500]);
~bass = 500;
~snare = 10000;
3. Pdef(\drumBeat,
	Pbind(
		\instrument, \drums,
		\dur, Pseq([0.5, 0.5, 1, 1, 1], 1),
		\freq, Pseq([~bass, ~bass, ~snare, ~bass, ~snare], 1)
	)
).play(TempoClock.default.tempo, quant: 4);

Actual result: Server crashes and I have to manually restart scide

Expected result: A simple drum pattern set to play once through.
![Screenshot 2024-05-26 115631](https://github.com/supercollider/supercollider/assets/151668536/01e2c55f-037d-415a-bf36-e0efe1ba6925)

**Comment by JordanHendersonMusic** [comment] 2024-05-27 14:26
Hi! 
Would you mind following the issue template so we have all the required information and the code is formatted properly? Right now, there isn't enough information to help you.

**Comment by capital-G** [comment] 2024-05-28 10:45
The bug is caused by passing a tempo instead of a clock as the first argument and a `quant` arg on `Pdef.play`.

`Pdef.play` will eventually call `.play` on `EventStreamPlayer`

https://github.com/supercollider/supercollider/blob/e610e6d22190eeeadfc7fb88d4740bf638438e51/SCClassLibrary/Common/Streams/Stream.sc#L563-L567

taking a look at `nextTimeOnGrid` on `Quant`

https://github.com/supercollider/supercollider/blob/e610e6d22190eeeadfc7fb88d4740bf638438e51/SCClassLibrary/Common/Streams/Quant.sc#L14-L16

As `clock` is not a `clock` here but a float instead, this will call `nextTimeOnGrid` on `SimpleNumber` which will be passed the argument `quant` as a float.

https://github.com/supercollider/supercollider/blob/e610e6d22190eeeadfc7fb88d4740bf638438e51/SCClassLibrary/Common/Math/SimpleNumber.sc#L693-L695

And voila - we have an infinite loop which will crash the interpreter.

Instead of fixing this issue "as late as possible", we should maybe simply reject float numbers as a clock in play and fall back to the default clock and yield a warning? At least I don't know what implications changing these nested calls might have across the library?
I think it should be fixed as this could create critical situations in live performances.

Do you have an opinion/suggestion on a fix @telephon ?

**Comment by JordanHendersonMusic** [comment] 2024-05-28 11:37
@capital-G Nice detective work! In that case this is a duplicate of #1981, mind if I close?

**Comment by JordanHendersonMusic** [comment] 2024-06-02 11:03
@javieryturriaga thanks for creating this issue.  Unfortunately it is a known issue, feel free to head on over to the link issues and prs to see why there isn't an obvious fix for this.

**Closed** 2024-06-02 11:03 UTC
Labels: bug, comp: class library
