### ISSUE TITLE
[SC-IDE] Project - create self-contained project

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#310] opened 2012-05-07 12:37 UTC
It should be possible from any project to create a self-contained project. This could do the following:
- Create a new directory.
- Copy in the sc class library, quarks and extensions and plugins. (scsynth and sclang ?)
- Copy all the documents of the project.
- create a new language config and project file that reflects the new file locations.

This project should then be completely portable. You should be able to mail it to someone else and it should Just WorkTM .

This would also allow to archive pieces, that would run several years after they were finished.

Issues:
   What about incompatabilities of the sclang and scsynth with the version of the class library and plugins ? To be truly portable also scsynth and sclang should be included, no ?

**Comment by brianlheim** [comment] 2017-01-14 23:44
Closing as duplicate of #311.

**Closed by brianlheim** 2017-01-14 23:44 UTC
Labels: enhancement, env: Qt IDE
