### ISSUE TITLE
 Empty function crashes interpreter

### ISSUE THREAD

**Issue by organic-jukebox** [supercollider/supercollider#5890] opened 2022-10-22 18:12 UTC
## Environment

* SuperCollider version: 3.12.2
* Operating system: MacOS Monterey 12.6
* Other details (Qt version, audio driver, etc.): Qt 5.15.2

## Steps to reproduce

```supercollider

1 !? {nil} // no crash
1 !? {} // crashes

nil ?? {nil} // no crash
nil ?? {} // crashes

```

## Expected vs. actual behavior

Instead of the empty function being evaluated, the interpreter crashes.

Interpreter has crashed or stopped forcefully. [Exit code: 11]

**Comment by dyfer** [comment] 2022-10-22 20:09
@organic-jukebox thanks for the report!
This is a duplicate of #4924 - I'm going to close this one.

**Closed** 2022-10-22 20:09 UTC
Labels: bug
