### ISSUE TITLE
NRT audio out file length more than defined in render

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#4165] opened 2018-11-21 12:43 UTC
Environment
-----------

* Your SuperCollider version:
* Your operating system and version:

Steps to reproduce
-------------------

```supercollider
// A pattern to render
(
p = Pbind(
	\instrument, \sin,
	\dur, Pseq([1], 1),
	\legato, 1
);
)

// make a score from the pattern
z = p.asScore(duration: 1, timeOffset: 0);

// add synthdef
z.add([0, [
	\d_recv, 
	SynthDef(\sin, {|freq, gate = 1|
		Linen.kr(gate, 0, 1, 0, doneAction: Done.freeSelf);
		Out.ar(0, SinOsc.ar(freq, 0.5pi))
	}).asBytes;
]]);
z.sort;

// print the score, check times
z.score.printAll;

// set pathname
a = PathName.tmp +/+ "temp_sin" ++ UniqueID.next;

// write osc file
z.write(a ++ ".osc");

// render "by hand"
"% -N %.osc _ %-hand.aiff 48000 AIFF int32 -o 1".format(Score.program, a, a).unixCmd;


Current Behavior
----------------

// check duration
SoundFile.use(a++"-hand.aiff", {|f| "dur: %\nnumFrames: %\nsamplerate: %\n".postf(f.duration, f.numFrames, f.sampleRate)})

/* duration should be 1.0
dur: 1.0013333333333
numFrames: 48064
samplerate: 48000
*/
```

this is not much more than 1 second but it means that, if rendering several clips to e.g. for feeding external or internal samplers, the length (and periodicity) is not correct.

**Comment by brianlheim** [comment] 2018-11-21 16:42
dupe of #77. please check open issues before creating a new one.

**Closed by brianlheim** 2018-11-21 16:42 UTC
Labels: comp: scsynth

**Comment by LFSaw** [comment] 2018-11-21 16:45
tried hard to check open issues but seemingly not hard enough. thanks for the heads up
