### ISSUE TITLE
OSCdef argTemplate not removed on reinitialization

### ISSUE THREAD

**Issue by antonhornquist** [supercollider/supercollider#1890] opened 2016-03-07 16:17 UTC
I tried this in SuperCollider-3.7alpha1. Recreate by evaluating the code below. The OSC message sent by the last sendMsg()-invocation should IMO be handled by the OSCdef. It appears the template is not removed. See attached screenshot for output.

```
(
OSCdef(
	\test,
	{ |...args| args.debug(\oscdef) },
	"/test",
	argTemplate: nil // <-- no template
).debug
)

NetAddr.localAddr.sendMsg("/test", 6);
NetAddr.localAddr.sendMsg("/test", -6);

(
OSCdef(
	\test,
	{ |...args| args.debug(\oscdef) },
	"/test",
	argTemplate: [{ |delta| delta > 0 }] // <-- template
).debug
)

NetAddr.localAddr.sendMsg("/test", 6);
NetAddr.localAddr.sendMsg("/test", -6); // <-- not handled, as the template filters away negative values, correct

(
OSCdef(
	\test,
	{ |...args| args.debug(\oscdef) },
	"/test",
	argTemplate: nil // <-- no template
).debug
)

NetAddr.localAddr.sendMsg("/test", 6);
NetAddr.localAddr.sendMsg("/test", -6); // <-- not handled, negative values still filtered away, this is a bug
```

![bug](https://cloud.githubusercontent.com/assets/32165/13575230/0b47ef82-e488-11e5-9c54-bdfe2932e185.PNG)

This is a bug for OSCdef but was brought to surface for me when I subclassed OSCFunc and made my own CustomFunc and Customdef where I noticed templates still hanging around. I believe this pertains to OSCFunc init but I'm not sure.

**Comment by muellmusik** [comment] 2016-03-07 18:24
Not a bug I'm afraid. Rather the problem is that SC cannot distinguish between explicit and implicit nils.

**Comment by antonhornquist** [comment] 2016-03-07 19:22
Can you elaborate on that? To me that sounds like a technical issue or consequence of the current implementation.

Consider the *new method in OSCdef:

```
	*new { arg key, func, path, srcID, recvPort, argTemplate, dispatcher;
		var res = all.at(key), wasDisabled;
		if(res.isNil) {
			^super.new(func, path, srcID, recvPort, argTemplate, dispatcher).addToAll(key);
		} {
			if(func.notNil) {
				wasDisabled = res.enabled.not;
				res.disable;
				try {
					res.init(func, path, srcID, recvPort, argTemplate, dispatcher);
					if(wasDisabled, { res.disable; });
				} {|err|
					res.free;
					err.throw;
				}
			}
		}
		^res
	}

```

Why must the OSCdef be reinitiated? Can't it just be thrown away / freed and a new one be used? Something like (note: totally untested code, just scribbled down):

```
	*new { arg key, func, path, srcID, recvPort, argTemplate, dispatcher;
		var res = all.at(key), wasDisabled;
		if(res.isNil) {
			^super.new(func, path, srcID, recvPort, argTemplate, dispatcher).addToAll(key);
		} {
			res.free;
			^super.new(func, path, srcID, recvPort, argTemplate, dispatcher).addToAll(key);
		}
	}
```

Thanks for your input.

**Comment by antonhornquist** [comment] 2016-03-07 19:30
On second thought, that probably has to do with disabled OSCdef's should keep being disabled. But let's say that's included as an option in the *new method.

**Comment by muellmusik** [comment] 2016-03-07 21:07
The idea is you should be able to just change the specified parts, e.g. swap the function. The help states: "If an OSCdef already exists at this key, its parameters will be replaced with the ones provided (args for which nil is passed will use the old values)."

I think replacing the argTemplate with an empty Array might work (untested)

**Comment by telephon** [comment] 2016-03-07 21:17
The schema that is behind the `def` idea (like `Ndef`or `OSCdef`) is that the object represents a "variable" that can be reassigned but passed around.

**Comment by antonhornquist** [comment] 2016-03-07 21:23
Now I get it. My bad. I didn't perceive OSCdef like that. I read the help file in detail now. You are totally right. I looked at this as a global of sorts, wholly replaced on invocation of *new.

I also now get the `variablename = argvariablename ? variablename;` pattern used throughout `OSCFunc.init`, which was confusing to me.

In practical use, though, isn't this a bit of an issue for the `def` idea? The fact that you can only add new properties.

**Comment by telephon** [comment] 2016-03-07 21:49
It would be generally useful to have a class that signals "reset to default", which could be like `Nil`, but responds to a different test. It could even subclass `Nil`, maybe.

**Comment by antonhornquist** [comment] 2016-03-09 12:26
Don't you think we would benefit from better OSCdef documentation of this particular behavior, though? The behavior is not evident from reading the [helpfile](http://doc.sccode.org/Classes/OSCdef.html) Description which says:

> OSCdef provides a global reference to the functionality of its superclass OSCFunc. Essentially it stores itself at a key within a global dictionary, allowing replacement at any time. Most methods are inherited from its superclass.

And nothing in the Examples section touch upon this.

I could look into extending the OSCdef helpfile for this particular gotcha. Adding some lines of code to the Examples section would make it clearer. What do you think?

**Comment by telephon** [comment] 2016-03-09 16:28
@antonhornquist definitely: if you have a suggestion, that would be very welcome.

**Comment by jamshark70** [comment] 2016-03-13 02:54
There's a workaround that is currently available: `argsTemplate: { true }`, meaning "replace the current argsTemplate with one that deliberately matches everything."

The argument template matcher uses the `matchItem` interface, in which `nil` means "match everything" -- but in this context, `nil` also means "don't change what was already there" and, as Scott said, there is no way to distinguish between them. But instead, you could put in a different matcher that always returns `true`. Currently, this needs to be a function. We could make it a little easier by defining:

```
+ Boolean {
	matchItem { ^this }
}
```

With that addition, you could write `argsTemplate: true` (but that isn't currently supported).

An empty array would not work because `[].includes(anything)` will always be false.

**Comment by telephon** [comment] 2016-03-13 19:18
@jamshark70: I don't think that we should change `Boolean`. This would result in:

```true.matchItem(false)``` to return true, which is at least a change in the interface.

But it would be good if we had a solution to the problem of resetting to default. Maybe it could simply be a method of all `def` objects.

**Comment by muellmusik** [comment] 2016-03-13 19:44
My inclination would be to not be too fine grained about it. You can always free the def, and then start it again.

**Comment by telephon** [comment] 2016-03-13 20:41
We could call `dereference` on the values in such cases:
```
argTemplate = (argtemplate ? argTemplate).dereference;
```
Then you just pass ``` `nil``` if you want to set to default.

**Comment by antonhornquist** [comment] 2016-03-29 21:54
I agree with muellmusik, you can always free the def and recreate it. See pull request for suggestion for clarification on this in the OSCdef help file.

**Comment by antonhornquist** [comment] 2016-03-30 10:18
Doc update merged. Should we close this and say this is by design or do you think some other measures should be taken?

**Closed** 2016-04-05 07:29 UTC
