### ISSUE TITLE
BPF and BBandPass blowing unrecoverably

### ISSUE THREAD

**Issue by tremblap** [supercollider/supercollider#5459] opened 2021-05-24 10:23 UTC
## Environment

* SuperCollider version: 3.11.2
* Operating system: MacOS

## Steps to reproduce

```supercollider
//blow the filter with dumb values (they don't need to be that stupid but that is the best way to reproduce
{BBandPass.ar(WhiteNoise.ar(),0,0)}.play
//stop the synth
//play something
{PinkNoise.ar(1)}.scope
```

## Expected vs. actual behaviour

We get the synth to work visually in the scope (it wiggles) but no audio is coming out of the left channel anymore. The only way to recover the blown audio channel is to restart the synth.

It does the same with BPF.

**Comment by muellmusik** [comment] 2021-05-24 10:49
Hey PA! Assuming I understand, and you meant the only way to recover is to restart _scsynth_, then I think this is maybe an OS issue? I think CoreAudio sometimes mutes applications which output nonsense values.

**Comment by muellmusik** [comment] 2021-05-24 10:51
Although I cannot reproduce this on 10.15.7 and 3.11.2. Left channel comes back for me when I stop the first synth.

**Comment by tremblap** [comment] 2021-05-24 10:52
Indeed I thought it could be the case - so I need to try on another soundcard on the same OS (could be the internal soundcard driver) and also on another OS if that is consistent. I'll update the issue.

**Comment by tremblap** [comment] 2021-05-24 11:34
ok this is a no-bug, or something. I cannot reproduce on an external soundcard either. So it is probably an unhealthy dynamic between the MacOS (same as yours) internal speaker and the scsynth.

One thing for sure that would help: is there a NaN filter at the output of scsynth? I know one can do this:

```supercollider
{Sanitize.ar(BBandPass.ar(WhiteNoise.ar(),0,0))}.play
```

but I struggle to see why Out.ar should allow NaNs - but then I have a solution so that is me sorted, feel free to declare that a false bug.

**Comment by muellmusik** [comment] 2021-05-24 12:09
I suppose one argument is that people might want to Sanitize on a UGen basis, rather than zap a whole synth's output or scsynth's. Might make a reasonable option though.

**Comment by telephon** [comment] 2021-05-24 16:33
> but I struggle to see why Out.ar should allow NaNs

I think that the same my be true also for any other connections between UGens? I think this is the reason why it isn't implemented: these are exceptions, and you may not want to pay the price for the safety where you are sure it isn't needed.

Would a simpler way to sanitize a UGen be helpful?

Maybe:

```supercollider
tidy { ^Sanitize.perform(this.class.methodSelectorForRate(this.rate), this) }
```

Then one could just write
```supercollider
BBandPass.ar(WhiteNoise.ar(),0,0).tidy
```

**Comment by muellmusik** [comment] 2021-05-24 16:53
> Then one could just write
> 
> ```supercollider
> BBandPass.ar(WhiteNoise.ar(),0,0).tidy
> ```

That's nice, but I'd prefer ```.sanitize``` for consistency.

**Comment by joshpar** [comment] 2021-05-24 17:00
I partly understand this, but I also feel like we are protecting against a valid output of these filters. .sanitize is basically filtering that output and we don’t have a way to describe what the output of this filter is. If you input parameters that cause a divide by zero, you get an infinity. Don’t do that. I’m less against this if we can figure out what the effect of this filter is more than ‘it won’t send out an infinity’ - but what should it output? Zeros? Ones / Negative Ones? Why?

**Comment by muellmusik** [comment] 2021-05-24 17:02
You're right of course Josh, but I think the distinction here is it's explicit, so you only filter that valid output if you want. I think in real world use, there are cases, where it's convenient to put in a safety net. IAC Sanitize is already there.

**Comment by joshpar** [comment] 2021-05-24 17:07
OK! I do think it’s better that the user has to explicitly add this method to the output of a UGen. But hopefully we can document this well to avoid surprises on the effect of the UGen. Maybe Sanitize should take a range of valid values? Default to -1 and 1, but allow others (for controls, etc., )

Best,

Josh

**Comment by telephon** [comment] 2021-05-24 18:14
btw. there will have been a method called `sanitize` already ...

> OK! I do think it’s better that the user has to explicitly add this method to the output of a UGen.

Yes. 

> Maybe Sanitize should take a range of valid values? 

Hm, that would be more something for `clip2`. I'm not sure if we can explicitly provide those to filter. From the helpfile: "infinities, NaNs, and subnormal numbers (denormals) "

**Comment by muellmusik** [comment] 2021-05-25 09:46
> Maybe Sanitize should take a range of valid values? Default to -1 and 1, but allow others (for controls, etc., )

It does (default to 0, but that's okay).

Sanitize.ar(in: 0.0, replace: 0.0)
Sanitize.kr(in: 0.0, replace: 0.0)
Arguments:
in	
Input signal to sanitize.

replace	
The signal that replaces bad values.

**Comment by muellmusik** [comment] 2021-05-25 09:47
> btw. there will have been a method called `sanitize` already ...

Ah, then I'd definitely prefer to add tidy.

**Comment by telephon** [comment] 2021-06-01 07:50
Given that the `sanitize` method exists, I close this issue.

**Closed by telephon** 2021-06-01 07:50 UTC
Labels: bug
