### ISSUE TITLE
Strange Resource Folder Path in High Sierra

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#4104] opened 2018-10-02 13:13 UTC
* Your SuperCollider version: 3.10-beta2
* Your operating system and version: macOS 10.11.6, macOS 10.13.6

Steps to reproduce (for bugs)
-----------------------------

1. Launch SuperCollider (path: /Applications/SuperCollider/SuperCollider.app)
2. Type SinOsc into Editor
3. Click the Link to the Path of the Help Document at the end of the Help Document

Expected Behavior
-----------------

SinOsc.schelp must appear in the editor of SC-IDE.

Current Behavior
----------------

Under High Sierra, SuperCollider cannot find the file SinOsc.schelp.
Under High Sierra, the path is as follows:
helpfile source: /private/var/folders/t1/3ttl8f9s1vgb32f639d6d1qm0000gn/T/AppTranslocation/DACA5D33-9802-44CB-8A0C-E6E277245B19/d/SuperCollider.app/Contents/Resources/HelpSource/Classes/SinOsc.schelp

However, the helpfile source in previous macOS (for eample in El Capitan) is as follows: /Applications/SuperCollider/SuperCollider.app/Contents/Resources/HelpSource/Classes/SinOsc.schelp

I think it is a bug.

**Comment by telephon** [comment] 2018-10-02 20:13
I can't produce it on High Sierra, but I have a self-compiled app.

**Comment by brianlheim** [comment] 2018-10-03 04:45
See http://krypted.com/mac-security/app-translocation-services-os-x-10-12/

How did you get SuperCollider into `/Applications` @prko? Read that article and see if it is consistent with what you experience.

It looks like this is an issue with macOS >= 10.12 and ultimately caused by (depending on how you look at it) #3438 or the fact that we don't use a .dmg to have users move the application into `/Applications`. Both are easy to solve, for a price :)

**Comment by prko** [comment] 2018-10-03 09:45
@telephon & @brianlheim 
Thank you!
Both of you are correct!

The application compiled on the same user's account as the logged-in account does not have this problem. The applications compiled on another user account except for the applications within AppStroe has the problem. To resolve this problem. I firstly have run the following command in a terminal window:
```
xattr -r -d com.apple.quarantine /Applications/SuperCollider/SuperCollider.app
```
Then I removed the following folders in _~/Library/Application\ Support/SuperCollider_ folder because I already had launched SuperCollider:
- Help
- HistoryLogs
- QtWebEngine
- sessions
- synthdefs

I also removed the following file:
- archive.sctxar

**However, I think removing only Help folder would be OK.**

If you prefer to buy a licence, then we need probably a cloud funding.

**Comment by prko** [comment] 2018-10-03 18:09
@brianlheim 
> How did you get SuperCollider into /Applications @prko?

sorry to forget to answer:
I had downloaded SuperCollider beta binary from [the Latest Build in Bleeding Edge](http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/develop-latest.html).
After extracting the zip file, I moved the extracted folder _SuperCollieder_ into _Applications_.

**Comment by brianlheim** [comment] 2018-10-06 14:16
Closing as this particular issue has been solved, and we have another ticket for codesigning already.

**Closed by brianlheim** 2018-10-06 14:16 UTC
Labels: env: SCIDE
