### ISSUE TITLE
Quark not properly checked-out and/or updated

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#1864] opened 2016-02-13 13:46 UTC
observable behaviour on SC 3.7.0b1 [d9c59f3] (OS X 10.9.5), initial situation for instance for *ModalityTests*. Note, with the official release of 3.7.0b1 I reinstalled Quarks from scratch, also for testing the functionality.
   already downloaded repository:
```
$ git log --all --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit 
72b893c - (HEAD -> master, origin/master, origin/HEAD) add MIDI sysex string test (8 months ago) <Marije Baalman>
39db867 - Manual tests for OSC, MIDI and initialisation messages. (9 months ago) <Marije Baalman>
d65d6e6 - minor fix (9 months ago) <LFSaw>
55ebd8a - added UnitTest dependency, added TestMKtlDesc (9 months ago) <LFSaw>
d2b60e1 - added intial quark files (9 months ago) <LFSaw>
43b08c3 - Initial commit (9 months ago) <LFSaw>
```
```Quarks.gui``` showing installed, downloaded and available Quarks:

![screen shot 2016-02-13 at 12 44 10](https://cloud.githubusercontent.com/assets/1922103/13027965/32ae1fe4-d261-11e5-801d-71d7aa6b6827.png)
Selecting *ModalityTests* in the gui posts the two unresolved dependencies:
```
-> a QuarksGui
WARNING: Modality not found
WARNING: UnitTest not found
```
@miguel-negrao  kindly fixes this (2 commits), after "Check for updates" which does  ```Fetching https://github.com/supercollider-quarks/quarks.git``` and some other, not notified action (apparently updating repos).
After that the tree looks like this:
```
$ git log --all --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit 
e09b619 - (origin/master, origin/HEAD) Update ModalityTests.quark (2 days ago) <Miguel Negrão>
b58d935 - fix typo in dependecies (2 days ago) <Miguel Negrão>
72b893c - (HEAD -> master) add MIDI sysex string test (8 months ago) <Marije Baalman>
39db867 - Manual tests for OSC, MIDI and initialisation messages. (9 months ago) <Marije Baalman>
d65d6e6 - minor fix (9 months ago) <LFSaw>
55ebd8a - added UnitTest dependency, added TestMKtlDesc (9 months ago) <LFSaw>
d2b60e1 - added intial quark files (9 months ago) <LFSaw>
43b08c3 - Initial commit (9 months ago) <LFSaw>
```
Since (according to @crucialfelix at https://github.com/ModalityTeam/ModalityTests/commit/55ebd8a2f7adfb3e9573cb9ca0f1b0050eb929c3#commitcomment-16056681) the resp. Quark's latest commit is checked out prior to installation it's apparently not involving the newest changes from *origin/master*.

cross-check:
removed the repo from the disk, hit "+" to install it. 
state of the newly downloaded repo:
```
$ git log --all --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit 
e09b619 - (HEAD -> master, origin/master, origin/HEAD) Update ModalityTests.quark (2 days ago) <Miguel Negrão>
b58d935 - fix typo in dependecies (2 days ago) <Miguel Negrão>
72b893c - add MIDI sysex string test (8 months ago) <Marije Baalman>
39db867 - Manual tests for OSC, MIDI and initialisation messages. (9 months ago) <Marije Baalman>
d65d6e6 - minor fix (9 months ago) <LFSaw>
55ebd8a - added UnitTest dependency, added TestMKtlDesc (9 months ago) <LFSaw>
d2b60e1 - added intial quark files (9 months ago) <LFSaw>
43b08c3 - Initial commit (9 months ago) <LFSaw>
```
apparently a ```git merge origin/master``` is missing ... **but** shouldn't a *pull* do *fetch + merge* ?
HTH!

**Comment by crucialfelix** [comment] 2016-02-13 16:23
Thanks for the very detailed write up. I'm still trying to isolate some simple steps: 1 2 3 4 ... voila le bug 

1. Select (Install ?) ModalityTests in Quarks gui
2. Click "check for updates"
3. ?

At this point did you expect ModalityTests to be updated ?  Check for updates just updates the directory, it does not update any Quarks at all.

Did you try:

3. Select ModalityTests, click INSTALL on the LATEST

**Comment by miczac** [comment] 2016-02-13 17:34
ok, I see, so I tried it again, but this way:
I kept the original situation and reset *downloaded-quarks* and *sclang_conf.yaml*.
So, *ModailtyTest* repo is downloaded, not up-to-date (2 commits behind) and not installed.
Now I did not "Check for updates", directly selected  *ModalityTests*, clicked INSTALL on the LATEST in the detail view.
That's what was posted:
```
WARNING: Modality not found
WARNING: UnitTest not found
Installing ModalityTests
WARNING: Tag not found: Quark: ModalityTests[1.0.0] 72b893cd0ff4bf7b3c6e47ea5d580a338904809 
 Possible tags: [  ]
WARNING: Modality not found
WARNING: UnitTest not found
Adding path: /Users/mz/Library/Application Support/SuperCollider/downloaded-quarks/ModalityTests
ModalityTests installed
WARNING: Modality not found
WARNING: UnitTest not found
WARNING: Modality not found
WARNING: UnitTest not found
```
looking at the git log nothing happened.
If I compiled the lang now, it would stoop and I'd have to start over.
Whereas, when doing "Check for updates", the missing commits are fetched but not merged.
Doing this I see two subsequent connections being established. 
After the first, sclang posts ```Fetching https://github.com/supercollider-quarks/quarks.git```. 
The second one acts without notice.
Selecting  *ModalityTests*, and hitting INSTALL on the LATEST in the detail view does nothing different than above, dependencies not resolved, commits not pulled or merged.
Interesting is this "Tag not found"-warning since the (if though old) commit is there. (see my prev. comment)

**Comment by miczac** [comment] 2016-02-13 17:52
BTW, just to be sure not to chase a tester's error: *downloaded-quarks* and *sclang_conf.yaml* are the corresponding entities in question defining the state of the downloaded and installed quarks?

**Comment by miczac** [comment] 2016-02-14 22:08
maybe this helps reproducing the issue, here the -2 commits old repo of *ModalityTests*:
[ModalityTests.zip](https://github.com/supercollider/supercollider/files/129942/ModalityTests.zip)

**Comment by miguel-negrao** [comment] 2016-02-16 00:07
Posting this again, since it is relevant here:



I think I found the issue. In the Git class:

    sha {
        // find what hash is currently checked out
        var out;
        ^sha ?? {
            out = this.git(["rev-parse HEAD"]);
            sha = out.copyRange(0, out.size - 2)
        }
    }
    remoteLatest {
        // find what the latest commit on the remote is
        var out;
        ^remoteLatest ?? {
            out = this.git(["rev-parse origin/master"]);
            remoteLatest = out.copyRange(0, out.size - 2)
        }
    }

It is copying with out.size - 2, that means it is discarding the last char, which means that sha will have 39chars instead of 40. Then when it gets to Quarks#validateRefspec it fails the regex and says that it doesn't find the tag. Don't know why this doesn't manifest in other cases, but I can confirm that changing from -2 to -1 then it checks out the lastest from ModalityTests correctly. @crucialfelix , why does it have out.size - 2 instead of out.size - 1, were you expecting a newline at the end ?

```
x = Git("/home/miguel/.local/share/SuperCollider/downloaded-quarks/ModalityTests")
x.git(["rev-parse HEAD"]).last
```

returns a `b`, not a newline.

**Comment by crucialfelix** [comment] 2016-02-16 09:13
That's it. sha was fixed [fixed in December](https://github.com/supercollider/supercollider/commit/d1538bc59cf641ed9a09f1bebd5e8abed2357340#diff-3bde4e1c7f8bddeff66e895820d4fbb2) but remoteLatest still needs it.

https://github.com/supercollider/supercollider/blob/3.7/SCClassLibrary/Common/Quarks/Git.sc#L70

**Comment by crucialfelix** [comment] 2016-02-21 18:17
I'll do a PR soon.

**Comment by telephon** [comment] 2016-02-21 18:56
ta!

**Closed** 2016-02-29 09:44 UTC
Labels: fix proposed
