### ISSUE TITLE
slang crash on recompile

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1398] opened 2015-04-01 12:09 UTC
alpha0 from releases page OSX 10.10

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   QtCore                          0x000000010d4754a0 QCoreApplication::postEvent(QObject*, QEvent*, int) + 32
1   sclang                          0x0000000108f8d5fb QtCollider::QObject_Finalize(VMGlobals*, PyrObject*) + 75
2   sclang                          0x0000000108f00384 PyrGC::RunAllFinalizers() + 164
3   sclang                          0x0000000108f0e45b shutdownLibrary() + 171
4   sclang                          0x0000000108f0e4ad compileLibrary + 13
5   sclang                          0x0000000108f4503d SC_TerminalClient::interpretInput() + 189
6   sclang                          0x0000000108f4945e void boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&, ...) + 110
7   sclang                          0x0000000108f49394 boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) + 84
8   sclang                          0x0000000108fd50c1 boost::asio::detail::task_io_service::do_poll_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) + 481
9   sclang                          0x0000000108fd4d2d boost::asio::detail::task_io_service::poll(boost::system::error_code&) + 429
10  sclang                          0x0000000108fd4aa4 QtCollider::LangClient::customEvent(QEvent*) + 116
11  QtCore                          0x000000010d4a040a QObject::event(QEvent*) + 874
12  QtWidgets                       0x000000010baac32b QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
13  QtWidgets                       0x000000010baaf648 QApplication::notify(QObject*, QEvent*) + 8136
14  QtCore                          0x000000010d475a5b QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 971
15  libqcocoa.dylib                 0x0000000111921b8e QCocoaEventDispatcherPrivate::processPostedEvents() + 190
16  libqcocoa.dylib                 0x0000000111922411 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 33
17  com.apple.CoreFoundation        0x00007fff91160661 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
18  com.apple.CoreFoundation        0x00007fff911527ed __CFRunLoopDoSources0 + 269
19  com.apple.CoreFoundation        0x00007fff91151e1f __CFRunLoopRun + 927
20  com.apple.CoreFoundation        0x00007fff91151838 CFRunLoopRunSpecific + 296
21  com.apple.HIToolbox             0x00007fff9082e43f RunCurrentEventLoopInMode + 235
22  com.apple.HIToolbox             0x00007fff9082e1ba ReceiveNextEventCommon + 431
23  com.apple.HIToolbox             0x00007fff9082dffb _BlockUntilNextEventMatchingListInModeWithFilter + 71
24  com.apple.AppKit                0x00007fff91bc86d1 _DPSNextEvent + 964
25  com.apple.AppKit                0x00007fff91bc7e80 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
26  com.apple.AppKit                0x00007fff91bbbe23 -[NSApplication run] + 594
27  libqcocoa.dylib                 0x00000001119212fd QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2189
28  QtCore                          0x000000010d47237d QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
29  QtCore                          0x000000010d47535a QCoreApplication::exec() + 346
30  sclang                          0x0000000108fd461e non-virtual thunk to QtCollider::LangClient::commandLoop() + 14
31  sclang                          0x0000000108f44c9c SC_TerminalClient::run(int, char**) + 284
32  sclang                          0x0000000108eb5403 main + 51
33  sclang                          0x0000000108eb53c4 start + 52
```

**Comment by scztt** [comment] 2015-04-11 15:26
Can you post the full crash report on this? Should still be in /Library/Logs/DiagnosticReports

**Comment by vivid-synth** [comment] 2016-08-03 05:14
@miguel-negrao

**Comment by miguel-negrao** [comment] 2016-08-03 10:30
Sorry, no OSX near me at the moment...

**Comment by brianlheim** [comment] 2017-01-19 20:03
@miguel-negrao I'm closing this due to lack of info. If anyone can find a reproducer, open a new issue or reopen this one.

**Closed by brianlheim** 2017-01-19 20:03 UTC
Labels: bug, comp: sclang, waiting for information
