### ISSUE TITLE
Help: links with spaces display with '%20'

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2805] opened 2017-03-20 18:02 UTC
Our url escaping work was too powerful!

e.g. "Original%20SynthDef%20format" in http://doc.sccode.org/Reference/Synth-Definition-File-Format.html

**Comment by brianlheim** [comment] 2017-03-20 18:15
(dupe of #2337)

**Closed by brianlheim** 2017-03-20 18:15 UTC
Labels: comp: help, low hanging fruit, not a big issue
