### ISSUE TITLE
PmonoArtic in ProxySpace with fadeTime kills all monitor synths

### ISSUE THREAD

**Issue by j0py** [supercollider/supercollider#5726] opened 2022-02-15 17:35 UTC
Maybe i want something that is not possible, but if you evaluate the lines below one by one, then after the last line all Monitor synths of all proxies in the ProxySpace seem to disappear:

```
s.boot;
p = ProxySpace.push(s);
~a.play
~b.play
~a = PmonoArtic(\default, \dur, 0.1, \degree, 0);
s.queryAllNodes
p.fadeTime_(0.5)
s.queryAllNodes
~a = PmonoArtic(\default, \dur, 0.1, \degree, 0);
s.queryAllNodes
```
- sometimes you have to repeat the last 2 steps, bust most times not.
- when using Pmono or Pbind, the Monitor synths are not killed
- i have no quarks installed.
- SuperCollider version 3.12.1 (compiled from source) on lubuntu 20.04 LTS.

**Comment by telephon** [comment] 2022-02-15 20:56
yes, I can reproduce this. Not sure yet where the bug is to be found.

As a preliminary workaround, you can use `PatternProxy` (or `Pdef`), which also allows for cross fade.

**Comment by j0py** [comment] 2022-03-11 21:50
Great! Thankyou

Verzonden van mijn HTC

----- Bericht beantwoorden -----
Van: "Julian Rohrhuber" ***@***.***>
Aan: "supercollider/supercollider" ***@***.***>
CC: "Johan Stuijt" ***@***.***>, "Author" ***@***.***>
Onderwerp: [supercollider/supercollider] PmonoArtic in ProxySpace with fadeTime kills all monitor synths (Issue #5726)
Datum: vr, mrt. 11, 2022 19:48

Just tried again, but I can't reproduce this anymore on the latest develop branch (712c32e)

&mdash;Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/supercollider/supercollider/issues/5726#issuecomment-1065393311",
"url": "https://github.com/supercollider/supercollider/issues/5726#issuecomment-1065393311",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dyfer** [comment] 2022-05-04 04:46
Can we close this?

**Closed** 2022-05-04 20:09 UTC

**Comment by dyfer** [comment] 2022-05-04 20:52
re: duplicate class - it seems that you didn't remove the old class library before installing a new version of supercollider. If you remove `SCClassLibrary` folder and run `sudo make install` again it should be fine.

**Comment by j0py** [comment] 2022-10-14 14:50
Today i came across probably the same bug: it also happens when ending a proxy, like: "~proxy.end(2)"

To reproduce:

```
p = ProxySpace.push(s.boot)

~a = Pbind(\dur, 1, \degree, 0);
~a.play

s.queryAllNodes; // note the Monitors of ~a

//~b = Pbind(\dur, 1, \degree, 5);
~b = PmonoArtic(\default, \dur, 1, \degree, 5);
~b.play

s.queryAllNodes; // note the Monitors of ~a and ~b

~b.end(2)

s.queryAllNodes; // error: the Monitors of ~a are gone too

// if you use a Pbind for ~b, then monitors of ~a stay alive

```
SuperCollider 3.12.2 on Lubuntu 20.04, no quarks / extensions installed / SC3plugins installed

**Comment by dyfer** [comment] 2022-10-14 18:28
> Maybe keep the bug open?

@telephon what do you think?

**Comment by telephon** [comment] 2022-10-15 13:55
The thing is that I can't reproduce it on my system. Here, all monitors stay alive also for `PmonoArtic`. Since the problem is on SC 3.12.2, and I am on the latest build, perhaps something was fixed inbetween? @j0py can you try the latest build as well?

**Comment by j0py** [comment] 2022-10-16 08:54
Yes, i will try the latest build and report back

Verzonden van mijn HTC

----- Bericht beantwoorden -----
Van: "Julian Rohrhuber" ***@***.***>
Aan: "supercollider/supercollider" ***@***.***>
CC: "Johan Stuijt" ***@***.***>, "Mention" ***@***.***>
Onderwerp: [supercollider/supercollider] PmonoArtic in ProxySpace with fadeTime kills all monitor synths (Issue #5726)
Datum: za, okt. 15, 2022 15:55

The thing is that I can't reproduce it on my system. Here, all monitors stay alive also for PmonoArtic. Since the problem is on SC 3.12.2, and I am on the latest build, perhaps something was fixed inbetween? @j0py can you try the latest build as well?

&mdash;Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/supercollider/supercollider/issues/5726#issuecomment-1279751019",
"url": "https://github.com/supercollider/supercollider/issues/5726#issuecomment-1279751019",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by telephon** [comment] 2022-10-19 20:27
Ah very good, thanks a lot for testing, Johan.
