### ISSUE TITLE
no quarks

### ISSUE THREAD

**Issue by dpalkowski** [supercollider/supercollider#4067] opened 2018-09-16 21:58 UTC
Environment
-----------

* Your SuperCollider version: 3.8
* Your operating system and version: osx hi sierra 10.13.6

Steps to reproduce (for bugs)
-----------------------------

```supercollider
// Please paste SuperCollider code here.
Quarks.gui;
// It really helps if you try to simplify your example as much as possible.
```

Error message (for bugs)
------------------------
Fetching https://github.com/supercollider-quarks/quarks.git
ERROR: Failed to read quarks directory listing: https://github.com/supercollider-quarks/quarks.git a PrimitiveFailedError
-> a QuarksGui
ERROR: Failed to read quarks directory listing: https://github.com/supercollider-quarks/quarks.git a PrimitiveFailedError
```
// Please paste any error messages here **in their entirety**.
// If this is a SuperCollider error message, include the full stack trace.
// Link to a Gist (https://gist.github.com) if the message is long.
```

Expected Behavior
-----------------
qurks window should populate with quarks.

Current Behavior
----------------
quarks gui window opens, empty.
I saw this mentioned in other threads on the web, but couldn't find a resolution.

**Comment by snappizz** [comment] 2018-09-16 23:46
hi, thanks for the report. 3.8 is too faint in my memory to recall whether this is something we've already addressed.

could you try upgrading to 3.9 or later and seeing if this is still an issue? we no longer do backports to 3.8.x.

**Comment by prko** [comment] 2018-09-17 01:52
You should do the followings:
- git: Do not confuse with github.  https://git-scm.com
- Xcode: it must be installed and launched at least one time.
- Xcode Command Line Tools: it must be installed

**Comment by jamshark70** [comment] 2018-09-17 01:56
Do we really need XCode for quarks? I think no.

AFAIK you only need to install git. I have no idea where the XCode rumor is coming from.

**Comment by prko** [comment] 2018-09-17 02:59
Hm, I experienced similar problems when using Quarks in January 2017. At that time I resolved the problem with these steps. 
Honestly, I do not remember if the error message at that time is the same error message in this thread.
Sorry, if I have misunderstood something here...

**Comment by dpalkowski** [comment] 2018-09-17 03:48
hi folks, I tried replacing with 3.9, same exact error. Which steps did you do to resolve in Jan?  I also just made sure i have the latest git installed, still same result. Is there a plist lurking somewhere that needs to be wiped?

Cheers
dp

**Comment by prko** [comment] 2018-09-17 04:55
1. installing xcode via App Store
2. launching xcode
3. installing xcode command line tool: https://developer.apple.com/download/more/

Please read the following:
https://www.listarc.bham.ac.uk/lists/sc-users/msg59414.html
https://www.listarc.bham.ac.uk/lists/sc-users-2016/msg53560.html

In the sc-users mailing lists, you can find some users had resolved by these steps.
Honestly, I did not understand why it happened, and I am still not understanding what it is..., but it worked.

**Comment by jamshark70** [comment] 2018-09-17 06:02
One of the problems with Quarks is that it doesn't provide any information about the git commands being issued, nor about the commands' output. So, when something goes wrong, we don't have much to go on.

I'm not proposing this (yet) as a PR, but the changes here give some visibility into the commands and results.

https://github.com/jamshark70/supercollider/commit/9b9ef39bed806d947862e22687e3f316db7df1da

With these changes, you can do:

```supercollider
GIt.debug = true;
Quarks.gui;
```

I already have some quarks checked out, so it isn't going to do the automatic checkout. But if I click "check for updates," then I get output like the following:

```
Fetching https://github.com/supercollider-quarks/quarks.git

Executing: cd /home/dlm/.local/share/SuperCollider/downloaded-quarks/quarks && git pull origin master
Command output:
Already up-to-date.

Executing: cd /home/dlm/.local/share/SuperCollider/downloaded-quarks/CCIn && git for-each-ref --format='%(refname)' --sort=taggerdate refs/tags
Empty output, or command failed (error code not available)

Executing: cd /home/dlm/.local/share/SuperCollider/downloaded-quarks/CCIn && git fetch
Empty output, or command failed (error code not available)

...
```

Now... what is also very curious here is `a PrimitiveFailedError`. As far as I can see, the execution flow is that Quarks' Git class calls `Pipe.callSync`, which calls `Pipe.new` --> `Pipe:open` (instance method) --> `Pipe:prOpen`. Then it goes directly to `getLine`.

- `prOpen` could fail if the mode string is wrong. But that shouldn't be the case, because `Pipe.callSync` explicitly specifies `"r"`.

- `getLine` (really `prGetLine`) can fail if it's called on a file that isn't open. This could be where the error is coming from: `callSync` does not check whether the Pipe is open or not -- it just assumes everything is fine.

If I'm right about that, then we might need to be investigating whether pipes are actually working in your system. Maybe try these as a test? The first one tests whether a very simple command works at all. The second test whether a compound cd&&something command causes a problem.

```supercollider
Pipe.callSync("ls ~", { |res| res.postln }, { "onError func".postln });

Pipe.callSync("cd ~ && ls", { |res| res.postln }, { "onError func".postln });
```

**Comment by jamshark70** [comment] 2018-09-17 10:13
> I've already had problems with git when being inside a corporate firewall.
> https: repos would work but not git: ones.
> Could it be something like this ?

In that case, I would expect the system to try to execute the git commands, but fail at the network connection stage.

`a PrimitiveFailedError` in the initial issue report suggests that SC isn't even getting that far.

I think we really need to see exactly the commands that are being issued in Daniel's system -- they should be similar to my example, but maybe there's something special or funky about paths or such.

We also need to know:

- Do *all* Unix commands fail in Daniel's SC installation, or only the ones issued for quarks? (The test statements I wrote earlier should help answer this.)

- Do they fail for both `Pipe.callSync` or also `unixCmd`?
  ```supercollider
  "ls ~".unixCmd;

  "cd ~ && ls".unixCmd;
  ```

That is, differential testing (if it's not clear what's going on, change some variables and find out where the boundaries of the problem lie).

**Comment by jamshark70** [comment] 2018-09-17 10:33
I'm harping on the primitive error because it's important.

If the Pipe *tries* to execute the Unix command and the command fails, there's no primitive error: you get a Pipe object anyway, and the pipe is open. You get `nil` if you try to read anything from it, and closing the pipe will return the error code to you.

```
p = Pipe("noncommand", "r");
-> a Pipe

p.isOpen;
-> true

p.getLine;
-> nil

p.close;
-> 32512

// https://stackoverflow.com/questions/5638321/why-child-process-returns-exit-status-32512-in-unix
// bits 15-8 are the error code
32512 >> 8
-> 127  // and 127 = command not found
```

If there is a primitive error, the above test means it can't be happening in the git layer.

- Maybe opening the pipe is throwing some error. We don't know what the error is, because Quarks code only prints the error object, instead of the error description. We should probably change
  ```supercollider
  ("Failed to read quarks directory listing: % %".format(if(fetch, directoryUrl, dirTxtPath), err)).error;
  ```
  to
  ```supercollider
  ("Failed to read quarks directory listing: % %".format(if(fetch, directoryUrl, dirTxtPath), err.errorString)).error;
  ```

- Or maybe the pipe object is not open. In that case, reading from it will produce a different primitive error.

Until we know what's up with that, we're shooting in the dark.

But I can't reproduce the primitive error without committing a coding error that I know Pipe.callSync is not making. I'm afraid Daniel is the only person who can give us more information at this point.

**Comment by nuss** [comment] 2018-09-17 11:28
@jamshark70 

> Do we really need XCode for quarks? I think no.
I stumbled upon this during a workshop I held in 2016. I tried to install Git via homebrew and it indeed turned out that quarks only worked with Git installed through XCode :(. I don't know if that's still an issue as I'm not using OSX anymore...

**Comment by jamshark70** [comment] 2018-09-17 12:35
> I stumbled upon this during a workshop I held in 2016. I tried to install Git via homebrew and it indeed turned out that quarks only worked with Git installed through XCode

Sounds like a homebrew problem to me, then. Possibly SC was calling a git executable at the wrong location.

**Comment by dpalkowski** [comment] 2018-09-18 05:07
all good folks, thanks...;looks like somthing happened to git during the
last upgrade..note that the latest build of git requires os10.14
Thanks again!

Cheers
dp

**Closed** 2018-09-18 05:36 UTC
Labels: quarks, waiting for information

**Comment by jamshark70** [comment] 2018-09-18 08:15
Also to close the loop on the xcode thing: I found today, in my school's Mac lab, that our `checkForGit` method seems to trigger MacOS to pop up a dialog box instructing the user to install XCode :scream: ... and it does this for just about every action in Quarks.gui. That's not gonna leave a nice flavor in the user's mouth. Probably worth investigating whether that git check could be less invasive and not do unwanted things on Mac.

**Comment by machty** [comment] 2020-01-15 09:57
I can confirm that you need Xcode's version of git to install successfully, though I'm not sure why homebrew git wasn't sufficient.

Silver lining: you don't need to install full Xcode; you can just install the ~180mb command line tools from https://developer.apple.com/download/more/ and it'll work
