### ISSUE TITLE
No titlebars in 3.7alpha under Linux/Gnome

### ISSUE THREAD

**Issue by scazan** [supercollider/supercollider#1544] opened 2015-06-15 01:42 UTC
I've compiled 3.7alpha and am not seeing any titlebars (File, Edit, etc...).

I'm running Gnome 3 on Ubuntu. Works fine when compiling 3.6.

**Comment by jamshark70** [comment] 2015-06-16 00:01
Which Ubuntu version, full Gnome version and window manager? I don't see this problem with gnome-shell on Ubuntu 12.04.

**Comment by scazan** [comment] 2015-06-16 00:58
I'm running Ubuntu 14.04.2 LTS (trusty) and Gnome Shell 3.10.4.

The only strange thing I noticed in the build process was this non-halting error which doesn't look like a make error in particular from what I can tell:
```
...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Error while loading 50dictionaries-common: Symbol's value as variable is void: debian-aspell-only-dictionary-alist
Loading /etc/emacs/site-start.d/50lilypond-data.el (source)...
...
```
A screenshot for reference:
![sc37alpha1](https://cloud.githubusercontent.com/assets/1750321/8173805/cc653d8c-1387-11e5-9236-ce91df1c4fd0.png)

**Comment by jamshark70** [comment] 2015-06-16 01:38
That's *weird*.

Ubuntu 12.04 has gnome-shell 3.4.1, and I don't see this problem.

Also, which Qt version? I got qt 5.4.1 from qt's website, not the Ubuntu repositories or any PPA.

(I have no idea how to fix it -- just gathering info.)

**Comment by scazan** [comment] 2015-06-16 01:45
Hmm.. it's possible that my Qt version is too old. I'm on Qt 5.2.1 installed from aptitude (qt5-default as noted in the README_LINUX.md). 

I'm gonna try upgrading Qt and see if I get the same results...

**Comment by bagong** [comment] 2015-06-16 17:21
Looks like a duplicate of #1374. And even the keyboard problem you report in another issue might have to do with ubuntu specific patches. Unfortunately the situation is quite messy with different Ubuntu versions and -flavors. Global menu works with 14.04 Unity, but not with the other flavors. On 15.04, that comes with Qt5.4.1, the situation seems to relax a bit...

**Comment by vivid-synth** [comment] 2017-03-14 03:53
Closing as there appear to be other issues which cover this.

**Closed by vivid-synth** 2017-03-14 03:53 UTC
Labels: env: SCIDE, os: Linux
