### ISSUE TITLE
Issue triggering old pre-compiled synthdefs in v3.9

### ISSUE THREAD

**Issue by samaaron** [supercollider/supercollider#3266] opened 2017-10-31 11:06 UTC
I tried to throw  `v3.9-beta1` into Sonic Pi but ran into an issue triggering the pre-compiled synthdefs. This behaviour can be reproduced with vanilla SuperCollider:

```
s = Server.new
s.boot
// 
s.sendMsg( '/d_loadDir', "/Users/sam/Development/sonic-pi/etc/synthdefs/compiled/tmp/" ); 
s.sendMsg("/s_new", "sonic-pi-beep", x = s.nextNodeID, 1, 1);
```

Where the `tmp` directory contains a single synthdef:

https://github.com/samaaron/sonic-pi/blob/master/etc/synthdefs/compiled/sonic-pi-beep.scsyndef

EDIT (Brian): v1 file here: https://github.com/samaaron/sonic-pi/blob/36496b69e7e821562c6608a276b4536229d38250/etc/synthdefs/compiled/sonic-pi-beep.scsyndef

The behaviour I observe is that scsynth silently dies when attempting to trigger the synthdef.

This may be because support for the older synthdef byte code has been deprecated? Sonic Pi's synthdefs are compiled with Overtone, which hasn't yet been updated to support the latest byte code format. 

If support for older synthdefs has been deprecated, it would be nice for SuperCollider to not silently die and instead print a warning explaining that the older byte code format has been deprecated - it should also probably listed as a breaking change in the release notes :-)

**Comment by samaaron** [comment] 2017-10-31 13:09
I just taught Overtone about SynthDef version 2 and recompiled the beep synth and it does indeed work with v3.9 of scsynth. 

I'm now fairly confident that the issue is that v1 of the SynthDef API no longer works with scsynth.

**Comment by brianlheim** [comment] 2017-10-31 13:17
@samaaron - thanks for the report! There was something I added recently that may be causing the crash, not directly related to updating the API. I'll look into it.

**Comment by samaaron** [comment] 2017-10-31 14:32
For the record, I updated all of Sonic Pi's synthdefs to v2 and got things up and running nicely with `v3.9.0-beta1` https://twitter.com/samaaron/status/925369255197134849

Thanks so much for everyone's hard work on this huge release :-)

**Comment by brianlheim** [comment] 2017-10-31 14:39
@samaaron - could you check whether this happens at 693c55564dcd9a8662879690179bbfb4a14bb328? that's before i merged #3138

**Comment by samaaron** [comment] 2017-10-31 14:41
Yep, although that'll require me to build SuperCollider from source which I haven't done for a while - I should get some time to do that this weekend (I'm away for the rest of this week) :-)

**Comment by brianlheim** [comment] 2017-10-31 15:05
Ah, no worries! I can also take a look at it on my machine since you've provided the synthdef file. But, I won't be able to get to it until this weekend either, and even then there's a chance I'll be swamped with schoolwork.

**Comment by snappizz** [comment] 2017-10-31 18:42
i can repro this in 693c55564dcd9a8662879690179bbfb4a14bb328, so i think the issue may predate #3138

**Comment by snappizz** [comment] 2017-10-31 19:17
currently bisecting, wish me luck

**Comment by snappizz** [comment] 2017-10-31 19:54
first bad commit is 891fcbc0eddde6503aa97ff4a2faf5413826654c, from #3063 i believe.

**Comment by jparmentervf** [comment] 2017-11-04 18:08
I can take a look as well today... but I'm wondering if 'you need to recompile your SynthDefs' isn't that big of an ask. With SynthDef.add being the primary use case in docs, I think a [BREAKING CHANGE] warning in release notes is the better solution:
[BREAKING CHANGE]: Precompiled SynthDef files before SC 3.9 will not load and could crash the server. Please Recompile SynthDef files if you rely on this functionality.

**Comment by snappizz** [comment] 2017-11-04 19:27
whether or not we make the conscious decision to drop support for old synthdefs, the server shouldn't crash.

**Comment by brianlheim** [comment] 2017-11-20 03:30
I ran this through a debugger, and it's crashing in the same place that #3196 is. I suspect both issues are being caused by the same problem (memory allocation bug), and therefore that fixing one will fix the other. In other words, I am about 60% sure this is _not_ related to the version number.

**Comment by brianlheim** [comment] 2017-11-20 03:48
also - fwiw, @samaaron - that file appears to be in synthdef version 2 format. That's what I see when I inspect it with a hex editor.

**Comment by brianlheim** [comment] 2018-01-03 20:33
@samaaron This issue needs clarification. Is the file linked above an actual reproducer? It's version 2 format AFAICT. Are we sure that the format of that file is correct according to the spec?

**Comment by samaaron** [comment] 2018-01-03 21:00
@brianlheim the files I liked to are on master at Github, and have subsequently been updated to version 2 to allow me to get Sonic Pi working with this 3.9 Beta release.

As far as I understand, the issue I'm referring to can be replicated with any synthdef compiled to v1 of the binary format. 

Here's a link to the v1 versions of the Sonic Pi synthdefs which aren't compatible with the first Beta release of scsynth v3.9:

https://github.com/samaaron/sonic-pi/commit/36496b69e7e821562c6608a276b4536229d38250#diff-f2dc8d650aee220d70a650603c577f6a

**Comment by brianlheim** [comment] 2018-01-03 21:08
Ok, thanks. I've done some testing of my own and it's not true that it can be replicated with any synthdef in v1 format. But, this may be because of the difference between platforms. Either way, more debugging information (stack trace, full error message) would be really helpful.

**Comment by samaaron** [comment] 2018-01-03 21:11
Oh, very interesting - it may very well be a particular weird quirk of the Overtone compiler? Have you been able to replicate the issue with any other synthdef compiled with vanilla sclang?

**Comment by brianlheim** [comment] 2018-01-03 21:32
I'll be home later and can throw this in as well just to make sure. Stepping through with a debugger might show where the issue is.

**Comment by brianlheim** [comment] 2018-01-04 00:35
OK, just tried again with your file. Still not causing problems here (macOS). But, @snappizz says he can reproduce this on Linux. I'm going to step through with the debugger to see if there is any issue.

**Comment by brianlheim** [comment] 2018-01-04 00:36
> Have you been able to replicate the issue with any other synthdef compiled with vanilla sclang?

@samaaron I definitely have not been able to do this, and I haven't heard a report of it. But it's certainly possible.

**Comment by brianlheim** [comment] 2018-01-04 00:42
Aha! I get a segfault in the debug build.

**Comment by jamshark70** [comment] 2018-01-04 01:49
Confirmed, it crashes using scsynth in Ubuntu. I'm on 408aea0e25 (basically 3.9 beta 2).

Running RelWithDebInfo in gdb:

```
Thread 9 "scsynth" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffec132700 (LWP 17966)]
0x00007fffc1a96b94 in Control_next_k (inNumSamples=1, unit=<optimized out>)
    at /home/dlm/share/sc-hjh.git/server/plugins/IOUGens.cpp:163
163			*out = **mapin;
(gdb) where
#0  0x00007fffc1a96b94 in Control_next_k (inNumSamples=1, unit=<optimized out>)
    at /home/dlm/share/sc-hjh.git/server/plugins/IOUGens.cpp:163
#1  Control_Ctor (unit=<optimized out>)
    at /home/dlm/share/sc-hjh.git/server/plugins/IOUGens.cpp:181
#2  0x000000000046226e in Graph_FirstCalc (inGraph=0x7fffb3c2d140)
    at /home/dlm/share/sc-hjh.git/server/scsynth/SC_Graph.cpp:443
#3  0x0000000000468bda in Group_Calc (inGroup=<optimized out>)
    at /home/dlm/share/sc-hjh.git/server/scsynth/SC_Group.cpp:72
#4  0x0000000000468bda in Group_Calc (inGroup=<optimized out>)
    at /home/dlm/share/sc-hjh.git/server/scsynth/SC_Group.cpp:72
#5  0x0000000000461962 in SC_JackDriver::Run (this=0x7fffb2e14010)
    at /home/dlm/share/sc-hjh.git/server/scsynth/SC_Jack.cpp:529
#6  0x0000000000461cac in sc_jack_process_cb (numFrames=<optimized out>, 
    arg=<optimized out>)
    at /home/dlm/share/sc-hjh.git/server/scsynth/SC_Jack.cpp:187
#7  0x00007ffff6ef4c1e in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#8  0x00007ffff6ef4058 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#9  0x00007ffff6f0c680 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#10 0x00007ffff79bc6ba in start_thread (arg=0x7fffec132700)
    at pthread_create.c:333
#11 0x00007ffff5d6b3dd in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

An incompatibility between the old scsyndef format and the new audio-control mapping code might not be surprising.

In scsynth code (SC_GraphDef.cpp), there's GraphDef_Read and GraphDef_ReadVer1 -- possibly, GraphDef_ReadVer1 isn't building the new data structure correctly?

**Comment by brianlheim** [comment] 2018-01-04 01:51
#3382.

> 

> In  scsynth code (SC_GraphDef.cpp), there's GraphDef_Read and  GraphDef_ReadVer1 -- possibly, GraphDef_ReadVer1 isn't building the new  data structure correctly?

This is 100% correct.

**Closed** 2018-01-05 01:42 UTC
Labels: bug, comp: scsynth, waiting for information
