### ISSUE TITLE
ide: focus lost on new document

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2933] opened 2017-06-09 18:39 UTC
When I make a new document, the current document stays in focus. The new document is somewhere else, I have to navigate there specially. This is a new thing (less than two months).

**Comment by brianlheim** [comment] 2017-06-09 18:42
@telephon is this a dupe of #2797?

**Comment by brianlheim** [comment] 2017-06-13 21:05
Since #2797 already has a good deal of documentation/steps to reproduce, let's just put any further info there.

**Closed by brianlheim** 2017-06-13 21:05 UTC
Labels: env: SCIDE
