### ISSUE TITLE
no version 3.7 on ubuntu ppa

### ISSUE THREAD

**Issue by qleonetti** [supercollider/supercollider#2255] opened 2016-07-30 21:55 UTC
https://launchpad.net/~supercollider/+archive/ubuntu/ppa
the last version from 2014, is it possible to update it? 

If not, where can I get SC version 3.7 for ubuntu? 
Thanks!

**Comment by snappizz** [comment] 2016-07-31 19:58
The Ubuntu PPA is definitely in need of an update. @danstowell, I believe you're in charge of that?

You can download the latest stable from here: http://supercollider.github.io/download

**Comment by danstowell** [comment] 2016-07-31 20:09
Hi. I have limited effort available for supercollider now, so I prefer to focus my energy on the official debian package, which then "percolates" into ubuntu. That means that 3.7.x is going to be in Ubuntu Yakkety - see here: http://packages.ubuntu.com/search?keywords=supercollider&searchon=names

**Comment by snappizz** [comment] 2017-12-31 06:36
closing as duplicate of #2917

**Closed by snappizz** 2017-12-31 06:36 UTC
Labels: enhancement, organizational, os: Linux
