### ISSUE TITLE
WARNING: SCDoc: In Applications/SuperCollider.app/Contents/Resources/HelpSource/Classes/UGen.schelp

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6129] opened 2023-11-08 06:21 UTC
## Environment

* SuperCollider version: 3.14.0_dev
* Operating system: macOS

## Steps to reproduce
1. Open Ugen help document in Help Document Browser.

## Expected vs. actual behavior
```
WARNING: SCDoc: In /Users/prko/Dropbox/prko/__myDocs/Writings/Making Sound using Open Sources/mixed/dev - Bleeding edge/SuperCollider.app/Contents/Resources/HelpSource/Classes/UGen.schelp
  Method -belaScope has arg named 'scopeChannel', but doc has 'argument:: channelOffset'.
WARNING: SCDoc: In /Users/prko/Dropbox/prko/__myDocs/Writings/Making Sound using Open Sources/mixed/dev - Bleeding edge/SuperCollider.app/Contents/Resources/HelpSource/Classes/UGen.schelp
  Method -thresh2 has arg named 'function', but doc has 'argument:: thresh'.
```
I was able to fix the problems by doing one of the following
- modifying the schelp file
- modifying the sc file
However, this should be checked by the author of these methods.

**Comment by SimonDeplat** [comment] 2023-11-08 11:24
Hi !
I think arguments names are pretty clear : 'channelOffset' refers to SC's internal way of dealing with busses, whereas 'scopeChannel' is more user oriented, so I'd advocate 'scopeChannel' ?
I don't have any 'thresh2' method on my installation, and searching doc.sccode.org doesn't yield any result. I suppose this comes from a Quark ? Without seeing the method implementation, I still can guess 'thresh' is better than 'function' ?

I'd propose to create a pull request directly when facing those kind of small 'bugs'. Waiting for the developer to give consent might slow or completely block development at some point. And issues are accumulating, which can be frightening at first sight.
Once the pull request is proposed, this stills leaves time for the developer to communicate about the fix, if he disagrees or has a better idea. And if the developer is not present on the project any more, this delegates the responsibility to the reviewer, so at least there's always someone who can approve (or not). This discussion stays open :) .

Anyway thanks for taking the time to fix this issue !

**Comment by redFrik** [comment] 2023-11-08 11:36
duplicate https://github.com/supercollider/supercollider/issues/6059

**Comment by joslloand** [comment] 2023-11-08 19:09
> duplicate #6059

Which is also a duplicate of https://github.com/supercollider-quarks/MathLib/issues/41, regarding `-thresh2`

**Comment by prko** [comment] 2023-11-08 22:53
@redFrik 
@joslloand 

Sorry for the duplicates.
I will search for the same topic before making a thread.

**Comment by joslloand** [comment] 2023-11-08 23:33
> Sorry for the duplicates.

No worries! Often when we're in the process of discovering issues it isn't always clear that what we're observing is a feature of something already noted.

**Comment by dyfer** [comment] 2023-11-11 12:25
Closing as it's a duplicate.

**Closed by dyfer** 2023-11-11 12:25 UTC
Labels: bug
