### ISSUE TITLE
Supernova test failures

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2193] opened 2016-06-18 05:40 UTC
@timblechmann 

Running tests for the first time on Linux

```
$ make test
Running tests...
Test project /home/air/box_build/supercollider/build/testsuite/supernova
      Start  1: buffer_manager_test_run
 1/15 Test  #1: buffer_manager_test_run ............   Passed    0.02 sec
      Start  2: callback_interpreter_system_run
 2/15 Test  #2: callback_interpreter_system_run ....   Passed    0.01 sec
      Start  3: memory-pool_test_run
 3/15 Test  #3: memory-pool_test_run ...............   Passed    0.01 sec
      Start  4: server_dsp_thread_queue_test_run
 4/15 Test  #4: server_dsp_thread_queue_test_run ...   Passed    0.83 sec
      Start  5: server_dsp_thread_test_run
 5/15 Test  #5: server_dsp_thread_test_run .........   Passed    3.92 sec
      Start  6: server_node_graph_test_run
 6/15 Test  #6: server_node_graph_test_run .........***Failed    0.01 sec
      Start  7: server_scheduler_test_run
 7/15 Test  #7: server_scheduler_test_run ..........   Passed    0.33 sec
      Start  8: server_synth_factory_test_run
 8/15 Test  #8: server_synth_factory_test_run ......   Passed    0.01 sec
      Start  9: server_test_run
 9/15 Test  #9: server_test_run ....................***Failed    0.25 sec
      Start 10: simple_pool_test_run
10/15 Test #10: simple_pool_test_run ...............   Passed    0.01 sec
      Start 11: sized_array_test_run
11/15 Test #11: sized_array_test_run ...............   Passed    0.01 sec
      Start 12: sndfile_backend_test_run
12/15 Test #12: sndfile_backend_test_run ...........   Passed    1.02 sec
      Start 13: static_pool_test_run
13/15 Test #13: static_pool_test_run ...............   Passed    0.01 sec
      Start 14: timetag_test_run
14/15 Test #14: timetag_test_run ...................   Passed    0.01 sec
      Start 15: perf_counter_test_run
15/15 Test #15: perf_counter_test_run ..............   Passed    0.01 sec

87% tests passed, 2 tests failed out of 15

Total Test time (real) =   6.48 sec

The following tests FAILED:
      6 - server_node_graph_test_run (Failed)
      9 - server_test_run (Failed)
Errors while running CTest
Makefile:72: recipe for target 'test' failed
make: *** [test] Error 8
```

```
 supernova $ ./server_node_graph_test 
Running 19 test cases...
/home/air/box_build/supercollider/testsuite/supernova/server_node_graph_test.cpp(27): fatal error: in "simple_synth_test_1": critical check n.group_count() == 1u has failed [0 != 1]
/home/air/box_build/supercollider/testsuite/supernova/server_node_graph_test.cpp(144): fatal error: in "free_all_test": critical check n.group_count() == 2u has failed [1 != 2]
/home/air/box_build/supercollider/testsuite/supernova/server_node_graph_test.cpp(186): fatal error: in "free_deep_test": critical check n.group_count() == 2u has failed [1 != 2]

*** 3 failures are detected in the test module "Master Test Suite"
```

```
 supernova $ ./server_test 
Running 3 test cases...
unknown location(0): fatal error: in "server_test_1": boost::interprocess::bad_alloc: boost::interprocess::bad_alloc
/home/air/box_build/supercollider/testsuite/supernova/server_test.cpp(29): last checkpoint: "server_test_1" entry.
unknown location(0): fatal error: in "server_test_2": boost::interprocess::bad_alloc: boost::interprocess::bad_alloc
/home/air/box_build/supercollider/testsuite/supernova/server_test.cpp(48): last checkpoint: "server_test_2" entry.
unknown location(0): fatal error: in "server_test_3": boost::interprocess::bad_alloc: boost::interprocess::bad_alloc
/home/air/box_build/supercollider/testsuite/supernova/server_test.cpp(66): last checkpoint: "server_test_3" entry.

*** 3 failures are detected in the test module "Master Test Suite"
```

**Comment by snappizz** [comment] 2016-06-27 16:26
Exact same results here.

**Comment by vivid-synth** [comment] 2016-07-31 18:23
Happens on Windows also: https://github.com/supercollider/supercollider/issues/1717

**Comment by vivid-synth** [comment] 2016-08-16 19:34
I don't have time to git-bisect this at the moment, but while git-bisecting another ticket, I discovered that at least one of these tests passed in the past:

```server_node_graph_test_run``` succeeds on ce1524052fc14a26edf7961e5ec19c408bec6a8a

**Comment by snappizz** [comment] 2017-01-15 18:14
Dupe of #1717.

**Closed by snappizz** 2017-01-15 18:14 UTC
Labels: bug, comp: supernova
