### ISSUE TITLE
Interpreter crashes on large selection in IDE

### ISSUE THREAD

**Issue by thormagnusson** [supercollider/supercollider#1499] opened 2015-05-26 17:14 UTC
Bug description: Interpreter crash on text selection

Steps to reproduce:
1. Make a file with ca. 250 lines of code (any text will do)
2. Go to the bottom of the file, click and start to drag upwards (to select all the text)
3. Wait until you reach the top of the file.

Actual result: Interpreter has crashed or stopped forcefully. [Exit code: 0]

Expected result:

**Comment by gusano** [comment] 2015-05-26 17:20
What OS are you on?

I cannot reproduce that with a build from yesterday on linux.

**Comment by thormagnusson** [comment] 2015-05-26 17:31
Very sorry to omit that info. This is on OSX - Yosemite. We should probably add an "OS: " field to the bug description here on Github. I just tried again and it does not happen every time (not for me now actually - weird stuff).

**Comment by scztt** [comment] 2015-05-26 18:17
Btw, you can use the "os: Mac OS X", "os: Windows" or "os: Linux" labels for known OS-specific bugs. I would generally recommend only tagging when it's confirmed (or at highly probable) that the issue only affects that OS.

**Comment by sofakid** [comment] 2015-05-28 05:48
i'm fixing the IPC for the windows port, I believe this won't happen with my changes.

**Comment by bagong** [comment] 2015-05-28 06:48
Ah, yes Lucas, if this is related, in fact on Windows the interpreter crashes after selecting just a few letters by mouse drag...

**Comment by telephon** [comment] 2015-06-02 14:21
Yes, I can reproduce on OS X 10.10

````
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   QtCore                        	0x000000011344a4a9 QVariant::toInt(bool*) const + 73
1   sclang                        	0x000000010efba943 SCIpcClient::updateDocSelection(QList<QVariant> const&) + 83 
````

**Comment by scztt** [comment] 2015-06-07 20:15
@telephon , @thormagnusson - I can't repro on Yosemite. There's nothing in the crashing code that varies in any important way with the size of the selection... I wonder if this is actually caused by rapidly sending messages via SCIpcClient, and iteratively selecting an entire large document is just the easiest way to repro?

If someone can catch the crash in a debugger, can you (a) verify that the quuid variable in SCIpcClient::updateDocSelection has a reasonable value (in XCode, the debugger command `p (char*)(quuid.d + 1)` should show something like `"{1bf06ef9-7200-4b89-a606-ec6be38c05a1}"`), and (b) verify that argList has the right number of values (in XCode, `p argList.size()` in the debugger to see this).

**Comment by bagong** [comment] 2015-06-19 15:07
I cannot reproduce this on OS X 10.10.3 with Qt 5.4.2

**Comment by telephon** [comment] 2015-06-19 15:45
I can't reproduce it any more with the latest fresh build.

**Comment by scztt** [comment] 2015-06-27 19:01
Let's leave this open until we close out 3.7? Heap corruption issues like this are hard to pin down, and often psuedo-fixing changes just move the crash to somewhere else. Of all the 3.7 bugs in the last few months, this one is maybe the worst, and thus warrants extra caution....

**Comment by telephon** [comment] 2015-06-27 19:24
Ok, sure, let's keep it open!

**Comment by bagong** [comment] 2016-10-27 19:59
I cannot reproduce this anymore on Windows and OSX. And this is after Luis' IPC fix.

**Comment by brianlheim** [comment] 2017-01-27 16:29
Ping. @scztt how do you feel about closing this now and/or opening a more appropriately named issue?

**Comment by bagong** [comment] 2017-02-20 11:10
Yes. The situation is likely completely different from what it was back then anyways, as Luis' cross platform IPC rework has been merged (quite some time ago). We tested large copy-pastes at the time and couldn't reproduce something like this anymore. Even creating a new issue isn't of much use I think, until somebody can reproduce something similar...

**Comment by brianlheim** [comment] 2017-02-20 14:16
Great!

**Closed by brianlheim** 2017-02-20 14:16 UTC
Labels: bug, cannot reproduce, crash, os: macOS, severe, waiting for information
