### ISSUE TITLE
switch() - Segfault in one situation

### ISSUE THREAD

**Issue by paum3** [supercollider/supercollider#6199] opened 2024-01-18 14:43 UTC
## Environment

* SuperCollider version: 3.14dev
* Operating system: Archlinux
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
(
        a = 7.rand.postln;
	switch(a,
		0,{},
		1,{},
		2,{},
		3,{},
		3,{}
	)

)
```

## Expected vs. actual behavior
As you can see in the code above, there are two '3' - which is of course a programming mistake but the sclang segfaults when ```a = 2```  - one value before the duplicates (two threes). Run this code several times to generate ```2```, or write ```switch(2 ...```
On my system it segfauts.

**Comment by cdbzb** [comment] 2024-01-18 16:18
confirmed on Mac (Big Sur - Intel)

**Comment by paum3** [comment] 2024-01-19 12:37
Further invesigation.

Slighty changed previous code, no segfault
```
(
    a = 7.rand.postln;
	switch(a,
		0,{},
		1,{},
		2,{\allgood.postln},
		3,{},
		3,{}
	)
)
```


It is strange. I was looking into the definition of ```switch``` in ```Object.sc```, I don't see any issue in there:


```
switch { arg ... cases;
		cases.pairsDo { | test, trueFunc |
			if (this == test.value) { ^trueFunc.value };
		};
		if (cases.size.odd) { ^cases.last.value };
		^nil
	}
```

**Comment by cdbzb** [comment] 2024-01-19 16:00
```
(
        a = 1;
	switch(a,
		2,{},
		3,{},
		3,{}
	)
)
```
is fine but
```
(
        a = 2;
	switch(a,
                1,{},
		2,{},
		3,{},
		3,{}
	)
)
```
fails: it seems the number of items needs to be odd *and* the last two tests equivalent

**Comment by mossheim** [comment] 2024-01-20 22:35
duplicate of https://github.com/supercollider/supercollider/issues/1005, please search open issues before reporting.

**Closed by mossheim** 2024-01-20 22:35 UTC
Labels: bug
