### ISSUE TITLE
Compile ERROR when starting sclang: Class extension for nonexistent class 'Document'

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1396] opened 2015-04-01 07:47 UTC
When not using the IDE, the Document class no longer exists.

These ERRORs are reported on compile, though it doesn't seem to be fatal. 
It still compiles. So maybe they are better as warnings.

I'm not even sure where the magical Document class is now. It would have been better not to have removed it, because there is now a mess of if-statements in classes and quarks.

``` supercollider
ERROR: Class extension for nonexistent class 'Document'
     In file:'/deprecated/3.7/deprecated-3.7.sc'
ERROR: Class extension for nonexistent class 'Document'
     In file:'/Platform/osx/AutoComplete/AutocompleteExtensions.sc'
    numentries = 1052068 / 15908574 = 0.066
    5879 method selectors, 2706 classes
    method table size 16806840 bytes, big table size 127268592
    Number of Symbols 13718
    Byte Code Size 444013
    compiled 427 files in 0.59 seconds
compile done
Execution warning: Class 'Document' not found
```

**Comment by muellmusik** [comment] 2015-04-01 11:14
Autocomplete extensions are obsolete now anyway, or? It refers to CocoaGUI and I think has been superseded by the IDE autocompletion.

The deprecated stuff is also SCApp related IIRC. Probably it makes sense to have it in IDE builds at least for the next version so users get warnings, but there should be subfolders in deprecated with the same exclusions as in the main class lib. That way you won't deprecate stuff that shouldn't be included.

Probably the best solution for the Quarks thing is a simple stub class which does nothing, or almost nothing. Either that, or come up with a nice way to have Quarks deal not only with dependencies, but editor/platform compatibility. The latter may be partial, or course. Sounds fun!

**Comment by jamshark70** [comment] 2015-04-01 12:38
Autocomplete extensions are definitely obsolete. Dump them.

**Comment by scztt** [comment] 2015-05-26 18:51
@crucialfelix - Can you confirm this was fixed by #1461?

**Comment by crucialfelix** [comment] 2015-05-26 19:15
that was just the autocomplete extensions.  its not all of the problem.

there are still errors/warnings posted. let's keep the ticket open still,
thanks

**Comment by scztt** [comment] 2015-06-07 20:43
The right solution here is to refactor Document to remove references to ScIDE, and instead call against some kind of LinkedDocument interface, a subclass of which actually calls ScIDE. That way, other IDE's can use Document as well, and even opens the door to allowing sclang TextView's to work as documents. This is most DEFINITELY not a 3.7 change...

For the time being, I think we should just live with the warning, and push this to 3.8? If folks feel like the warning is too confusing/unclean, I would opt for moving the deprecated methods from the deprecated file, directly to the Document class definition, which will prevent the warning.

**Comment by brianlheim** [comment] 2017-02-07 14:36
Closing as dupe of #1208

**Closed by brianlheim** 2017-02-07 14:36 UTC
Labels: bug, comp: class library
