### ISSUE TITLE
Synth overridden release time is always linear

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3782] opened 2018-06-11 08:39 UTC
Irrespective of the envelope release segment shape, when providing a release time for `Synth.release(time)`, the release is linear.

This is documented behavior (in `EnvGen` help), but still I suppose it is not what we really want.

reproducer:

```supercollider



SynthDef(\test, { |out, gate=1| Out.ar(out, SinOsc.ar(1e3) * EnvGen.kr(Env.asr(curve:-4), gate, doneAction:2)) }).add;


(
fork {
	a = Synth(\test, [\out, 77]);
	0.2.wait;
	defer { 77.asBus.plot(1) };
	a.release(1);
}
)



(
fork {
	a = Synth(\test, [\out, 77]);
	0.2.wait;
	defer { 77.asBus.plot(1) };
	a.set(\gate, 0);
}
)
```

**Comment by LFSaw** [comment] 2018-06-11 09:11
Definitely not what I'd expect, especially for doing crossfades...

**Comment by LFSaw** [comment] 2018-06-11 09:35
From `Node.schelp`: 

> This is a convenience method which assumes that the synth contains an envelope generator (an EnvGen, Linen, or similar UGen) running a sustaining envelope (see Env) and that it's gate argument is set to a control called \gate. This method will cause the envelope to release.
Arguments:
**releaseTime** if not nil, it will override the envelope's decay or release time.

In this description there is no mention of "forced", it could be rather interpreted as a "late decision" :) .

If we come to the conclusion that this is not worth (or too complicated) to change, we should at least add a comment here (telling that this is considered a forced release and pointing to the corresponding `EnvGen` description).

Note that there's a typo in the `EnvGen:gate` description in the `EnvGen` schelp:

`If gate < 0` >> `If gate < -1`

**Comment by telephon** [comment] 2018-06-11 10:22
>I don't see much of an issue here. Forced release time always struck me as an emergency thing to do. 

Then why doesn't `Synth.release` set the gate to zero and set some release time parameter? I suppose the main problem is that we have no accepted convention about the name of a release time parameter.

**Comment by telephon** [comment] 2018-06-11 10:30
Reading the code of `EnvGen` it seems that it just was the simplest thing to do at the time.

https://github.com/supercollider/supercollider/blob/develop/server/plugins/LFUGens.cpp#L2789

The main reason why it is linear (I think) is that it makes it easier to calculate the values for the correct time. But this has to be done also for other segments elsewhere, so it is probably more a matter of refactoring that.

I understand that it is not a big issue, but still, it caused a bug in jitlib that we didn't notice for a very long time.

**Comment by jamshark70** [comment] 2018-06-11 10:32
In EnvGen, it's directly called "Forced release":

http://doc.sccode.org/Classes/EnvGen.html#Forced%20release

"If the gate of an EnvGen is set to -1 or below, then the envelope will cutoff immediately. The time for it to cutoff is the amount less than -1, with -1 being as fast as possible, -1.5 being a cutoff in 0.5 seconds, etc. The cutoff shape is linear."

(Incidentally, I've adjusted the issue title. Saying that a release is always linear implies that it's true of all releases, but it isn't true when closing the gate normally.)

Anyway... if we want different curves when overriding the release time (I'll go with that phrase instead of "forced release"), then EnvGen has to get the curve specifier somewhere. I can imagine only two possibilities:

- From the Env. Normally, an envelope's release phase consists of only one segment -- then, it's easy. But there can be any number of segments following the releaseNode. Which curve to use? Probably the last one makes the most sense. That might be an acceptable solution -- though it isn't necessarily less arbitrary than settling on a linear fade out in every case.

- From additional inputs to EnvGen. I think that idea is a non-starter. Adding inputs will require other clients to adapt, or exhibit buggy behavior. (You can't add new inputs at the end, because the envelope goes at the end of the input list, and this isn't a fixed size.) Also, then, users would have to handle the extra input to EnvGen.ar or .kr. (Note also that the UGen would require two inputs, releaseShape and releaseCurve.)

Of these two, the least objectionable is to take the last shape/curve given in the Env. I would be OK with this, actually -- no strong objection (except that we don't know if anybody is relying on the linear fade out).

> Then why doesn't Synth.release set the gate to zero and set some release time parameter?

Hm, the user would be responsible for patching the release time argument into the Env, e.g.:

```
SynthDef(\name, { |out, freq, gate = 1, releaseTime = 0.1, ...|
	var eg = EnvGen.kr(Env.asr(0.01, 1, releaseTime), gate, doneAction: 2);
	...
}).add
```

There are already a lot of things for users to mess up -- if release-override depends on *two* SynthDef controls with specific names, I would foresee either a lot of questions being raised on the mailing list, or people simply avoiding the feature because it's too complicated. (The latter of those wouldn't be so bad, in fact.)

**Comment by telephon** [comment] 2018-06-11 11:52
>Of these two, the least objectionable is to take the last shape/curve given in the Env. I would be OK with this, actually -- no strong objection (except that we don't know if anybody is relying on the linear fade out).

Yes, I agree.

**Comment by elgiano** [comment] 2020-03-01 16:35
Hello, I recently run into this problem and thought about a simple solution. How about really overriding the duration of the release segment, and then jumping to release as for when gate==0?
```
else if (gate <= -1.f && prevGate > -1.f && !unit->m_released) {
        // cutoff
        int numstages = (int)ZIN0(kEnvGen_numStages);
        float dur = -gate - 1.f;

        int stageOffset = (unit->m_releaseNode << 2) + kEnvGen_nodeOffset;
        float** envPtr = unit->mInBuf + stageOffset;
        Print("EnvGen overriding dur: %f -> %f\n",*envPtr[1],dur);
        *envPtr[1] = dur;

        counter = counterOffset;
        unit->m_stage = unit->m_releaseNode - 1;
        unit->m_released = true;
        return false;
    }
```

**Comment by jamshark70** [comment] 2020-03-01 23:24
> How about really overriding the duration of the release segment, and then jumping to release as for when gate==0?

The other problem is, how do you know there is only one release segment? The releaseNode defines where the release *begins* but there is no requirement that there be one and only one segment for the release: e.g., if the user wanted the release to do a weird reverse-reverb kind of thing, she might write `Env([0, 0.8, 0.1, 1, 0], [0.01, 2, 0.8, 0.1], -4, releaseNode: 2)`. So if you do a forced release and overwrite the duration of the first release segment, the total release time here will be new_release_time + 0.1.

I think this is one of the reasons why the emergency cutoff release time was implemented as a total replacement for the release phase. It was never intended to be a general purpose release.

If you want that kind of control over release time, I'd suggest to make the release time and curve into synth arguments and set them at the same time as the gate: `node.set(\rel, 1.2, \relCurve, -3, \gate, 0)`.

**Comment by elgiano** [comment] 2020-03-02 00:02
Ok, I see your point. I'm then thinking about using curve and end level from Env's last node, instead of taking them from the release node. As you said earlier, it's as arbitrary as using the linear ramp, but at least would be useful for simpler envs like Env.asr or Env.perc. How about that?

**Closed** 2020-05-03 14:16 UTC
Labels: comp: class library

**Comment by caseybasichis** [comment] 2020-05-10 00:33
I'm getting unexpected behavior releated to this change.

    the last commit where it works is 
        80c23102d67b6018a79548b1c5b67773ae8bee4f
    and the first commit where it's b0rken is
        ce7361baf79e76c2581d61ec730bdc786a6616dd

Original output:

http://www.caseyjamesbasichis.com/sc/old_sc_doneAction14.wav

Latest pull:

with a single doneAction:13/14, no gating or other EnvGen args:

http://www.caseyjamesbasichis.com/sc/new_sc_pop.wav

removing doneAction altogether, the evenlopes are motionless:

http://www.caseyjamesbasichis.com/sc/new_sc_no_envelope_movement.wav


Could this be NRT mode specific?  The sc is below.  There is no gating and the args are all default but one.


    var srv = Server(\nrt,     
    options: ServerOptions.new 
    .numOutputBusChannels_(2)  
    .numInputBusChannels_(2)   
    );

    // TEST MAX ENV POINT COUNTS
    var e_ct_1  = 128;
    var e_ct_2  = 1024;

    // GLOBAL PER NOTE Pitch and Db CURVES
    var epg = SynthDef(\exp_and_pitch, { arg exp_bus=0, pitch_bus=1;
        var exp_env   = NamedControl.ir(\exp_env,   Env.newClear(e_ct_1));
        var exp       = EnvGen.kr(exp_env, doneAction: 14); 
        var pitch_env = NamedControl.ir(\pitch_env, Env.newClear(e_ct_1));
        var pitch     = EnvGen.kr(pitch_env);
        Out.kr(exp_bus,   exp);
        Out.kr(pitch_bus, pitch);
    }).asBytes;

    // NOISE MODULATOR
    var nsm = SynthDef(\noise_mod, { arg outbus = 0;
        var wdt_env  = NamedControl.ir(\wdt_env, Env.newClear(e_ct_1));
        var width    = EnvGen.kr(wdt_env);
        var lp_env   = NamedControl.ir(\lp_env,  Env.newClear(e_ct_1));
        var lp_hz    = EnvGen.kr(lp_env);   
        var hp_env   = NamedControl.ir(\hp_env,  Env.newClear(e_ct_1));
        var hp_hz    = EnvGen.kr(hp_env);
        Out.kr(outbus, HPF.kr(LPF.kr(WhiteNoise.kr * width, lp_hz.midicps), hp_hz.midicps));
    }).asBytes;     

    // SINE FM MODULATOR
    var snm = SynthDef(\modulator, { arg outbus = 0, pitch_bus = 0, ovt=0;          
        var pitch     = In.kr(pitch_bus) + ovt;
        Out.ar(outbus, SinOsc.ar(pitch.midicps));
    }).asBytes;

    // MATRIX ROUTER FOR SINE MODULATOR
    var rtr = SynthDef(\router, {  arg inbus = 2, outbus = 0;
        var mtx_env   = NamedControl.ir(\mtx_env,   Env.newClear(e_ct_1));
        var mtx       = EnvGen.kr(mtx_env);
        Out.ar(outbus, In.ar(inbus) * mtx);
    }).asBytes;

    // SINE CARRIER
    var crr = SynthDef(\carrier, { arg outbus = 0, 
                                   fm_mod_bus = 0, am_mod_bus = 0,
                                   pitch_bus  = 0, exp_bus    = 0,
                                   ovt        = 0;  
        var fm_mod = In.ar(fm_mod_bus);
        var am_mod = In.ar(am_mod_bus);
        var pitch  = In.kr(pitch_bus) + ovt + fm_mod;   
        var exp    = In.kr(exp_bus)   - 85  + am_mod;
        Out.ar(outbus, SinOsc.ar(pitch.midicps, 0, exp.dbamp).dup);
    }).asBytes;

    // ENVELOPES
    var pitch_env = Env([60, 60, 72, 72],       [2.0, 0.5, 1.5]);
    var exp_env   = Env([40, 60, 50, 35],       [1.0, 2.0, 1.0]);
    // NOISE PITCH MOD
    var nm_wdt_p  = Env([24,0,0, 12,0,0],       [0.25, 1.625, 0.125,  0.5, 1.5]);
    var nm_lp_p   = Env([36,36,36, 36],         [2.0, 0.0, 2.0]);
    var nm_hp_p   = Env([24, 48, 36, 60],       [2.0, 0.0, 2.0]);
    // NOISE AMP MOD
    var nm_wdt_a  = Env([24,0,0, 12,0,0],       [0.25, 1.625, 0.125,  0.5, 1.5]);
    var nm_lp_a   = Env([36,12,36, 36],         [2.0, 0.0, 2.0]);
    var nm_hp_a   = Env([6, 24, 36, 48],        [2.0, 0.0, 2.0]);
    // FM ROUTING
    var mtx_1_1_p = Env([0, 0, 5, 0],           [3.0, 0.5, 0.5]);
    var mtx_1_3_p = Env([1, 0],                 [0.5]);
    var mtx_2_1_p = Env([0, 0, 5],              [3.5, 0.5]);
    var mtx_3_1_p = Env([0, 0, 1],              [2.0, 2.0]);
    var mtx_3_2_p = Env([0, 36, 0],             [0.5, 0.5]);
    var mtx_3_3_p = Env([0, 1, 12],             [3.0, 1.0]);
    // AM ROUTING
    var mtx_1_3_a = Env([12, 0, 36],            [3.0, 1.0]);
    var mtx_3_2_a = Env([0, 12, 0, 24],         [1.0, 1.0, 2.0]);

    a = Score([
    [0.0, ['/d_recv', epg]],
    [0.0, ['/d_recv', nsm]],
    [0.0, ['/d_recv', snm]],
    [0.0, ['/d_recv', rtr]],
    [0.0, ['/d_recv', crr]],
    // NOTE GROUP
    [0.0, (g = Group.basicNew(srv)).newMsg],
    // GLOBAL PITCH / EXP CONTROLS AND NOISE MOD
    [0.0, (Synth.basicNew(\exp_and_pitch, srv)).newMsg(g, [\pitch_bus, 0, \exp_bus, 1, \exp_env, exp_env, \pitch_env, pitch_env], \addToTail)],
    [0.0, (Synth.basicNew(\noise_mod,     srv)).newMsg(g, [\outbus, 0, \wdt_env, nm_wdt_p, \lp_env, nm_lp_p, \hp_env, nm_hp_p],  \addToTail)],
    [0.0, (Synth.basicNew(\noise_mod,     srv)).newMsg(g, [\outbus, 1, \wdt_env, nm_wdt_a, \lp_env, nm_lp_a, \hp_env, nm_hp_a],  \addToTail)],
    // MODULATORS
    [0.0, (Synth.basicNew(\modulator,     srv)).newMsg(g, [\outbus, 2, \pitch_bus, 0, \ovt, 0],  \addToTail)],
    [0.0, (Synth.basicNew(\modulator,     srv)).newMsg(g, [\outbus, 3, \pitch_bus, 0, \ovt, 12], \addToTail)],
    [0.0, (Synth.basicNew(\modulator,     srv)).newMsg(g, [\outbus, 4, \pitch_bus, 0, \ovt, 19], \addToTail)],
    // FM ROUTING
    [0.0, (Synth.basicNew(\router,        srv)).newMsg(g, [\outbus, 5,  \inbus, 2, \mtx_env, mtx_1_1_p], \addToTail)],
    [0.0, (Synth.basicNew(\router,        srv)).newMsg(g, [\outbus, 7,  \inbus, 2, \mtx_env, mtx_1_3_p], \addToTail)],
    [0.0, (Synth.basicNew(\router,        srv)).newMsg(g, [\outbus, 5,  \inbus, 3, \mtx_env, mtx_2_1_p], \addToTail)],
    [0.0, (Synth.basicNew(\router,        srv)).newMsg(g, [\outbus, 5,  \inbus, 4, \mtx_env, mtx_3_1_p], \addToTail)],
    [0.0, (Synth.basicNew(\router,        srv)).newMsg(g, [\outbus, 6,  \inbus, 4, \mtx_env, mtx_3_2_p], \addToTail)],
    [0.0, (Synth.basicNew(\router,        srv)).newMsg(g, [\outbus, 7,  \inbus, 4, \mtx_env, mtx_3_3_p], \addToTail)],
    // AM ROUTING
    [0.0, (Synth.basicNew(\router,        srv)).newMsg(g, [\outbus, 10, \inbus, 2, \mtx_env, mtx_1_3_a], \addToTail)],
    [0.0, (Synth.basicNew(\router,        srv)).newMsg(g, [\outbus,  9, \inbus, 4, \mtx_env, mtx_3_2_a], \addToTail)],
    // CARRIERS
    [0.0, (Synth.basicNew(\carrier,       srv)).newMsg(g, [\outbus, 0, \fm_mod_bus, 5, \am_mod_bus, 8,  \pitch_bus, 0, \exp_bus, 1, \ovt, 0] , \addToTail)],
    [0.0, (Synth.basicNew(\carrier,       srv)).newMsg(g, [\outbus, 0, \fm_mod_bus, 6, \am_mod_bus, 9,  \pitch_bus, 0, \exp_bus, 1, \ovt, 12], \addToTail)],
    [0.0, (Synth.basicNew(\carrier,       srv)).newMsg(g, [\outbus, 0, \fm_mod_bus, 7, \am_mod_bus, 10, \pitch_bus, 0, \exp_bus, 1, \ovt, 19], \addToTail)],
    ]);

    a.recordNRT(
        outputFilePath: "~/nrt-help.wav".standardizePath,
        headerFormat: "wav",
        sampleFormat: "int16",
        options: srv.options,
        duration: 8,
        action: { "done".postln; srv.remove; 0.exit  }
    );

**Comment by elgiano** [comment] 2020-05-10 14:54
Thanks for reporting this! I'm looking into it now

**Comment by elgiano** [comment] 2020-05-10 15:42
Sorry, there was indeed a serious typo in my PR, that I introduced during review.
@brianlheim @dyfer I fixed it now, so how do we do it? shall I make another PR to fix it? Or should we roll back my PR, fix it, and merge it again?

**Comment by brianlheim** [comment] 2020-05-10 16:25
@elgiano you can just make another PR to fix it :)

**Comment by elgiano** [comment] 2020-05-10 17:28
#4921

**Comment by brianlheim** [comment] 2020-05-10 17:30
@elgiano no need to apologize, these things happen. i should have been more careful reviewing!

**Comment by caseybasichis** [comment] 2020-05-10 21:36
Back in business. Thank you for such a quick fix!

**Comment by elgiano** [comment] 2020-05-10 21:45
Thanks for catching it and reporting it quickly!
