### ISSUE TITLE
SuperCollider built with XCode 11 toolchain fails to open

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#5188] opened 2020-10-03 03:56 UTC
## Environment

* SuperCollider version: develop
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.): SC built with CMake, using command line tools from XCode 11 

## Steps to reproduce

- Install XCode 11 (11.0, 11.3, 11.6 tested)
- build using regular cmake commands
- try opening by double-clicking the bundle

(trying to open after dragging SC into `/Applications`, as well right-clicking and selecting "Open" results in the same behavior) 

## Expected vs. actual behavior

After successful build, double clicking the SuperCollider bundle results in a dialog stating `"SuperCollider” is damaged and can’t be opened. You should move it to the Trash.`

`SuperCollider` (the IDE) can still be opened from the terminal, but not by double-clicking the bundle, nor the executable inside `SuperCollider.app/Contents/MacOS`.

I have tested various configurations using Travis, here are the results. All version numbers in the table refer to the _build environment_. Opening itself was tested on macOS 10.13.

| macOS | XCode | CMake | QT | opens on double click |
|---|---|---|---|---|
|10.13.6 | 10.1 | 3.15.5 | 5.13.2 | YES | 
|10.13.6 | 10.1 | 3.15.5 | 5.15.1 | YES | 
|10.14.6 | 11.0 | 3.17.0_1 | 5.14.1 | no | 
|10.14.6 | 11.0 | 3.17.0_1 | 5.15.1 | no | 
|10.14.6 | 11.3 | 3.17.0_1 | 5.14.1 | no | 
|10.14.6 | 11.3 | 3.17.0_1 | 5.15.1 | no | 
|10.15.5 | 11.6 | 3.18.0 | 	5.15.0 | no |
|10.15.5 | 11.6 | 3.18.0 | 	5.15.1 | no |

test 1 [artifacts](https://github.com/supercollider/supercollider/releases/tag/3.11-macOS-test-01) and [travis builds](https://travis-ci.org/github/supercollider/supercollider/builds/732433656)
test 2 [artifacts](https://github.com/supercollider/supercollider/releases/tag/3.11-macOS-test-02) and [travis builds](https://travis-ci.org/github/supercollider/supercollider/builds/732442962)

**Comment by brianlheim** [comment] 2020-10-03 04:30
this is because the builds aren't signed by a real developer certificate and therefore gatekeeper stops them from opening while they are quarantined (an app bundle downloaded from the internet will be quarantined by default). all you have to do is move the bundle into `/Applications`, or run `xattr -rc SuperCollider.app` to remove the quarantine status. the 'more info' button on the error dialog leads to the following explanation as well:

> The app has been modified, and its code does not match the original signed code. The app may be broken or corrupted, or it may have been tampered with. If you think that an app has been damaged or tampered with, you should delete it by dragging it to the Trash.

the macos 10.13 + xcode 10 builds working would make sense in that context, i don't think the concept of notarization existed in those versions.

**Comment by brianlheim** [comment] 2020-10-03 04:40
if i'm wrong please feel free to reopen, there are probably still corner cases i'm not aware of w/r/t notarization but i think i encountered most of the behavior while working on the last release

**Comment by dyfer** [comment] 2020-10-03 04:55
I still think something is wrong here.
Moving SuperCollider to `/Applications` does not solve this for me. 
Running `xattr -rc` did allow me to run the app (asked if I want to run it), but the output of the command is suspicious to me:
```
xattr -rc /Applications/SuperCollider\ 6/SuperCollider.app/
xattr: [Errno 13] Permission denied: '/Applications/SuperCollider 6/SuperCollider.app//Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/Resources/empty.lproj'
xattr: [Errno 13] Permission denied: '/Applications/SuperCollider 6/SuperCollider.app//Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/Resources/QtWebEngineProcess.entitlements'
xattr: [Errno 13] Permission denied: '/Applications/SuperCollider 6/SuperCollider.app//Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/Info.plist'
xattr: [Errno 13] Permission denied: '/Applications/SuperCollider 6/SuperCollider.app//Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/PkgInfo'
```

**Comment by brianlheim** [comment] 2020-10-03 04:59
oh. i know what it is... :/ PR coming shortly

**Comment by dyfer** [comment] 2020-10-03 05:20
FWIW the files in the zip archive have a future date (possibly ~8 hrs difference, i.e. one of the Europe's time zones). I wonder if that messes up notarization in any way.

**Comment by brianlheim** [comment] 2020-10-03 16:26
currently bisecting to find when this changed

**Comment by dyfer** [comment] 2020-10-03 16:27
thanks @brianlheim !

**Comment by brianlheim** [comment] 2020-10-03 16:41
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
26aa0385b6622d35df93740e9da550ad053e1bdf
ee5ef5fd474b0bb13ef472a3ae24ad9ffa7eac62
b3e4c8019d6aa5ad095e63624ac2b092d503b6fd
e9563d261211828fff2cd30e0ef764b105d32701
ccc8a88654e5db5cb73920b61c6f5d10678e6f46
We cannot bisect more!
```

which are all from my platform support PR, so that must have been it.

i have a couple thoughts about the possible issue:
- did xcode 9 and 10 do codesigning? if not then it may just be we don't do that right and are just noticing
- this was broken *before* the qt 5.15.1 deployment PR #5178 (which agrees with what marcin is posting above)
- could be that a newer cmake version does codesigning differently too. this seems less likely to me but it's possible.
- macdeployqt has a codesigning command line option, maybe we need to use that
- can we find a way to turn a "broken/damaged" app bundle into a working one locally? experimentation with codesigning here could yield some good results
- both codesign and spctl have verification modes for checking this kind of stuff, maybe that will help pinpoint the problem

**Comment by brianlheim** [comment] 2020-10-03 18:36
i'm investigating this now. for reference:

last good build: supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-79c9d77f3946a3caf49fc0522319b52acd51878d.zip
first bad build: supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-4234f9392344cc6334c4c036d87724f60508adf0.zip

1. the first thing i notice by comparing `tree` output is that the bad build has code signing output at `SuperCollider.app/Contents/_CodeSignature`. aside from that no differences in contents.

2. codesign --verify shows that the bad build has an 'invalid signature' (presumably this is why gatekeeper thinks it's broken), and the good build 'is not signed at all':

```
[brianheim@BrianMBP Downloads]$ codesign --deep --verify bad/SuperCollider.app/
bad/SuperCollider.app/: invalid signature (code or signature have been modified)
In architecture: x86_64
[brianheim@BrianMBP Downloads]$ codesign --deep --verify good/SuperCollider.app/
good/SuperCollider.app/: code object is not signed at all
In architecture: x86_64
```

**Comment by brianlheim** [comment] 2020-10-03 22:01
3. using `codesign --verify` to inspect, QtWebEngineProcess.app and every executable/library in the bad bundle except SuperCollider has no signature. the outer app bundle and SuperCollider (the IDE process) have invalid signatures. this is also consistent with the report that `SuperCollider` does not launch but `sclang` does when run in a shell.

**Comment by brianlheim** [comment] 2020-10-03 22:37
5. i'm able to transform a "bad" app bundle into one that works on my system (after trusting it within system preferences) with the following commands:

```bash
CODESIGN='/usr/bin/codesign --sign - --force --verbose=4'
# select executables, *.app's, dylibs, and frameworks
find SuperCollider.app \( \( -type f -a -perm -1 \) -o \( -name '*.app' \) -o \( -name '*.dylib' \) -o \
    \( -name '*.framework' \) \) -exec $CODESIGN {} \;
$CODESIGN SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework
$CODESIGN SuperCollider.app/Contents/MacOS/SuperCollider
$CODESIGN SuperCollider.app
```

**Comment by brianlheim** [comment] 2020-10-03 23:15
@dyfer can you try the artifact from these build jobs? they're from this branch: https://github.com/supercollider/supercollider/tree/topic/add-ad-hoc-codesigning

all i've done is add the codesigning commands above to the build. i'm able to download them and run them after i allow them through system preferences or run `xattr -cr SuperCollider.app`.

legacy osx: [travis](https://travis-ci.org/github/supercollider/supercollider/jobs/732615440) / [s3](https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-legacy-a9f324b61a97591f0bb510d714816dbc10c076d8.zip)
osx: [travis](https://travis-ci.org/github/supercollider/supercollider/jobs/732615441) / [s3](https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-a9f324b61a97591f0bb510d714816dbc10c076d8.zip)

**Comment by brianlheim** [comment] 2020-10-03 23:40
both open for me, however, i can't use my microphone to record. i guess maybe we need to do even more of the signing process, adding entitlements?

**Comment by joshpar** [comment] 2020-10-04 03:39
So - the OS X one (not legacy) gave me a scary warning. I right clicked and opened, and everything worked. 

Also - my sendBundle(0.1) issue was NOT present on this build! Totally off topic, but that excited me.

Josh

**Comment by dyfer** [comment] 2020-10-04 04:25
On macos 10.13 I can open both, after right-click open and confirmation. 
With legacy build, server boots, everything works.
HOWEVER on the non-legacy boot, both servers fail to start. scsynth segfaults, supernova prints `Bus error: 10` and exits.
@joshpar , did the servers work for you?

**Comment by joshpar** [comment] 2020-10-04 04:37
Yes - that’s how I noticed that the sendBundle issue was gone.

**Comment by brianlheim** [comment] 2020-10-04 04:38
just want to confirm that when yall say everything works, that also includes mic input?

**Comment by joshpar** [comment] 2020-10-04 04:39
For me, on macOS 11, yes - microphone worked. My feedback was awesome.

**Comment by dyfer** [comment] 2020-10-04 04:51
For the record - on legacy build server worked, including sound input. This is to be expected on 10.13, where input was never an issue, at least permission-wise. Microphone permissions started with 10.14 I believe.

**Comment by brianlheim** [comment] 2020-10-04 18:40
@dyfer and i spent some time diagnosing the issue w 10.13 today. here are my notes. all the builds on my machine are done on latest develop (608bb981162c2c26f0a32c09d82557b29774a32e), Xcode 11.5, cmake 3.18.3, Qt 5.15.1, building the install target and then zipping with `zip -qry SuperCollider.zip SuperCollider`. Marcin is testing with these two procedures on macOS 10.13:

1.
- move unzipped folder to `/Applications/SuperCollider`
- unquarantine with `xattr -rc SuperCollider.app`
- double-click app in finder to start it
- boot the server, if the app boots

2.
- from where it is unzipped, open in finder
- boot the server, if the app boots

build 1: Ninja generator, Debug -> (1) and (2) both work
build 2: Xcode generator, Debug -> "SuperCollider is damaged and can't be opened" before running `xattr -rc`, after it starts but server crashes
build 3: Ninja gen, Release -> (1) and (2) both work
build 4: Xcode gen, Debug, signed as in https://github.com/supercollider/supercollider/issues/5188#issuecomment-703173064 -> same as for build 2
build 5: Ninja gen, Release, signed as in https://github.com/supercollider/supercollider/issues/5188#issuecomment-703173064 -> (1) and (2) both work, translocated while quarantined
build 6: Travis build of Ninja+release+no signing, downloaded from http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-444dc45eea7d5d30ac17e4be2ec4fbf5901dfb1e.zip -> (still waiting on Marcin)

(5) is very promising. my current hunch is that cmake's signing steps leaves some metadata in that signing later does not overwrite. next i will try to collect all the signing steps cmake takes during the build and see what differs.

**Comment by brianlheim** [comment] 2020-10-04 18:42
also, i noticed that sclang, scsynth, plugins are signed during the build process, but only *after* they are copied into the bundle. cmake does this:
- build scsynth/sclang/a plugin in its own build directory
- copy into editors/sc-ide/Debug/SuperCollider.app/...
- sign it in its own build directory

i've asked about this on a c++ forum to see if i can get some more information for why cmake behaves this way.

**Comment by brianlheim** [comment] 2020-10-04 18:50
also off-topic but neither @dyfer and i knew this: the app isn't unquarantined when moving the SuperCollider *folder* from ~/Downloads to /Applications ; it's only when you move SuperCollider.app itself. the move also has to be done in Finder directly as far as I'm aware.

**Comment by brianlheim** [comment] 2020-10-04 20:48
build 7: Travis build of Ninja+release+signing as in https://github.com/supercollider/supercollider/issues/5188#issuecomment-703173064: [s3](https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-c5aec18328fac92a2c47508b432ebf6e44400a1d.zip) / [travis](https://travis-ci.org/github/supercollider/supercollider/jobs/732787204)

i *think* there might be a path to an xcode-generator build where everything is automatically signed, using both https://cmake.org/cmake/help/v3.18/prop_sf/MACOSX_PACKAGE_LOCATION.html and `macdeployqt`'s `-codesign=` option. but thanks to that bug in qt5.15.1's macdeployqt which does not deploy QtWebEngineProcess.app, we can't rely on only those features anyway.

i would really like to figure out why cmake does any codesigning steps at all under the xcode generator. we don't set any options related to it. if this were a 'correct' build step, then i would expect other generators to have steps that run `codesign` as well, but this doesn't seem to be true at least for the ninja generator.

**Comment by brianlheim** [comment] 2020-10-04 21:16
i think that build 7 above is what we want to deploy: it launches on 10.15 and 10.13 (thanks again @dyfer for testing). @joshpar says the sendbundle bug is present on 11 Big Sur. so apparently, switching from the Ninja to Xcode generator causes scsynth to segfault while loading plugins on 10.13, whereas switching from Xcode to Ninja causes this Big Sur bug, and yet i don't know how the act of codesigning -- the only difference i've seen between the builds -- could possibly cause either of those things.

**Comment by brianlheim** [comment] 2020-10-04 22:57
here is what i think we should do:

* use make (or ninja) as our generator for macOS builds on 3.11 and develop -- ideally merging #5189 and [the changes from the branch for build 7 above](https://github.com/supercollider/supercollider/compare/topic/travis-ninja)
* document the possible issues sharing a build made with the xcode generator + xcode 11+ (local development builds should still be OK)
* document that we don't have Big Sur support yet, but that the project can be built locally by early adopters of Big Sur
* wait for more info / research on why xcode generator+xcode 11 has broken
* reorganize build system on the develop branch to fix longstanding inverted dependencies and to try using MACOSX_PACKAGE_LOCATION and `macdeployqt -codesign` to get automatic signing

this allows us to get working builds again quickly, and we can also keep looking into the other issues meanwhile. hopefully, any problems caused by switching to make/ninja as our generator should appear during the release candidate process, since these problems seem to appear pretty consistently on launch with the exception of Big Sur.

other notes:
* we could keep an additional build just for Big Sur but since Big Sur is still beta, i don't know if it is a good idea, things could break in other ways once it's released.
* we could keep looking to fix the Xcode-generator build. since we don't know how long that will take, it may not be a good idea if it will keep us from releasing. and if the Ninja-generator build is somehow broken, that would also be really good information to know.
* it is very likely that any solution using `macdeployqt -codesign` won't work anyway with Qt 5.15.1's broken `macdeployqt`

@joshpar @dyfer , what do you think?

**Comment by dyfer** [comment] 2020-10-05 01:26
@brianlheim I agree with all your propositions for the develop branch (switch to ninja temporarily etc).

For 3.11 branch, we could do what you propose, but that's quite a substantial change for a bugfix release. I'm not totally opposing it, but I'd like us to also consider the possibility of sticking with xcode 10 on the 3.11 branch. If we do that, we could:
- temporarily disable updating QT on the release build (IIUC this will change the QT in the release to 5.13.2, which is the same version as in the 3.11.0 release)
  - this means that the [transparent windows](https://github.com/supercollider/supercollider/issues/5033) bug will be still present in 3.11.2
- keep the build system as is (using QT 5.15.1), which will cause to not support macOS 10.12 in the 3.11.2 release *)
  - we would rectify that by providing legacy build (for macOS 10.10+) with the 3.12 release

*) 3.11.0 supports macOS 10.12, while 3.11.1 does not (only 10.13+); we were [discussing](https://github.com/supercollider/supercollider/issues/5177) bringing 10.12 support back in 3.11.2 through a second "legacy" build; if we keep the old build setup for 3.11.2, the legacy build will be introduced with 3.12

**Comment by brianlheim** [comment] 2020-10-05 01:43
yes we can also do that. i would definitely like to keep our build at qt 5.15.1, and i do want to add a legacy build. so would you just propose merging in only the changes to add the legacy build then?

**Comment by dyfer** [comment] 2020-10-05 02:16
I don't think adding a legacy build outside of  #5189 is feasible, IIUC this would cause many conflicts merging 3.11 back to develop. In my proposition we'd either not offer a legacy build until 3.12, or drop QT version on the release build.

**Comment by brianlheim** [comment] 2020-10-05 02:33
i dont think the merge conflicts would be that bad, i am happy to do them myself. there would only be future conflicts when those config sections are edited again, which hopefully shouldnt be too many times before 3.11.2. is that your only reservation?

**Comment by dyfer** [comment] 2020-10-05 03:08
> is that your only reservation?

Yes, that was the main one. Thanks for clarifying.

**Comment by brianlheim** [comment] 2020-10-18 18:22
i believe #5190 closed this, thanks @dyfer!

**Comment by brianlheim** [comment] 2020-10-18 19:35
reopening because we may not have actually solved this, will revisit

**Comment by dyfer** [comment] 2020-10-19 17:46
Just to summarize: 
- currently cmake's xcode generator seems to have an issue with XCode 11 resulting in improper signing
- it seems that switching to ninja generator solves this issue
- our CI builds in `develop` branch use XCode 11 and do not have a fix for this yet
- `3.11` branch is not affected as it uses older XCode

**Comment by dyfer** [comment] 2020-12-25 00:49
As mentioned in https://github.com/supercollider/supercollider/issues/4664#issuecomment-744090103, another (better?) workaround is disable codesigning in cmake:
```cmake -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY="" ..```
In that case we can stick to XCode generator.

**Comment by dyfer** [comment] 2021-02-17 21:27
I wonder what would be a "solution" for this:
- adding `-DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""` to macOS readme?
- adding `-DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""` automatically in our CMake?

**Comment by brianlheim** [comment] 2021-02-17 22:04
since we don't make any other use of code signing in CMake at the moment, i think one thing that would make sense to me would be to add an option() named something like `SC_DISABLE_XCODE_CODESIGNING` to set both of those parameters in CMake, and turn it on by default

**Closed** 2021-02-18 07:38 UTC
Labels: comp: build, os: macOS
