### ISSUE TITLE
Building on ubuntu, boost linking problem

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#4398] opened 2019-05-02 17:10 UTC
with this command
```
cmake  -G"Unix Makefiles"  -DCMAKE_BUILD_TYPE="RelwithDebInfo" -DCMAKE_INSTALL_PREFIX="./sup_install" -DLIBSCSYNTH=on -DSC_QT=OFF -DSC_IDE=OFF  -DSUPERNOVA=ON -DSC_EL=no -DSC_HIDAPI=OFF ../../supercollider

```
after doing make, got this
```
[ 53%] Linking CXX shared library libscsynth.so
/usr/bin/ld: ../../external_libraries/libboost_filesystem.a(operations.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN5boost10filesystem16filesystem_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_4pathESC_NS_6system10error_codeE' can not be used when making a shared object; recompile con -fPIC

```
libboost_filesystem was compiled without complains

**Comment by dvzrv** [comment] 2019-05-02 17:35
Hi! This is a duplicate of #4183 .

**Closed by dvzrv** 2019-05-02 17:35 UTC
Labels: bug
