### ISSUE TITLE
Help browser is blank

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#3249] opened 2017-10-22 21:19 UTC
Submitter: Cassard Zoé
hi,
don't manage to fully open Supercollider : indeed, the Help browser page is absolutely empty when I open Supercollider, consequently I can't find  code examples .

**Comment by jamshark70** [comment] 2017-10-22 23:15
I'm guessing it's the known issue where the username has a non-ascii character, such as Zoé. But, lacking any contact information, it's impossible to follow up with the user. So we may simply have to close it.

**Comment by jamshark70** [comment] 2017-10-22 23:45
Hm, I was about to suggest coming back to the question of a bug report template, but the contact question is a serious one: We shouldn't encourage users to list private email addresses in public bug reports, nor can we create github accounts for them (and casual users won't check back at github anyway).

An extreme solution would be to delete the bug report feature from the IDE and advise users to contact the mailing list. There could be a popup dialog in the IDE to help with that process (or a help page) and explain why we don't recommend automated bug reports. Then we can triage reports instead of having situations like this one, where it's impossible to proceed.

Alternately, accept that many bug reports coming in from the IDE will be less than useful. I don't like leaving things unresolved and I think we could do more to educate users how to avoid their issues falling into digital limbo.

**Comment by scztt** [comment] 2017-10-25 18:14
I don't think the contact issue is a huge one - the dialog that leads to the bug report form explicitly says "submit anonymously" - and, even then, there's a spot on the form for an email address, a checkbox to elide that email from the public part of the bug report, and another request to use the github issues page for reporting. If we see a report with no contact info attached, it means the user has skipped several opportunities to add their contact info or report in other ways - I think it's safe to assume it was intentional.

We can [pre-populate](https://gitreports.com/tutorial) the submission form with a template bug report, which would probably help the quality of the reports we're getting - the [gitreports](https://github.com/supercollider/supercollider/blob/cca12ff02a774a9ea212e8883551d3565bb24a6f/editors/sc-ide/widgets/main_window.cpp#L1650) url simply needs to be amended. The text on the report form itself can be changed by anyone in the supercollider organization, at https://gitreports.com

GitReports is the almost the most simple/crude bug report form conceivable... I recall there being a few commercial options around, but nothing that was really appropriate for an OS project - but that was a few years ago. Maybe there are better options available now? I do think it's important that there be a simple way to report problems that doesn't entail signing up for an email list or joining a cloud service. If I had to join an email list for every OS product I've ever reported a bug on....

**Comment by snappizz** [comment] 2017-12-31 06:14
closing as duplicate of #2441.

**Closed by snappizz** 2017-12-31 06:14 UTC
Labels: bug, gitreports
