### ISSUE TITLE
change qt5-webengine for another stuff

### ISSUE THREAD

**Issue by axelkramble** [supercollider/supercollider#4396] opened 2019-04-29 13:47 UTC
## Motivation

I was trying to install Supercollider 3.10 in my hyperbola arch distro, but it was not possible because of `your-freedom` and `qt5-webengine` are in conflict.

Hyperbola has a version of supercollider, but it's old  (3.8), also installing sc3-plugins is such a headache in old supercollider versions.

I researched and found out Richard Stallman does not recomend to use chromium's project  anymore because i'ts not properly licenced, also this package had a bad reputation talking to google services in the past.

https://trisquel.info/it/forum/whats-wrong-qt5-webengine
https://doc.qt.io/qt-5/qtwebengine-licensing.html 

I'm not much a programmer, so I could not make a fork for changing this (also have no idea how), so I'm writing this issue if anyone could help me fix this.

## Description of Proposed Feature

change qt5-webengine for other free thing 

## Plan for Implementation

I could try to change it, but I would need time.

**Comment by snappizz** [comment] 2019-04-29 20:39
hi, thanks for the report. this is a known issue and top priority for the 3.10.3 release. i have an open PR that allows disabling qtwebengine that you can try out: #4328

closing as duplicate of #4010.

**Closed by snappizz** 2019-04-29 20:39 UTC
Labels: enhancement

**Comment by snappizz** [comment] 2019-04-29 20:51
also wanted to add -- although i knew there are technical barriers with installation of qt webengine, i didn't know about the seriousness of the licensing controversy. thank you for alerting us to that. the urgency of getting a functional webengineless SC is even more clear now!
