### ISSUE TITLE
Supernova: segfault (missing args?)

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#3466] opened 2018-01-24 00:45 UTC
Try adding `Server.supernova` to the example code in https://github.com/everythingwillbetakenaway/DX7-SuperCollider -- it dies with a segfault.

Specifically, it seems to die on e.g. ```[ 9, "InfEfx", 1001, 2, 1000, "lfo_speed", 4.80054, "lfo_wave", 4,"lfo_phase", 1.5708, "envTrig", 0, "envTrig", 1, "pitchCons", 0.297928, "lfoGet1", 0, "lfoGet2", 1, "tameM", 1, "tameC", 0, "lfo_delay", 1.72212, "lfo_amd", 0 ]```.

```InfEfx``` seems to have arguments that aren't provided there (e.g. ```pitch```, ```gate```, ```lfo_pmd```), but it works fine in ```scsynth```.

**Comment by jamshark70** [comment] 2018-01-24 04:28
FWIW, the following does not crash on my machine. I also tried with the full DX7 script, no crash.

Which OS and SC version (or git branch) are you using?

```
(
Server.supernova;

s.waitForBoot {
	SynthDef(\InfEfx, {
		arg outBus=0, pitch, gate,
		lfoGet1 = 0, lfoGet2=1,
		lfo_speed, lfo_wave, lfo_phase,
		lfo_delay, lfo_pmd, lfo_amd, lfo_sync, lfo_pms, pitchCons,envTrig, tameC, tameM,
		eg_r1, eg_r2, eg_r3, eg_r4, eg_L1, eg_L2, eg_L3, eg_L4;
		//
		var lfo, pitchenv, output, randomlfo, multiPitch, lfoAmp;
		//
		FreeSelf.kr(gate);
		lfo = Osc.ar(lfo_wave,lfo_speed, lfo_phase, 0.5 * lfoGet2, 0.5 * lfoGet2) + LFNoise0.ar(lfo_speed, 0.5 * lfoGet1, 0.5 * lfoGet1);
		lfo = lfo * EnvGen.ar(Env.asr(lfo_delay,releaseTime:0.01, curve: -5),envTrig);
		multiPitch = LinLin.ar(lfo, 0, 1, (pitchCons.neg.midiratio * tameM) + tameC, pitchCons.midiratio);
		lfoAmp = LinLin.ar(lfo, 0, 1, lfo_amd * (-3/4), 0);
		
		//Poll.ar(Impulse.ar(10), lfoAmp);
		//PHASE PART++
		//tri en tepeden basliyor
		//sawdown en asagidan baslio
		//pms 4, pmd 40, +-1 semitone yapiyor
		//sawup en yukardan
		//square en asaidan
		//sine sifirdan baslio
		
		Out.ar(200 /*busMePitch*/, multiPitch);
		Out.ar(300 /*busMeAmp*/, lfoAmp)
	}).add;
	s.sync;
	p = ParGroup.new;
	
	s.sendBundle(nil, [ 9, "InfEfx", 1001, 2, p.nodeID, "lfo_speed", 4.80054, "lfo_wave", 4,"lfo_phase", 1.5708, "envTrig", 0, "envTrig", 1, "pitchCons", 0.297928, "lfoGet1", 0, "lfoGet2", 1, "tameM", 1, "tameC", 0, "lfo_delay", 1.72212, "lfo_amd", 0 ]);
};
)
```

**Comment by vivid-synth** [comment] 2018-01-26 00:05
Interesting! The example you give does crash for me.

```
  $ sclang -v
sclang 3.9dev (Built from branch 'master' [2cc157d])
  $ supernova -v
supernova 3.9dev (Built from branch 'master' [2cc157d])
  $ scsynth -v                                    
scsynth 3.9dev (Built from branch 'master' [2cc157d])
```

**Comment by jamshark70** [comment] 2018-01-26 07:41
Actually, it's good that the shorter example crashes in your environment -- a simple, easy reproducer makes it easier to troubleshoot.

But first... 2cc157d doesn't exist in my copy of the repository, neither in 3.9, master nor develop. So I have no way to know about the state of the code in your environment (maybe very recent, maybe weeks old). If you're on one of the beta versions, or somewhere in between, then it's quite possible that I've applied a later fix and you haven't. Plus, as a general rule, once a version goes out of beta status and is released, it's not a good idea to stay on the beta. It wouldn't hurt to update and try again.

If still crashes, run supernova in a debugger. Assuming Linux, first get the server arguments by: `s.options.asOptionsString` -- copy the output to the clipboard. Then:

```
$ gdb supernova
... blah blah...
(gdb) run (paste args here)
```

In SC:

```
s.startAliveThread;  // so sclang notices there's a server running
```

... and run the test code. When it crashes, do `where` at the (gdb) prompt and copy/paste all the output here.

(Of course, you don't need to run it in gdb if there's no crash after updating.)

**Comment by vivid-synth** [comment] 2018-01-27 21:23
```2cc157d``` was a merge commit of mine (just from updating a .schelp file). The previous commit was ```81e3144```, from September.

I'm working on updating my SC but here's the the gdb output for my current crash:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe04af700 (LWP 28979)]
0x0000000000496f24 in malloc_ex (size=352,
    mem_pool=0x7ffff51fb010)                                       
    at /home/air/box_build/supercollider/external_libraries/TLSF-2.4.6/src/tlsf.c:757
757         EXTRACT_BLOCK_HDR(b, tlsf, fl, sl);
```

And here's the output of ```where```:

```
(gdb) where
#0  0x0000000000496f24 in malloc_ex (size=352,
    mem_pool=0x7ffff51fb010)
    at /home/air/box_build/supercollider/external_libraries/TLSF-2.4.6/src/tlsf.c:757
#1  0x000000000042f907 in malloc (size=328, this=<optimized out>)
    at /home/air/box_build/supercollider/server/supernova/sc/../server/../utilities/simple_pool.hpp:128
#2  operator new (size=328)
    at /home/air/box_build/supercollider/server/supernova/sc/../server/node_types.hpp:193
#3  nova::sc_synth_definition::create_instance (
    this=<optimized out>, node_id=1002)
    at /home/air/box_build/supercollider/server/supernova/sc/sc_synth_definition.cpp:114
#4  0x00000000004791fe in create_instance (node_id=1002,
    name=name@entry=0x7fffe046eba0 "\320\321\037\365\377\177",
    this=0x7fffffff1ea8)
    at /home/air/box_build/supercollider/server/supernova/server/synth_factory.hpp:53
#5  nova::nova_server::add_synth (this=0x7ffffff28b60,
    name=name@entry=0x70b11c <nova::static_pooled_class<nova::audio_sync_callback, 1048576ul, true, 16u>::object_pool+8220> "DX7",
    id=id@entry=1002, constraints=...)
    at /home/air/box_build/supercollider/server/supernova/server/server.cpp:120
#6  0x0000000000443b80 in add_synth (target_id=1000, action=0,
    node_id=1002,
    name=0x70b11c <nova::static_pooled_class<nova::audio_sync_callback, 1048576ul, true, 16u>::object_pool+8220> "DX7")
    at /home/air/box_build/supercollider/server/supernova/sc/sc_osc_handler.cpp:1254
#7  nova::detail::(anonymous namespace)::handle_s_new (msg=...)
    at /home/air/box_build/supercollider/server/supernova/sc/sc_osc_handler.cpp:1393
---Type <return> to continue, or q <return> to quit---
#8  0x0000000000456bbe in dispatch_synth_commands<true> (
    endpoint=std::shared_ptr (count 1, weak 1) 0x7fffd8023740,
    msg_size=2488, message=...,
    address=0x70afb0 <nova::static_pooled_class<nova::audio_sync_callback, 1048576ul, true, 16u>::object_pool+7856> "/s_new")
    at /home/air/box_build/supercollider/server/supernova/sc/sc_osc_handler.cpp:3783
#9  nova::detail::sc_osc_handler::handle_message_sym_address<true>
    (this=<optimized out>, message=..., msg_size=2488,
    endpoint=std::shared_ptr (count 1, weak 1) 0x7fffd8023740)
    at /home/air/box_build/supercollider/server/supernova/sc/sc_osc_handler.cpp:3843
#10 0x0000000000457005 in nova::detail::sc_osc_handler::handle_message<true> (this=<optimized out>, message=...,
    msg_size=<optimized out>, endpoint=...)
    at /home/air/box_build/supercollider/server/supernova/sc/sc_osc_handler.cpp:1064
#11 0x0000000000448ceb in nova::detail::sc_osc_handler::handle_packet (this=0x7fffffff5ed8, data=<optimized out>,
    length=<optimized out>,
    endpoint=std::shared_ptr (count 1, weak 1) 0x7fffd8023740)
    at /home/air/box_build/supercollider/server/supernova/sc/sc_osc_handler.cpp:1020
#12 0x0000000000429c82 in nova::callback_system<nova::audio_sync_callback, false, boost::checked_deleter<nova::audio_sync_callback> >::run_callback (this=<optimized out>,
    runme=0x70af88 <nova::static_pooled_class<nova::audio_sync_callback, 1048576ul, true, 16u>::object_pool+7816>)
    at /home/air/box_build/supercollider/server/supernova/./utilities/callback_system.hpp:82
#13 0x000000000042bb2f in operator() (cb=<optimized out>,
    __closure=0x7fffe046ed20)
    at /home/air/box_build/supercollider/server/supernova/./utilities/callback_system.hpp:60
---Type <return> to continue, or q <return> to quit---
#14 run_functor_and_delete<nova::callback_system<callback_type, mpmc, callback_deleter>::run_callbacks() [with callback_type = nova::audio_sync_callback; bool mpmc = false; callback_deleter = boost::checked_deleter<nova::audio_sync_callback>]::<lambda(nova::audio_sync_callback*)> > (this=0x7ffffff71cc0, functor=..., last=0xa15c98,
    first=0xa15c90)
    at /home/air/box_build/supercollider/external_libraries/boost/boost/lockfree/spsc_queue.hpp:414
#15 boost::lockfree::detail::ringbuffer_base<nova::audio_sync_callback*>::consume_all<nova::callback_system<nova::audio_sync_callback,false, boost::checked_deleter<nova::audio_sync_callback> >::run_callbacks()::{lambda(nova::audio_sync_callback*)#1}>(nova::callback_system<nova::audio_sync_callback, false, boost::checked_deleter<nova::audio_sync_callback> >::run_callbacks()::{lambda(nova::audio_sync_callback*)#1} const&, nova::audio_sync_callback**, unsigned long)
    (this=this@entry=0x7ffffff71cc0, functor=...,
    internal_buffer=<optimized out>, max_size=2049)
    at /home/air/box_build/supercollider/external_libraries/boost/boost/lockfree/spsc_queue.hpp:220
#16 0x000000000042e9e3 in consume_all<nova::callback_system<callback_type, mpmc, callback_deleter>::run_callbacks() [with callback_type = nova::audio_sync_callback; bool mpmc = false; callback_deleter = boost::checked_deleter<nova::audio_sync_callback>]::<lambda(nova::audio_sync_callback*)> > (f=..., this=0x7ffffff71cc0)
    at /home/air/box_build/supercollider/external_libraries/boost/boost/lockfree/spsc_queue.hpp:589
#17 consume_all<nova::callback_system<callback_type, mpmc, callback_deleter>::run_callbacks() [with callback_type = nova::audio_sync_callback; bool mpmc = false; callback_deleter = boost::checked_deleter<nova::audio_sync_callback>]::<lambda(nova::audio_sync_callback*)>> (f=..., this=0x7ffffff71cc0)
    at /home/air/box_build/supercollider/external_libraries/boost/boost/lockfree/spsc_queue.hpp:930
#18 run_callbacks (this=0x7ffffff71cc0)
---Type <return> to continue, or q <return> to quit---
    at /home/air/box_build/supercollider/server/supernova/./utilities/callback_system.hpp:59
#19 run_callbacks (this=0x7ffffff71cc0)
    at /home/air/box_build/supercollider/server/supernova/server/../sc/../server/server_scheduler.hpp:121
#20 tick (this=0x7ffffff28b60)
    at /home/air/box_build/supercollider/server/supernova/server/server.hpp:239
#21 nova::run_scheduler_tick ()
    at /home/air/box_build/supercollider/server/supernova/server/server.hpp:281
#22 0x000000000042ed69 in run_tick ()
    at /home/air/box_build/supercollider/server/supernova/server/server.hpp:329
#23 nova::jack_backend<nova::realtime_engine_functor, float, false>::perform (this=0x7fffffff1df8, frames=1024)
    at /home/air/box_build/supercollider/server/supernova/./audio_backend/jack_backend.hpp:322
#24 0x00007ffff777be86 in Jack::JackClient::CallProcessCallback()
    () from /usr/local/lib/libjack.so.0
#25 0x00007ffff777bd8e in Jack::JackClient::ExecuteThread() ()
   from /usr/local/lib/libjack.so.0
#26 0x00007ffff7779ac7 in Jack::JackClient::Execute() ()
   from /usr/local/lib/libjack.so.0
#27 0x00007ffff7798c3a in Jack::JackPosixThread::ThreadHandler(void*) () from /usr/local/lib/libjack.so.0
#28 0x00007ffff7bc7064 in start_thread (arg=0x7fffe04af700)
    at pthread_create.c:309
#29 0x00007ffff640062d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```

**Comment by jamshark70** [comment] 2018-01-28 02:00
From the call stack, it looks like supernova is grabbing memory for a synth. In the last few months, we did fix a bug about synth memory -- maybe here. https://github.com/supercollider/supercollider/commit/d07b120f3f1d97b447cf4c15179a9d55b189b63f#diff-94f24a794b648540c011a0d3d7162bf3

Definitely try it with the 3.9 release version.

**Comment by vivid-synth** [comment] 2018-01-28 06:29
Ok, this is fixed with latest master. Feel free to close if this isn't interesting given the bug doesn't manifest anymore.

**Comment by jamshark70** [comment] 2018-01-28 06:52
Thanks for confirming. Since the call stack is relevant to a concrete change, merged in after the version you were testing, I'm comfortable calling it the prior known issue.

**Closed by jamshark70** 2018-01-28 06:52 UTC
Labels: comp: supernova
