### ISSUE TITLE
CMD+Enter evaluates codes in the help documents twice

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3924] opened 2018-08-01 08:29 UTC
Environment
-----------

* SuperCollider version: 60daca8
* Operating system and version: ma OS El capitan

Expected Behavior
-----------------
CMD+Enter evaluates a code only one time when evaluating any code(s) in help document.

Current Behavior
----------------
in [60daca8] under macOS, CMD+Enter evaluates a code twice when evaluating any code(s) in help document.

Steps to reproduce (for bugs)
-----------------------------
1. launch SC
2. Select a code in any help document
3. Evaluate it by pressing cmd+enter
4. Observe the post window
5. you will see that the post window posts the same line twice.

**Comment by brianlheim** [comment] 2018-08-04 01:17
I can reproduce this, but only after having evaluated code at least once.

**Comment by prko** [comment] 2018-08-13 07:44
In [88821c5f], it still happens under 10.11.6.

**Comment by htor** [comment] 2018-08-21 08:34
made a pull above that may fix this issue.

**Comment by miczac** [comment] 2018-08-23 02:42
@brianlheim here it makes a difference whether the line is selected or not.
Selected lines get evaluated twice here.
Checked w/ SuperCollider 3.10 [89e71b429] / macOS 10.12.6 / Qt 5.11.1 via homebrew

**Comment by miczac** [comment] 2018-08-23 03:10
interestingly enough I can't reproduce it w/ [60daca839]

**Comment by brianlheim** [comment] 2018-08-23 10:45
@miczac That's consistent with what I see, I realized later that i observed the "at least once" bit because in that build evaluating caused the evaluated bit to become selected.

**Comment by brianlheim** [comment] 2018-08-23 10:47
When i threw this into a debugger before i observed there were two spots where HelpBrowser::evaluateSelection was being called. it should be enough to determine which of those is triggered by evaluating with nothing selected, and then removing the other call path.

**Comment by brianlheim** [comment] 2019-06-04 01:16
Fixed in #4390 , thanks @jrsurge !

**Closed by brianlheim** 2019-06-04 01:16 UTC
Labels: env: SCIDE
