### ISSUE TITLE
Help browser docklet doesn't load

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#908] opened 2013-07-14 19:45 UTC
The help browser docklet doesn't load the home page if scide starts with it closed:

start ide
close help docklet (from the ide menu or the docklet menu icon)
restart ide
View->Docklets->Help browser

note: executing  AnyClass.help loads the page.
unity desktop.

**Comment by scztt** [comment] 2015-03-15 01:25
I can still see this issue. Maybe View->Docklets->Help Browser just needs to hit the "home" action if it's unhiding the docklet?

**Comment by crucialfelix** [comment] 2015-03-15 13:16
maybe related: for me a fresh build would open the Help Browser in a
separate window but empty. it was the front most window. and I couldn't
close it.

it might be related to some saved IDE app state.

**Comment by bagong** [comment] 2015-04-03 11:03
I've seen variants of this too but haven't found a way to reproduce this reliably. But I have one sequence of reproducible steps that produce an empty help-Window where it shouldn't be:

1. open IDE, detach and close help docklet
2. close and reopen IDE (notice that editor does not have focus - do *not* click inside editor to "correct" that)
3. Click on any menu item
-> an empty uncloseable help window will come to the front.
Activating the help window "properly" by cmd-d or menu/help/show help will turn that window into a proper useable/closeable help window. Using menu/view/docklets/Help-browser will make the window closeable, but it remains empty.

Something similar can be observed with other docklets, so with post- and document-docklet:
1. open IDE, open help browser and bring it into docked state
2. open and detach post window
3. close post window
4. restart IDE (don't move focus to editor)
5. click on any menu item
-> a dead post-window will pop up -> it can be brought to life with menu/view/docklets/post window

Finally if both help- and post-docklet are attached you can do the same with the document docklet.

**Comment by smrg-lm** [comment] 2015-05-06 02:30
Hi @crucialfelix, you should fill a bug report for that because is a different issue. I didn't saw your comment and made one but now is closed by the smiley face development policy.

**Comment by smrg-lm** [comment] 2015-05-06 02:32
and please notice the date of this report (I'm sorry, I'm hurt </3)

**Comment by bagong** [comment] 2015-05-06 08:01
True, Lucas, the original bug is quite different from the subsequent observations, but there is also overlap (help not displaying). It might be good to look at them together when trying to find out what is going on. Looks like:

- in some cases help doesn't get displayed properly, the help window remains empty (ranging from no window decoration at all to just text missing). Reproducible: opening (unhiding?) the help docklet for the first time from the menu.
- in some cases an (empty) ghost window is displayed. This is usually observed with the help window, but it might very well be a general docklet (detached) issue. Reproducible (for me): clicking the menubar as first action after sc startup when "closed" detached docklets exist.

Looking at it the positive way: it is quite likely that people will be looking at both of the issues in the following weeks, which is a lot better than what happened to your original bug...

**Comment by animanoir** [comment] 2015-10-27 03:52
I'm having the issue on Windows 10.

**Comment by jamshark70** [comment] 2015-10-27 05:31
@aminanoir, which SC version? The SC 3.7 alpha 1 builds are newer than this issue, meaning it's possible that the newer version fixes it.

SC 3.7 alpha 1 for Windows is here: https://drive.google.com/folderview?id=0B7igZrWv7UxdM3ZnUzZpSURZVzQ&usp=sharing&tid=0B7igZrWv7UxdUmxHdThYLUE2QXc#list -- prerelease but working well in general. (IIRC the one major bug that's not fixed yet in it is that the server doesn't quit if you quit the IDE while the server is running.)

**Comment by animanoir** [comment] 2015-10-27 15:39
3.6.6.

Thanks, I'll test it.

**Comment by animanoir** [comment] 2015-10-27 23:12
Still doesn't work, but I really think it has something to do with my computer, not the program itself. Though the floating help window works great, so I don't really need the help browser window.

**Comment by elfh78** [comment] 2016-07-03 11:37
win 10 x32, supercollider 3.7.2. help browser doesn't work for me at all, just blank window all the time. Also, "File/Open recent" doesn't work. In compilation messages Russian symbols displayed not properly "���" but this is almost not an issue.

**Comment by bagong** [comment] 2016-10-27 20:16
@elfh78 does your username contain non-ascii characters or a space? That's a known, Windows specific issue, sorry. Different from smrg-lm's.

**Comment by vivid-synth** [comment] 2017-01-19 04:13
Are any of these still an issue / distinct from the Windows non-ASCII bug?

**Comment by brianlheim** [comment] 2017-01-19 18:08
What @elfh78 is describing is definitely the Windows character encoding bug.

However, I can recreate this using @smrg-lm's original instructions. I like @scztt's solution of having the open-docklet action trigger a go to home. As for the other issues, I can't speak to those, and I think they should be their own issue if they can be reproduced.

**Comment by carltesta** [comment] 2017-02-17 23:10
I'm on macOS, I moved where the SuperCollider.app was stored (from /Applications/SuperCollider/SuperCollider.app to /Applications/SuperCollider.app). This seemed to break the Help Browser and it ceased to load on startup. Is this related to this issue? When I tried to load a class help file it wouldn't load and "Sending Request" would continually show in the docklet bar. Once I move the .app back into the SuperCollider folder the problem goes away.

**Comment by bagong** [comment] 2017-02-17 23:29
@carltesta , I don't think there is any relation to the other issues. Also I cannot reproduce your problem on OSX. But to inspect this more seriously we'd need more info on your system. Might you be using an oold SC verion?

**Comment by vivid-synth** [comment] 2017-02-18 19:43
@carltesta that looks more related to https://github.com/supercollider/supercollider/issues/2604 -- maybe you should mention your issue there

**Comment by carltesta** [comment] 2017-02-18 19:54
@vivid-synth ah, got it. I'll repost. Thank You.

**Comment by bagong** [comment] 2017-03-11 11:52
This issue has diverged into multiple. I am trying to do something about "it" (although I'll likely fail), as part of getting rid of a few small annoyances, especially on Linux. I thin there are 4 issues discernible here. Two I'll exclude:

- problem opening help because of path issues in Windows (that's partly been addressed)
- problem opening help because of changed path on OSX

So I'll focus here on what has nicely be coined the "ghost" issue in a closed thread, and the issue that help doesn't display if you unhide (I think) the docklet from Menu/View/Docklets/Help browser. I think the two are not directly related, but there seems some overlap because the "ghost-window" might be the result of imperfectly hiding the docklet on Linux. As to that second issue I want to add here that it is not restricted to the help-docklet but can be reproduced with the post-window docklet, and the document docklet as well. On Linux (at least Ubuntu Unity) this is clearly visible. The pattern to reproduce is always:

- detach docklet
- close it (there is only the header-bar-switch to do so)
- quit SC
- reopen SC
- you'll have a ghost Window for each docklet that was treated this way. I contains nothing and cannot be closed.

On OSX the docklets are hidden, but are not prooperly initialized when unhidden via Menu/View/Docklet/xyz

I am assigning this to myself as I am currently trying myself on it, but please make suggestions if you have ideas, it might very well be that I fail ;) I am cc-ing @LucaDanieli , as he is currently working on related stuff.

Btw: I have also looked at broken shortcuts in Ubuntu-Unity with more recent Qt's and will offer a fix for discussion soon.

**Comment by bagong** [comment] 2017-03-11 13:02
Thinking about the unhiding, and the emptiness at SC startup: usually unhiding works and presents the help-docklet where it was when it was hidden, i.e. you still have the help history. After a restart the history (and current state) is lost. So I think the right logic for a fix would be:

Quote @scztt 

>I can still see this issue. Maybe View->Docklets->Help Browser just needs to hit the "home" action if it's unhiding the docklet?

AND no document has been loaded yet (or history is empty)?

**Comment by jamshark70** [comment] 2018-06-04 22:13
See also #3660 and a more complete problem description at #3287. It might be fixed in 3.10.

**Comment by prko** [comment] 2018-07-14 11:06
Hi,
Today I have worked on macOS 10.13.5 shortly.
And the SC which I compiled  on July 14 does not show the help document system.

<img width="771" alt="screenshot 2018-07-14 19 48 58" src="https://user-images.githubusercontent.com/416281/42723742-ff625f7e-879e-11e8-92f6-eac59fb5b699.png">

The official release of SC 3.9.3 shows help document system under the same OS on the same machine.

It is very strange because the same SC which I compiled  shows  help document system properly under macOS 10.11.6.

**Comment by prko** [comment] 2018-08-01 14:46
I am using now [60daca83] under macOS 10.12.6. and the same phenomenon occurs.

**Comment by prko** [comment] 2018-08-10 13:41
3.9.3 and [0f779a49] have the same problem under macOS 10.13.5.
3.8.1 is the last version which runs correctly under macOS 10.13.5.

**Comment by prko** [comment] 2018-08-11 00:15
[49a67460] has the same problem under macOS 10.13.6.

The following codes do not work:
```supercollider
HelpBrowser.new.goTo("google.com")
WebView().url_("google.com").front
```

I am wondering if this issue still alive...
I hope bug to be fixed as soon as possible.

Should I create a new issue?

**Comment by bartart3d** [comment] 2019-06-19 08:35
After upgrading from ubuntu 18.10 tot 19.04 I'm not able to see most of the documentation, in SuperCollider 3.10 with the IDE . Some of the getting started documentation does show up, but without the example code.
![image](https://user-images.githubusercontent.com/2852174/59749683-ce3a3800-927d-11e9-8cf2-f9cdbf1cac54.png)
Any ideas on how to fix this?

**Comment by geoffroymontel** [comment] 2019-08-10 13:59
On my MacBook Air, release 3.10.2 shows an empty help browser, while reverting to 3.10.1 shows the browser.

**Comment by snappizz** [comment] 2019-08-10 16:21
there are clearly multiple issues with the help browser, and there are multiple overlapping issue tickets for it. @bartart3d appears to be actually experiencing #4367. @geoffroymontel seems to be experiencing something new that may not have an actual ticket open.

since this issue is six years old and has gotten way too confusing to read, i am closing it. @geoffroymontel thanks for the report, please open a new ticket.

i'm opening up a new board, ["help browser issues"](https://github.com/supercollider/supercollider/projects/16), to help organize the half dozen different problems we're encountering with this component in hopes of disentangling them and understanding the priorities at hand. i'll be in touch over sc-dev and slack on this since this seems to be an obvious high priority for the near future.

**Closed by snappizz** 2019-08-10 16:21 UTC
Labels: bug, env: SCIDE
