### ISSUE TITLE
method extensions warnings for non-existent class Document when using sclang without of the IDE

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1208] opened 2014-10-19 17:06 UTC
The following warnings are posted when using sclang if you are not using the IDE:

```
ERROR: Class extension for nonexistent class 'Document'
     In file:'/deprecated/3.7/deprecated-3.7.sc'
ERROR: Class extension for nonexistent class 'Document'
     In file:'/Platform/osx/AutoComplete/AutocompleteExtensions.sc'
```

Additionally the Document class is no longer present unless you are using the IDE, which broke a lot of previous code that used Document for manipulating source code files.

---

IMO all IDE code should be moved to a class called DocumentEditor which deals with opening  A Document in a text editor.  

Document should return to a simpler interface that just deals with document objects (source code loaded from a file or sc source code not yet saved to a file)

but that's just my opinion, man.

**Comment by scztt** [comment] 2015-03-14 23:41
The document class itself has only two points of contact for sc-ide specific code... one is _ScIDE_SetDocTextMirror/_ScIDE_GetDocTextMirror, and the other is in the form of various calls to ScIDE's class methods. I think an appropriate (and easy) fix would be:
1. Move SetDoc/GetDoc primitive calls back into ScIDE class, and have Document call via a class method.
2. Repoint all ScIDE.xxxxxx() calls inside of Document to an "ide" classvar, so that e.g. ScIDE.processUrl becomes this.class.ide.processUrl
3. On startup, if an IDE is present, set Document.ide to the interface class.
4. Make the Document:ide getter throw in case of no ide class being set.
5. Create an abstract base class IDE, with stub methods for everything required by Document.

Step 5 is probably optional for now - no need to do that until there's a compelling case for creating an IDE subclass other than ScIDE.... The rest is some pretty trivial search and replace, and it doesn't seem to be particularly risky.

**Comment by brianlheim** [comment] 2017-02-07 14:36
(See #1396 for another discussion about this)

**Comment by brianlheim** [comment] 2017-02-18 04:47
#2718

**Comment by JordanHendersonMusic** [comment] 2024-05-10 09:29
Closing cannot reproduce.

Running `sclang` from the terminal produces no such warnings. This was probably fixed a while ago.

**Closed by JordanHendersonMusic** 2024-05-10 09:29 UTC
Labels: bug
