### ISSUE TITLE
No sound from SC, but no errors, sound cards is working. Windows 7 64 bit, SC 3.9.3

### ISSUE THREAD

**Issue by svatty89** [supercollider/supercollider#4147] opened 2018-11-07 19:08 UTC
Environment
-----------

* Your SuperCollider version: supercollider 3.9.3 64 bit
* Your operating system and version: windows 7 64 bit professional service pack 1

I want to get a sound from it. I type standart code in SC, then nothing happens. 

Current Behavior

No errors seems to appear, from the point of veiew of interpreter everything seems to be just fine.
I have lexicon Lamda sound card, which is connected via usb-port to my PC. 
I make myself clear for avoiding typical question about what i do. I do everything correct. But have no sound, belive me. I dont want to write a bit of code containing typical sclang expression for booting server and for creating sine-wave simple oscillator. 
Nothing works.  It happens however that having no error messages, no mistakes or any kinds of notificatian i can't get a sound from IDE.  That's very confusing. Because i spent yesterday more than 8 hours making it work.  I tried my built -in sound card, i tried Lexicon. All others applications have sound, but this SC - isn't. 
 Please, don't judge and do not write answers containing remarks e.g "why don't you paste in your message logs of the interpreter", "there's no code you'have given to us, we can't help". 
  Repeat myself for the last time. SC give no errors, sound card is working well with it's own driver installe properly, but magically it gives nothing. I write this in order to have answer. Maybe someone had the same thing. on windows 7 , this version 3.9.3, 64 bit, sound card well working, but with SC it is not give a sound. 
 Please be patient, I'm not an idiot, just bored and frustrated from the fact that i spent so much time to this.  Thanks and i appologise for long and maybe not too informative message.

**Comment by geoffroymontel** [comment] 2018-11-08 07:44
Could you print the output of the console when you evaluate 
```supercollider
Server.default.boot;
```
please ?

**Comment by snappizz** [comment] 2018-11-08 18:19
i'm really sorry that you've had an immensely frustrating experience, but i must say i am very much not a fan of the tone of this bug report. maybe it wasn't your intention to come off this way, but i do not appreciate these weird proactive side-accusations about how we're going to be unhelpful and patronizing.

i know it's absolute hell to be stuck on something like this for eight hours, but bypassing basic courtesies when reporting bugs is not cool. steps to reproduce are basic information that people need to process your issue. outwardly refusing to share them is a bizarrely inconsiderate move, and certainly doesn't get your problem solved any faster.

for example, if you had stated the explicit steps you took, i would know whether or not you had tried setting `Server.default.options.outDevice` because you're using an external sound card.

sorry to be a scold, but this is really not an okay attitude to use when reporting bugs. thanks.

**Comment by snappizz** [comment] 2018-11-18 09:11
closing due to lack of followup

**Closed by snappizz** 2018-11-18 09:11 UTC
