### ISSUE TITLE
Quark.update fails if quark repo uses "main" rather than "master"

### ISSUE THREAD

**Issue by cdbzb** [supercollider/supercollider#6071] opened 2023-08-17 22:29 UTC
## Expected vs. actual behavior

Calling Quark("scparco").update leads to an error ( @shimpe )

"fatal: couldn't find remote ref master"

This is because the branch "master" is hard coded into the .update method here

https://github.com/supercollider/supercollider/blob/9d54ee82fbffc8ea4fb1e07368de8dd4b81bf44f/SCClassLibrary/Common/Quarks/Quark.sc#L107

This could arguably be called an enhancement but A) the docs do not insist that Quarks use "master" and B) more and more repos are using "main"

**Comment by dyfer** [comment] 2023-08-17 23:33
Thanks for the report!
Yes, it would be good to be able to support both/any default branch name, but that's not straightforward. And yes, the docs are lacking.
I'd consider this issue a duplicate of #5096

**Comment by shimpe** [comment] 2023-08-18 05:23
Or, as a pragmatic approach, try to checkout main and if it fails, try to checkout master instead?
I know it's not a general solution but it might cover the majority of practical uses cases in new enough versions of supercollider.

**Closed** 2023-09-24 18:13 UTC
Labels: bug
