### ISSUE TITLE
OS X: scsynth icon bounces forever in the dock

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1804] opened 2016-01-19 18:18 UTC
I would prefer that scsynth did not appear in the dock at all. But then again it makes it easier to kill it. 

It definitely shouldn't be bouncing forever and ever like that. I guess its because the process started but it isn't an OS X application (no NSApplication)

**Comment by miczac** [comment] 2016-01-20 00:05
Today I pulled and compiled again, on 10.9.5 / Xcode 6.2, and none of that happens.
Besides I (virtually) never saw scsynth popping up anywhere.

**Comment by miczac** [comment] 2016-01-20 01:36
I can confirm on 10.10.5 / Xcode 7.0.1 I can see scsynth showing up and bouncing. Still not on 10.9.5. ("still" because I gave it a deployment target of 10.7 for the second test)

**Comment by miczac** [comment] 2016-01-20 01:38
and I suspect it may be related to https://github.com/supercollider/supercollider/issues/1805 - but that's just a hunch.

**Comment by crucialfelix** [comment] 2016-01-20 07:58
I've only recently noticed it, so I can well believe that it only happens on 10.10+

isn't it always a deployment target of 10.7 ? did you explicitly set it to something else previously ?

**Comment by sfogar** [comment] 2016-01-20 09:57
On 10.10 this does not happen...

**Comment by telephon** [comment] 2016-01-20 10:24
On 10.11. it bounces for a while (too long to be sane) but then it stops. Probably the system has a setting for stopping it automatically after a while, so something is still wrong.

**Comment by miczac** [comment] 2016-01-20 12:14
@crucialfelix  I browsed the logs and the deployment target appears to be depended on Xcode's version!
I'm not a dev, so I only can guess what's the idea (or error?) behind that.
E.g. that's from 10.9.5/Xcode 6.2 w/o additional options for cmake:
build/CMakeFiles/CMakeOutput.log:    export MACOSX_DEPLOYMENT_TARGET=10.9
That's from 10.10.5/Xcode 7.0.1 also w/o additional options for cmake:
build/CMakeFiles/CMakeOutput.log:  export MACOSX_DEPLOYMENT_TARGET=10.11
as I found this morning, binaries generated this way won't even run on 10.10.
So I had to set a deployment target <= 10.10

**Comment by miczac** [comment] 2016-01-20 12:14
@sfogar - how did you get/generate the binaries?

**Comment by sfogar** [comment] 2016-01-20 12:19
I did not generate the binaries by myself it's the 3.7.0 beta1 submitted yesterday ...

**Comment by crucialfelix** [comment] 2016-01-20 12:36
Thanks @miczac 

I se that the travis build explicitly sets `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.7`

**Comment by miczac** [comment] 2016-01-20 12:42
AFAICT, until 10.9.5/Xcode 6.2 (*) wrong icons or bouncing scsynth don't occur:


(*) didn’t happen on 10.8.5 either.

binaries compiled on 10.10.5 w/ Xcode 7.0.1 for OS X >= 10.7 (same source-tree!) on 10.10.5 looks like



but those very binaries launched on 10.9.5 show this - and no bouncing sysynth.



Since @sfogar downloaded the binaries, which IIRC are built by travis on 10.9.5 (which implies Xcode <= 6.2) this hopefully narrows it down a bit.

**Comment by miczac** [comment] 2016-01-20 13:06
(EDIT: pics don't currently work on github comments - grr)
- AFAICT, until 10.9.5/Xcode 6.2 (*) wrong icons or bouncing scsynth don't occur.
(*) didn’t happen on 10.8.5 either.

- binaries compiled on 10.10.5 w/ Xcode 7.0.1 for OS X >= 10.7 (same source-tree!) on 10.10.5 cause three cubes, one bouncing for scsynth.

- but those very binaries launched on 10.9.5 show two cubes for sclang and ide, but no bouncing scsynth.

-and, if it wasn't funny enough, the binaries from 10.9.5 (above) on 10.10.5 show the correct icons for ide and sclang _and_ the bouncing icon for scsynth.

- on top of it, @sfogar downloaded the binaries, which IIRC are built by travis on 10.9.5 (which implies Xcode <= 6.2)

**Comment by miczac** [comment] 2016-01-20 13:08
(EDIT: pics don't currently work on github comments - grr)
- AFAICT, until 10.9.5/Xcode 6.2 (*) wrong icons or bouncing scsynth don't occur.
(*) didn’t happen on 10.8.5 either.

- binaries compiled on 10.10.5 w/ Xcode 7.0.1 for OS X >= 10.7 (same source-tree!) on 10.10.5 cause three cubes, one bouncing for scsynth.

- but those very binaries launched on 10.9.5 show two cubes for sclang and ide, but no bouncing scsynth.

- and, if it wasn't funny enough, the binaries from 10.9.5 (above) on 10.10.5 show the correct icons for ide and sclang _and_ the bouncing icon for scsynth.

On top of it, @sfogar downloaded the binaries, which IIRC are built by travis on 10.9.5 (which implies Xcode <= 6.2) - and no bouncing icon?

**Comment by miczac** [comment] 2016-01-20 13:20
@sfogar on what OS X version are you exactly? 
I just downloaded the binaries (SC-9899190d8808191e871cbfced848d7791374ed8c.zip) and ran it on 10.10.5.
I got the correct icons for ide and sclang _but_ the bouncing scsynth cube.

**Comment by crucialfelix** [comment] 2016-01-20 13:21
![brutalism](https://cloud.githubusercontent.com/assets/218738/12449956/0776daac-bf81-11e5-8362-d6f7abdefb7f.jpg)

Works for me.

**Comment by miczac** [comment] 2016-01-20 13:29
ok, works now, updated the comment again - thanks!

**Comment by crucialfelix** [comment] 2016-01-20 13:32
Here are the docs:

https://developer.apple.com/library/mac/documentation/AppKit/Reference/NSRunningApplication_Class/index.html#//apple_ref/c/tdef/NSApplicationActivationPolicy

I think we want NSApplicationActivationPolicyAccessory for sclang

> The application does not appear in the Dock and does not have a menu bar, but it may be activated programmatically or by clicking on one of its windows. This corresponds to value of the LSUIElement key in the application’s Info.plist being 1.

but these are processes being started from another and there is no objective-c in either of them. I'll have to investigate more.

Does anybody else want to volunteer for this ?

**Comment by sfogar** [comment] 2016-01-20 13:35
@miczac I'm on 10.10, I am currently away from my Mac so no further details at the moment ...

**Comment by miczac** [comment] 2016-01-28 18:31
Update, in reply to https://github.com/supercollider/supercollider/issues/1804#issuecomment-173198373

Just in case, FWIW,
the screenshots I posted from the 10.10 system [1] were with Qt 5.4 (.1 I think).
It’s now with Qt 5.5.1 and after re-compiling it’s just the bouncing scsynth icon on 10.10 and the uniform process names left:

![screen shot 2016-01-28 at 16 29 55](https://cloud.githubusercontent.com/assets/1922103/12654674/6c61d0c8-c5f5-11e5-8977-eb37926eb871.png)

On 10.9.5 [1] the dock icons are ok, besides that scsynth won’t come up (tested w/ supernova):

![screen shot 2016-01-28 at 18 19 12](https://cloud.githubusercontent.com/assets/1922103/12654697/95374140-c5f5-11e5-8c35-46d9f67b8bad.png)

[1] compiled on 10.10.5 w/ Xcode 7.2 - deployment target 10.7

**Comment by crucialfelix** [comment] 2016-01-29 08:25
I worked on this a bit. I haven't yet found any way to stop the icon from being shown for any executable that is in that MacOS folder. 

one solution is to create a separate bundle for scsynth and its plugins with its own plist that specifies not to activate windows, menu, icon or dock.  this means changing the path of scsynth which is disruptive for the 3.7 release

another solution is to move scsynth and plugins to `SuperCollider.app/scsynth/` which means that it would not get the icon (because its not inside the main app bundle). also disruptive in that the path changes. but its easy to copy it to somewhere else if we want a standalone scsynth.

**Comment by crucialfelix** [comment] 2016-01-29 08:33
https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html

> MacOS
> (Required) Contains the application’s standalone executable code. Typically, this directory contains only one binary file with your application’s main entry point and statically linked code. However, you may put other standalone executables (such as command-line tools) in this directory as well.

They seem to allow people to put another executables in there, but I haven't found anyway to supress the dock icon for those.

**Comment by noiseconformist** [comment] 2016-01-29 11:30
regarding the icon (cubic vs circular) display: would it make sense to have Qt 5.5 as minimum for 3.7?
because apparently that makes the difference.
ATM the readme states: 
```As of this writing the latest stable Qt is 5.5.x. The 5.6 beta has also been reported to work fine.```
Or at least to formulate a strong recommendation, because it's not a show-stopper but ugly?

**Comment by telephon** [comment] 2016-01-29 11:56
>another solution is to move scsynth and plugins to SuperCollider.app/scsynth/ which means that it would not get the icon (because its not inside the main app bundle). also disruptive in that the path changes. but its easy to copy it to somewhere else if we want a standalone scsynth.

It doesn't sound that bad. What paths would have to change in sclang? Maybe we should also move the class library and the help source folders there. Hm, but this may break exisiting config files.

**Comment by crucialfelix** [comment] 2016-01-29 12:26
It would break a lot of things. 3.8

But let's do 3.8 by April or may. Regular small releases with less
disruptive changes

**Comment by timblechmann** [comment] 2016-01-29 13:35
SuperCollider.app/scsynth:

is this tested or speciation? sc/osx uses apple's bundle API to infer certain paths.

**Comment by crucialfelix** [comment] 2016-01-29 16:15
I'm suggesting that one possible solution is to move scsynth and its
plugins to a folder outside of the SuperCollider.app/Contents

That would mean that the plist doesn't affect how the process is displayed
in the dock.

But you are right that we can't use the bundle API to infer the relative
path.
We could still use normal relative paths.

"Speciation is the evolutionary process by which new reproductively
isolated biological kinds, species, arise."

I'm pretty sure I'm not indulging in speciation. Its just thinking.



On Fri, Jan 29, 2016 at 2:35 PM Tim Blechmann <notifications@github.com>
wrote:

> SuperCollider.app/scsynth:
>
> is this tested or speciation? sc/osx uses apple's bundle API to infer
> certain paths.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1804#issuecomment-176758329>
> .
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by timblechmann** [comment] 2016-01-30 09:18
typo: Speciation/speculation ... 

these parts will probably have to be touched:

```
✔ 17:17 ~/dev/supercollider [master|✚ 2…727⚑ 41] $ git grep CFBundle common/
common/SC_DirUtils.cpp:# include <CoreFoundation/CFBundle.h>
common/SC_DirUtils.cpp: CFBundleRef mainBundle;
common/SC_DirUtils.cpp: mainBundle = CFBundleGetMainBundle();
common/SC_DirUtils.cpp:         CFDictionaryRef dictRef = CFBundleGetInfoDictionary(mainBundle);
common/SC_DirUtils.cpp:         strRef = (CFStringRef)CFDictionaryGetValue(dictRef, CFSTR("CFBundleName"));
common/SC_StandAloneInfo_Darwin.cpp:#include <CoreFoundation/CFBundle.h>
common/SC_StandAloneInfo_Darwin.cpp:            CFURLRef enablerURL = CFBundleCopyResourceURL (
common/SC_StandAloneInfo_Darwin.cpp:                    CFBundleGetMainBundle(),
common/SC_StandAloneInfo_Darwin.cpp:                    enablerURL = CFBundleCopyResourceURL (
common/SC_StandAloneInfo_Darwin.cpp:                              CFBundleGetMainBundle(),
```

**Comment by miguel-negrao** [comment] 2016-02-12 11:13
> It would break a lot of things. 3.8

Is this still going to be addressed for 3.7.0 or is it passing to 3.8 ? If the later it is one less issue preventing the release of 3.7.0 ...

**Comment by telephon** [comment] 2016-02-12 18:03
@miguel-negrao 3.7.0 has been released already. The question is more if it goes to 3.7.1 or 3.8.

**Comment by miguel-negrao** [comment] 2016-02-12 18:11
> @miguel-negrao 3.7.0 has been released already.

Hum, I don't think so. I saw no announcement of that, and it's not in http://supercollider.github.io/download or https://github.com/supercollider/supercollider/releases. Only a beta was released. 

But yes, I should have asked, does it go into 3.7.0 or 3.7.x ? We are two bugs away from no more issues before 3.7.0 can be released, no (forgetting windows for a moment) ?

**Comment by telephon** [comment] 2016-02-13 13:27
I counted the beta as a release

**Comment by telephon** [comment] 2016-02-13 13:29
I'd love to understand better how to judge what goes where and how it is done.

**Comment by crucialfelix** [comment] 2016-02-13 14:34
3.7.0 is closed for features or API changes.  In that sense its "released", that's what Herr Telephon means. 

Moving the executables would be great for many of us, but I don't think we can do it for this release.

**Comment by miguel-negrao** [comment] 2016-02-13 16:35
> I counted the beta as a release

I don't think that is the usual understanding. A beta is for testing, a final release is for wide distribution. Certainly there will be point releases afterwards with bug fixed, but that is a different matter. I thought the point of having a milestone 3.7.0 was to know which bugs have to be fixed before 3.7.0 can be released, and people fill the streets overcome with joy. :-)

**Comment by crucialfelix** [comment] 2016-02-13 17:24
There will be fireworks and schnapps, I promise you.

3.7.0 is still not finalized. I will have some time this week to work on
things.
Its mainly the Windows stuff, but a 3.7.1 could bring the windows release
if necc.

On Sat, Feb 13, 2016 at 5:35 PM Miguel Negrão <notifications@github.com>
wrote:

> I counted the beta as a release
>
> I don't think that is the usual understanding. A beta is for testing, a
> final release is for wide distribution. Certainly there will be point
> releases afterwards with bug fixed, but that is a different matter. I
> thought the point of having a milestone 3.7.0 was to know which bugs have
> to be fixed before 3.7.0 can be released, and people fill the streets
> overcome with joy. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1804#issuecomment-183699946>
> .
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by timblechmann** [comment] 2016-02-14 07:16
this needs proper investigation: i had been using `TransformProcessType` with supernova for a few days, but the supernova process was marked as "not responding" ... not exactly trustworthy when knowing that the osx scheduler will do arbitrary things with real-time processes.

fwiw, there is always a good point to have bugfix releases ...

**Comment by crucialfelix** [comment] 2016-02-14 08:45
Good point. Its not just the annoying bouncing.


On Sun, Feb 14, 2016 at 8:16 AM Tim Blechmann <notifications@github.com>
wrote:

> this needs proper investigation: i had been using TransformProcessType
> with supernova for a few days, but the supernova process was marked as "not
> responding" ... not exactly trustworthy when knowing that the osx scheduler
> will do arbitrary things with real-time processes.
>
> fwiw, there is always a good point to have bugfix releases ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1804#issuecomment-183841004>
> .
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by crucialfelix** [comment] 2016-02-23 18:32
I've tested moving scsynth into Resources. That is actually where misc executables (not the primary application) should go.  

It works fine; no icon appears in the dock. It would solve this ticket.

I could see moving it right now for 3.7. It means a last minute change of path for those of us that use scsynth separately from sclang/ide. Its just changing a path, not that big a deal.

sclang is a different beast. It should have an icon in the dock since it may create windows. (Though it would be nicer if it waited to do that until a gui is created.)  I propose leaving it in MacOS.

thoughts ?

**Comment by telephon** [comment] 2016-02-26 08:05
good!

**Closed** 2016-03-06 11:18 UTC
Labels: bug, os: Mac OS X
