### ISSUE TITLE
Missing functionality in Qt: Views highlighting themselves

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#621] opened 2012-10-24 23:02 UTC
Views highlighting themselves when moving over during drag and drop (if they accept the drag that is). I'm really missing the clear blue rectangle that is around views that receive drag and drop items from cocoa in qt. With smaller gui items close to each other it is nearly impossible to drop in the right place in qt.

**Comment by scztt** [comment] 2015-04-18 23:15
Duplicate of #246.

**Closed by scztt** 2015-04-18 23:15 UTC
Labels: comp: Qt GUI, duplicate, enhancement
