### ISSUE TITLE
application folder can't be renamed (OSX)

### ISSUE THREAD

**Issue by constantinpopp** [supercollider/supercollider#2604] opened 2017-01-01 11:57 UTC
The folder can't be renamed to a new name without causing the help system to fail. For example, if i were to rename /Applications/SuperCollider to /Applications/SuperCollider_3.8 the SCIDE can't load help files anymore.

**Comment by telephon** [comment] 2017-02-04 19:35
I can reproduce this, it can't be avoided by changing the LanguageConfig

**Comment by carltesta** [comment] 2017-02-18 19:55
Following up that I'm currently experiencing this issue on macOS Sierra. I moved where the SuperCollider.app was stored (from /Applications/SuperCollider/SuperCollider.app to /Applications/SuperCollider.app). This seemed to break the Help Browser and it ceased to load on startup. Is this related to this issue? When I tried to load a class help file it wouldn't load and "Sending Request" would continually show in the docklet bar. Once I move the .app back into the SuperCollider folder the problem goes away.

**Comment by bgold-cosmos** [comment] 2017-03-11 20:44
Not sure if this is related, I just ran into a similar issue with SuperCollider 3.8.0, MacOS X 10.11.6:

After a system reboot (and nothing else that I know of changing!) the Help browser would not load, and trying to look up a function results in the endless "sending request..."  The only thing that seemed to fix it is moving the application from the folder `~/Applications (Local)/SuperCollider` (where I've always had it) to `~/Applications/SuperCollider`.

Not sure if the spaces/parens in the directory name were causing an issue - they never have before.

**Comment by clembie** [comment] 2017-09-15 03:42
The same thing happened to me when I installed SC 3.8.0 on Mac OS 10.12.6.  SC worked fine.  When I installed plugins in the Extensions folder (which I had to create), the help browser wouldn't load and just said "sending request..."  Removing the Extensions folder solved the issue.

**Comment by htor** [comment] 2018-07-31 07:45
i can't reproduce this on my mac on a clean install. renamed `/Applications/SuperCollider.app` to `/Applications/SuperCollider_3.9.3.app` re-booted, re-started sc and the help browser still works normally.

sc version: 3.9.3
macos: 10.13.6

**Comment by bgold-cosmos** [comment] 2018-07-31 13:08
Can also confirm that this seems to work now, I think it was fixed in 3.9

**Closed** 2018-07-31 21:30 UTC
Labels: bug, comp: SCDoc, os: macOS
