### ISSUE TITLE
HID does not work on Windows

### ISSUE THREAD

**Issue by gilfuser** [supercollider/supercollider#3200] opened 2017-09-22 15:32 UTC
Hi,
I just made a build from the SC3.9dev in Windows and I'm trying to make use of the HIDAPI.
```
// it finds HID.available:
HID.findAvailable; 
-> IdentityDict with 5-6 devices
HID.postAvailable;
-> e.g number 4 is:
4: 	Usage name and page: 	Joystick, 	GenericDesktop
	Vendor name: 	Jess Tech
	Product name: 	Dual Analog Pad
	Vendor and product ID: 	3888, 274
	Path: 	\\?\hid#vid_0f30&pid_0112#6&4eea161&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
	Serial Number: 	
	Releasenumber and interfaceNumber: 	257, -1

the long path is strange...

// Trying to open it fails:
HID.openAt(4);   
-> 
HID: path was not set specified yet, chosen the one with path: \\?\hid#vid_0f30&pid_0112#6&4eea161&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
HIDAPI : Unable to open device \\?\hid#vid_0f30&pid_0112#6&4eea161&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}: 3888, 274
ERROR: HID: Could not open device
```
Does anyone else get that to work?

bests,
Gil

**Comment by brianlheim** [comment] 2017-09-22 17:52
Hi Gil,

Sorry, the serial port interface is not yet supported on Windows. I'm closing this as a duplicate of #2461.

**Comment by gilfuser** [comment] 2017-09-22 18:07
Hi Brian. I'm asking about HID, not Serial Port. Or are they somehow
connected?

Brian Heim <notifications@github.com> schrieb am Fr., 22. Sep. 2017 um
19:52 Uhr:

**Comment by brianlheim** [comment] 2017-09-22 19:18
Oops, sorry, you are right. I don't know why I thought they were the same thing.

**Comment by adcxyz** [comment] 2017-09-23 08:24
@sensestage 
- do you have any tips where to look to get this fixed?
Both Gil and I have windows machines available now, 
so we can try things quickly and report back :-)  
thanks, adc

**Comment by jrsurge** [comment] 2019-08-10 18:01
Tested on Win10 with v3.10.2 - this appears to be fixed?

**Comment by brianlheim** [comment] 2019-08-10 20:31
@jrsurge can you be more specific abt how you tested?

looking at the original report again:

```
Path: 	\\?\hid#vid_0f30&pid_0112#6&4eea161&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
```

i wouldn't be surprised if it has something to do with this long path fromat

**Comment by jrsurge** [comment] 2019-08-10 21:01
Here's what I ran (as original report):

```supercollider
HID.findAvailable;
HID.postAvailable;
/*
5: 	Usage name and page: 	GamePad, 	GenericDesktop
	Vendor name: 	
	Product name: 	Controller (XBOX 360 For Windows)
	Vendor and product ID: 	1118, 654
	Path: 	\\?\hid#vid_045e&pid_028e&ig_00#7&1266d29f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
	Serial Number: 	
	Releasenumber and interfaceNumber: 	0, -1
*/

HID.openAt(5);

/*
open device 00000217B36ED9F0
start polling thread for -1284580880
HID: Opened device: a HIDInfo(, Controller (XBOX 360 For Windows), IDs:1118, 654, \\?\hid#vid_045e&pid_028e&ig_00#7&1266d29f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, , 0, -1)
*/

HID.debug = true;
// using controller posts values
HID.closeAll;
```

I have noticed that the background thread takes a while to shutdown once `closeAll` gets called, but I might not be using the HID api properly:
```supercollider
device thread interrupted 
// significant time later:
device thread closed device 
```

But once it's all closed, I can open the device again, no issue.
That background thread might need looking at, but that's a separate issue?

**Comment by brianlheim** [comment] 2019-08-10 21:05
SGTM! Let's close this as unreproducible.

**Closed by brianlheim** 2019-08-10 21:05 UTC
Labels: os: Windows
