### ISSUE TITLE
do not default to debug build on not providing CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#5159] opened 2020-09-09 17:55 UTC
## Motivation
When building supercollider and not providing a `CMAKE_BUILD_TYPE` the build will not be done using `-DNDEBUG` leading to a few debug configurations.

Additionally: The default optimization level for Arch Linux (`-O2`) is overridden by `-O3` when providing `-DCMAKE_BUILD_TYPE=Release`, which is why we [try to avoid using it](https://wiki.archlinux.org/index.php/CMake_package_guidelines#CMake_can_automatically_override_the_default_compiler_optimization_flag).

Unfortunately this (setting `-DCMAKE_BUILD_TYPE=None`) seems to lead to a debug build. 

Examples:
snippet from 3.10.4 build with build type `Release`:
```
cd /build/supercollider/src/supercollider-3.10.4/build/external_libraries/hidapi/linux && /usr/bin/cc -DBOOST_CHRONO_HEADER_ONLY -DBOOST_NO_AUTO_PTR -DLINUX_FREEBSD -DSC_DATA_DIR=\"/usr/share/SuperCollider\" -D_FORTIFY_SOURCE=2 -I/build/supercollider/src/supercollider-3.10.4/external_libraries/hidapi/hidapi  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt   -msse -mfpmath=sse -msse2 -O3 -DNDEBUG   -fschedule-insns2 -fomit-frame-pointer -Wreturn-type -fno-math-errno -fno-signaling-nans -fsigned-zeros -fno-associative-math -pthread -fvisibility=hidden -o CMakeFiles/hidapi.dir/hid.c.o   -c /build/supercollider/src/supercollider-3.10.4/external_libraries/hidapi/linux/hid.c
```

snippet from 3.11.1 build with build type `None`:
```
cd /build/supercollider/src/supercollider-3.11.1/build/external_libraries/hidapi/linux && /usr/bin/cc -DBOOST_CHRONO_HEADER_ONLY -DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE -DBOOST_NO_AUTO_PTR -DLINUX_FREEBSD -DSC_DATA_DIR=\"/usr/share/SuperCollider\" -D_FORTIFY_SOURCE=2 -I/build/supercollider/src/supercollider-3.11.1/external_libraries/hidapi/hidapi -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt   -msse -mfpmath=sse -msse2   -fschedule-insns2 -fomit-frame-pointer -Wreturn-type -fno-math-errno -fno-signaling-nans -fsigned-zeros -fno-associative-math -pthread -fvisibility=hidden -o CMakeFiles/hidapi.dir/hid.c.o -c /build/supercollider/src/supercollider-3.11.1/external_libraries/hidapi/linux/hid.c
```

## Description of Proposed Feature

Do not imply debug build when not providing the build type (i.e. `-DCMAKE_BUILD_TYPE=None`):
* set `-DNDEBUG` *unless* a debug build is requested (i.e. `-DCMAKE_BUILD_TYPE=Debug`)

## Plan for Implementation

I can try to look into changing the cmake setup for this, but am little unsure how to solve this exactly, as a lot of this is inherent cmake magic.
I don't believe this would take a long time to implement though.

**Comment by dvzrv** [comment] 2020-09-09 18:59
An additional question that I have in regards to the build type `Release`:
Is besides the automatic increase in optimization anything else being set, that I should be aware of? I can not find any specific references to this build type in the cmake setup.

FTR: I can get around the missing "no debug" when no build type is set by appending `-DNDEBUG` to `CFLAGS` and `CXXFLAGS`.

**Comment by brianlheim** [comment] 2020-09-10 11:38
for supercollider, there's a difference here between *not setting the build type* (i.e. `cmake -G<gen> ..`) and *setting the build type to None* (i.e. `cmake -G<gen> -DCMAKE_BUILD_TYPE=None`).

if CMAKE_BUILD_TYPE isn't set, and is used with a multi-config generator, it will be set to `RelWithDebInfo` (i.e., compile in release mode but with debug info).

if CMAKE_BUILD_TYPE is set to None, then that default logic will be skipped and you will get a build with no new flags added.

i set my build type to None on Arch and here is what i see:

```
cd /home/bheim/code/supercollider/build/server/scsynth && /usr/bin/ccache /usr/bin/c++ -DBOOST_CHRONO_HEADER_ONLY -DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE -DBOOST_NO_AUTO_PTR -DHAVE_AVAHI=1 -DNOVA_SIMD -DSC_AUDIO_API=SC_AUDIO_API_JACK -DSC_DATA_DIR=\"/usr/local/share/SuperCollider\" -DSC_FFT_FFTW -DSC_MEMORY_ALIGNMENT=32 -DSC_PLUGIN_DIR=\"/usr/local/lib/SuperCollider/plugins\" -DSC_PLUGIN_EXT=\".so\" -DUSE_RENDEZVOUS=1 -I/home/bheim/code/supercollider/build/common -I/home/bheim/code/supercollider/external_libraries -I/home/bheim/code/supercollider/external_libraries/nova-simd -I/home/bheim/code/supercollider/external_libraries/nova-tt -I/home/bheim/code/supercollider/external_libraries/boost -I/home/bheim/code/supercollider/include/common -I/home/bheim/code/supercollider/common -I/home/bheim/code/supercollider/include/server -I/home/bheim/code/supercollider/include/plugin_interface -I/home/bheim/code/supercollider/server/scsynth/. -I/home/bheim/code/supercollider/external_libraries/boost_sync/include -I/home/bheim/code/supercollider/external_libraries/TLSF-2.4.6/src -msse -mfpmath=sse -msse2   -fschedule-insns2 -fomit-frame-pointer -Wreturn-type -fno-math-errno -fno-signaling-nans -fsigned-zeros -fno-associative-math -pthread -fvisibility=hidden -std=gnu++11 -o CMakeFiles/libscsynth.dir/SC_MiscCmds.cpp.o -c /home/bheim/code/supercollider/server/scsynth/SC_MiscCmds.cpp
```

no -DNDEBUG, or -O2 or -O3 unless i'm missing it.

the wiki section you posted above even notes this distinction:

> Since the default None build type does not append any flags to CFLAGS and CXXFLAGS by default, using the -DCMAKE_BUILD_TYPE=None option can also work. Generally speaking, using the -DCMAKE_BUILD_TYPE=None option is better than omitting the usage of CMAKE_BUILD_TYPE. It will cover the case when upstream automatically sets the build type to Release when CMAKE_BUILD_TYPE is omitted, it will not append any flags by default and it's uncommon to see software setting undesired flags for the None build type. 

i would like to leave this default-to-relwithdebinfo logic in place as it does mostly the right thing for most people's use cases, and changing it would be disruptive. although i'd add i personally don't agree with it, and if i were starting from scratch i wouldn't do it.

**Comment by redFrik** [comment] 2020-09-10 12:22
in any case, something we need to address is that the build instructions here... https://github.com/supercollider/sc3-plugins#compile-from-source
does not produce Release builds on for example a Raspberry Pi.
I do not know what changed but `--config Release` does nothing. The resulting plugs must be debug because they run unbearably slow.
The old method of building still work and I get release binaries...
`cmake -DCMAKE_BUILD_TYPE="Release" -DSUPERNOVA=OFF -DNATIVE=ON -DSC_PATH=../../supercollider/ ..`

**Comment by dvzrv** [comment] 2020-09-10 12:35
@brianlheim  the CFLAGS added to my build are due to the makepkg defaults (see `/etc/makepkg.conf`) which get used in the build environment (that way a distribution can set flags globally).
Only if you build supercollider in a packaging context (i.e. either using `makepkg` directly or by using e.g. devtools' `extra-x86_64-build`) they will be added.

> if CMAKE_BUILD_TYPE is set to None, then that default logic will be skipped and you will get a build with no new flags added.

In a way that is "correct", but: I explicitly have to add `-DNDEBUG` to CFLAGS in such a use-case to not have certain things be built in a debug mode, as omitting the preprocessor macro builds those components in debug mode (see `grep -R "NDEBUG" .` in the supercollider sources).

**Comment by brianlheim** [comment] 2020-09-10 12:57
> the CFLAGS added to my build are due to the makepkg defaults (see /etc/makepkg.conf) which get used in the build environment (that way a distribution can set flags globally).

i understand that, i am just showing that it is possible to get a None-type build currently.

> In a way that is "correct", but: I explicitly have to add -DNDEBUG to CFLAGS in such a use-case to not have certain things be built in a debug mode, as omitting the preprocessor macro builds those components in debug mode (see grep -R "NDEBUG" . in the supercollider sources).

yes, you will have to add `-DNDEBUG -O2` to cflags -- i don't understand the problem. i don't agree with changing the flags added for Release, if that's what you're getting at.

@redFrik please don't leave off-topic comments. i'll open a PR to fix the build instructions.

**Comment by dvzrv** [comment] 2020-09-10 13:24
> yes, you will have to add -DNDEBUG -O2 to cflags -- i don't understand the problem. i don't agree with changing the flags added for Release, if that's what you're getting at.

I don't want to change the `Release` build type. I just want to note, that `-DNDEBUG` has to be provided if setting the build type to `None` (as otherwise - parts - of the code base is set to be in debug mode).
The latter feels wrong. I understand the desire to use `RelWithDebInfo` if there is no build type select at all, but also (implicitly) building parts of the code base in debug mode when `None` is explicitly selected seems not right (the user did not select `Debug` or `RelWithDebInfo`).

Maybe we can specifically set `-DNDEBUG` if build type is `None`? It does not make sense to me to be building a debug build there too.

**Comment by redFrik** [comment] 2020-09-10 13:41
@brianlheim sorry but in my world that wasn't off-topic. the broken sc3-plugins instructions are what initially lead to the findings and the report of the problem you're discussing now (involving other people and other channels).

**Comment by brianlheim** [comment] 2020-09-10 14:27
@dvzrv thanks for clarifying. i don't want to change it. `None` is supposed to be for people to add their own flags. this is expected by users of projects that build with cmake. if we added -DNDEBUG to None it would prevent people from doing things like compiling under `-O1` or `-Os` with NDEBUG code and asserts enabled. note that what you said also applies to any codebase using the common `assert` macro which also changes based on NDEBUG.

> Is besides the automatic increase in optimization anything else being set, that I should be aware of? I can not find any specific references to this build type in the cmake setup.

it's `-DNDEBUG -O3` and we don't add anything else.

@redFrik thanks for clarifying. it would be much more helpful in the future, if you think you've found a problem, to report it on the relevant repo under a new ticket, so that the maintainers of that project can see it and reference it in discussions. if that's background knowledge for this issue, you could have made that connection in your earlier comment -- i had no way of knowing it was connected to this in that way.

**Comment by brianlheim** [comment] 2020-09-10 14:38
if you or someone else puts a PR together i'll review it. IMO, using `None` at all is 'advanced knowledge', and at that level anyone using it had better know about `NDEBUG` and have a good idea of what they want to accomplish. i'm not sure who would be helped by this information, which is why i'm not going to add it myself.

closing this ticket as the original question has been answered.

**Closed by brianlheim** 2020-09-10 14:38 UTC
Labels: enhancement, question

**Comment by simonvanderveldt** [comment] 2020-10-18 15:30
@dvzrv Just to be sure: Are you saying that some parts of sc3-plugins are being built with debug enabled when `CMAKE_BUILD_TYPE` is set to `None`?

**Comment by brianlheim** [comment] 2020-10-18 15:41
@simonvanderveldt effectively yes because some debugging code is only *disabled* if the macro NDEBUG is defined during compilation. a `None` build type doesn't define this macro because it doesn't pass any flags at all to the compiler.

**Comment by simonvanderveldt** [comment] 2020-10-18 16:04
@brianlheim Thanks for the info. Isn't that a bug/wrong though? Shouldn't the debugging code only be enabled when doing a debug build (`CMAKE_BUILD_TYPE=Debug`)?

**Comment by brianlheim** [comment] 2020-10-18 16:08
no, it is not a bug. please reread the above conversation for an explanation.

**Comment by simonvanderveldt** [comment] 2020-10-18 16:53
@brianlheim Thanks, I already read the issue, I don't see anything like this mentioned? I guess you mean the part that `-DNDEBUG` shouldn't be added to `CMAKE_BUILD_TYPE=None`?
That wasn't really what I meant, I was wondering why debugging code actively needs to be disabled instead of enabled, that seems backwards to me.

But I guess this is just what it is, `NDEBUG` has been around for ages and it results in this backwards situation.It never made sense to me to use a negated thing (`NOdebug`) to conditionally enable/disable some code (and even worse, you need to use another negation (`ifndef`) to do so) instead of just using the non-negated thing (`DEBUG`).

In any case, I think we can simply use `CMAKE_BUILD_TYPE=None` together with `-DNDEBUG` which should result in no compiler flags coming from the build system and all debug code disabled.

**Comment by brianlheim** [comment] 2020-10-18 16:58
let's continue discussing this on https://github.com/gentoo-audio/audio-overlay/issues/367#issuecomment-711289300? don't want to split the conversation.

**Comment by brianlheim** [comment] 2020-10-18 16:59
(or maybe here is better? up to you :) )

**Comment by brianlheim** [comment] 2020-10-18 17:24
@simonvanderveldt sorry for the misunderstandings!

> But I guess this is just what it is, NDEBUG has been around for ages and it results in this backwards situation.It never made sense to me to use a negated thing (NOdebug) to conditionally enable/disable some code (and even worse, you need to use another negation (ifndef) to do so) instead of just using the non-negated thing (DEBUG).

yeah, that's mainly the problem, it's also in the C standard as something to disable the `assert` macro.

@dvzrv @simonvanderveldt would it make sense at all to add one or more new build types for distribution maintainers? @simonvanderveldt you mentioned `CMAKE_BUILD_TYPE=gentoo` on the other page. instinctively, this feels like an odd solution because i would expect this to be something distribution maintainers themselves manage, but since i don't package anything myself i'd be ready to believe it makes things easier.

**Comment by simonvanderveldt** [comment] 2020-10-18 18:01
> @simonvanderveldt you mentioned `CMAKE_BUILD_TYPE=gentoo` on the other page. instinctively, this feels like an odd solution because i would expect this to be something distribution maintainers themselves manage, but since i don't package anything myself i'd be ready to believe it makes things easier.

Ah, yeah, there's some misunderstanding here I think :)
The value "gentoo" is only provided to ensure that the build type doesn't exist in the CMake config to ensure no compilation settings are set via the build script. It's just a additional safety measure which slightly enhances the chance of no compilation settings being set vs `None`. It should definitely not be included in any CMake config.

> @dvzrv @simonvanderveldt would it make sense at all to add one or more new build types for distribution maintainers?

I think we're totally OK with `CMAKE_BUILD_TYPE=None` together with `-DNDEBUG`. I'll do a test compilation that way to check. I'd expect the same to be the case for Arch/@dvzrv, although it would be better if he could confirm of course :)

**Comment by brianlheim** [comment] 2020-10-18 18:12
oh, i see, thanks for the clearing that up! cmake lets you add build configuration types with any name you want, so i thought maybe other projects had already set this up. i wasn't aware you could pass a nonexistent build type!

**Comment by simonvanderveldt** [comment] 2020-10-25 09:01
> I think we're totally OK with CMAKE_BUILD_TYPE=None together with -DNDEBUG. I'll do a test compilation that way to check.

@brianlheim quick follow-up on this, it worked as expected :) Thanks for the help!
