### ISSUE TITLE
Supernova NRT issues

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#5270] opened 2020-11-28 18:46 UTC
## Environment

* SuperCollider version:
* Operating system:
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce
Supernova crashes when receiving \d_recv message. Example:
```supercollider
(
var g;
Server.supernova;
Score.program = Server.program;
g = [
	[0, [\d_recv, SynthDef(\nrt, {Out.ar(0, SinOsc.ar(0.5))}).asBytes]],
	[0.2, [\s_new, \nrt, 1001, 0, 0]],
    [10, [\c_set, 0, 0]] // finish
    ];
Score.recordNRT(g, nil, "~/Desktop/testNRT.wav".standardizePath); // synthesize
)
```
(tested on 3.10.3 on macOS)

## Expected vs. actual behavior

This thread aims to gather issues with non-realtime synthesis on supernova. Let's use this thread to gather them all in one place.

**Comment by smrg-lm** [comment] 2020-11-29 02:56
Supernova also prints "late messages" in nrt when timetag is equal to now. From the example above it prints on Linux:
```
Performing non-rt synthesis:
late: 0.000000
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.000000000
late: 0.000000
node id 1 already in use
late: 0.000000
```
The cause is the following condition:
https://github.com/supercollider/supercollider/blob/f6a25a4b2a7d5e5e9e9d68bf4ca872c19ea92e4a/server/supernova/sc/sc_osc_handler.cpp#L846

I think it should be ``bundle_time < now`` for boot rt and nrt because that would be logically correct. Also to check for equality at that time scale wouldn't make any difference compensating later cpu time time.

**Comment by smrg-lm** [comment] 2020-11-29 02:56
There is still another related issue based on that example, something is duplicating the default group.

**Comment by smrg-lm** [comment] 2020-11-29 07:09
A workaround to the original problem is to store the definitions instead of putting them into the score, supernova will read them from disk.

I looks like a problem with the dispatchers in nrt (fire_system_callback) but I don't get it.

**Comment by Spacechild1** [comment] 2021-11-19 14:21
Hey, https://github.com/supercollider/supercollider/issues/5270 contains several bug fixes for NRT synthesis in Supernova.

I think it address all the issues described in this thread (including the duplicate default Group, which is really a bug in Score).

Can you give it a try? Are there any other issues that you notice with NRT synthesis in Supernova?

**Comment by smrg-lm** [comment] 2021-11-22 05:58
User test. The problems described above seem to be gone and render seems fine. Running the sample code above I have this output in Linux with one command late: 0.000544 which I don't know what could it be:

```
Supernova booting

Performing non-rt synthesis:
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.199999999
  Next OSC bundle: 10.000000000
late: 0.000544
  Next OSC bundle: 10.000000000

Non-rt synthesis finished in 0.009s
Peak summary:
  Channel 0: 0dB
  Channel 1: -infdB
```

**Comment by smrg-lm** [comment] 2021-11-22 06:26
Running a different example I get that late messages more often:

```
[[0.0, ['/g_new', 1, 0, 0]],
 [0.0, ['/d_recv', <memory at 0x7f50337bc4c0>, None]],
 [0.0, ['/s_new', 'default', 1000, 0, 1, 'freq', 233.08188075904496]],
 [0.3333333333333333,
  ['/s_new', 'default', 1001, 0, 1, 'freq', 293.6647679174076]],
 [0.6666666666666666,
  ['/s_new', 'default', 1002, 0, 1, 'freq', 329.6275569128699]],
 [1.0, ['/s_new', 'default', 1003, 0, 1, 'freq', 440.0]],
 [1.3333333333333333,
  ['/s_new', 'default', 1004, 0, 1, 'freq', 261.6255653005986]],
 [1.6666666666666665,
  ['/s_new', 'default', 1005, 0, 1, 'freq', 369.9944227116344]],
 [2.0, ['/n_set', 1000, 'gate', 0]],
 [2.0, ['/s_new', 'default', 1006, 0, 1, 'freq', 554.3652619537442]],
 [2.3333333333333335, ['/n_set', 1001, 'gate', 0]],
 [2.6666666666666665, ['/n_set', 1002, 'gate', 0]],
 [3.0, ['/n_set', 1003, 'gate', 0]],
 [3.333333333333333, ['/n_set', 1004, 'gate', 0]],
 [3.6666666666666665, ['/n_set', 1005, 'gate', 0]],
 [4.0, ['/n_set', 1006, 'gate', 0]],
 [4.333333333333333, ['/c_set', 0, 0]]]
Supernova booting

Performing non-rt synthesis:
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.333333333
  Next OSC bundle: 0.666666666
  Next OSC bundle: 1.000000000
  Next OSC bundle: 1.333333333
  Next OSC bundle: 1.666666666
  Next OSC bundle: 2.000000000
late: 0.001333
  Next OSC bundle: 2.000000000
  Next OSC bundle: 2.333333333
  Next OSC bundle: 2.666666666
  Next OSC bundle: 3.000000000
  Next OSC bundle: 3.333333333
  Next OSC bundle: 3.666666666
  Next OSC bundle: 4.000000000
  Next OSC bundle: 4.333333333

Non-rt synthesis finished in 0.009s
Peak summary:
  Channel 0: -9.69822dB
  Channel 1: -9.69822dB
```
That shows all score bundles (for sure) first and supernova output after. Maybe Score is duplication the last message now.

**Comment by Spacechild1** [comment] 2021-11-22 12:47
Yes, there was another logic error in the NRT scheduling. This should be fixed with the most recent commit. Can you give it a try?

**Comment by smrg-lm** [comment] 2021-11-22 19:43
It works, no more late maessages, boot time is a bit faster. Score.section is adding a dummy package at the time of the duration of the score, the last bundle, I think that is intentional but it is not possible to know the tail time of the last bundle, for example, if it's a release action with fade time, or in the first example of this issue if there is already a dummy message. It could be optional depending on whether the chain of parameters *recordNRT `duration`, -writeOSCFile `to` and  -section `end` time is notNil.

**Comment by smrg-lm** [comment] 2021-11-22 19:57
Also, in that chain, there is something quite common in sclang, of three nested methods two check if the same value is nil and set a value for it. The uncertainty of the null value. I should be resolved as soon as possible for the error message to be clear or the state of the object consistent. I think `section` and `writeOSCFile` aren't really part of the public interface.

**Comment by Spacechild1** [comment] 2021-11-22 20:16
> It works, no more late maessages, boot time is a bit faster. 

Great!

Regarding the dummy package: it is added if the duration is longer than the timestamp of the last bundle. But it seems to also get added when no duration is specified, so it gets the same timestamp as the last user specified bundle. I don't think there is a problem with that. Why would you want to omit this dummy bundle?

Anyway, this is not really about Supernova. I would suggest opening another issue instead if you think it is something that needs to be fixed/improved.

**Comment by smrg-lm** [comment] 2021-11-22 20:42
> I don't think there is a problem with that. Why would you want to omit this dummy bundle?

Because is like a duplicate message that's difficult to know from where it comes, but it's ok.

**Closed** 2021-12-02 23:38 UTC
Labels: bug, comp: supernova
