### ISSUE TITLE
branches/tags used for versioning of current git version

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#2857] opened 2017-04-29 12:39 UTC
I'm maintaining [supercollider-git](https://aur.archlinux.org/packages/supercollider-git/) for Arch Linux/ Arch Linux ARM, which is supposed to be the "bleeding edge" package for supercollider on those distributions.
I try to keep buildable for ARM and x86_64, but currently I'm stuck on the `3.8` branch, as I'm having a hard time understanding how to compile the version string for the current master version. Is there a git tags policy for this repository (especially the `master` branch)?
As far as I understand, supercollider is now in `3.9dev`, however, there's only the `master` branch to keep track of it?!

Usually something like `git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g;s/Version.//g'` is used to compile the version string. On master this currently returns `non.qt.build.r774.ged6cb1151` (which is not a valid version string).
When using `git describe --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g;s/Version.//g'` one gets `3.7.2.r1329.ged6cb1151` (which is a valid version string, but hopelessly "out of date" and as Arch is rolling release this would mean a downgrade, which is not impossible but very ugly).
There used to be valid tags for `master`. What happened to that?
`non.qt.build` seems to me more like a feature that should be developed in a separate branch and then merged.

It would be very helpful to get some input on this, as I'd like to be able to build a properly versioned supercollider-git package again (somewhere above 3.8 and below 3.9 (which reflects being 3.9dev), also to fix [the issue with scvim](https://github.com/supercollider/scvim/issues/27) (by disabling it in the build).

**Comment by telephon** [comment] 2017-04-29 19:37
First of all: thanks a lot for this excellent support! Our bleeding edge is just the latest commit in `master`.

 I am not the right person to talk to probably, so I just ask a question: for referring to that latest version, you are always referring to a specific tag? So we'd need to add tags to master?

**Comment by dvzrv** [comment] 2017-04-29 20:24
@telephon: you're welcome. Since I'm using it a lot myself, someone has to do it ;-)

> for referring to that latest version, you are always referring to a specific tag? So we'd need to add tags to master?

[Tagging in git](https://git-scm.com/book/en/v2/Git-Basics-Tagging) is usually used for creating versions (and that's how it's usually done: tags on master branch define the versions, [branching](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) is used to create new functionality and merge it into master).

I don't know what your workflow with the supercollider repository is, so I can't really comment on that.
What I've mentioned earlier is just what I've come across in every other software project so far and when looking at git seems to be the default.

Arch Linux [requires version strings to be created](https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git) for vcs/git packages (using the pkgver() function, as part of a [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) - the recipe for [building a package on Arch Linux](https://wiki.archlinux.org/index.php/Arch_Build_System)).
In the case of supercollider, there is versioning (we're currently above version `3.8`, that's also somehow reflected in the (now unused) branch `3.8`) available, so the rule of getting "the most recent un-annotated tag reachable from the last commit" or "the most recent annotated tag reachable from the last commit" applies (as shown [in the first comment](https://github.com/supercollider/supercollider/issues/2857#issue-225254421) respectively).
Unfortunately, the consequent tagging in `master` stopped somehow, which is why I had to use the `3.8` branch for the git package.

It would be very good to create version tags in master again and remove the ones that are not useful for versioning (such as `non.qt.build`).

**Comment by brianlheim** [comment] 2017-04-29 21:55
I've been experimenting around with this. We _do_ have a tag for 3.8.0, but like you I haven't been able to get it to show up with `git describe`, @dvzrv.

https://github.com/supercollider/supercollider/tags

No idea why it's not showing up. `3.8.0` is later than `non.qt.build`, so even if you were searching all tags (not just annotated ones) it should show.

**Comment by dvzrv** [comment] 2017-04-29 22:05
@brianlheim I think the tag `3.8` is only available in the branch `3.8`.
In any case, it's not a good idea to tag in `master` using non-version tags.

**Comment by brianlheim** [comment] 2017-04-29 22:10
> I think the tag 3.8 is only available in the branch 3.8.

Ah, you're right. I'm unfamiliar with tagging and kind of assumed the tags I was seeing locally were only for the currently checked out branch.

> In any case, it's not a good idea to tag in master using non-version tags.

Agreed.

**Comment by brianlheim** [comment] 2017-04-29 22:38
Ok, it looks like the commit we want is https://github.com/supercollider/supercollider/commit/968a5b4780bb1798c91c50b5867e6356ec4feb11, which is the commit directly before the version string was bumped to "3.9dev" and directly after all the 3.8 branch changes were merged into master. My question is, would it be OK to force-update the tag to point there instead of the 3.8 branch? `Version-3.8.0` can only point to one place, and that seems like the far better place to point it... I'm just not sure if that's going to make trouble elsewhere. Otherwise, we could tag the commit directly after it with `Version-3.9.0-dev`... not so into that, but just thought I'd ask.

**Comment by dvzrv** [comment] 2017-04-29 22:53
@brianlheim I would suggest deleting the tag in the `3.8` branch if possible and then adding it to `master`.
Getting rid of all non-version tags would also be great. Helps keeping things clean :-)

**Comment by crucialfelix** [comment] 2017-05-01 16:24
3.9dev is the informal version number for something that isn't released at all yet. That is so that the application itself displays the version as 3.9dev

Our "master" branch is what most projects would call "development".  

I would prefer that master be only for releases (git flow style) and development to happen on "development" but that isn't how it is set up. I've proposed it before.  git flow is great for doing releases. So there we are.

X.Y.z Releases are on their own branches. New patch releases will appear on those branches. (3.8.1 etc)  Changes made there are merged back into master.

The latest release is 3.8.0  The tag Version-3.8.0 should point to exactly the code that was shipped for that release. The commit after that is the merge to master, and that may be different than what was released. It probably includes development work that was going on while the release was being finalized.

I think supercollider-git should be checking out and building precisely that commit: https://github.com/supercollider/supercollider/commit/0947eddc009e2cfe504aeb88f46476e90935a259

Can you fetch this: https://api.github.com/repos/supercollider/supercollider/releases

then you can get the tag of the latest release.

**Comment by crucialfelix** [comment] 2017-05-01 16:28
@dvzrv " I would suggest deleting the tag in the 3.8 branch if possible and then adding it to master." 

That would be really messy I think. You would have to change every release.  If the problem is just how to fetch the latest release then let's just solve that in a less invasive way.

**Comment by crucialfelix** [comment] 2017-05-01 16:30
>> In any case, it's not a good idea to tag in master using non-version tags.
> Agreed.

I would agree if master was just for releases and development work was done in a development branch. But that isn't the case.  What you guys are implying is that tags cannot be used at all unless they are for tagging releases. Nobody could tag anything at all if there is any chance that that commit will eventually make it into any release.  A tag is just a variable that points to a commit hash. It isn't "on" a branch — it is a point on a river that may flow into other rivers.

**Comment by brianlheim** [comment] 2017-05-01 17:09
This is probably a good topic for discussion at the next dev meeting. It's been brought up before and definitely still needs to be resolved. @crucialfelix, @dvzrv are you interested in talking about it this weekend with some of the other devs?

**Comment by dvzrv** [comment] 2017-05-01 17:36
> I think supercollider-git should be checking out and building precisely that commit: 0947edd

Unfortunately that would be a fixed version. We have the supercollider package in the main repositories to deal with the stable `3.8` version. VCS packages are explicitely for grabbing the most current version from a repository (preferably `master` branch, or any `development` branch, if available). Users using the [AUR](https://aur.archlinux.org) can therefore choose to build "the latest version" at any given moment in time, neatly packaged (in theory).
To be able to reach commits > `3.8` from within a PKGBUILD's pkgver() function, I had to switch to the `3.8` branch. This however is not the latest version and a branch separate from what is currently being developed. From the above commit I can not reach anything above the `Version-3.8` tag (ending up in a version string, prefixed with a 3.8).

The supercollider-git package is specifically for people, who want to try out newest features and test that everything builds okay.
As mentioned in [my first comment](https://github.com/supercollider/supercollider/issues/2857#issue-225254421), the usual ways of calculating the version string (which is a requirement for a package) currently don't work, which means, that for half a year this package has been stuck. I unfortunately didn't have the time to deal with this earlier.

While I agree, that tags can be used for basically anything, doing so on the master branch also breaks with the convention of using it for versioning in a coherent way (especially, if used like that before and if the project requires versioning).
Git frontends such as [cgit](https://git.zx2c4.com/cgit/about/) even use this functionality to automatically generate the version tarballs for you, once a tag has been added.

@brianlheim sure thing. will date/place be pushed to the mailing list?

**Comment by brianlheim** [comment] 2017-05-01 17:42
@dvzrv Wonderful. Usually the meeting is at 20:00 UTC on Saturday, but the time is negotiable since we have a smallish group.

**Comment by crucialfelix** [comment] 2017-05-01 22:40
OK, I understand. You need to be on master, and there isn't really going to be a tag.

Can you use just HEAD ?

> To be able to reach commits > 3.8 from within a PKGBUILD's pkgver() function, I had to switch to the 3.8 branch. This however is not the latest version

Well certainly not. 3.8 is all that is going to be on 3.8 and there isn't anything after that. master is always the latest.

**Comment by dvzrv** [comment] 2017-05-01 23:55
> [..] there isn't really going to be a tag.

Why is that?

> Can you use just HEAD ?

That boils down to something like `Version-3.7.2-1336-gf80d6e047` (in one commit it would be cool ;-) ).
I could do search/replace on `Version-3.7.2`, but it requires more maintenance, is more error prone and technically not really correct.

> master is always the latest.

I get that. I'm just wondering, why since `3.7.2` the `Version-` tags didn't end up on `master`.

> I would prefer that master be only for releases (git flow style) and development to happen on "development" but that isn't how it is set up. I've proposed it before. git flow is great for doing releases. So there we are.

I get the feeling this topic is rather blessed with resentment. For my case I can try and make the above version work. Seems the easiest solution.

**Comment by dvzrv** [comment] 2017-05-02 16:01
So... I can get a version string such as `3.8.r1336.gf80d6e047` when applying what was proposed above.
The thing with this solution is: the `r1336.gf80d6e047` part is tracking all commits since the tag `Version-3.7.2` and not since `Version-3.8`. Not ideal, but it works.

Anyways: I'd be happy to see some sort of flow pattern (personally, I prefer [oneflow](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow) over [gitflow](http://endoflineblog.com/gitflow-considered-harmful) though). Having release tags on master (or any other eternal branch) would be great, as it gives some consistency and helps me and others to maintain development packages (which in turn help the project to fix bugs).

@brianlheim I might not be able to join on Saturday. Seems I have a gig then...

**Comment by crucialfelix** [comment] 2017-05-02 16:24
I'm not quite sure why 3.7.2 and 3.8 are not on master. It might have to do with the really weird Windows branch surgery we had to do. (It's a long story...)

It might be my mistake. I've always merged to master right after doing the release.

All the actual code is definitely on master.

**Comment by bagong** [comment] 2017-05-02 16:31
I am not getting this: how could the version tags be on master if they serve to tag the commit, from which the release was made? Would it be possible at all to merge that tag into master? You can't have the same tag twice, can you? And, as we continued committing to master during the release process, in my understanding there is no "spot" in master where the source equals a release, so it wouldn't make sense there either. Maybe in the past the n.x.0-release was made from master?

**Comment by gusano** [comment] 2017-05-02 17:35
@crucialfelix @bagong that's probably because those "missing" tags are ["lightweight" tags](http://stackoverflow.com/a/13412713):

```
$> git cat-file -t non-qt-build
commit
$> git cat-file -t Version-3.6.0
commit
$> git cat-file -t Version-3.7.2
tag
$> git cat-file -t Version-3.8.0
tag
```

> To create a tag object you must use one of -a (annotated) or -s or -u (signed) options to git tag, otherwise a lightweight tag (a reference pointing straight to a commit) will be created.
> [...]
> To resolve the issue you can recreate the tag with -f and (say) -a.
> `git tag -f -a Version-xxx Version-xxx`

**Comment by bagong** [comment] 2017-05-02 17:45
Thanks for the explanation @gusano. I didn't know that...

**Comment by crucialfelix** [comment] 2017-05-03 11:13
Lord love a duck...  git is an endless source of amusement.

I wonder if there is any messy consequences if we rewrite those and push.

**Comment by dvzrv** [comment] 2017-05-03 11:23
@gusano thx, didn't know that either! Luckily always used `-a` by default.
@crucialfelix hehehe, only one way to find out :>

\*thumbspressed\*

**Comment by telephon** [comment] 2017-05-03 12:38
Probably we could start to tag master, in small steps, and every once in a while make a release branch from one of them.

**Comment by brianlheim** [comment] 2017-05-06 23:59
I am going to close this because I intend to keep bringing this topic up at dev meetings until we reach a good solution for git workflow. It sounds like as a team we're all on board with version tagging on master, modulo 3.8 as an anomaly, and that for now a working solution is to use the tag on the 3.8 branch.

**Closed by brianlheim** 2017-05-06 23:59 UTC
Labels: git repository

**Comment by snappizz** [comment] 2017-12-09 21:43
just for the record -- we have now moved to git-flow and master branch will always be stable from 3.9 on, and that's where tags will reside.
