### ISSUE TITLE
Sclang keeps crashing on recent build (Win)

### ISSUE THREAD

**Issue by Jaaaaaa** [supercollider/supercollider#1405] opened 2015-04-04 12:09 UTC
Bug description:

sclang seems to be crashing all the time on recent build, I am running win 7 64-bit

I have compiled the recent version from GH via MSYS and QT 5.3.2, the problematic library seems to be Qt5Cored.dll which throws APPCRASH with exception 40000015 (have no idea what it means)

Steps to reproduce:
1. Run the interpreter
2. random crashes of sclang.exe (quite often, not lasting more then 2 mins inbetween)
3. rebooting interpreter hold for few minutes

**Comment by bagong** [comment] 2015-04-04 13:32
The crashes are triggered by typing and mouse dragging in an editor pane. It's the one serious bug that keeps the Windows-version from being use-/teste-able. Btw, work is currently under way to build a 64-bit version of SC 3.7 with Visual Studio 2013. That compile shows the same problem. It should be available in a slightly polished version of this pull request https://github.com/supercollider/supercollider/pull/1387 in a few days. Interested to help? You're strongly encouraged :)

**Comment by sofakid** [comment] 2015-04-04 18:54
I'll bet 7 internets that it's a bug in the autocomplete menu stuff.

**Comment by bagong** [comment] 2015-05-04 16:43
Lucas Cornelisse has been looking into this. It's not easy to debug. It has been there since Tim revitalized the Windows port last November. Lucas came to the conclusion that the problem is located in the IPC and must have to dow with how Qt and yaml-cpp interact (I hope I reproduce this correctly ;) ). 

Quote: "for the ipc, it seems they just used qt and yaml because it was convenient ... but it's just sending strings and numbers ... wrapped in QStrings and stuffed in QVariantLists ... windows localsockets might be a little different ... blockingwise ... the receiving end is correctly serializing a string, and then serializing an empty list that should have data ... if i check if the args are empty first, it works ... but the sending end then goes nuts in yaml ... consuming all the memory and cycles ... but there's only two functions and they are simple ... well four, one on each end ... i think it would be easy ... just write the bytes and read them”

The current Windows version is in a branch `winport` in https://github.com/bagong/supercollider.git. The open pull-request in the SC Github repo is outdated - you should not work from it. The Readme in the new version is updated and contains both a detailed and a tl;dr description of the build systems (VS & Msys2/MinGW. It shouldn’t take more than two hours to get it going.

**Comment by Jaaaaaa** [comment] 2015-05-04 21:56
Thanks a lot of for that answer. I will try to make a new build but on the other hand, i don't have almost any experience with compiling. After first reading of readme_win i'm little bit afraid it doesn't take just 2h for me. Before i manage to setup that isnt it possible to find any installer that has been built after half of march? Its little bit frustrating to watch SC on other platforms and see how some problems are solved here.

**Comment by bagong** [comment] 2015-05-04 23:31
I hope I didn't sound misleading: the bug has not been resolved yet. So an installer wouldn't help. As you've built with msys in the past, following the quick steps for msys2 should be fine. Building with msys2 is now a lot cleaner than it used to be in the past

**Comment by Jaaaaaa** [comment] 2015-05-05 10:20
I understand that issue still isn't solved. But mine build is extremely unstable and that's a reason why i used older one from march. That's true on that the interpreter crash there to but it looks no so often. And I'm sure is somehow connected with qt5 and keyDownAction. Second reason why i look for some installer is i have problem to make my own -install, so i can't test it on other pc. During that period but was made a lot of changes on other issues (for example around Document and ScIDE) which aren't possible to use for me. Thats why I asking for some semi-stable installer

**Comment by bagong** [comment] 2015-05-05 10:49
Hmm, so what do you need, exactly? Since the switch to Qt5 I haven't had a build that can be used from the IDE. That's the case for both build environments, and from Qt 5.2.1-5.4.1, and as to MinGW for gcc4.8.2 up to 4.9.2. In all my builds sclang crashes after a few keystrokes. It's hard for me to help, because I don't want to change my environment, which is locked to GCC4.9.2 and Qt5.4.1. Likely any perceived differences in stability are due to differences in the environment, or build type/configuration.
I have a build of 3.7alpha from end 2013 (before the switch to boost-asio) using qt4, or I could create an installer of the current build, that's easy. But maybe you can wait until the issue is resolved? Then we don't get immature builds floating around in public.

**Comment by bagong** [comment] 2015-05-05 10:58
And, btw, if you still have a build you like, just zip the application install folder and move it to another machine, that should work fine. The installer just makes this process a bit more comfortable and creates/removes registry settings which are not that important.

**Comment by Jaaaaaa** [comment] 2015-05-05 12:32
That's what i tried, but it doesn't found after move some dll??? And sorry, i forgot. Like last I tried switch back to qt4.8.2. because I wasn't successful with Qt5. I will wait for some new release and will try again to prepare some build by instructions from readme_win

**Comment by bagong** [comment] 2015-05-05 12:44
If it's missing dll's you likely didn't run the step:
`make bundle`
That will copy all required dll's into the install folder (takes ages)
I still don't fully understand what you're actually after. If you'd like to have your own build system of a recent version with Qt5, go for the `winport` branch in https://github.com/bagong/supercollider.git. That's the latest as to the Windows port and will likely make it into master in a few weeks.
There is no SCWin version with Qt5 that does not contain the bug you describe. If you want to make a 3.7 build with Qt4 you have to go way back to get a working build - I think it has to be before August 2013.

**Comment by bagong** [comment] 2015-05-06 00:24
So the only thing I can offer are most recent builds and a few quite old ones. Have a look here if you find anything that suits your needs:
https://drive.google.com/folderview?id=0B7igZrWv7UxdUmxHdThYLUE2QXc&usp=sharing

**Comment by Jaaaaaa** [comment] 2015-05-06 10:09
Really thanks a lot for that but unfortunately any of them doesn't run to me. I tried all of them with this result. x64-VS missing MSVCR120.dll and MinGW make Runtime to terminate it in an unusual way with comment to contact support team:) Missing dll is something from win framework? And why it isn't attached during bundle? At MinGW no idea

**Comment by bagong** [comment] 2015-05-06 10:19
Okay, I'll look into that. Must find a second Windows computer first ;)

**Comment by bagong** [comment] 2015-05-07 02:12
Should be fixed now! Would be great if you tried them again (just two) to let me know if it's okay now.

**Comment by Jaaaaaa** [comment] 2015-05-07 09:43
Ok, both of them works. Thanks again, both looks more stable than mine own old build where it was just about one or three keyDown press.

**Comment by bagong** [comment] 2015-05-07 09:44
Thank you for verifying!!

**Comment by bagong** [comment] 2015-05-07 09:50
You can kind of use it by editing your text with dead interpreter and then boot the interpreter before you want to evaluate some code. Not ideal ;) If you head into other issues, we are very interested to here about them!

**Comment by Jaaaaaa** [comment] 2015-05-07 10:26
Yes, i see some other, so i will add new issues for win. And most common crash of interpretr is exit code:3. Is it Qt exception? What is it?

**Comment by sofakid** [comment] 2015-05-07 19:22
I dont know what 3 is, but qt is how we're doing the ipc from the ide to
sclang. i've verified with a debugger that the receiving end gets a header
but no payload, and it crashes when attepting to read the payload (supposed
to be a list of qstrings).

**Comment by bagong** [comment] 2015-05-10 10:10
Btw, I have switched compiler optimizations off (-O0) for now. That allows the release build to work and makes the sclang crashes significantly less frequent. If you want to give it a try, they are under the link quoted above.
Thanks!

**Comment by Jaaaaaa** [comment] 2015-05-10 11:43
I tried two of them (SuperCollider-201505100522-3.7alpha0_Release-x64-VS-01ec3bf and SuperCollider-201505100522-3.7alpha0_Release-x86-MinGW-01ec3bf) but both of them crashing extremly often.

**Comment by bagong** [comment] 2015-05-10 11:50
Okay, that's quite relative though. The issue is not gone, as I said, I just saw that it's significantly less (on my system) than before, so might be worth experimenting with that one rather than older builds. Release doesn't mean release candidate, just release build as opposed to debug build...
So you didn't notice any difference at all? Have you tried renaming your appSupportDirectory to get a clean upstart? At some point I thought that would make a change, but... ;)

**Comment by Jaaaaaa** [comment] 2015-05-10 12:44
I understand and I just making test. I tried it again with clear upstart but it looks same. But what look like great help is switch off IDE-popup autocomplete help. Not at all, but it help to me.

**Comment by Jaaaaaa** [comment] 2015-05-10 12:55
hmm, not to much

**Comment by bagong** [comment] 2015-05-10 22:13
Thank you for keeping trying! It's a strange thing, I sometimes can keep typing for minutes without a crash, and then again it get's into a state where it crashes every three keystrokes... Same build, same machine... Some outer factor must be interfering, but I haven't isolated it yet...

**Comment by Jaaaaaa** [comment] 2015-05-10 22:23
For me looks now like most stable some release which i found at march (SuperCollider-3.7alpha0-win32-2014.03.16  -  89Mb). Has similar style of naming like yours. Is running on Qt5.3.2 and running around 3hours without any crash. I know in code has been happend a lot from march, but if that can help.

**Comment by bagong** [comment] 2015-05-10 22:28
Please send me the build, I will be happy to test it! It could help us find out what's going on. Myself I don't remember ever having a built something more stable than the ones available now.

**Comment by bagong** [comment] 2015-05-10 22:34
I found a copy of the build in an old backup! Will test it tomorrow!

**Comment by Jaaaaaa** [comment] 2015-05-10 22:35
https://dl.dropboxusercontent.com/u/33961056/SuperCollider-3.7alpha0-win32-2014.03.16.exe

**Comment by bagong** [comment] 2015-05-10 22:37
Thanks, I assume it is the same I found when starting to search seariously...

**Comment by bagong** [comment] 2015-05-11 09:39
Man, you're right, it doesn't have that bug! I'll test now if it's the Qt-version. Lucas already assumed it could be a Qt bug and I contradicted because I remembered (wrongly) it was there in all builds I made... I'll try building with VS using Qt5.3.2 and see how it's there. Thanks for keeping bugging!!

PS: I'll remove that march build again as it's missing the platform plugin ;)

**Comment by bagong** [comment] 2015-05-11 10:28
Wow, the bug is gone when using Qt5.3 in the VS build! Thanks man, I'll investigate further.

**Comment by bagong** [comment] 2015-05-15 06:43
I tried this build on another computer, and the bug resurfaced. It's there in that March build as well. The weird thing is in some situations it seems to be gone, but it comes back for sure! So just to be clear: Qt5.3.2 is *not* the solution. (I went as far as building Qt5.3.2 for my msys2 environment just to find it makes no difference :( ) If anything, it's the combination of building with Qt5.3.2 and using VS... But that's also not really a "solution" either...

**Comment by bagong** [comment] 2015-06-26 09:14
This problem is solved now. You can build from the branch topic/scwin3.7 now or get binary installers from:
https://drive.google.com/folderview?id=0B7igZrWv7UxdUmxHdThYLUE2QXc&usp=sharing

**Comment by Jaaaaaa** [comment] 2015-06-26 09:26
Thanks, thanks a lot. I tested it after yours comments on issue #1560 yesterday and I can confirm, no crash yet.

So again, thanks

**Comment by bagong** [comment] 2015-06-26 09:44
So close this?

**Closed** 2015-06-27 19:58 UTC
Labels: bug, crash, os: Windows, waiting for testing
