### ISSUE TITLE
rendered schelp troubles with indented string continuations

### ISSUE THREAD

**Issue by shimpe** [supercollider/supercollider#3734] opened 2018-05-20 09:30 UTC
The problem is with strings in combination with indentation, e.g.

```
(
~st = "sea"
      "saw".postln;
)
```

The above works when typed into scide and executed and produces the expected "seasaw". 

However, when you paste it from scide in a

code::
::

environment in a schelp document, it no longer works when copy pasting the example from the rendered help page into scide, and fails with:

> ERROR: syntax error, unexpected STRING, expecting DOTDOT or ':' or ',' or ')'
>   in interpreted text
>   line 3 char 14:
> 
>         "saw".postln;
>             ^^^^
>   ) 
> -----------------------------------
> ERROR: Command line parse failed
> -> nil

It starts working only if you remove the indentation before the word "saw" in the schelp document.

**Comment by brianlheim** [comment] 2018-05-20 16:40
Duplicate of #361.

**Closed by brianlheim** 2018-05-20 16:40 UTC
