### ISSUE TITLE
convert editors/scel to submodule like scvim

### ISSUE THREAD

**Issue by nilninull** [supercollider/supercollider#3066] opened 2017-07-29 11:48 UTC
I want to edit scel programs. 
Since this directory is independent of other parts, it is easier to develop if it is submodule like scvim, I think.

**Comment by brianlheim** [comment] 2017-07-29 14:38
i am in favor of this; i'm generally in favor of breaking smaller less frequently used SC components into submodules.

helpful reading in case anyone is interested in taking a swing at this in a way that preserves history:
https://stackoverflow.com/questions/17413493/create-a-submodule-repository-from-a-folder-and-keep-its-git-commit-history

**Comment by telephon** [comment] 2017-09-23 19:03
just keep in mind that in the past the introduction of submodules have made it very hard to switch between branches that don't share the same submodules. Each time you switch, you have to delete files by hand.

So maybe there is a way to do such changes in a way and at a time where they cause less troubles?

**Comment by brianlheim** [comment] 2017-09-23 19:44
yes, that's a good point. if we do decide on it we should consider other submodules that could be moved out at the same time.

**Comment by widp** [comment] 2018-01-31 07:29
I want to give this a try.
 Could you elaborate how submodules cause problems? If it's the modifications in the submodules that don't have to be commited adding "ignore = dirty" in the .gitmodules file do the trick.

**Comment by vivid-synth** [comment] 2018-02-04 15:04
I'm not positive about this but I recall one of the scvim issues being that the submodule was named the same as the previous directory was (both "editors/scvim"), which caused git to act annoyingly. If we change the submodule's name to something slightly different than "editors/scel" we _might_ not have the same switching-branches issue.

**Comment by widp** [comment] 2018-02-08 04:36
@vivid-synth this is indeed the case. The problem is caused because the contents of the submodule are not tracked. When we try to switch branches, since the  untracked files  have the same name as the still not submodule'd files in the other branch, those files have to be removed.

I suggest we rename the submodule to sclang-mode. Is that ok? I'll look into the impact of the rename (docs and build files to be changed etc.).

I've a history preserving repo [here](https://github.com/widp/sclang-mode). You can verify this by running "git log --name-status editors/scel" in the sc git repo. Could you fork that repo? After that's done, I'll submit a pull request which removes the existing scel directory and adds a submodule pointing to the forked repository.

**Comment by brianlheim** [comment] 2018-02-08 05:09
> adds a submodule pointing to the forked repository.

Just to be clear: it will be forked as an sc-org repo. I would be perfectly happy to give people interested in improving scel admin or close to admin access over that repo.

> I suggest we rename the submodule to sclang-mode

A name that includes "el" or "emacs" would be best, to distinguish it from other editor targets.

**Comment by brianlheim** [comment] 2018-02-08 05:09
Thanks for taking initiative on this @widp!

**Comment by widp** [comment] 2018-02-08 07:26
> Just to be clear: it will be forked as an sc-org repo. I would be perfectly happy to give people interested in improving scel admin or close to admin access over that repo.

yup, that was what I meant. I am interested in maintaining the package.

el-sc, el-supercollider are some other names I can think of.

**Comment by brianlheim** [comment] 2018-02-08 23:08
OK, testing locally I can confirm that separating out into a submodule with a different name doesn't cause conflicts. I believed you, but just had to see it for myself since I'd never tried it before. :)

All concerns in this thread so far have been addressed, but this is a big move so I'm going to ask about this on the mailing list too.

**Comment by brianlheim** [comment] 2018-02-15 03:56
@widp - I've forked your repo and given you write access. @nilninull, are you also still interested in working on scel?

Coming back to this after a couple days, my feeling is that to avoid having to rename everything everywhere, it might be best to simply use a slightly different name for the submodule folder, but keep the project name as `scel`. Is that OK with everyone? The folder can be `scel-proj` or `sc-el` or something similar. This doesn't have to be a user-facing change; I just see no other compelling reason to change it.

**Comment by gusano** [comment] 2018-02-15 15:01
@brianlheim `sc-el` for the folder sounds great!

**Comment by brianlheim** [comment] 2018-02-15 15:50
OK great. I will change the name of the repository and make a PR for the submodule soon

**Comment by widp** [comment] 2018-02-15 17:10
@brianlheim I was already working on it. The PR is here #3519.

**Comment by brianlheim** [comment] 2018-03-01 03:24
Closed by #3519.

**Closed by brianlheim** 2018-03-01 03:25 UTC
Labels: env: scel, organizational
