### ISSUE TITLE
.schelp errors break install with -DSC_DOC_RENDER

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2024] opened 2016-05-03 17:50 UTC
On Linux, with SC already installed, installing from a fresh repository:

```
 $ git clone git://github.com/supercollider/supercollider
 $ cd supercollider/
 $ git submodule update --init --recursive
 $ git fsck
 $ echo $?
0
 $ mkdir build && cd build
 $ cmake -DSC_DOC_RENDER=True -DSC_IDE=False -DSC_QT=False ..
 $ echo $?
0
 $ make
```

I see (cutting to the interesting part here):

> [ 40%] Built target sclang
> Scanning dependencies of target doc
> Exception when parsing YAML config file: yaml-cpp: error at line 0, column 0: bad dereference
> init_OSC
> empty
> Exception when parsing YAML config file: yaml-cpp: error at line 0, column 0: bad dereference
> compiling class library...
> initPassOne started
> 	NumPrimitives = 591
> initPassOne done
> 	compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary'
> 	compiling dir: '/usr/local/share/SuperCollider/Extensions'
> 	pass 1 done
> ERROR: Class extension for nonexistent class 'Document'
>      In file:'/deprecated/3.7/deprecated-3.7.sc'

[...]

Then a ton of warnings like:

> WARNING: SCDoc: In /home/air/box_build/sc8/supercollider/HelpSource/Classes/RawArray.schelp
>   Method -write not found.
> WARNING: SCDoc: In /home/air/box_build/sc8/supercollider/HelpSource/Classes/Paddp.schelp
>   Method *new has 3 args, but doc has 1 argument:: tags.
> WARNING: SCDoc: In /home/air/box_build/sc8/supercollider/HelpSource/Classes/Paddp.schelp
>   Method *new has arg named 'name', but doc has 'argument:: value'.
> WARNING: SCDoc: In /usr/local/share/SuperCollider/Extensions/SC3plugins/DEINDUGens/HelpSource/Classes/JPverbRaw.schelp
>   Method *ar has arg named 'mdepth', but doc has 'argument:: midx'.
> WARNING: SCDoc: In /usr/local/share/SuperCollider/Extensions/SC3plugins/DEINDUGens/HelpSource/Classes/JPverbRaw.schelp
>   Method *ar has arg named 'mfreq', but doc has 'argument:: mdepth'.

And finally:

> SCDoc: Done!
> main: quit request 0
> empty
> cleaning up OSC
> terminate called without an active exception
> Aborted
> CMakeFiles/doc.dir/build.make:57: recipe for target 'CMakeFiles/doc' failed
> make[2]: *** [CMakeFiles/doc] Error 134
> CMakeFiles/Makefile2:963: recipe for target 'CMakeFiles/doc.dir/all' failed
> make[1]: *** [CMakeFiles/doc.dir/all] Error 2
> Makefile:160: recipe for target 'all' failed
> make: *** [all] Error 2

This seems to be because it's looking at /usr/local/share/SuperCollider even while running ```make``` (before ```make install```) -- shouldn't it be looking in the build (or source) directory? If a person has SC already installed but they don't have ```make uninstall``` available (say, their repo is gone or they installed from a binary), does this mean they'd be unable to build the docs from source?

**Comment by bagong** [comment] 2016-05-03 18:04
You mean the error? The error is because sclang doesn't close properly (terminate called without an active exception). SCDoc completed successfully (SCDoc: Done!). I don't know how it comes that SCDoc is so smart to look in the sc3-plugins folders too, but that does not trigger the error. You get the same error (at least I got it on Windows) if you build SCDoc without SC3plugins installed.

**Comment by vivid-synth** [comment] 2016-05-03 18:13
@bagong this breaks the cmake install; it never gets past 40%

**Comment by bagong** [comment] 2016-05-03 18:16
Yes, true. I only know a workaround, if that is what you are looking for: build first without adding sc_doc_render, and then have the docs rendered in a second go. The fix would be to repair the shutdown-behaviour of sclang. This problem is kind of known, but usually doesn't impair the build because people rarely run sc_doc_render as part of a SC build.

**Comment by vivid-synth** [comment] 2016-05-03 18:29
So the huge number of .schelp warnings are accurate?

**Comment by bagong** [comment] 2016-05-03 18:37
Accurate in which sense? I think they are parse errors during help rendering, but they don't throw the build. SCDoc ends it's job without breaking. I think the SCDoc errors are the same kind of error you occasionally get informed about in the post window when you open a help page. The page triggers an error message but it still opens.

**Comment by bagong** [comment] 2016-05-03 19:02
You actually made me curious, because something is fishy with SCDoc, but who know what. So I opened the help document for `JPVerbRaw`, and got these errors (compare above your snippets):

```
SCDoc: Indexing help-files...
SCDoc: Indexed 1941 documents in 2.57 seconds
WARNING: SCDoc: In C:\Users\Rainer\AppData\Local\SuperCollider\Extensions\SC3plugins\DEINDUGens\HelpSource\Classes\JPverbRaw.schelp
  Method *ar has arg named 'mdepth', but doc has 'argument:: midx'.
WARNING: SCDoc: In C:\Users\Rainer\AppData\Local\SuperCollider\Extensions\SC3plugins\DEINDUGens\HelpSource\Classes\JPverbRaw.schelp
  Method *ar has arg named 'mfreq', but doc has 'argument:: mdepth'.
WARNING: SCDoc: In C:\Users\Rainer\AppData\Local\SuperCollider\Extensions\SC3plugins\DEINDUGens\HelpSource\Classes\JPverbRaw.schelp
  Method *ar has arg named 'midx', but doc has 'argument:: mfreq'.
```

I think your issue title is somewhat misleading... ;)

**Comment by vivid-synth** [comment] 2016-05-03 19:11
Ok, looks I mis-diagnosed because there are so many .schelp warnings: I assumed something particular to my system was wrong.

This issue now seems to be two things:
   - There are lots and lots of .schelp errors (around 294 for the supercollider repo plus sc3-plugins)
   - ```-DSC_DOC_RENDER``` shouldn't kill the cmake process even if there are .schelp errors (Maybe? Or maybe we actually want a clean build)

**Comment by bagong** [comment] 2016-05-03 19:15
> -DSC_DOC_RENDER shouldn't kill the cmake process even if there are .schelp errors (Maybe? Or maybe we actually want a clean build)

I think this is still not accurate. Cmake just closes sclang, and it is sclang itself that has a problem with this. You could try the following: open sclang (you have readline now, right? ;) ) and execute 0.exit on the command line and observe the shutdown behaviour. I think (but don't kill me if not ;) ) you will see the same error you got above:

`````
main: quit request 0
empty
cleaning up OSC
terminate called without an active exception
Aborted
````

**Comment by vivid-synth** [comment] 2016-05-03 19:19
Yes, I see that same "Aborted" message, including

```
$ echo $?
134
```

Is there a better way for me to describe the problem of the build dying?

(By the way, I added a third bullet point to the above list of issues)

**Comment by bagong** [comment] 2016-05-03 19:38
Sorry, I am feeling a bit pedantic now, but as you ask: you could say of course "the issue is that the build dies", it is a fact. But the fix is not repairing the build, there is nothing wrong with the build script, it just fails because sclang cannot be closed cleanly. Maybe you could try closing sclang in some other way so that it doesn't crash, or maybe there is a way to tell the build to ignore the sclang crash, but that would be a workaround. Sclang should not crash during a shutdown triggered by 0.exit.

As to your third bullet: from the snippets you post above it looks to me as if SCDoc was rendering the help-sources of *sc3-plugins*, which you must have installed before you built with sc_doc_render=on. Ohterwise JPVerbRaw would not be in that location. SCDoc must have some smartness as to identifying different places where help sources might be. It does render the help sources as contained in the SC-source (as we can see in your snippet), but it is also smart enough to find the sc3-plugins help sources and render them. That seems to me like a feature rather than a problem?

**Comment by bagong** [comment] 2016-05-12 14:00
@vivid-synth , You're on Linux, right? Could be that this is fixed in master now. Wanna give it a try?

**Comment by vivid-synth** [comment] 2016-05-15 01:43
Just rebuilt; can confirm that bullet point #2 (the whole cmake process dying) is no longer an issue. Thanks yall!

**Comment by bagong** [comment] 2016-05-15 06:08
Can we close this? Cleaning the help-doc markup is really a long term issue (people have been working on it lately, while enhancing the actual documentation), and technical problems with the scdoc renderer (of which I am sure there are some) may need a more specific description?

**Comment by crucialfelix** [comment] 2016-05-15 10:33
So in summary:
- it was 0.quit that caused the error message; this is part of the build process to make and install the help docs
- the docs do produce some warnings, but they weren't responsible for the build failure

2nd the motion to close. re-open if there's something still to do to make the doc building smoother.

**Closed by crucialfelix** 2016-05-15 10:33 UTC

**Comment by vivid-synth** [comment] 2016-08-08 19:45
Yes, can confirm this doesn't crash anymore.
