### ISSUE TITLE
QtWebEngine not copied correctly into SC Install builds

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3971] opened 2018-08-11 00:54 UTC
Environment
-----------

* SuperCollider version: [49a6746]
* Operating system and version: macOS 10.13.6
* QT: 5.11.1 (included in SC)

Under macOS 10.13.6, SC 3.8.1 is the last version which runs correctly regarding this.
Under macOS 10.11.5, SC 3.8.1, SC3.9.3 and SC3.10.beta1 runs correctly regarding this.

Expected Behavior
-----------------
- Help Browser should display its contents.
- `HelpBrowser.new.goTo("google.com")` should display its contents.
- `WebView().url_("google.com").front` should display its contents.

Current Behavior
----------------
- Help Browser is not loaded as reported in #908.
- `HelpBrowser.new.goTo("google.com")` displays a blank window after the window shortly blinks.
- `WebView().url_("google.com").front` displays nothing

Steps to reproduce (for bugs)
-----------------------------
1. launch SC and observer Help Browser.
2. evaluate: `HelpBrowser.new.goTo("google.com")`
3. evaluate: `WebView().url_("google.com").front` displays nothing

Error message (for bugs)
------------------------
There are no error messages.

**Comment by scztt** [comment] 2018-08-11 01:39
@prko If you launch from terminal, ala:
`/Applications/SuperCollider/Contents/MacOS/SuperCollider`, do you see any errors or oddities?

**Comment by prko** [comment] 2018-08-11 01:56
Last login: Sat Aug 11 10:48:38 on ttys000
prko-MBP:~ prko$ /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/MacOS/sclang
compiling class library...
	Found 835 primitives.
	Compiling directory '/Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Resources/SCClassLibrary'
	Compiling directory '/Users/prko/Library/Application Support/SuperCollider/Extensions'
	numentries = 1166851 / 17392662 = 0.067
	5571 method selectors, 3122 classes
	method table size 18790160 bytes, big table size 139141296
	Number of Symbols 13944
	Byte Code Size 395292
	compiled 443 files in 0.75 seconds
compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.02 seconds

QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found


*** Welcome to SuperCollider 3.10.0-beta1. *** For help type cmd-d.
Booting server 'localhost' on address 127.0.0.1:57110.
sc3> no more csLADSPA plugins
no more csLADSPA plugins
Found 0 LADSPA plugins
Number of Devices: 3
   0 : "Built-in Microph"
   1 : "Built-in Output"
   2 : "FF800-SF"

"Built-in Microph" Input Device
   Streams: 1
      0  channels 2

"Built-in Output" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 44100.000000, driver's block size = 512
Exception in World_OpenUDP: bind: Address already in use
Server 'localhost' exited with exit code 1.
[5958:80899:0811/105518.891050:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[5958:80899:0811/105518.893657:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[5958:80899:0811/105518.896659:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[5958:80899:0811/105519.161204:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[5958:80899:0811/105519.162003:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[5958:80899:0811/105519.162391:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[5958:80899:0811/105519.162506:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Users/prko/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service

**Comment by prko** [comment] 2018-08-11 05:53
I manually installed QT 5.11.1  (open source).
It does not solve the problem.

**Comment by scztt** [comment] 2018-08-12 20:40
The missing libraries / binaries listed in the log need to be copied as part of the "install" step in CMake. Probably just getting QtWebEngineProcess.app installed should do it.

**Comment by brianlheim** [comment] 2018-08-12 21:38
If this is reproducible it should be reported as a bug to the authors of macdeployqt of the qt project.

**Comment by prko** [comment] 2018-08-13 01:12
The following is the test of SC [0f779a49] under macOS 10.13.6 on iMac (27 inches, Late 2013):

Last login: Mon Aug 13 10:04:35 on console
prahms-iMac:~ prko$ /Volumes/Data\ iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/MacOS/SuperCollider        
GVA info: Successfully connected to the Intel plugin, offline Gen75 
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[1856:49411:0813/100719.636679:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[1856:49411:0813/100719.636899:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[1856:49411:0813/100719.636975:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[1856:49411:0813/100805.409105:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[1856:49411:0813/100805.410008:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[1856:49411:0813/100805.410122:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[1856:49411:0813/100809.500072:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[1856:49411:0813/100809.500424:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[1856:49411:0813/100809.500576:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Volumes/Data iMac/Dropbox/SuperCollider/3.10pre/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"

**Comment by prko** [comment] 2018-08-13 01:28
This is one more test.
In this test SC [0f779a49] location is /Applications/SuperCollider/
A new error in javascript occurs as well:

Last login: Mon Aug 13 10:06:57 on ttys000
prahms-iMac:~ prko$ /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider 
*** ERROR in JavaScript: "ReferenceError: Can't find variable: $"
* line: 464
* source ID: "file:///Users/prko/Library/Application%20Support/SuperCollider/Help/scdoc.js"
prahms-iMac:~ prko$ /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider 
GVA info: Successfully connected to the Intel plugin, offline Gen75 
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[2148:50947:0813/102441.420761:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[2148:50947:0813/102441.421636:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[2148:50947:0813/102441.421834:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[2148:50947:0813/102457.965422:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
[2148:50947:0813/102457.992944:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[2148:50947:0813/102457.993734:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[2148:50947:0813/102457.993864:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
dyld: Library not loaded: /usr/local/Cellar/qt/5.11.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
[2148:50947:0813/102458.069579:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[2148:50947:0813/102458.078077:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[2148:50947:0813/102458.081459:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[2148:50947:0813/102458.081623:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Applications/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service

**Comment by miczac** [comment] 2018-08-13 12:10
> On 13 Aug 2018, at 10:20, prko <notifications@github.com> wrote:
> 
> 3.9.3 does not return error messages in terminal. However, Help Browser only shows "sending request ..."


@prko : but this is different than this:
https://www.listarc.bham.ac.uk/lists/sc-users/msg61630.html
?

**Comment by prko** [comment] 2018-08-13 12:25
Oh, they seem to have the same problem.
In my case, The CPU usage does not reach 100%.

We know that 3.10-beta has the problem of QtWebEngine.
However, the cause of 3.9.x is still unknown. Probably we need a new issue for 3.9.2 and 3.9.3.

**Comment by miczac** [comment] 2018-08-13 12:33
> On 13 Aug 2018, at 14:25, prko <notifications@github.com> wrote:
> 
> We know that 3.10-beta has the problem of QtWebEngine.
> However, the cause of 3.9.x is still unknown. Probably we need a new issue for 3.9.2 and 3.9.3.

in sc-users you posted a request for testing: https://www.listarc.bham.ac.uk/lists/sc-users/msg61755.html
what combinations of versions of macOS, SC and Qt you would need?
I’m not sure if this post is clear (to me) in this regard.

And would it be jumping to conclusions, saying, that it’s probably Qt since the problems are just under macOS and not Windows or Linux?

**Comment by prko** [comment] 2018-08-13 12:53
Under Linux, I have only SC 3.6.6. Thus, I do not know if Linux release of SC 3.9.3 and 3.10-beta has the problem of displaying Help Document Browser.

Under Windows, I have SC 3.9.3 and SC3.10-beta built by Miguel Negrão (https://scsynth.org/t/request-for-testers-new-process-spawning-code-in-windows/152). They all work without the problem of Help Document Browser.

Under macOS, the problem occurs differently in each macOS version. Daily I can access three Apple computers. On one of them, El Capitan is installed, and I have an external storage installed High Sierra. On two of them, High Sierra is installed.
The problem occurs only under High Sierra, and launching SC3.10-beta in terminal returns long error messages mentioned above. Launching SC3.9.3 in terminal does not return error messages. Scott pointed out the Qt libraries is missing and Brian seems to need to know if the problem is reproducible.

I requested a test to help Brian and other developers.

Sorry, I am not a developer and cannot know what exactly the problem is just by reading the long error messages. I believe Scott, Brian and Nathan.

**Comment by scztt** [comment] 2018-08-13 19:08
> If this is reproducible it should be reported as a bug to the authors of macdeployqt of the qt project.

I'm reasonably confident this is a bug on our side (or, at least, can be fixed on our side). I believe I addressed this and it working at some point in my qt 5.9 work, but it very easily could have regressed, since the issue won't repro on any machine that already has qt installed (meaning, basically, any developer machine).

**Comment by brianlheim** [comment] 2018-08-16 02:38
Thanks for the diligent reporting @prko !

**Closed** 2018-08-16 02:38 UTC
Labels: bug
