### ISSUE TITLE
Windows: no output on the post window

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3302] opened 2017-11-19 21:53 UTC
This is on Windows 8.1 (Enterprise, 64 bits), supercollider 3.9-beta.

SuperCollider starts up, saying:

```
compiling class library...
	Found 695 primitives.
	Compiling directory 'C:\Program Files\SuperCollider-3.9.0-beta1\SCClassLibrary'
WARNING: Could not open directory: 'C:\Users\snip\AppData\Roaming\SuperCollider\Extensions'
	To resolve this, either create the directory or remove it from your compilation paths.

	Compiling directory 'C:\Users\snip\AppData\Local\SuperCollider\Extensions'
	numentries = 811257 / 11586330 = 0.07
	5205 method selectors, 2226 classes
	method table size 12390808 bytes, big table size 92690640
	Number of Symbols 11764
	Byte Code Size 359638
	compiled 321 files in 0.85 seconds

Info: 2 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.03 seconds
```

But then running any line of code doesn't post to the post window, as it seems.

If anyone has some clues of what to try next, we'll be very grateful!

**Comment by brianlheim** [comment] 2017-11-20 04:07
is this the beta binary that's up on the releases page? it looks like the server is also being booted at the same time?

**Comment by telephon** [comment] 2017-11-20 06:31
yes, I think it's the beta binary (I don't have direct access).

**Comment by telephon** [comment] 2017-11-20 06:32
>it looks like the server is also being booted at the same time?

well, maybe my colleague has manually booted the server, so that isn't guaranteed.

**Comment by brianlheim** [comment] 2017-11-20 06:34
>> it looks like the server is also being booted at the same time?

> well, maybe my colleague has manually booted the server, so that isn't guaranteed.

oops, I guess those messages just happen every time you start up SuperCollider. never mind!

**Comment by brianlheim** [comment] 2017-11-20 06:40
I can't recreate this on Windows 10 (Education Edition). Without more information there is nothing I can do to help, sorry. More testing from the user as well as environment info would help.

**Comment by brianlheim** [comment] 2017-12-08 15:22
Closing as unreproducible

**Closed by brianlheim** 2017-12-08 15:22 UTC
Labels: os: Windows, waiting for information

**Comment by cmaughan** [comment] 2019-05-17 10:59
I have this same problem; the bleeding edge build or the last one on Windows 64 bit.  I get nothing in the post window, and when running sclang I never get to a prompt.
