### ISSUE TITLE
Multiple-line code blocks in the help documents evaluate twice

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4035] opened 2018-08-31 01:05 UTC
Environment
-----------

* Your SuperCollider version: 3.10 beta
* Your operating system and version: Ubuntu Studio

Steps to reproduce (for bugs)
-----------------------------

1. In a help document, add the following:
   
   ```
   p = Pbind().play;
   ```

2. Evaluate it and observe that the number of synths is 1.

3. Stop playing (`p.stop` or ctrl-.). Number of synths should go back to 0.

4. Now add:
   
   ```
   (
   p =
   Pbind()
   .play;
   )
   ```

5. Evaluate this block (it doesn't matter if you select the lines manually, or double-click next to the open-paren) and observe that the number of synths is 2.

6. Also, at this point `p.stop` does not stop the sound (leaves one stray EventStreamPlayer running).

Expected Behavior
-----------------

If you hit Ctrl-Return once, the code block should evaluate only once.

Current Behavior
----------------

Multiple evaluations.

EDIT: I realized I had updated my 3.10 branch while the IDE was running. I had seen weird things in help before when doing this, so I just rebuilt SC and relaunched. Same issue. So this seems to be a real problem.

**Comment by brianlheim** [comment] 2018-08-31 02:39
Dupe of #3924.

**Closed by brianlheim** 2018-08-31 02:39 UTC
Labels: bug, comp: SCDoc, env: SCIDE
