### ISSUE TITLE
Sporadic corruption of Lists

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#243] opened 2012-05-06 05:49 UTC
[Issue migrated from SourceForge | ID: 3481616 | Submitted by 'howthebodyworks']
[http://sourceforge.net/support/tracker.php?aid=3481616]

I believe that I can, with reasonable reliability, cause List instances to become corrupted with random crud that has demonstrably not come from within my code. I submit this for your consideration as a bug, though i would appreciate tips on how to reduce my test case a little further so that it may be a more precisely defined bug, or even advice about whether it is reproducible on other machines (I have but one to hand), or whether I've just been hitting the schnapps a little hard. 

Accordingly I am posting it on sc-users before posting it to the bug tracker, as per the bug tracker request. 

The catch is that I found this bug with a complex codebase, and while I've deleted 80% of my SC code to find a minimal test case I've been having trouble getting the last 20% cut down to a truly minimal reproduction. Further cuts result in large breakages and fixing them causes the original problem to go away. bisection is tricky since the behaviour is sporadic. I'm sure it can be done better, I'd just appreciate tips before I burn any more time on it than the weekend I already did. Bug seems to appear best when I rapidly update a List many thousands of times from within a convoluted nest of dynamically loaded Functions and Routines. 

(FYI, it is a genetic algorithm class I'm developing. Why I am developing yet _another_ GA on top of the 3+ already out there is a question I will answer some other time ;) ) 

OS 10.6.8 
Supercollider 3.5 (beta2) 

Long instructions to reproduce the bug and discussion of the output follows. If this isn't your bag and you haven't stopped reading, now would be a good time. 

To reproduce: 
check out my code (on github at https://github.com/howthebodyworks/pattern_machine) and switch to the "minimal_list_corruption_case_list" branch 

---
```
git clone git://github.com/howthebodyworks/pattern_machine.git 
git checkout minimal_list_corruption_case_list 
```

Link it into your Extensions folder and recompile sclang. 
Now, the following commands will cause the horrible behaviour to appear. (or, if liked, you can use phenosynth_list_problems_reduction.scd

The PSIsland instance contains a list of PSPhenotype instances stored in a public instance variable called "population". If we run it enough times, it eventually acquires a random non-PSPhenotype member, an exception is thrown and the alien element can be inspected. Now, we set up a PSIsland instance with some default GA simulation parameters and observe this behaviour. The following terminal log represents a typical case. Notes about how it varies from run to run are included after this first example. 

In what follows user input denoted >>>, commentary by // and naked lines are sclang post window output. Without further ado: 

```

//instantiate a GA simulation: 

> > > ~island = PSIsland.new; 
> > > a PSIsland 

// Now, fire the simulation 
// you might need to repeat these first two steps a few times to get the simulation to 
// throw the required error, but upping the maximum iteration count can be tedious on my 
// ancient hardware ;) 

> > > ~island.play; 
> > > a PSIsland 

[ iterations, 1, 0.47415266076724 ] 
[ iterations, 2, 0.48084045490095 ] 
[ iterations, 3, 0.52157389364751 ] 
[ iterations, 4, 0.54453962842518 ] 
//skip a few dull progress messages.... 
//... 
[ iterations, 614, 0.8414587343304 ] 
[ iterations, 615, 0.89881876806221 ] 
ERROR: Message 'chromosome' not understood. 
RECEIVER: 
Instance of Function {    (0x1216ade08, gc=34, fmt=00, flg=00, set=02) 
  instance variables [2] 
    def : instance of FunctionDef in Method SequenceableCollection:join 
    context : Frame (0x11989f988) of SequenceableCollection:join 
} 
ARGS: 
PATH: /Users/dan/src/sc/pattern_machine/phenosynth.scd 
CALL STACK: 
        DoesNotUnderstandError:reportError   0x12166f358 
                arg this = <instance of DoesNotUnderstandError> 
//... 
        Object:doesNotUnderstand   0x11d9391c8 
                arg this = <instance of Function> 
                arg selector = 'chromosome' 
                arg args = [_0] 
        < closed FunctionDef >   0x11d93c298 
                arg params = <instance of Event> 
                arg phenotype = <instance of Function> 
        < FunctionDef in Method PSIsland:evaluate >   0x1199ac7f8 
                arg phenotype = <instance of Function> 
        ArrayedCollection:do   0x11d93b9a8 
                arg this = [_100] 
                arg function = <instance of Function> 
                var i = 36 
        List:do   0x11d935a18 
                arg this = <instance of List> 
                arg function = <instance of Function> 
        PSIsland:evaluate   0x11d92c598 
                arg this = <instance of PSIsland> 
        PSIsland:tend   0x1215b7838 
                arg this = <instance of PSIsland> 
                var toCull = nil 
                var toBreed = nil 
                var beforeFitness = nil 
                var afterFitness = nil 
        < FunctionDef in Method PSIsland:iterator >  (no arguments or variables) 
        Object:while   0x120e42e58 
                arg this = <instance of Function> 
                arg body = <instance of Function> 
        < FunctionDef in Method PSIsland:iterator >  (no arguments or variables) 
        Routine:prStart   0x1212a6d08 
                arg this = <instance of Routine> 
                arg inval = nil 
For advice: [http://supercollider.sf.net/wiki/index.php/DoesNotUnderstandError#chromosome] 

// So, there is something that is not a PSPhenotype in the ~island.population List 
// instance. Let's find it. 

> > > ~wIdx=~island.population.detectIndex({|i, idx| i.class!=PSPhenotype;}); 

36 

> > > ~w=~island.population[~wIdx]; 

a Function 

> > > ~w.asCompileString; 

{ "open Function" } 

> > > ~w.def 
> > > a FunctionDef in Method Scheduler:init 
> > > 
> > > ~w.def.context.context; 
## Method Scheduler:init 
## OK, so on this run we found a Function somehow acquired from the Scheduler.init method. In general, though, the foreign list crud can be anything. Here are some examples from other runs. 

//... 
[ iterations, 23, 0.73600867235716 ] 
ERROR: Message 'fitness' not understood. 
RECEIVER: 
Instance of Function {    (0x1237cd578, gc=60, fmt=00, flg=00, set=02) 
  instance variables [2] 
    def : instance of FunctionDef in Method Meta_Collection:newFrom 
    context : Frame (0x121da28e8) of Meta_Collection:newFrom 
} 
ARGS: 
PATH: /Users/dan/src/sc/pattern_machine/phenosynth.scd 
CALL STACK: 
//... 
        Object:doesNotUnderstand   0x120f9c508 
                arg this = <instance of Function> 
                arg selector = 'fitness' 
                arg args = [_0] 
        < FunctionDef in Method Collection:collectAs >   0x120e44478 
                arg elem = <instance of Function> 
                arg i = 13 
        ArrayedCollection:do   0x1255f1b58 
                arg this = [_100] 
                arg function = <instance of Function> 
                var i = 13 
        List:do   0x128682c68 
                arg this = <instance of List> 
                arg function = <instance of Function> 
        Collection:collectAs   0x129571a08 
                arg this = <instance of List> 
                arg function = <instance of Function> 
                arg class = <instance of Meta_Array> 
                var res = [*13] 
        < FunctionDef in Method PSIsland:iterator >  (no arguments or variables) 
        Object:while   0x128e4ae68 
                arg this = <instance of Function> 
                arg body = <instance of Function> 
        < FunctionDef in Method PSIsland:iterator >  (no arguments or variables) 
        Routine:prStart   0x12561d708 
                arg this = <instance of Routine> 
                arg inval = nil 
For advice: [http://supercollider.sf.net/wiki/index.php/DoesNotUnderstandError#fitness] 

> > > ~wIdx=~island.population.detectIndex({|i, idx| i.class!=PSPhenotype;}); 

13 

> > > ~w=~island.population[~wIdx]; 

a Function 

> > > ~w.asCompileString; 

{ "open Function" } 

> > > ~w.def.context 
> > > Method Meta_Collection:newFrom 
> > > ~w.def.argumentString 

item 

---

//... 
[ iterations, 800, 0.90388895862069 ] 
ERROR: Message 'chromosome' not understood. 
RECEIVER: 
Instance of String {    (0x125bfc0c8, gc=30, fmt=07, flg=00, set=02) 
  indexed slots [20] 
      0 : ' 
      1 : c 
      2 : h 
      3 : r 
      4 : o 
      5 : m 
      6 : o 
      7 : s 
      8 : o 
      9 : m 
     10 : e 
     11 : M 
     12 : i 
     13 : n 
     14 : L 
     15 : e 
     16 : n 
     17 : g 
     18 : t 
     19 : h 
} 
ARGS: 
PATH: /Users/dan/src/sc/pattern_machine/phenosynth.scd 
CALL STACK: 
//... 
        Object:doesNotUnderstand   0x1197a8c18 
                arg this = "'chromosomeMinLength" 
                arg selector = 'chromosome' 
                arg args = [_0] 
        < closed FunctionDef >   0x121195f18 
                arg params = <instance of Event> 
                arg phenotype = "'chromosomeMinLength" 
        < FunctionDef in Method PSIsland:evaluate >   0x128f45678 
                arg phenotype = "'chromosomeMinLength" 
        ArrayedCollection:do   0x125635a58 
                arg this = [_100] 
                arg function = <instance of Function> 
                var i = 9 
        List:do   0x125903238 
                arg this = <instance of List> 
                arg function = <instance of Function> 
        PSIsland:evaluate   0x128f13b38 
                arg this = <instance of PSIsland> 
        PSIsland:tend   0x124ec35e8 
                arg this = <instance of PSIsland> 
                var toCull = nil 
                var toBreed = nil 
                var beforeFitness = nil 
                var afterFitness = nil 
        < FunctionDef in Method PSIsland:iterator >  (no arguments or variables) 
        Object:while   0x125874f48 
                arg this = <instance of Function> 
                arg body = <instance of Function> 
        < FunctionDef in Method PSIsland:iterator >  (no arguments or variables) 
        Routine:prStart   0x1212e9838 
                arg this = <instance of Routine> 
                arg inval = nil 
For advice: [http://supercollider.sf.net/wiki/index.php/DoesNotUnderstandError#chromosome] 
~wIdx=~island.population.detectIndex({|i, idx| i.class!=PSPhenotype;}); 

9 
~w=~island.population[~wIdx]; 

'chromosomeMinLength 

~w.class; 

String 

~w.asCompileString; 

```

## "'chromosomeMinLength" 

Note, for the last example, that I do not have a String containing "'chromosomeMinLength" anywhere in my code, although I do use a Symbol \chromosomeMinLength as an Event key. 

Other crud that has appeared in my list includes a String, "_*sync_s", and a single element Array, [1]. 

Finally, you can eliminate this odd behaviour by switching from a List to a LinkedList. To see this, check out the branch minimal_list_corruption_case_linkedlist (i.e. git checkout minimal_list_corruption_case_list ) and recompile sclang. 

If you do this, the simulation runs fine but never explodes. 

Enough from me. All hints on pinning this bug down gratefully accepted. 

Cheers, 
Dan

**Comment by telephon** [comment] 2017-01-15 09:21
feel free to reopen

**Comment by telephon** [comment] 2017-01-15 09:23
@brianlheim I just saw this was assigned to you, so yes, feel free to reopen.

**Comment by brianlheim** [comment] 2017-01-15 14:44
@telephon thanks. I am planning to retest and will reopen if I find anything!

**Comment by vivid-synth** [comment] 2017-01-18 00:36
Hmm, are we sure we want to close this without making sure it's not an issue (seeing as it could potentially be an important bug)? If i were to see a closed issue with the "retest" tag I'd assume it had been retested and found not to be an issue.

**Comment by brianlheim** [comment] 2017-01-18 01:00
Repoening until I have time to retest.

**Comment by telephon** [comment] 2017-01-18 21:12
@vivid-synth hm, what would be the best way to proceed in similar cases? If we want to close issues we have no chance to work on or which we personally cannot reproduce, we should probably have a way to keep them on the list. Should they get added to the project page?

**Comment by brianlheim** [comment] 2017-01-18 21:49
I think in this case I just shouldn't have closed the issue before there was a chance to retest. I self-assigned it so I could come back later, but in all likelihood I could have easily forgotten!

This would be a good topic to cover this weekend.

**Comment by LFSaw** [comment] 2017-07-30 11:58
any news? any more compact description of the issue (puh, that text up there is really long... :) )

**Comment by JordanHendersonMusic** [comment] 2024-04-17 17:59
Closing because the git branch required to reproduce no longer exists.

**Closed** 2024-04-19 17:08 UTC
Labels: bug, comp: sclang, retest
