### ISSUE TITLE
Buffer.cueSoundFile error on files with more than one channel

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2474] opened 2016-11-04 16:34 UTC
Threads: [1](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Buffer-cueSoundFile-trouble-with-more-than-one-channel-td7611357.html), [2](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Strange-sporadic-libsndfile-DiskIn-problem-quot-Bad-format-field-in-SF-INFO-struct-quot-td7614418.html). It seems that all the people experiencing this issue are OS X users.

> I am having trouble with  Buffer.cueSoundFile when useing more than one channel
>
> b = Buffer.cueSoundFile(s, "/Users/xxxx/Documents/projects/xxxxx/soundFiles/test.aiff", 0,2);
>
> I get the  messages
>
> Buffer(10, 32768, 2, 44100, /Users/xxxx/Documents/projects/xxxxx/soundFiles/test.aiff)
> File '/Users/xxxx/Documents/projects/xxxxx/soundFiles/test.aiff' could not be opened: Error. Bad format field in SF_INFO struct when openning a RAW file for read.

This error message comes from libsndfile, so this may be an upstream bug.

**Comment by telephon** [comment] 2016-11-04 20:32
Here is a test:

`Buffer.cueSoundFile(s, Platform.resourceDir +/+ "sounds/SinedPink.aiff", 0, 2);`

Works fine on OS X 10.11.6.

**Comment by snappizz** [comment] 2016-11-04 21:31
@Sciss Can you still reproduce this issue?

**Comment by Sciss** [comment] 2016-11-05 10:59
Did I report that? Well, I left OS X for good :-) I think the multi-channel issue was in SC 3.6.6. I'm on 3.7.2 now and have not seen a similar problem.

**Comment by telephon** [comment] 2016-11-05 17:39
thanks, sciss, feel free to reopen if it comes back.

**Comment by snappizz** [comment] 2016-11-05 17:44
Hang on. It's not just Hanns, there are still other people who are reporting this (see the end of thread 2).

**Comment by telephon** [comment] 2016-11-05 21:28
sorry, so let's keep this open. Thanks for the notice.

**Comment by telephon** [comment] 2016-12-02 14:43
(the above reference is wrong, but couldn't remove it here.)

**Comment by bagong** [comment] 2017-03-02 21:55
I feel a bit of responsibility here as I messed with libsndfile for 3.7.1, but I don't see what I could do as long as none of the reports are reproducible. Also the SC versions referenced are different... I'd rather close this until the day somebody turns up who invests enough into an error-report to allow to analyze/reproduce it.

**Comment by bagong** [comment] 2017-03-03 22:56
So more and more point to it being an issue with soundfile headers. "Bad format field in SF_INFO struct when openning a RAW file for read" is not triggered by SC. So let's close until we get more info.

**Comment by snappizz** [comment] 2017-03-04 08:19
Have we reported anything upstream yet?

**Comment by bagong** [comment] 2017-03-04 09:35
Do you think that would help? @erikd would have the same problem as we: it's likely the soundfiles, and whether libsndfile is erring here, producing unnecessarily generic error-messages - or - what is the most likely - the soundfile headers are corrupt in a way that's between hard and impossible to analyze, could only be ascertained with a precise analysis of the sound-file headers and it's interaction with libsndfile.

At the very least we need a reproducer, the sound file, and then we need the person that is qualified to do this and thinks it's worth it... You could always say: go get a clean soundfile. Libsndfile is used on millions of computers, that's a pretty good test base...

**Comment by erikd** [comment] 2017-03-04 09:58
What does the `sndfile-info` program say about the file in question?

**Comment by bagong** [comment] 2017-03-04 10:29
Thanks, @erikd , for chiming in, and sorry for stirring you up with something that is not ready to become "a case"! I just did it because I know you care for SC. We'll check as soon as we *have* a soundfile. So far we only have error reports ;)

**Comment by Sciss** [comment] 2017-03-13 22:19
I'm reopening the issue, because I can confirm it's definitely a SuperCollider bug. I'm encountering it again now that I'm using 3.8.0 (used 3.7.x before).

I'm seeing these strange messages:

> File '/data/projects/Imperfect/audio_work/impulse/sweep_input.aif' could not be opened: Error. Bad format field in SF_INFO struct when opening a RAW file for read.

This seems to happen with AIFF mono files so far. I built 3.8.0 from source (Debian). The global libsndfile tools seem to be happy with these files:

```
$ sndfile-info /data/projects/Imperfect/audio_work/impulse/sweep_input.aif
========================================
File : /data/projects/Imperfect/audio_work/impulse/sweep_input.aif
Length : 6879698
FORM : 6879690
 AIFC
 FVER : 4
 COMM : 36
  Sample Rate : 44100
  Frames      : 1719888
  Channels    : 1
  Sample Size : 16 (should be 32)
  Encoding    : fl32 => 32-bit float
 INST : 20
  Base Note : 69
  Detune    : 0
  Low  Note : 0
  High Note : 127
  Low  Vel. : 0
  High Vel. : 127
  Gain (dB) : 0
  Sustain
   mode  : 800 => none
   begin : 0
   end   : 0
  Release
   mode  : 800 => none
   begin : 0
   end   : 0
 MARK : 26
  Count : 2
   Mark ID  : 1
   Position : 617400
   Name     : Mark
   Mark ID  : 2
   Position : 1675800
   Name     : Mark
 SSND : 6879560
  Offset     : 0
  Block Size : 0

----------------------------------------
Sample Rate : 44100
Frames      : 1719888
Channels    : 1
Format      : 0x00020006
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:39.000
Signal Max  : 0.501187 (-6.00 dB)
```

I'm attaching a slightly smaller file that has the same problem. The totally weird thing is, if I play a stereo file, and then again the mono file, scsynth is totally happy again with the mono file. So seems some weird libsndfile initialisation problem perhaps?
[ForumVerb-LGain.zip](https://github.com/supercollider/supercollider/files/839776/ForumVerb-LGain.zip)

**Comment by bagong** [comment] 2017-03-13 22:30
Yes, there is definitely something wrong, and it's not a libsndfile mistake. SC does something bad that let's libsndfile fire, I've seen it with 4-channel files that would play just fine with SC in other contexts, and also the weird thing that you can repair the problem by playing stereo file. Could you post a brief code example that triggers the error? Would this contain a <buffer>.free?

**Comment by Sciss** [comment] 2017-03-13 22:33
This for me reproduces the error with the attached file:

```supercollider
s.boot;
p = "/data/projects/Imperfect/audio_work/ForumVerb-L.aif"; // change to any (?) mono file here
s.sendBundle(nil, [ "/b_alloc", 0, 65536, 1 ], [ "/b_read", 0, p, 0, -1, 0, true ]);
```

SC info: 
- SuperCollider 3.8.0
- Built from branch '3.8.0' [0947eddc0]

**Comment by snappizz** [comment] 2017-03-13 22:35
I can't reproduce it. The error does *not* occur with `Buffer.read`, right? In that case we might be able to play a game of spot the difference in the source code of `/b_read` vs `/b_allocRead`.

**Comment by Sciss** [comment] 2017-03-13 22:39
`Buffer.read` does not do the same thing semantically, and you are right, `Buffer.read` doesn't produce the error. But `Buffer.cueSoundFile(s, p, 0, 1, 65536)` does (which is the equivalent). The differences being:

- here we read only a part of a longer file
- here we leave the file open for streaming via `DiskIn`

I suspect the second bit is responsible.

**Comment by snappizz** [comment] 2017-03-13 22:43
The bigger difference is that `Buffer.read` emits `/b_allocRead` and `Buffer.cueSoundFile` emits `/b_read`. So let's look at the source.

[Exhibit A](https://github.com/supercollider/supercollider/blob/master/server/scsynth/SC_SequencedCommand.cpp#L626), [Exhibit B](https://github.com/supercollider/supercollider/blob/master/server/scsynth/SC_SequencedCommand.cpp#L791). A line I'm seeing in BufAllocReadCmd::Stage2 that appears to be missing in BufReadCmd::Stage2 is this one:

    memset(&fileinfo, 0, sizeof(fileinfo));

Looks like it clears the SF_INFO struct, which is exactly what libsndfile is complaining about. Can you try adding that after line 633 in Exhibit A?

**Comment by Sciss** [comment] 2017-03-13 22:48
Great find. Stupid question, if I installed SuperCollider via `sudo make install`, do I just run `sudo make clean` before recompiling, or do I need to run something else?

**Comment by snappizz** [comment] 2017-03-13 22:50
In this case, since you're recompiling the scsynth executable you don't need to clean anything. However, if a file in the class library is moved or deleted, you will need to run `sudo make uninstall` to avoid conflicts.

**Comment by Sciss** [comment] 2017-03-13 22:57
Great. I can confirm the problem is gone after adding that `memset` line as you described!

**Comment by snappizz** [comment] 2017-03-13 23:01
I'm pretty pleased with myself for having solved this without any domain expertise! I'll open a PR.

I think the problem also affects `/b_readChannel`, which is missing that line as well (see `BufReadChannelCmd::Stage2`). `/b_allocReadChannel` is fine.

**Comment by bagong** [comment] 2017-03-13 23:02
Congratulations! :smile:

**Comment by snappizz** [comment] 2017-03-13 23:09
Aha, also see this from the [libsndfile docs on `sf_open`](http://www.mega-nerd.com/libsndfile/api.html#open):

> When opening a file for read, the format field [of the SF_INFO struct] should be set to zero before calling sf_open(). The only exception to this is the case of RAW files where the caller has to set the samplerate, channels and format fields to valid values. All other fields of the structure are filled in by the library. 

So passing uninitialized memory as the `sfinfo` is a bad idea. Good to know.

**Comment by brianlheim** [comment] 2017-03-13 23:14
:tada: :tada: :tada: all around

**Comment by snappizz** [comment] 2017-03-13 23:18
#2793

**Closed** 2017-03-14 03:38 UTC
Labels: bug, comp: scsynth, fix proposed
