### ISSUE TITLE
Qt GUI: WebView: .onLinkActivated doesn't fire

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2295] opened 2016-08-19 17:45 UTC
Open the following and click on a link. There should be a post, but there isn't:

```
WebView().front.url_("http://example.com/").onLinkActivated_{|view,url| [view,url].postln };
```

According to [reports on the mailing list](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/onLinkActivated-td7627286.html) this was working in 3.7.

**Comment by snappizz** [comment] 2017-01-15 01:57
LNX Studio depends on this, so this is important for 3.9.

**Comment by neilcosgrove** [comment] 2017-02-18 11:48
Will anyone get a chance to look at this? It would mean for me to get this fixed. Thanks.

**Comment by gusano** [comment] 2017-03-23 05:23
> Will anyone get a chance to look at this? It would mean for me to get this fixed. Thanks.

@neilcosgrove Meanwhile you could port LNX Studio to linux :)
(more seriously, let me know if you need help with that)

**Comment by neilcosgrove** [comment] 2017-03-23 16:55
Have a look here... https://github.com/neilcosgrove/LNX_Studio/blob/xplat/README_linux.md


Its a working version on Linux. The differences between Mac and Linux version are less and less since moving to Qt.

Help with porting to linux or fixing WebView: .onLinkActivated ? [😊]
________________________________

**Comment by gusano** [comment] 2017-03-23 20:45
@neilcosgrove Ah now I see you did some work for linux already! I was only looking at master :)

Re-the present issue, I had a quick look but it seems that the problem comes from Qt (c++) side so it's beyond my knowledge, sorry.

**Comment by snappizz** [comment] 2017-03-25 22:00
Related to #2296?

**Comment by neilcosgrove** [comment] 2017-04-02 12:33
I think most of the methods for WebView don't work...
onLoadFinished
onLoadFailed
onLinkActivated
onReload
evaluateJavaScript
refresh

**Comment by brianlheim** [comment] 2017-04-02 13:04
Interesting... onReload has worked for me. Can you post and describe your reproducer? Thanks.

**Comment by neilcosgrove** [comment] 2017-04-02 13:44
:) sorry my bad, i was using a Proxy to hold the WebView and it wasn't passing these on. They do work.

but onLinkActivated still doesn't.

**Comment by patrickdupuis** [comment] 2017-06-12 05:30
I've looked at this issue a bit. `onLinkActivated` calls `this.setProperty(\linkDelegationPolicy, value)` which, as far as I can tell, does not work. The property stays unchanged. Calling `.getProperty(\linkDelegationPolicy)` always returns `nil`. This is doubly strange because you would expect that property to have a default value of `0` rather than `nil`. 

I wonder if anyone can figure out how to change this property. Might be the solution we need.

**Comment by snappizz** [comment] 2017-06-16 06:36
@patrickdupuis i think you're on to something... there's something up with `WebView::[set]LinkDelegationPolicy`

**Comment by patrickdupuis** [comment] 2017-06-17 15:32
The `linkDelegationPolicy` belongs to QWebPage and `linkClicked` is the signal that is emitted (by QWebView?) whenever the user clicks on a link and the page's `linkDelegationPolicy` property is set to delegate the link handling. This is from the Qt 5.5 documentation. See below.
https://doc.qt.io/archives/qt-5.5/qwebview.html#linkClicked
https://doc.qt.io/archives/qt-5.5/qwebpage.html#linkDelegationPolicy-prop

**Comment by snappizz** [comment] 2017-06-27 18:19
@scztt i know you're probably really busy but do you have any idea why calling `setProperty(\linkDelegationPolicy, true)` on `QWebView` doesn't seem to have any effect (`getProperty(\linkDelegationPolicy)` always returns nil)?

**Closed** 2017-06-27 20:30 UTC
Labels: bug, comp: Qt GUI
