### ISSUE TITLE
Collection.includes does not match strings

### ISSUE THREAD

**Issue by KoltesDigital** [supercollider/supercollider#4572] opened 2019-09-11 18:34 UTC
## Environment

* SuperCollider version: 3.10.3
* Operating system: Win 10 64b

## Steps to reproduce

```supercollider
[42].includes(42) //-> true
["a"].includes("a") //-> false
["a"].occurrencesOf("a") //-> 1
```

## Expected vs. actual behavior

I'd expect `["a"].includes("a")` to yield `true`.

**Comment by redFrik** [comment] 2019-09-11 18:52
```supercollider
["a"].includesEqual("a")  //->true
```

**Comment by KoltesDigital** [comment] 2019-09-11 19:27
Nice, thanks! So maybe the request is just about documenting this function.

Any idea why it's so?

**Comment by redFrik** [comment] 2019-09-11 19:57
yes.  it's not a bug but an un(der)-documented area of how the supercollider language works.  there's a bit about it in Object helpfile - "Equality and Identity" but really not enough.  i'm surprised .includesEqual isn't documented.  we should add something.
the similar method .indexOf have at least a sentence in SequenceableCollection help.  we could adapt that.
```supercollider
[3, 4, "foo", "bar"].indexOf("foo");  //-> nil
[3, 4, "foo", "bar"].indexOfEqual("foo");  //-> 2
```

**Comment by KoltesDigital** [comment] 2019-09-11 20:11
Maybe there's a need for `Collection.occurencesOfEqual` and more generally for adopting a stricter segregation convention between identity and equality?

**Comment by brianlheim** [comment] 2019-09-12 00:48
> Maybe there's a need for Collection.occurencesOfEqual

`occurrencesOf` already tests for equality (at least, that's what I understand from the example code in your ticket); I think you mean "occurrencesOfIdentical", which could be written using `count` as `c.count(_ === y);`.

> adopting a stricter segregation convention between identity and equality?

The APIs of collection types in SC are not ideally consistent here, I agree. In my experience it's rare that you really want to test on identity, and having the smaller function names "indexOf" and "includes" check for identity just leads to lots of mistakes. In general, I think a good pattern would be to test on equality by default, and not even provide separate functions for identity testing. They can always be written quickly using other functions as building blocks when you really need them.

Since this issue turned out to be intended behavior, I'm closing it and opening a new one for clarifying the documentation for these methods with a focus on the distinction between equality and identity testing. It is not clear enough now.

**Closed by brianlheim** 2019-09-12 00:48 UTC
Labels: bug

**Comment by KoltesDigital** [comment] 2019-09-12 06:11
Yes, I was just pointing out that the base/default function (i.e. without any Equal or Identical suffix) is sometimes about equality and sometimes about identicality.

The behavior of C#/.Net seems to be the same as SC: by default `.Equals` checks for identicality on objects, and can be overridden for classes where it makes sense. `String` notably overrides that to check the contents and not the reference. Can't we imagine the same for SC? That is, convenience functions like `.includes` and `.occurrencesOf` should work with `==` which by default checks on identicality, but is overridden to check on value for primitive-like types like `Integer` and `String`, and so developers can override it for their own types if they want to, and if we really need identity checks with such types, we can always rely on predicate-based functions like `.any` or `.count` in order to compare with `===`. I can't tell for cycle releases, breaking changes, and all that stuff.
