### ISSUE TITLE
ERROR: Message 'prSetEdited' not understood.

### ISSUE THREAD

**Issue by meiry** [supercollider/supercollider#6056] opened 2023-07-17 04:29 UTC
## Environment

SuperCollider 3.13.0
Built from tag 'Version-3.13.0' [3188503]
window 10  
Qt version 5.15.2.

after installnig when starting to typie in the editor gettting the error :
i typed the integer: 4 

```
*** Welcome to SuperCollider 3.13.0. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1367 documents in 0.95 seconds
WARNING: Attempted to modify missing Text Mirror for Document {ea24edf4-ac3b-4e49-8700-62fddf4daa82}
ERROR: Message 'prSetEdited' not understood.
RECEIVER:
   nil
ARGS:
   Integer 1
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'prSetEdited'
		arg args = [*1]
	Process:interpretCmdLine
		arg this = <instance of Main>
^^ ERROR: Message 'prSetEdited' not understood.
RECEIVER: nil


```

**Comment by JordanHendersonMusic** [comment] 2024-05-05 14:02
Closing because this is a duplicate of #4812

**Closed by JordanHendersonMusic** 2024-05-05 14:02 UTC
Labels: bug
