### ISSUE TITLE
3.9dev can't load Plugins OSX sierra

### ISSUE THREAD

**Issue by unculcated** [supercollider/supercollider#3250] opened 2017-10-23 02:32 UTC
I get this on all the plugins in the post window;

ERROR: API version mismatch: /Library/Application Support/SuperCollider/Extensions/SC3plugins/SCMIRUGens/OnsetStatistics.scx
    This plugin is not compatible with SuperCollider >=3.9.0
    The plugin has not been loaded; please find or compile a newer version.
    Releases of sc3-plugins can be downloaded from https://github.com/supercollider/sc3-plugins/releases
    (Plugin's API version: 2. Expected: 3)

**Comment by brianlheim** [comment] 2017-10-23 03:45
Hi @unculcated - have you tried doing what the message says? You will need to compile a new version of sc3-plugins.

**Comment by unculcated** [comment] 2017-10-23 15:03
I can't compile them. Ive compiled tons of programs . The instructions are awful

Im using sierra

**Comment by unculcated** [comment] 2017-10-23 16:45
I don't think I have command line tools installed. I tried to install them.  I have Xcode, but cmake gives an error..   
-bash: cmake: command not found

gcc is there. Im used to linux, not Xcode.  I don't know where to start. 
homebrew is installed maybe that's an issue. I dont know.

**Comment by miguel-negrao** [comment] 2017-10-23 16:55
You can't compile it without having all the development tools installed. Please follow the section on installing the build tools from the README for building SuperCollider in OSX, in the SuperCollider repository. As this doesn't seem to be a bug I will close the issue for now, and recommend that you continue the discussion in the user mailing list. If at a later point you still think there is an issue here, feel free to reopen.

**Comment by unculcated** [comment] 2017-10-23 19:06
ok, i did this (installed everything from the readme you mentioned)
cd to sc3-plugins
mkdir build && cd build
cmake -DSC_PATH=/Users/ss/sc3-plugins/source ..

[CMakeOutput.log](https://github.com/supercollider/supercollider/files/1408473/CMakeOutput.log)

**Comment by unculcated** [comment] 2017-10-23 20:14
terminal read out;....


Franks-MBP:build ss$ cmake -DSC_PATH=/Users/ss/sc3-plugins/source ..
-- The C compiler identification is AppleClang 9.0.0.9000038
-- The CXX compiler identification is AppleClang 9.0.0.9000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using SC source located at /Users/ss/sc3-plugins/source
CMake Error at CMakeLists.txt:34 (include):
  include could not find load file:

    /Users/ss/sc3-plugins/source/SCVersion.txt


-- Building plugins for SuperCollider version: .
-- Performing Test HAS_SSE
-- Performing Test HAS_SSE - Success
-- Performing Test HAS_CXX_SSE
-- Performing Test HAS_CXX_SSE - Success
-- Performing Test HAS_SSE2
-- Performing Test HAS_SSE2 - Success
-- Performing Test HAS_CXX_SSE2
-- Performing Test HAS_CXX_SSE2 - Success
-- Performing Test HAS_FPMATH_SSE
-- Performing Test HAS_FPMATH_SSE - Success
-- Performing Test HAS_CXX_FPMATH_SSE
-- Performing Test HAS_CXX_FPMATH_SSE - Success
-- local_sources: 
CMake Warning (dev) at source/StkInst/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring incomplete, errors occurred!

**Comment by unculcated** [comment] 2017-10-23 20:27
Sure im a bit of a novice but a little guidance for the other idiots that come along might be helpful

**Comment by jamshark70** [comment] 2017-10-23 23:03
> -- Using SC source located at /Users/ss/sc3-plugins/source

Here's the problem. "SC source" means the source code package for *SuperCollider*, not for sc3-plugins, but listed here is the path for the plugin sources.

sc3-plugins depends on header files defined for the SC server. That's a reasonable dependency. Copying the headers into the plugins and syncing them would be a nightmare, so we don't do that. You need the SC sources too.

**Comment by jamshark70** [comment] 2017-10-23 23:08
PS Your issue is getting attention here, there was no need to open a duplicate issue. I'll reopen this one temporarily. (Though, do note that this is a bug tracker, not a general support community, and this is really a support question -- admittedly the lines blur at times, but more often lately, users' thought process seems to be "I had a problem, so it must be a bug" which dilutes the bug tracker for dev purposes. That's the reason why this issue was closed.)

**Comment by unculcated** [comment] 2017-10-24 00:53
The bug is the crappy documentation. 

There needs to be a plain English explanation;
Most important!
You have to build supercollider from source with the git command in terminal!
You have to paste a path to the source folder that is Supercollder ..ie, sc3source
misleading because you might think it's the Plugins source folder.
cmake is the beginning of the command. Not the path to the source folder then cmake,.. etc
Just plain talk.

Im fine now, but it took some searching on the forum and a few mistakes

**Comment by jamshark70** [comment] 2017-10-24 01:44
No particular objection to improving that. But I would recommend opening a ticket for that in the sc3-plugins project on github -- the sc3-plugins REAMDE.md is not hosted in the supercollider/supercollider repository. It's in https://github.com/supercollider/sc3-plugins.

IMO it's a valid issue, but impossible to fix in this particular repository.

> cmake is the beginning of the command. Not the path to the source folder then cmake

On this point, it looks like the readme uses the convention that `$` and everything before `$` is the terminal prompt, and what follows is the command. You're correct that the text doesn't explain the convention. (The path in the prompt is included to clarify that the `cmake` commands should be run inside of a `build/` directory that you create. That detail is often overlooked.)

Agreed, however, that it's inconvenient to copy/paste commands when the code block includes non-code elements.

> You have to build supercollider from source with the git command in terminal!

Other developers: Is this true? I thought it might be sufficient to have the SC source directory + submodules, but not necessarily to compile SC.

We have had issues with .zip / .tar.gz downloads of the SC sources, which don't include submodules.

> You have to paste a path to the source folder that is Supercollder ..ie, sc3source

Agreed that this could be clearer. It's obvious to those of us who have been around forever, but documentation needs to help newcomers.

**Comment by patrickdupuis** [comment] 2017-10-24 03:26
-> You have to build supercollider from source with the git command in terminal!

-> Other developers: Is this true? I thought it might be sufficient to  have the SC source directory + submodules, but not necessarily to compile SC.


You are right James. You don't need to build SC from source in order to build the plugins from source. You can simply point cmake to the SC source files. If you have SC 3.8 installed from a packgage, you should ideally build the plugins against the SC 3.8 source (obtained from github, I guess).


We can definitely improve the documentation with regard to building sc3-plugins! Thanks for bringing this up @unculcated.

**Comment by brianlheim** [comment] 2017-10-24 03:42
@unculcated i'm sorry it was difficult for you to understand the instructions, but a little courtesy would be appreciated.

> Other developers: Is this true?

No. there's a sentence early on that says:

> To compile from source (see below), either download a tarball or clone this repository:

Which, to someone who's not reading carefully, sounds like the command below (`git clone`) builds the source. I've made this mistake several times actually.

closing because this is no longer an issue on this repository.

**Closed by brianlheim** 2017-10-24 03:42 UTC
Labels: comp: server plugins

**Comment by brianlheim** [comment] 2017-10-24 04:03
https://github.com/supercollider/sc3-plugins/pull/165

**Comment by miguel-negrao** [comment] 2017-10-24 08:33
@unculcated
> The bug is the crappy documentation.
...
> Im fine now, but it took some searching on the forum and a few mistakes

Would you be willing to contribute specific suggestions for change, possibly opening a pull request with changes to the documentation ? Complaining (and with some lack of politeness) is not very useful for solving the issue.

**Comment by unculcated** [comment] 2017-10-24 18:30
Don't take it personal! Im afraid supercollider will become an undocumented mess if it's maintained by long time users who just assume everything is understood. I left a comment up there on my concerns. Just assume someone knows nothing. The build instructions for supercollider itself are very good in that regard. Best wishes. No offense.

**Comment by miguel-negrao** [comment] 2017-10-24 19:34
I'm not taking it personal, but "The bug is the crappy documentation." might not be the best tone to use here, it is confrontational. How would you like it if I responded by saying that the problem is your "crappy" bug report,which doesn't give any details about what exactly went wrong ? It's just not helpful language to use in this context. 
Regarding the documentation, sure, probably it needs to be improved. The correct procedure would have been to open a ticket in the right github repo (sc3-plugins), making a specific suggestions about what should be improved.
