### ISSUE TITLE
Detached ghost window

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#1442] opened 2015-04-30 08:44 UTC
People says that in ubuntu 14.04 with qt5.4, when you are coding late at night, if you open the IDE, you detach the help window, you close the detached help window, you close the IDE and open it again, a ghost window will appear...

A blurry image that proves: https://drive.google.com/file/d/0BzChHosTTZFQTjVzYnJDU2ZUZkE/view?usp=sharing

**Comment by bagong** [comment] 2015-04-30 09:13
Spooky, but real! It's not specific to Linux, maybe not even to night time :)

**Comment by bagong** [comment] 2015-05-05 08:45
Likely a duplicate of #908

**Comment by scztt** [comment] 2015-05-05 16:38
:)

**Closed by scztt** 2015-05-05 16:38 UTC
Labels: duplicate

**Comment by smrg-lm** [comment] 2015-05-06 02:13
Smiling face is never a good argument before to close a bug. I would like to know a better reason. In the other bug, the window was supposed to be displayed and functioning, and in fact it was, except for the "it does not load the help page as it should, bro" part. In this case the window "does not exist for sure, bro".

**Comment by smrg-lm** [comment] 2015-05-06 02:21
oh, I see. You refer to the bug misplaced in the comment. That may be because people is afraid to report bugs. I wonder why.

**Comment by scztt** [comment] 2015-05-06 21:28
Sorry, didn't mean to come across as rude - the smile was about the way you wrote the bug, which made me laugh. Ordinarily I'd probably leave the bug open so you can track it, but there are already SEVERAL duplicates of this same fundamental bug floating around already - I closed to try keep things clean. Thanks for the report.

**Comment by smrg-lm** [comment] 2015-05-06 23:29
ok, thank you, there is no problem. And thank you for the effort on supercollider, I really appreciate it.
