### ISSUE TITLE
Error when saving with 3.7.0 beta1

### ISSUE THREAD

**Issue by sfogar** [supercollider/supercollider#1806] opened 2016-01-20 07:54 UTC
When saving, this error is shown (the document is saved):

ERROR: Message 'didBecomeKey' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError   0x118aac5e8
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x1152318b8
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x1153cf9b8
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x115243b18
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x11594f7a8
		arg this = nil
		arg selector = 'didBecomeKey'
		arg args = [*0]
	Meta_Document:prCurrent_   0x1151b0eb8
		arg this = <instance of Meta_Document>
		arg newCurrent = nil
	Meta_Document:setActiveDocByQUuid   0x11540f408
		arg this = <instance of Meta_Document>
		arg quuid = '{b117fe7e-5c4c-4a05-ac3e-ee1cbb917d1c}'
		var newCurrent = nil
	< closed FunctionDef >  (no arguments or variables)
	Process:interpretCmdLine   0x1151ae788
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'didBecomeKey' not understood.
RECEIVER: nil

**Comment by miguel-negrao** [comment] 2016-02-02 15:57
Can't reproduce this (linux)...

**Comment by crucialfelix** [comment] 2016-02-02 16:49
I haven't had a chance to check it yet.

**Comment by duckpow** [comment] 2016-02-11 21:11
Have had this happen as well on OS X 10.9.5 - SC3.7[b305a24]
Error message was very similar to @sfogar 's. Along with other errors from the Document class.
It seems Document is largely broken in 3.7?

**Comment by crucialfelix** [comment] 2016-02-12 10:26
I can save a document no problem. ( OS X )

I can create one with Document.new and then type and then save. no problem.

What other errors from Document class ? Please post them here.

More info please. thx

**Comment by miguel-negrao** [comment] 2016-02-12 10:50
> Have had this happen as well on OS X 10.9.5 - SC3.7[b305a24]

Is that the commit you are using or are you just pointing to that commit as a possible source of the error ? That is from 25 May 2015, you should test again on HEAD before reporting errors, they might be fixed by now.

**Comment by sfogar** [comment] 2016-02-12 10:54
Hi,

in a recent build downloaded from Travis (02/07/2016), it seems the error
is gone now...

AF

2016-02-12 11:50 GMT+01:00 Miguel Negrão <notifications@github.com>:

> Have had this happen as well on OS X 10.9.5 - SC3.7[b305a24
> <https://github.com/supercollider/supercollider/commit/b305a24f1ea7c16587da6e822cb26b09bd6c0636>
> ]
>
> Is that the commit you are using or are you just pointing to that commit
> as a possible source of the error ? That is from 25 May 2015, you should
> test again on HEAD before reporting errors, they might be fixed by now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1806#issuecomment-183270905>
> .
>



-- 
Alessandro Fogar

http://www.fogar.it

**Comment by miguel-negrao** [comment] 2016-02-12 11:14
> Hi, in a recent build downloaded from Travis (02/07/2016), it seems the error is gone now... AF

Ok, 3 people report no error, in that case closing for now. If it appears again it can be opened again.

**Closed by miguel-negrao** 2016-02-12 11:14 UTC
