### ISSUE TITLE
[question] Why sclang behaves different compared to scide?

### ISSUE THREAD

**Issue by yurivict** [supercollider/supercollider#3128] opened 2017-08-12 05:07 UTC
I am trying to run sclang with the following example:
```
s = Server.local;
s.boot;

// modulate a sine frequency and a noise amplitude with another sine
// whose frequency depends on the horizontal mouse pointer position
(
  {
        var x = SinOsc.ar(MouseX.kr(1, 100));
        SinOsc.ar(300 * x + 800, 0, 0.1)
        +
        PinkNoise.ar(0.1 * x + 0.1)
  }.play;
)
```

It says:
> booting 57110
> WARNING: server 'localhost' not running.

and there is no sound.

How can I understand why doesn't it work the same way as in scide?

FreeBSD 11.1

**Comment by telephon** [comment] 2017-08-12 06:50
did you wait between the first and second part until the server is running?

Btw. questions are usually posted to our mailing lists.

**Comment by vivid-synth** [comment] 2017-08-17 04:24
which can be found here: http://www.birmingham.ac.uk/facilities/ea-studios/research/supercollider/mailinglist.aspx

**Comment by jamshark70** [comment] 2017-08-17 08:20
@yurivict Can you confirm that telephon's answer helped you? Otherwise, we have an open item sitting around, with nothing for developers to act on.

To explain further, in the IDE, you probably hit ctrl-return on the first line, and then again on the second line, and then waited for the server to finish booting, and *then* ran the final block.

But, if you put all of the text into one file and then do `sclang thefile.scd`, it will not wait. So it will try to play the function before the server is up and running -- and at that point, indeed, "server 'localhost' not running."

Simplest solution is to use the instruction to make sclang wait until the server is up and running. Note that you have to give this instruction a function in `{ }`.

```
s = Server.local;
s.waitForBoot {
// modulate a sine frequency and a noise amplitude with another sine
// whose frequency depends on the horizontal mouse pointer position
  {
        var x = SinOsc.ar(MouseX.kr(1, 100));
        SinOsc.ar(300 * x + 800, 0, 0.1)
        +
        PinkNoise.ar(0.1 * x + 0.1)
  }.play;
};
```

Note also that, if you run sclang with a script file, you can't interact with it -- no command line. You'll have to force quit with ctrl-C. It's possible to write quite sophisticated scripts, but you'll need to learn some more basics.

Agree with telephon, this is not a bug report. Better for the mailing list. I'll give this another day and then close it.

**Closed** 2017-08-19 16:12 UTC
