### ISSUE TITLE
scide: newTextWindow failure with long strings

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#4688] opened 2019-12-21 11:57 UTC
running macOS (10.12.6) and different versions of sc (sc3.6.6 up to sc3.10.4rc1).

Bug description:
with a long string newTextWindow refuses to create more than one new document.

Steps to reproduce:
run this line multiple times...
```
String.newClear(1971).asCompileString.newTextWindow("test");  //BAD - only 1 new
```
Actual result:
after the first successful document, there are no more documents/textwindows created.

Expected result:
restart sc and again run the same line but with a slightly shorter string multiple times...
```
String.newClear(1967).asCompileString.newTextWindow("test");  //OK
```
here many new documents will be created.  just as expected.  The difference in length is 4 characters.
With a string length set to something in between 1967 and 1971 one can create two new documents and then no more.
```
String.newClear(1968).asCompileString.newTextWindow("test");  //BAD - only 2 new
```

**Comment by telephon** [comment] 2019-12-21 13:45
These must be magic numbers. But I somehow have forgotten what is so special about them.

**Comment by brianlheim** [comment] 2019-12-21 14:49
i would venture that at root this is either the same issue as https://github.com/supercollider/supercollider/issues/2569, or that some code in this call is using a buffer of size 2048 for scratch space.

**Comment by brianlheim** [comment] 2019-12-21 14:50
whoops, did not mean to close

**Comment by jamshark70** [comment] 2019-12-21 23:31
AFAICS the flow goes something like:

1. newTextWindow (btw isn't this cruft? What's better about using this rather than Document.new?)
2. Document.new
3. Document `init`
4. `text_`
5. ... eventually ScIDE.setTextByQuuid
6. ScIDE send --> prSend
7. ScIDE_Send primitive
8. Which stuffs the data into a YAML serializer

I'm gonna guess step 8.

**Comment by jamshark70** [comment] 2019-12-28 01:33
FWIW this appears to be platform specific. I can't reproduce it in Linux.

Also @redFrik does the issue occur with a long string filled with non-whitespace?

```
String.fill(1971, $a).asCompileString.newTextWindow("test");
```

**Comment by redFrik** [comment] 2019-12-28 07:04
yes (3.10.4-rc2)

**Comment by jamshark70** [comment] 2019-12-28 15:15
That kinda makes sense... At first I thought maybe the newClear was filled with zeroes (which I could imagine wreaking havoc) but in fact String.newClear fills with spaces (32). So it isn't because of unprintable ASCII codes. Checking whitespace vs visible characters was a long shot.

**Comment by bgola** [comment] 2020-06-14 19:05
I think me and @adcxyz found the reason and fix for this. See the PR above.

**Comment by adcxyz** [comment] 2020-06-14 19:30
>     1. newTextWindow (btw isn't this cruft? ...)

yes it is cruft and should be deprecated - it was a kludge to get PsyCollider windows to work.
I can do a PR for that. 
And the bugs are exactly the same for Document(...) equivalents of fredriks examples ;-)

**Closed** 2020-06-14 20:20 UTC
Labels: bug, comp: sclang
