### ISSUE TITLE
Some IDE windows and all sclang windows are blank and transparent when a custom color profile is active

### ISSUE THREAD

**Issue by ThatsJustCheesy** [supercollider/supercollider#5033] opened 2020-06-20 17:40 UTC
## Environment

* SuperCollider version: 3.11.0
* Operating system: macOS 10.15.5, Windows 10
* Other details (Qt version, audio driver, etc.): my own hardware is [MacBookPro12,1](https://support.apple.com/kb/SP715), with Intel Iris Graphics 6100

## Steps to reproduce

- Start SuperCollider 3.11.0 with a custom color profile active (see comments ↓).
- Select SuperCollider > About SuperCollider. The window that appears is a transparent box.
- Select SuperCollider > About Qt. Likewise, a transparent box.
- SuperCollider > "Preferences…". Same deal
- Run some sclang code that produces graphics. The window appears with the correct title but is a transparent box.

## Expected vs. actual behavior

Expected behavior is obvious.

Actual behavior:

<img width="1280" alt="Screen Shot 2020-06-20 at 1 37 38 PM" src="https://user-images.githubusercontent.com/16456186/85208034-473df680-b2fb-11ea-89ca-272139488388.png">
<img width="1280" alt="Screen Shot 2020-06-20 at 1 37 49 PM" src="https://user-images.githubusercontent.com/16456186/85208037-4b6a1400-b2fb-11ea-9277-efb3e0f86d0f.png">

**Comment by redFrik** [comment] 2020-06-20 18:50
yes, this is annoying.  i've seen this as well (macOS 10.12.6).
it started with sc3.10.4.  does not occur in sc3.9.3.

the same problem can be reproduced if i open SystemPreferences / Displays / Color and click on any display profile.

as a temporary workaround try uninstalling f.lux or similar programs that change the screen color.

**Comment by eleses** [comment] 2020-06-23 11:20
FWIW, under Linux (Lubuntu 20) compositing with compton works fine. You can make the SC windows as semi-transparent as you like, but you don't lose any text (unless that's what you want i.e. 100% transparency). So this is a Mac-only problem, it seems.

**Comment by dyfer** [comment] 2020-06-23 23:02
I think it would be good to get more information here. I'm on macOS (10.13 though) and never experienced this issue.
- IUUC correctly, homebrew just pulls the signed release, is that correct?
- does f.lux need to be installed for this to happen?

**Comment by redFrik** [comment] 2020-06-24 06:25
there was a thread on sc-users... https://www.listarc.bham.ac.uk/lists/sc-users-2019/msg66260.html with a little bit more info.

no, f.lux does not need to be installed.  it's just an example of one program that changes the display colours.  and in the original poster's screenshot i can see that f.lux is present (menu bar icon).

but as noted, just changing the colours in system preferences / display is enough to break scide.

**Comment by jritch** [comment] 2020-07-01 03:04
Yep, just commenting to say that I encountered this issue on Windows because I was using the built-in Night Light function.

**Comment by jamshark70** [comment] 2020-07-01 07:21
Per [this forum post](https://scsynth.org/t/meter-does-not-show-up-in-supercollider-ide/2355), the server meter may also be affected -- that's a sclang window, so the scope might be broader than the IDE.

**Comment by ThatsJustCheesy** [comment] 2020-07-01 15:25
Right, I tried to communicate that but I guess I wasn't clear.

> Run some code that produces graphics. The window appears with the correct title but is a transparent box.

I've edited to say "sclang code".

**Comment by dyfer** [comment] 2020-09-21 00:11
I have tried to test and reproduce this on macOS. 
It seems to happen only on builds using **QT 5.13 and 5.14**. On my system it works fine for builds using QT 5.15 (as well 5.12).

For macOS, the **3.11.1** release uses QT 5.15. @ThatsJustCheesy @redFrik could you confirm whether the 3.11.1 release on macOS fixes this issue?
@jritch haven't tested on Windows yet
For Linux updating QT depends on the OS distribution, as I understand. If anyone has linux with QT 5.15 and could build SC to test this, that would be great.

**Comment by ThatsJustCheesy** [comment] 2020-09-21 12:47
Can confirm that the issue seems resolved on macOS.

**Comment by redFrik** [comment] 2020-09-21 13:04
sorry, can't check to confirm.
i'm stuck on 3.11.0 as 3.11.1 does not start on my macOS 10.12.6.

(so the differences betweet 3.11.0 and 3.11.1 must be quite substantial.  curious about the version numbering here).

**Comment by dyfer** [comment] 2020-09-21 17:23
> (so the differences betweet 3.11.0 and 3.11.1 must be quite substantial. curious about the version numbering here).

Sorry to hear!
I don't think we were checking/guaranteeing 10.12 support for a while. My guess is that it's the QT upgrade (as we are just using the latest that homebrew provides), or maybe the XCode upgrade on Travis... I don't think SC changes have been so substantial between 3.11.0 and 3.11.1

**Comment by dyfer** [comment] 2020-09-21 20:03
@redFrik would you be interested in trying a [custom build](https://github.com/dyfer/supercollider/releases/download/Version-3.11.1/SuperCollider.zip) of 3.11.1? I've built it using QT 5.12. On my system it doesn't have the issue reported in this thread; I also think it should be compatible with macOS 10.12 (I'm on 10.13 so can't confirm that).

**Comment by brianlheim** [comment] 2020-09-21 20:04
> i'm stuck on 3.11.0 as 3.11.1 does not start on my macOS 10.12.6.

you can build 3.11.1 on your computer yourself with an older version of Qt; macOS 10.12 is unfortunately an obsolete OS now according to Apple, so Qt have dropped support for it. this project is compatible going back to Qt 5.7 still i'm pretty sure, and i don't think our other dependencies break compatibility so quickly, so that should be the only thing you need to build it.

the main release shouldn't change what version of qt it uses, partially because that would be difficult as old versions of qt are not typically available in homebrew, and partially because we have to sacrifice important bug fixes if we make the official release with an older Qt version.

if someone can figure out a way to get a working build in Travis with support for macOS versions < 10.13, then we could offer 2 macOS releases to cover a wider range and that would be really great. but because the graphics support has moved so quickly with the last several macOS releases, i think we have to prioritize support for the latest versions.

**Comment by dyfer** [comment] 2020-09-21 20:12
> you can build 3.11.1 on your computer yourself with an older version of Qt; 

The only problem with that is that it's difficult to get older version of Qt with homebrew. I've done it though, so if my build proves to work for macOS 10.12 I'll try to add this to our Travis build matrix.

**Comment by brianlheim** [comment] 2020-09-21 20:30
you can easily download and install older versions manually with the online installer from Qt's website, unless that was something else they changed recently.

**Comment by redFrik** [comment] 2020-09-21 20:41
> @redFrik would you be interested in trying a [custom build](https://github.com/dyfer/supercollider/releases/download/Version-3.11.1/SuperCollider.zip) of 3.11.1? I've built it using QT 5.12. On my system it doesn't have the issue reported in this thread; I also think it ~should~ could be compatible with macOS 10.12 (I'm on 10.13 so can't confirm that).

thanks, tried your build but nop... does not want to open on 10.12. dialogue says require 10.13 or higher.

**Comment by brianlheim** [comment] 2020-09-21 20:53
> > @redFrik would you be interested in trying a custom build of 3.11.1? I've built it using QT 5.12. On my system it doesn't have the issue reported in this thread; I also think it should could be compatible with macOS 10.12 (I'm on 10.13 so can't confirm that

> thanks, tried your build but nop... does not want to open on 10.12. dialogue says require 10.13 or higher.

possibly because of not setting CMAKE_OSX_DEPLOYMENT_TARGET when building?

**Comment by dyfer** [comment] 2020-09-21 20:55
> thanks, tried your build but nop... does not want to open on 10.12. dialogue says require 10.13 or higher.

Thanks for testing! I think I forgot to update the deployment target. Here's the build with deployment target set to 10.12: https://github.com/dyfer/supercollider/releases/download/Version-3.11.1/SuperCollider_3.11.1_macOS10.12.zip
Could you give it a try? Thanks!

**Comment by redFrik** [comment] 2020-09-21 21:09
yes, this one works on 10.12.  and the above transparent window issue is fixed.  thanks!
i'll play with it some more but so far no problems.

**Comment by dyfer** [comment] 2020-09-21 21:16
Back to this issue, confirming what we know now:
- on macOS
  - the issue occurs with 5.13 and 5.14 (it's fine for QT <5.12 and with 5.15)
- on Windows
  - I wasn't able to reproduce this with 5.14
- on Linux
  - ??

**Comment by brianlheim** [comment] 2020-09-21 21:32
this has never happened to me on arch linux using i3 or sway, and ive not seen a report of this from another linux user, this appears to be mac only.

**Comment by dyfer** [comment] 2020-09-21 21:34
It seems there has been one [report on Windows](https://github.com/supercollider/supercollider/issues/5033#issuecomment-652159606)

**Comment by brianlheim** [comment] 2020-09-25 00:06
5171 did not fix this, right?

**Comment by dyfer** [comment] 2020-09-25 01:18
nope; this will be fixed once I update travis to use Qt 5.15 + legacy build (PR coming soon)

**Comment by dyfer** [comment] 2020-10-27 05:27
This should be fixed in the current 3.11.2 (pre-)release, where we use Qt 5.15.
This issues also doesn't seem to be present in Qt 5.9, which we use in the newly introduced "legacy" build for older macOS systems.

**Closed by dyfer** 2020-10-27 05:27 UTC
Labels: bug
