### ISSUE TITLE
Feature request: option for matching brackets' background colour to apply to just the brackets

### ISSUE THREAD

**Issue by rygen** [supercollider/supercollider#1942] opened 2016-03-31 23:28 UTC
Currently when we set a background colour for _matching brackets_ in the SC-IDE configuration > Editor > Fonts & Colours, that same colour is applied to all text in between them, whereas the foreground colour is applied to the brackets only.

Similar to some other IDE's, I believe it would be useful to have an extra option to style just the brackets, making it easier to highlight them properly without affecting the visibility of the range within brackets.

**Comment by jamshark70** [comment] 2016-03-31 23:55
Be aware that some of us like... or rather, *love*... the current behavior. It makes it millions of times easier to see the range within the matching brackets.

Speaking just for myself, I'd be extremely cross if the current approach disappeared totally. Maybe make it configurable, but this is IMO not a bug.

**Comment by rygen** [comment] 2016-04-01 00:10
I apologise for submitting is at a bug, since it might be a loved feature for a lot more people. I've updated the title.
This is not new to 3.7, is it?

**Comment by jamshark70** [comment] 2016-04-01 01:28
I should also add that it's perfectly valid to want a more opaque, stronger background color for brackets. The current design seems to assume otherwise. I don't have a concrete idea for implementation, though.

**Comment by telephon** [comment] 2016-04-13 20:09
excellent, I didn't know that feature existed - really useful!
@rygen: just wondering: what are you using the bracket background color for?

**Comment by rygen** [comment] 2016-04-13 22:58
@telephon: not much, just to see what's the corresponding opening/closing bracket (and therefore knowing that all that's in between belongs to that scope). Helps me detecting some errors every now and then.

Highlighting all the code in between feels a bit aggressive to me. I do reckon it's just personal preference, and maybe because I'm used to XCode and Coda's workflows... :)
I'm also using a dark background, so having the matching brackets stand out by being highlighted is quite useful. They aren't as easily highlighted if I just change their text colour, whereas if I change their background colour to something that is easily noticed, then I do see them easily but all the code in between becomes a bit impossible to read, as it has other highlights that are not affected by this setting. Or maybe I'm just using the wrong colours, haha :)

**Comment by telephon** [comment] 2016-04-17 19:34
ah ok, I see. Well, I guess that's a feature request for the future to have those as separate settings (bracket character background color vs. background between brackets).

**Comment by rygen** [comment] 2016-04-17 21:22
Exactly :)

**Comment by miczac** [comment] 2016-04-17 22:30
forgive my ignorance, I'm not sure if I understand this request:
![screen shot 2016-04-18 at 0 28 16](https://cloud.githubusercontent.com/assets/1922103/14590523/bef0d2da-04fc-11e6-9593-12986e577e76.png)

**Comment by jamshark70** [comment] 2016-04-18 01:37
Rygen wants to have a bright, easily visible background color for brackets *only*, and a less intrusive background color for the material between brackets. That is not currently possible in the ide.

**Comment by brianlheim** [comment] 2017-01-17 15:50
We're not currently focusing on feature requests, so I'm closing this for now, but saving it [here](https://github.com/supercollider/supercollider/projects/3).

**Closed by brianlheim** 2017-01-17 15:50 UTC
Labels: enhancement, env: Qt IDE
