### ISSUE TITLE
String with escaped quote in brackets raises error at compilation time

### ISSUE THREAD

**Issue by wasamasa** [supercollider/supercollider#3607] opened 2018-03-26 22:49 UTC
Given the following code in `test.class` on my search path, I get a confusing error at compilation time:

```supercollider
MyTestClass {
	var foo = "[\"]";
}
```

```
ERROR: Parse error
  in file '/home/wasa/code/plt/mal/supercollider/lib/test.sc'
  line 2 char 16:

        var foo = "[\"]";
                 ^
  }
-----------------------------------
opening bracket was a '{', but found a ']'
  in file '/home/wasa/code/plt/mal/supercollider/lib/test.sc' line 2 char 16
Open ended string started on line 2 of file '/home/wasa/code/plt/mal/supercollider/lib/test.sc'
Open ended string started on line 2 of file '/home/wasa/code/plt/mal/supercollider/lib/test.sc'
ERROR: syntax error, unexpected $end
  in file '/home/wasa/code/plt/mal/supercollider/lib/test.sc'
  line 2 char 16:

        var foo = "[\"]
                  
-----------------------------------
ERROR: file '/home/wasa/code/plt/mal/supercollider/lib/test.sc' parse failed
error parsing
Library has not been compiled successfully.
```

However I can evaluate `var foo = "[\"]; foo` just fine in the interpreter.

OS: Arch Linux.
Reproducible with "sclang 3.9.2" and "sclang 3.9.2 (Built from branch 'develop' [3f0d27b])".
Plugins: No plugins whatsoever.

**Comment by wasamasa** [comment] 2018-03-26 22:53
Is there a reasonable workaround for stable versions? Could I create a regex from character literals?

**Comment by brianlheim** [comment] 2018-03-27 01:10
This is a dupe of #3352.

**Closed by brianlheim** 2018-03-27 01:10 UTC
Labels: bug, comp: sclang
