### ISSUE TITLE
[HiDPI] QcCanvas doesn't handle fractional scaling

### ISSUE THREAD

**Issue by elgiano** [supercollider/supercollider#4844] opened 2020-03-30 23:53 UTC
## Environment

* SuperCollider version: 3.11.0-beta1 (it was like this in 3.10 and 3.9 as well)
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): Qt 5.14

## Steps to reproduce
run: 
```
QT_AUTO_SCREEN_SCALE_FACTOR=1 QT_SCALE_FACTOR=0.75 sclang
```
And exec:
```supercollider
Env.perc.plot
```

## Expected vs. actual behavior
Expected: Window and Plot have the same size
Actual: Plot is smaller

Pics and fix idea [on this forum post](https://scsynth.org/t/problem-with-high-resolution-screen-display/823/12)

**Comment by dyfer** [comment] 2020-03-31 20:31
@elgiano are you planning on submitting a PR with the proposed fix?
also this likely is a duplicate of https://github.com/supercollider/supercollider/issues/2442 but can't say for sure

**Comment by elgiano** [comment] 2020-03-31 20:40
> @elgiano are you planning on submitting a PR with the proposed fix?
Yes, I thought it would have been nice to open an issue first, and listen to other people's thought on it
>  also this likely is a duplicate of #2442 but can't say for sure
I also can't say, it looks promising, but I have no Windows machine to test it on, and I'm not confident with Windows at all...

**Comment by dyfer** [comment] 2020-04-01 02:25
Thank you for submitting a PR @elgiano !

**Comment by dyfer** [comment] 2020-04-01 03:16
@elgiano just to compare behavior with Windows: when you run `s.makeGui`, does it create a properly scaled GUI window? With your fix and/or without your fix?

**Comment by elgiano** [comment] 2020-04-01 11:45
There is no difference... and actually understandably so, since my fix applies only to QcCanvas, and #2442 has problems with Widgets :(

**Comment by elgiano** [comment] 2020-04-01 12:19
Since we are here, and you can test on Windows...
Let's try to set QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
I add a commit to this PR, if you can please test it and let me know, that would be great :)

**Comment by dyfer** [comment] 2020-04-01 20:50
@elgiano thanks for this!
I was trying to have a go at the issue of display scaling on Windows (mostly, but ideally Linux as well) few times now. It just seem much more messy on the Qt-Windows/Linux side, than it is with macOS. I'd be happy share my findings if you're interested, I just wonder if this thread is best for this, or would it be better in a separate issue, or maybe a conversation on slack?

**Comment by brianlheim** [comment] 2020-04-01 22:46
since it looks like the problems/solutions here are somewhat different, i would really recommend keeping the discussions on issues and PRs separate. will make it easier for other people to follow in the future too.

**Comment by brianlheim** [comment] 2020-04-01 22:47
(btw thanks to @elgiano and @dyfer for looking into this!)

**Comment by elgiano** [comment] 2020-04-02 10:19
@brianlheim totally agree, so let's keep this issue for QcCanvas (which IMO is fixed by the PR), and talk about widgets in issue #2442 
About Qt::AA_EnableHighDpiScaling, let's talk about it in PR https://github.com/supercollider/supercollider/pull/4846

Thanks to you all!

**Closed** 2020-04-10 15:42 UTC
Labels: bug, comp: Qt GUI
