### ISSUE TITLE
labelX/labelY properties of plot are not shown

### ISSUE THREAD

**Issue by michaeldzjap** [supercollider/supercollider#2225] opened 2016-07-08 09:25 UTC
From the Plotter help file:

```
(
a = { (0..30).scramble }.dup(2).plot;
a.setProperties(
    \fontColor, Color.red,
    \plotColor, Color.blue,
    \backgroundColor, Color.grey(0.8),
    \gridColorX, Color.white,
    \labelX, "Humidity",
    \labelY, "Hello"
);
a.refresh;
);
```

The x and y labels are not shown for some reason.

**Comment by snappizz** [comment] 2016-07-09 17:17
Can reproduce.

**Comment by telephon** [comment] 2016-07-09 17:49
same here. seems to draw at a wrong position.

**Comment by Sciss** [comment] 2017-03-21 22:11
The problem is in `Plot:drawLabels` that `Pen.strokeColor_=` is used, but it should be `Pen.fillColor_=`.

**Comment by paum3** [comment] 2022-02-22 18:28
resolved in https://github.com/supercollider/supercollider/pull/5419

**Closed** 2022-02-22 18:39 UTC
Labels: bug, comp: Qt GUI, comp: class library
