### ISSUE TITLE
Code from the IDE is pasted into Apple Mail as a vCard file

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#1623] opened 2015-07-28 13:39 UTC
If you drag or paste text into a rich text message it shows up as a vcf attachment called PastedContact-1.vcf

Text copied from other plain text editors does not exhibit this problem.

**Comment by adcxyz** [comment] 2015-09-16 21:20
This is on OSX - does the same happen in linux as well?
I'd offer a beer for the person that fixes that - it is really annoying...

**Comment by timblechmann** [comment] 2015-09-16 21:32
while i neither drink beer, use apple mail nor paste code into email clients, the corresponding entry points might be:
http://doc.qt.io/qt-5/dnd.html
http://doc.qt.io/qt-5/qmacpasteboardmime.html
http://doc.qt.io/qt-5/qplaintextedit.html#createMimeDataFromSelection

**Comment by telephon** [comment] 2015-12-05 08:48
It can be "fixed", by sending only plain text mail... But still, it is a problem worth addressing.

**Comment by baconpaul** [comment] 2016-06-08 13:52
I don't have a fix, but did a bit of debugging. If you download apple's ClipboardViewer app from their developer site (https://developer.apple.com/library/mac/samplecode/ClipboardViewer/Introduction/Intro.html) you can see inside the clipboard.

If you copy from, say, textedit or Xcode you get a variety of types. For instance, here is me copying a chunk of text from textedit onto my clipboard. See all the mime-types we get.
<img width="693" alt="screen shot 2016-06-08 at 9 49 40 am" src="https://cloud.githubusercontent.com/assets/13387561/15896444/636347a6-2d5e-11e6-8c63-6dd3a4decce3.png">

But if you copy from the SC IDE you get a few extra mime types, including the vcard types. This is what causes the paste to be wrong into mail; and also why if you paste into textedit or whatever then re-copy (since textedit doesn't support vcard and it ignores that; and then fill the clipboard with just the text variants) it works.

<img width="696" alt="screen shot 2016-06-08 at 9 50 39 am" src="https://cloud.githubusercontent.com/assets/13387561/15896507/a8d2746a-2d5e-11e6-8fe2-0b539b37f694.png">

So now at least I know how to figure out if I can debug it. I may take a shot next few days but figured this research and info was useful.

**Comment by baconpaul** [comment] 2016-06-08 14:04
Ahh and a bit of googling. It seems that this is a bug in QT which the QT team is fixing. 

https://bugreports.qt.io/browse/QTBUG-48953

so either we can wait until that's merged, or try and do our own subclass of QMacMime.mm in our build (sounds ugly) or ship with a patched QT (sounds super ugly). But I think the first is the way to go, so I'm not going to write any code here today.

**Comment by telephon** [comment] 2016-06-08 19:30
I think it is ok to wait for QT to fix it. You can always cope and paste as a workaround till then.

**Comment by baconpaul** [comment] 2016-06-08 23:42
Yup. And if the QT fix is delayed for an insufferable time, I suppose we could bang out a hack like this

https://github.com/owncloud/client/commit/98b966d27433a51b4a4f77816b8c2d689bafec5e

which would have us override ::copy() and #ifdef out a MACOS thingy. Wouldn't even need objective c in the build path; could popen pbcopy in a pinch, I guess. Or some such thing.

**Comment by muellmusik** [comment] 2018-08-29 16:06
Hey! This seems to be solved in SuperCollider 3.10.0-beta1 and OSX 10.13.5.

My favourite kind of issue, one that solves itself!

If someone can confirm, I suggest we close.

**Comment by telephon** [comment] 2018-08-29 16:35
confirmed!

**Closed by telephon** 2018-08-29 16:35 UTC
Labels: bug, env: SCIDE, known issue, not a big issue, os: macOS, qt5
