### ISSUE TITLE
help: recent changes for 3.7 documentation

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1516] opened 2015-05-31 21:40 UTC
We should have a comprehensive explanation of news that we can add to until 3.7 is fully released, so that people can test new features and changed behavior quickly.

**Comment by telephon** [comment] 2015-06-01 21:45
Added a stub with a few links already, please add to it!

**Comment by jamshark70** [comment] 2015-06-02 09:43
This is very nearly a duplicate of #1347, isn't it?

**Comment by telephon** [comment] 2015-06-02 21:36
Ah yes, déjà vu. Closed that one, but I leave this one open to remind us that it still needs work (please everyone add those things missing they know of). We should also add a long "full list of changes since 3.6" section to the end with the final long list of changes.

**Comment by LFSaw** [comment] 2015-06-28 13:30
is this also to be added to that document?

f1e6bee445e3cfc37eae282fd9586c6428e453f2

**Comment by LFSaw** [comment] 2015-06-28 13:31
also, should we maybe add links to the commits if possible?

**Comment by telephon** [comment] 2015-06-28 17:52
>

is this also to be added to that document?

>f1e6bee

I've added that already, but feel free to improve!

>also, should we maybe add links to the commits where the feature/bugfix was introduced, to the document?

Good idea. At least wherever it is a single issue/commit/merge.

**Closed** 2015-09-13 19:13 UTC
Labels: comp: help, enhancement, low hanging fruit
