### ISSUE TITLE
no menu under Ubuntu with Fluxbox with Supercollider 3.8dev 

### ISSUE THREAD

**Issue by enrike** [supercollider/supercollider#1983] opened 2016-04-21 04:17 UTC
After compiling Supercollider from latest github source I get no menu. I use Fluxbox. If I log out from Fluxbox and login into Unity the menu is there. Back to Fluxbox no menu at all. I have been using fluxbox for years and I have never had this problem with any program. 

Removing the Unity global menu seems to solve it. But it is not ideal to have to do this.
$ sudo aptitude remove appmenu-qt5 appmenu-gtk

I am runnin

SuperCollider 3.8dev
3.13.0-85-generic #129-Ubuntu 
Fluxbox 1.3.5-2

I attach a screenshot

![sc_fluxbox](https://cloud.githubusercontent.com/assets/710785/14697862/6fbec3fa-0788-11e6-86de-b0e75fd8a389.png)

**Comment by miguel-negrao** [comment] 2016-04-21 11:06
duplicate of #1374, please add information on that issue, we can start compiling there which window managers have this issue under ubuntu.

**Closed by miguel-negrao** 2016-04-21 11:06 UTC

**Comment by gusano** [comment] 2016-04-21 23:03
@enrike just had a try with latest sc (c0276ab) and `fluxbox-1.3.7` (default config) on archlinux and the ide menu appears as expected.
