### ISSUE TITLE
Latency issues with supernova and Jack on OSX

### ISSUE THREAD

**Issue by mathiasbredholt** [supercollider/supercollider#4606] opened 2019-10-01 23:17 UTC
I'm running SuperCollider 3.10.3 and I'm using Jack with supernova on macOS 10.14. Everything works perfectly, but when I start a pattern such as:
```
Pbind(\degree, Pwhite(0, 10)).play
```
sclang returns a "late: 0.620066" message. I believe this has to do with the latency calculation when supernova boots:
```
Booting server 'localhost' on address 127.0.0.1:57110.
Supernova booting
Available Audio Devices:
0: Built-in Microphone (2 inputs, 0 outputs)
1: Built-in Output (0 inputs, 2 outputs)
2: JackRouter (4 inputs, 4 outputs)

opening portaudio device name: JackRouter / JackRouter
opening portaudio device name: JackRouter / JackRouter
  latency: -394928160
opened portaudio device name: JackRouter / JackRouter
  Sample rate: 48000.000
  Latency (in/out): 81250.814 / 81250.815 sec
Supernova ready
Requested notification messages from server 'localhost'
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
StageLimiter active
Shared memory server interface initialized
```
Changing block size and sample rate changes the latency value but it doesn't solve the problem. It seems that supernova calculates a wrong latency value when using JackRouter as the audio device.  Everything works fine, when I'm not using Jack.

UPDATE:
I found that the problem is solved by setting the ServerOption useSystemClock = true.

**Comment by sonoro1234** [comment] 2019-10-02 09:44
Which is the AUDIOAPI coreaudio or jackaudio?

**Comment by mathiasbredholt** [comment] 2019-10-02 12:24
Do you mean the driver setting in jack? I selected coreaudio.
![image](https://user-images.githubusercontent.com/8356424/66043747-03e1f480-e4ee-11e9-9fa5-d821b40a6d30.png)

**Comment by jamshark70** [comment] 2019-10-02 14:19
I think he means the SC cmake option -- https://github.com/supercollider/supercollider/blob/develop/CMakeLists.txt#L175

```
set(AUDIOAPI "default" CACHE STRING "Audio API to use (one of {default,coreaudio,jack,portaudio})")
```

... which IMO is a moot question, as the supernova bootup transcript clearly mentions PortAudio connecting to JackRouter.

I'm gonna guess that Jack is feeding bad numbers into PortAudio...?

**Comment by sonoro1234** [comment] 2019-10-02 14:33
> I think he means the SC cmake option --

Yes, and if it is jack then https://github.com/supercollider/supercollider/issues/4596 may be relevant

**Comment by dyfer** [comment] 2019-10-02 19:01
I too have experienced that latency reported by JACK/JackRouter to portaudio is a weird number. I haven't observed any practical problems with it, however I don't have this setup available now to confirm.

**Comment by mathiasbredholt** [comment] 2019-10-02 19:27
@sonoro1234 I'm running the release version, so I didn't change the cmake option. It's true that it looks like a JackRouter fault, but it does not happen with scsynth + JackRouter.

**Comment by jamshark70** [comment] 2019-10-02 22:48
> But I guess that's because it's an issue between JackRouter/portaudio?

In Windows, scsynth uses PortAudio too as the default backend.

> It's true that it looks like a JackRouter fault, but it does not happen with scsynth + JackRouter.

Couple of things to try (to find the boundaries of this condition):

- `s.options.hardwareBufferSize = 512;` before booting supernova: force a buffer size and it should calculate the latency based on your value (if it's successful in opening the audio driver with that value). https://github.com/supercollider/supercollider/blob/9f6bc367ba7d42002e7b3c5261e824ec3031ed07/server/supernova/audio_backend/portaudio_backend.hpp#L145

- `s.options.hardwareBufferSize = -1;` Presumably your tests so far have been with the default hardware buffer size (0). In scsynth, "0" means ask the device for its default low latency (https://github.com/supercollider/supercollider/blob/9f6bc367ba7d42002e7b3c5261e824ec3031ed07/server/scsynth/SC_PortAudio.cpp#L497) but in supernova, 0 means default high latency (https://github.com/supercollider/supercollider/blob/9f6bc367ba7d42002e7b3c5261e824ec3031ed07/server/supernova/audio_backend/portaudio_backend.hpp#L137). So there's a concrete difference between default settings. `-1` here would ask supernova to use the same function call as scsynth. Then, either supernova will behave correctly as scsynth does (and we would know the problem is JackRouter's value for `defaultHighOutputLatency`), or it doesn't and we have to look elsewhere.

- One other difference between scsynth and supernova is that scsynth always resolves timestamps against the system clock, but supernova by default resolves against the sample clock. It's a long shot but you might try `s.options.useSystemClock = true;` before booting to see if maybe latency handling is different? I think that's extremely unlikely (I'd put my money on the high vs low default latency) but it doesn't hurt to eliminate any possible variables.

**Comment by mathiasbredholt** [comment] 2019-10-02 23:00
@jamshark70 Thanks for your suggestions. 
> * `s.options.hardwareBufferSize = 512;` before booting supernova: force a buffer size and it should calculate the latency based on your value (if it's successful in opening the audio driver with that value).
I tried this and it didn't solve the problem. 
> * `s.options.hardwareBufferSize = -1;` Presumably your tests so far have been with the default hardware buffer size (0). In scsynth, "0" means ask the device for its default low latency 
>   ) but in supernova, 0 means default high latency 
I tried this too, same thing.
> * One other difference between scsynth and supernova is that scsynth always resolves timestamps against the system clock, but supernova by default resolves against the sample clock. It's a long shot but you might try `s.options.useSystemClock = true;` before booting to see if maybe latency handling is different? I think that's extremely unlikely (I'd put my money on the high vs low default latency) but it doesn't hurt to eliminate any possible variables.
As I wrote in the update this works 👍 👍, but I didn't know that scsynth resolves timestamps against the system clock. Maybe the issue is related to system/sample clock then? I wonder if it's a OSX issue only, or if it applies to other platforms?

**Comment by jamshark70** [comment] 2019-10-03 02:23
> Maybe the issue is related to system/sample clock then?

That's a very interesting finding -- surprising to me.

Sclang generates timestamps by getting the number of seconds for the clock's current logical time and adding `latency`. "Getting the number of seconds" is relative to a `std::chrono::high_resolution_clock` which is not tied to sample counts in any way.

Scsynth (and supernova with `useSystemClock = true`) also resolve timestamps against `std::chrono::high_resolution_clock`, so we expect reasonable sync.

Supernova with `useSystemClock = false` measures timestamps against sample counts. Sample rate is never 100% accurate, so we expect sclang's clock to drift away over time: if the actual sample rate is faster, eventually you will get "late" messages; if slower, then latency gets longer and longer.

I wouldn't have expected a big discrepancy right after booting supernova, though. Maybe JackRouter is providing wrong information about sample counts?

**Comment by mathiasbredholt** [comment] 2019-10-04 02:15
It makes sense for h_blocksize = 0 and h_blocksize = -1, that the value is wrong if JackRouter reports wrong information. It's strange though that when h_blocksize is set to 512 it shouldn't give a negative number?

**Comment by mathiasbredholt** [comment] 2019-10-04 02:16
But I guess the latency value and not the latency (in/out) is calculated elsewhere?

**Comment by sonoro1234** [comment] 2019-10-04 09:00
> But I guess the latency value and not the latency (in/out) is calculated elsewhere?

https://github.com/supercollider/supercollider/blob/develop/server/supernova/audio_backend/portaudio_backend.hpp#L191

simple multiplication of portaudio provided numbers!!
Could be portaudio fault or JackRouter fault!!

**Comment by mathiasbredholt** [comment] 2019-10-21 19:42
Problem is solved by using
`Server.default.useSystemClock = true`

**Comment by mathiasbredholt** [comment] 2019-10-21 20:17
I wrote a test in C to get device info from PortAudio and it is definitely reporting the wrong values for output latency for JackRouter:
```
Device: Built-in Output
Low input latency: 0.010000
Low output latency: 0.005208
High input latency: 0.100000
High output latency: 0.014542
Device: JackRouter
Low input latency: 0.010000
Low output latency: 68763.148937
High input latency: 0.100000
High output latency: 68763.148937
```
The test was created using this
```
    const PaDeviceInfo *deviceInfo;
    for(int i = 0; i < numDevices; i++) {
        deviceInfo = Pa_GetDeviceInfo( i );
        printf("Device: %s\n", deviceInfo->name);
        printf("Low input latency: %f\n", deviceInfo->defaultLowInputLatency);
        printf("Low output latency: %f\n", deviceInfo->defaultLowOutputLatency);
        printf("High input latency: %f\n", deviceInfo->defaultHighInputLatency);
        printf("High output latency: %f\n", deviceInfo->defaultHighOutputLatency);
    }
```

**Comment by dyfer** [comment] 2019-10-21 20:25
As this seems to be a bug between PortAudio and JackRouter, should we keep this open as a SuperCollider issue?

**Comment by jamshark70** [comment] 2019-10-22 01:45
Would be good to log a bug somewhere... I guess JackRouter would be the most likely place to start. https://github.com/jackaudio/jack2/issues perhaps? (I'm not able to search their existing issues at the moment.)

**Comment by mathiasbredholt** [comment] 2019-10-22 20:09
https://github.com/jackaudio/jack2/issues/519

**Comment by sletz** [comment] 2019-10-23 08:28
Can you poset your C test code?

**Comment by jamshark70** [comment] 2019-10-23 10:28
> Can you post your C test code?

https://github.com/supercollider/supercollider/issues/4606#issuecomment-544689241

**Comment by sletz** [comment] 2019-10-23 20:57
Well since nodody is maintaining the JackRouter code anymore, I doubt this issue will be fixed.

**Comment by JeffGreenlee42** [comment] 2019-11-05 01:42
Hmmm..since no one is maintaining JackRouter anymore..  is there ANY attempt afoot anywhere at creating a multi-platform, multi-channel  Audio -  routing system?   I mean I know there are competing alternatives on MAC and Linux .. but why is there no effort to keep this available for the Windows platform?    It seems like its  a critical technology for parallel Audio streams that need to connect to each other!

**Comment by mathiasbredholt** [comment] 2019-11-05 05:17
@JeffGreenlee42 The jack audio server is being maintained, and it is possible to compile scsynth with jack as the backend. In that case you don't need JackRouter anymore and it also makes the integration much better (possibility to change number of inputs/outputs with s.options.numOutputBusChannels etc.)

**Comment by mathiasbredholt** [comment] 2019-11-05 05:18
I think it would be useful to make a prebuilt version of SuperCollider with jack as the backend available for all platforms.

**Comment by JeffGreenlee42** [comment] 2019-11-07 18:46
OMG!   A prebuilt version of SC with jack as Backend!!!  That would be a
dream come true!
I am embarrassed to say how many hours I have spent burning a candle...
trying to get this to work!!!  After a lot of fuss, there are times I can
manage to get both SC and Jack Router running.. but Neither Server can see
each other.. I can get Jack to include my DAW as one of its Audio sources..
but it has NEVER shown SC ..   so I can't Route the output of TidalCycles
via SC  into an input channel of my DAW!    When I boot the SC server  I do
NOT see "ASIO : Jack Router"    among the available output choices.  So I
am wondering...   in the scenario where Jack is a "backend" ,   Would one
be able to manipulate Jack with Jack Control?   In other words,  HOW do I
divert SC audio to my DAW?    By the way, I've also tried adding
"Synchronous Audio Router"  (SAR)  to this mess.. but so far no luck with
that either.

Jeff Greenlee

"Music is a higher revelation than all wisdom and philosophy. Music is the
electrical soil in which the spirit lives, thinks and invents."
Ludwig Van Beethoven

**Comment by sletz** [comment] 2019-11-07 18:52
Note that JACK can be linked using a weak API (see https://github.com/jackaudio/jack2/blob/develop/common/JackWeakAPI.c). Il means a SC binary could be built an run even JACK server is not installed, ans possibly switch to the native audio API . I would recommend trying if this model can be used on OS X and Windows at least.

**Comment by JeffGreenlee42** [comment] 2019-11-09 08:11
Hmmm.. there is ZERO documentation on that.  I have no clue what to do with
it.. or how to use it!

Jeff Greenlee

"Music is a higher revelation than all wisdom and philosophy. Music is the
electrical soil in which the spirit lives, thinks and invents."
Ludwig Van Beethoven

**Comment by jamshark70** [comment] 2019-11-09 20:22
> Hmmm.. there is ZERO documentation on that.  I have no clue what to do with it.. or how to use it!

sletz's comment was intended as a potential solution that SC developers could implement in the future. It would require some changes to the server's codebase. Unfortunately it hasn't been implemented yet (which would explain the lack of documentation) and, as it's a new suggestion, there's no concrete plan for it at this time.

Incidentally, a few of my students who use Windows have found something called Voicemeeter, which poses as an ASIO device and claims "to mix and manage any audio sources from or to any audio devices or applications." It doesn't fall within the free/libre software ecosystem (donationware -- if FLOSS is important to you then this wouldn't be ok) and *I have not tried it personally with SC and I can make no promises that it will work for any particular use* (at your own risk) and the SC community can't offer any help with configuring it -- but it might be an option in the meantime...?

**Comment by sonoro1234** [comment] 2019-11-10 09:24
> OMG! A prebuilt version of SC with jack as Backend!!! That would be a dream come true!

https://github.com/supercollider/supercollider/pull/3692

**Comment by jamshark70** [comment] 2019-11-10 10:54
> #3692

Seems to have slipped through the cracks, though the current status is that there are merge conflicts... final review might be stalled waiting for those to be resolved.

**Comment by sonoro1234** [comment] 2019-11-10 11:05
There were not merge conflict some months ago...

**Comment by beatboxchad** [comment] 2019-12-11 16:41
I'm willing to help drive this home any way I can. I'm a new contributor, though, and am going to warm up on some other stuff first. 

JACK API stuff is well within my wheelhouse, but other aspects of this PR are not. I don't know the supernova codebase well, and all my systems programming experience is on Linux. 

Resolving merge conflicts is likely to mostly just be grunt work, and would typically fall to the submitter who knows most about how their contributions fit in. But since @sonoro1234 has been waiting so long and because I could probably learn a thing or two in doing so, I hereby volunteer to slog through that if they are amenable.

**Comment by JeffGreenlee42** [comment] 2020-01-14 02:37
Hi,

Sorry for answering this so late!     Hey.. In November/early December ,  I
too discovered Voicemeter!  I purchased and installed Voicemeter Potato ..
and This has solved most of the problems I had with Jack.  (Now I don't use
Jack at all!)   I fret perhaps a little... I can't imagine voicemeter has
the smallest footprint regarding CPU time... but for the most part it works
Quite well!  I actually love that you can take an input .. like audio from
an application like a browser or something and tweak the sound quality of
the input... It comes in quite handy for  audio that isn't normalized or
sounds kind of dull or flat. And it works great with OSC.   Voicemeter DOES
take some getting used to... It's not really designed for Music
production.. It's obviously much more suited for people doing voice and
video hosting production work. But one thing I haven't explored yet that is
quite exciting about it is that its fully OSC compliant...  So if you've
got a router and a network..  you can communicate between devices with
audio and signals... you just need to be able to create ports in your
network.  I speculate that OSC might one day dominate musical communicaiton
channels.

Jeff Greenlee

"Music is a higher revelation than all wisdom and philosophy. Music is the
electrical soil in which the spirit lives, thinks and invents."
Ludwig Van Beethoven

**Comment by dyfer** [comment] 2020-01-28 00:00
I think this issue is not valid anymore and I'd like to close it to avoid confusion.

IUUC, this issue has to do with supernova using audio clock by default:
https://github.com/supercollider/supercollider/issues/4606#issuecomment-544675377

In the past I have worked quite a bit with supernova and JackRouter and while I have noticed the latency being reported erroneously, it did not seem to affect the actual latency (hence I think keeping this issue open is misleading to others.) 

Also, for the record, `s.options.hardwareBufferSize` had no effect for me, as JackRouter seemed to always force supernova to use the Jack buffer size.

Feel free to reopen if I missed something or if you disagree :)

**Closed by dyfer** 2020-01-28 00:00 UTC
Labels: bug
