### ISSUE TITLE
waitForBoot is broken: ID allocation is reset after function is executed

### ISSUE THREAD

**Issue by rkuivila** [supercollider/supercollider#3331] opened 2017-12-08 21:47 UTC
s.waitForBoot {s.nextNodeID.postln };

// wait for the above line to return
// then

s.nextNodeID.postln;

//same ID!!!

Perhaps this is due to an uncompleted change from 3.8:
		/*
				// this is not yet implemented.
				or: { serverBooting and: mBootNotifyFirst.not }
				and: { (limit = limit - 1) > 0 }
				and: { server.applicationRunning.not }
				*/

**Comment by jamshark70** [comment] 2017-12-08 21:53
Dupe of https://github.com/supercollider/supercollider/pull/3275, if I'm not mistaken.

They've been working on this for a month already. It's more complicated than you think, mainly because the boot process is a(n expletive deleted) mess. But we decided not to fix the boot process until 3.9.1 (too large a change, too risky in beta), so we're waiting on the hacks from this PR.

**Comment by rkuivila** [comment] 2017-12-08 22:02
Thanks!

RJK

On Dec 8, 2017, at 4:53 PM, H. James Harkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Dupe of #3275<https://github.com/supercollider/supercollider/pull/3275>, if I'm not mistaken.

They've been working on this for a month already. It's more complicated than you think, mainly because the boot process is a(n expletive deleted) mess. But we decided not to fix the boot process until 3.9.1 (too large a change, too risky in beta), so we're waiting on the hacks from this PR.

**Closed** 2017-12-08 22:09 UTC
