### ISSUE TITLE
Multichannel recording does not work in Windows 7

### ISSUE THREAD

**Issue by gogobd** [supercollider/supercollider#1560] opened 2015-06-24 17:25 UTC
In Windows 7, with SC 3.6.6 recording 4 channels does not work for me et al. I use this code:

---
// Test recording - multichannel recording fails for me...
(
    Server.default.quit;
    Server.default.options.device = "ASIO : JackRouter";
    Server.default.options.numOutputBusChannels = 8;
    Server.default.options.sampleRate = 48000;
    Server.default.options.memSize = 1024 * 32;
    s = Server.default.boot;
)

(
    var duration = 10.00;        // 10 seconds
//    var duration = 2.00 * 3600.0;   // 2 hours

    s.recChannels = 4;
    s.recHeaderFormat = "WAV";
    s.recSampleFormat = "int24";

    x = {SinOsc.ar([440,441,880,881])};

    r = Routine.new({
        thisProcess.platform.recordingsDir.postln;
        s.prepareForRecord(thisProcess.platform.recordingsDir +/+ 'Test_out.' ++ s.recHeaderFormat);
        s.sync;
        "START: ".post;
        Date.getDate.postln;
        "DURATION: ".post;
        (duration / 3600.0).postln;
        s.record;
        t = x.play;
        wait(duration);
        t.free;
        s.stopRecording;
        "STOP: ".post;
        Date.getDate.postln;
    });

    r.run;
)
---

and the resulting .WAV file is completely corrupted, the server process dies.

**Comment by timblechmann** [comment] 2015-06-25 13:48
this is broken by design: the diskout ugen uses a pre-defined buffer size and double-buffering inside this recording buffer. according to the sc community, a buffer size of 1 second is sufficient.
on windows the access to the file system is one or two orders of magnitude slower than on unixy platforms, so you will most likely run into the issue of buffer sizes being to small.

unfortunately my workaround to significantly increase the recording buffer size was reverted, though.

**Comment by jamshark70** [comment] 2015-06-25 15:08
Tim, the point of the previous discussion was that there really is no one-size-fits-all buffer size that has no disadvantages. Your approach was wildly inappropriate for the sample rates at which most users work because it requires most users to keep the recording running for some 30 seconds longer than needed, and it was correct to revert it.

It is fair to revisit the issue of the recording buffer size, and perhaps introduce a platform switch to use a larger recording buffer in Windows.

**Comment by bagong** [comment] 2015-06-25 15:18
Hmmm? I thought this change was introduced quite recently on the master branch? How should it be relevant for 3.6.6?

I’ll check 3.7 anyways. There are useable builds out there since today, Lucas fixed IPC. check:

https://drive.google.com/folderview?id=0B7igZrWv7UxdUmxHdThYLUE2QXc&usp=sharing <https://drive.google.com/folderview?id=0B7igZrWv7UxdUmxHdThYLUE2QXc&usp=sharing>

I’ll make a nicer announcement later.

Best
.r.

**Comment by bagong** [comment] 2015-06-27 12:01
Okay, I've been trying simple recording with the currently available build of scwin3.7alpha1. I can reproduce this partially insofar as file-size and format limits are involved (wav and aiff). So a 4 channel 48khz recording with more than 2 hours will break. And we know it's because the headers of these formats cannot accommodate files bigger than 2 or 4 GB. Among the alternatives I found the following: Mac-CAF does in fact not work on Windows, it's use crashes the Server. But W64 (Soundforge wave) works nicely. I didn't wait for another 3 hours, but pushed the file size up to 10GB via multichannel. No problems so far. Writes nicely and the file can be opened in Audacity. I'll let it run for 3 hours later, but I'd be surprised if there was a problem.
Could we close this issue? (I'll file a separate issue for CAP on Windows, as well as FLAC, that also doesn't work, but I'll try out other formats first)

**Comment by gogobd** [comment] 2015-06-27 12:26
@bagong Does a 10 second 4 channel .wav file work for you on Windows?

**Comment by bagong** [comment] 2015-06-27 12:33
Yes. But I didn't use your code. I just recorded via menu/or simple command line input. I tried up to 128 channels and several formats. The recordings break if file-size limits are overstepped, I can confirm that, but the footnote of course is that that's not sc's fault. W64 seems to be the format of choice for bigger stuff on Windows.

**Comment by bagong** [comment] 2015-06-27 13:38
The problem is here:
s.prepareForRecord(thisProcess.platform.recordingsDir +/+ 'Test_out.' ++ s.recHeaderFormat)
I get no file written with this setting.
But the you say you get a broken file? I get no file at all...

**Comment by bagong** [comment] 2015-06-27 13:57
Okay, I am close now: the file is not created, if the folder ...../Documents/SuperCollider/Recordings doesn't already exist. That given, your code works for me. No corruption of the audio-file. I'll run 3 hours with w64 now (it's grilling time ;))

**Comment by bagong** [comment] 2015-06-27 18:09
So no problems with 3 hours 4 channels 48 kHz, format w64. Filesize 5.79 GB. Wanna switch to 3.7alpha1? ;) We need testers.
So I'd draw a few conclusions from this:
- multichannel recording (allowing a looot of channels) basically works on scwin3.7
- format of choice for quality recordings of long duration would be w64
- there are problems with a few formats, most notably FLAC and CAF
- there is something fishy with creating paths from strings (not really surprisingly)

The later two points need further research.

**Comment by bagong** [comment] 2015-06-27 18:12
Could you please checkou how your ultimate findings differ from mine. I'd like to close this and add more specific issues for the later two points. But if you prefer to keep the issue I'll tag it as 'limited to old version'

**Comment by telephon** [comment] 2015-06-27 19:55
Feel free to reopen if it turns out not to be fixed by recent changes to DiskIn.

**Closed** 2015-06-27 19:55 UTC
Labels: limited to old version
