### ISSUE TITLE
compiling master on win mingw

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1975] opened 2016-04-18 15:32 UTC
@bagong my command with may be some unnecesary flags

```
cmake  -G"MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="./toolchain.cmake" -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DSUPERNOVA=ON -DSC_ONLY_SERVER=ON -DSC_PSYCOLLIDER=OFF -DINSTALL_HELP=OFF -DINSTALL_OLD_HELP=OFF -DSSE2=ON -DSC_OX=ON -DSC_IDE=OFF -DSC_QT=OFF -DCMAKE_INSTALL_PREFIX="./installdir" -DLIBSCSYNTH=ON  -DPA_LIBRARY_TYPE="STATIC" ../scfork/SuperCollider
```
then mingw32-make scsynth
```
Linking CXX shared library "$$<CONFIG>\liblibscsynth.dll"
c:/mingw32-4.8.2-posix-dwarf/bin/../lib/gcc/i686-w64-mingw32/4.8.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot open outpu
t file $$<CONFIG>\liblibscsynth.dll: Invalid argument
collect2.exe: error: ld returned 1 exit status
server\scsynth\CMakeFiles\libscsynth.dir\build.make:845: recipe for target 'server/scsynth/CONFIG>/liblibscsynth.dll' failed
mingw32-make[3]: *** [server/scsynth/CONFIG>/liblibscsynth.dll] Error 1
CMakeFiles\Makefile2:3408: recipe for target 'server/scsynth/CMakeFiles/libscsynth.dir/all' failed
mingw32-make[2]: *** [server/scsynth/CMakeFiles/libscsynth.dir/all] Error 2
CMakeFiles\Makefile2:3420: recipe for target 'server/scsynth/CMakeFiles/libscsynth.dir/rule' failed
mingw32-make[1]: *** [server/scsynth/CMakeFiles/libscsynth.dir/rule] Error 2
Makefile:1330: recipe for target 'libscsynth' failed
mingw32-make: *** [libscsynth] Error 2

```

after I commented line 
C:\SupercolliderRepos\scfork\supercollider\server\scsynth\CMakeLists.tt:246
```
set_target_properties(scsynth libscsynth PROPERTIES RUNTIME_OUTPUT_DIRECTORY "$<CONFIG>")
```
libscsynth got compiled
but then libsclang and others tried to be compiled as dependencies of scsynth (which should not be)
and finished with error
```
Linking CXX shared library "$$<CONFIG>\liblibscsynth.dll"
c:/mingw32-4.8.2-posix-dwarf/bin/../lib/gcc/i686-w64-mingw32/4.8.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot open outpu
t file $$<CONFIG>\liblibscsynth.dll: Invalid argument
```

I am not able to understand how the CONFIG issue should be solved.
As for the false dependencies perhaps they come from the add_custom_command POST_BUILD?

best
victor

**Comment by sonoro1234** [comment] 2016-04-18 15:48
I have confirmed that commenting this POST_BUILD commands false dependencies go away but I dont know how to solve it!!

**Comment by bagong** [comment] 2016-04-18 16:06
I'll look into it right now. Something is fishy here "$$<CONFIG>" (two $) and "'server/scsynth/CONFIG>/liblibscsynth.dll" ($<CONFIG> not resolved). I didn't pay much attention to libscsynth.dll in the latest versions of the build system, sorry. Will try to solve. In general the MinGW build system does use build-configuration specific target folders now. This simplifies maintaining the build system for building with both MinGW and VS (VS always uses them), and creating useable target folders.

As to the the "false dependencies": probably wrapping the post build steps into something like `if(target sclang)` would make them go away. But I remember vaguely running into some trouble there. You know there is a PR on the way that will explicitly allow for a server only build. If that uses an SC_SCLANG ON/OFF flag, that flag could be used to avoid the post-build step as well.  I have a prototype for extending that to Windows... Unfortunately atm the situation with PRs is a bit messy because different PRs conflict. We'll have to see how to get out of that...

Can you please tell me *how* you used to build "server only"?

**Comment by sonoro1234** [comment] 2016-04-18 16:26
@bagong Thanks for your interest, I'll wait untill all the mess gets solved.

>Can you please tell me how you used to build "server only"?
I had fortune: scsynth and plugins were built before everything else. Afterwards build was broken but I already had my binaries :-)

**Comment by bagong** [comment] 2016-04-18 16:36
Hahaha, foul play ;) But just to let you know, for me the complete master builds with MinGW 4.8.2 now. (Including supernova with your PR, but - as I learn from your report - except for libscsynth.dll).

MinGW 4.9.2 breaks with that "internal compiler error" you also saw. Fixing the build for 64-bit would be a fantastic next step on Windows. It seems that several problems (optimization, Qt-segfaults) only occur in the 32-bit target architecture (msys2 mailing list is full of problems with the 32-bit toolchain).

**Comment by bagong** [comment] 2016-04-18 17:13
@sonoro1234 , I do not get this problem. Libscsynth.dll was copied properly to the target folder :p Did you checkout latest master? Did you maybe stay where you added that supernova related pull-request? Could you try to checkout latest master, merge or add that supernova change and try again? I'd like to fix that if it really is a problem, but atm I cannot reproduce it...

**Comment by sonoro1234** [comment] 2016-04-18 18:04
no, i checked out last master. Perhaps my cmake command is missing something (it is in the first post)?

**Comment by bagong** [comment] 2016-04-18 18:39
Well, half of the variables you use do not exist anymore (so no use for them, but they can also do no harm, right). 3 or 4 you set to the default value, which should also do no harm. I cannot see what you have in your toolchain file, but I assume you do check cmake output, right, so you would see anything dangerous there. Ah, maybe try `git submodule update` and see if it does anything? But all in all none of this should cause *that* kind of error. The question is, where does that second `$` in

    `$$<CONFIG>\liblibscsynth.dll`

come from, why isn't $<CONFIG> resolved to `server\scsynth\RelWithDebInfo`, as it is on my system...

Did you maybe accidentally add the second `$` when you were editing manually? Does `git status` return everything clean? Does `git diff` return anything?

If this all leads to nothing, I only see two alternatives: you try to reproduce the build system exactly as described in the readme, or we go step by step through your configuration and see when the error is triggered. Sorry, I'd like to help and increase the robustness of the build system, but right now I cannot see what causes this kind of error.

Eh, maybe the cmake version? All this generator-expressions stuff should work with 2.8.12, but I actually gave 3.0.2 as min-requirement for Windows in the readme, and current cmake is actually at 3.5.1 ;) We're not bound to distributions, are we, so no need to use the old stuff. But that's a shot in the dark too.

**Comment by bagong** [comment] 2016-04-19 05:08
Maybe you're not doing a clean build? After all those changes best thing is to start from an empty build folder.

**Comment by sonoro1234** [comment] 2016-04-19 14:45
@bagong I have tried googling
```
cmake "$<CONFIG>"
```
but cant find nothing.
Where did you found this variable?

**Comment by sonoro1234** [comment] 2016-04-19 14:57
ok, founded in
https://cmake.org/cmake/help/v3.0/manual/cmake-generator-expressions.7.html
my cmake is 3.0, will try 3.0.2

**Comment by sonoro1234** [comment] 2016-04-19 15:19
with cmake 3.0.2
```
message(STATUS "config is" $<CONFIG>)
```
outputs
```
-- config is$<CONFIG>
```
so my config variable is not set
why?
investigating...

**Comment by sonoro1234** [comment] 2016-04-19 15:33
according to http://stackoverflow.com/questions/28692896/how-to-use-cmake-generator-expression-target-filetgt
my test is not ok as this generator expressions only work at generate or build time and not at configure time

**Comment by sonoro1234** [comment] 2016-04-19 16:36
have new cloned the supercollider repo with everything as before. Problem remains.

**Comment by bagong** [comment] 2016-04-20 09:41
I wonder how we should approach this and which amount of time you are willing to invest ;) If you want/have time to bear with me, an approach could be to reproduce what would currently be the default way to build master for Windows. Depending on success/failure we had some indicator in which direction to move:
You'd have to download Qt 5.5.1 and MinGW 4.8.2 (in Tools) from the "official" download, using the web-installer.
- arrange your libsndfile, fftw3 and optionally readline libs in a specific way:

         x86/libsndfile
         x86/fftw
         x86/readline

as a "sibling"of /next to the supercollider source folder (just like the ASIO SDK). The subfolders of those library root folders should just be arranged like in the download from the respective providers. So fftw a flat folder, libsndfile and readline using the bin/lib/include subdivision.

- set the environment variable `CMAKE_PREFIX_PATH`
- add Qt and MinGW at the head of your environment path (mind that master currently still requires mingw 4.*8*.2)

and then run cmake with just very few arguments.

    $> SET PATH=C:\Qt\5.5\mingw492_32\bin;C:\Qt\Tools\mingw482_32\bin;%PATH%
    $> SET CMAKE_PREFIX_PATH=C:\Qt\5.5\mingw492_32
    $> cd supercollider
    $> mkdir build
    $> cd build
    $> cmake -G "MinGW Makefiles" ..

This will give you full SC in RelWithDebInfo but without supernova. Your PR for supernova has been merged (pull again before building), so this should work out of the box now:

    $> cmake -G "MinGW Makefiles" -D SUPERNOVA=ON ..

Add `CMAKE_BUILD_TYPE=Release` for a release build, or `Debug` for a debug build. Note that it is possible to run SC in debug mode from the target folder, you don't really need to install if your environment is set up properly. This also works in Qt-Creator.

I have also verified stuff like `SC_IDE`, `SC_QT`, `LIBSCSYNTH`, help on/off, help only, so that should actually all work, but for now you may want to do just the most common standard build to see if you still get that error?

Then build:

    $> cmake --build . // will create target folders in which you can run scsynth/sclang/scide

If required, install:

    $> cmake --build . --target install

This will install full sc to `<build folder>/Install. It requires some patience as fixup_bundle is very slow when using MinGW

For now, btw, there is a workaround for "scsynth only" requirements. After that generic build finished (no need to run the install target), you can do:

    $> cmake --build . --target install_server_only

That should give you what you *actually* want. You don't really have to do the full install (but we might profit from the availability of a full SC on your system ;) )

If that succeeds we could try to work out what makes the build fail in your specific setup? (And you do want to post your toolchain file at some point, to brighten up the remaining dark hole ;) )

**Comment by sonoro1234** [comment] 2016-04-21 15:48
fftw-3.3.4 makes a dll at fftw./libs directory but not at fftw so it is not properly detected.
I am reinstalling Qt to try

**Comment by sonoro1234** [comment] 2016-04-21 16:39
I have tried instructions from your lat message with fftw dll in correct directory master branch from original supercollider repo and command line
```
set PATH=%PATH%;C:\cmake-3.0.2-win32-x86\bin\;

SET PATH=C:\Qt\5.5\mingw492_32\bin;C:\Qt\Tools\mingw482_32\bin;%PATH%
SET CMAKE_PREFIX_PATH=C:\Qt\5.5\mingw492_32

cmake  -G"MinGW Makefiles"  -DCMAKE_BUILD_TYPE=Release  -DSUPERNOVA=ON  -DINSTALL_HELP=OFF -DSSE2=ON -DSC_IDE=OFF -DSC_QT=OFF -DCMAKE_INSTALL_PREFIX="./installdir" -DLIBSCSYNTH=ON   ../scorig/SuperCollider
```
but problem remains

**Comment by bagong** [comment] 2016-04-21 16:51
How if you'd just try everything as I said, just to see if it makes a difference? ;) Will cost you 30 mins, and you can drink a coffee while the computer is working ;) It will help us focusing in on the problem. 

But I'll try to find out if any of your cmake variables make a difference in my environment.

Note that I am using cmake 3.5.1... I am of the "use the latest if possible type"... ;)

The one thing I don't remember having ever tried is install_help=off

I'll let you know...

**Comment by sonoro1234** [comment] 2016-04-21 16:57
It is everything as you told ecept for cmake
I am going to try

**Comment by bagong** [comment] 2016-04-21 16:59
Well, I was suggesting to use *only* -G "MinGW Makefiles" and -D SUPERNOVA=ON ;) But never mind, my build is running now, we'll see. Thanks for trying latest cmake! I would have tried the opposite as next step...

**Comment by sonoro1234** [comment] 2016-04-21 17:01
Ohh, I see you build directory is inside supercollider src directory

**Comment by bagong** [comment] 2016-04-21 17:02
While it is, it shouldn't be necessary. But I will test that as well.

Having it inside has the advantage that you can access git while you're building...

**Comment by sonoro1234** [comment] 2016-04-21 17:23
Got it: cmake 3.5.2 (3.5.1 could not be found) is the answer
So now it should be required at least for windows

**Comment by sonoro1234** [comment] 2016-04-21 17:30
other things to fix:
fftw compiled (not binaries) have dll in other place
mingw can compile directx with the included libraries (dont need to download)

**Comment by bagong** [comment] 2016-04-21 17:49
Okay, I found another problem in the post install step: model.sc has been moved. I'll fix that as well. But that's really master specific.

- Would be nice to know which cmake version is the smallest required. You jumped from 3.02, right, so I should try 3.2 maybe.

- That DirectX thingy is very interesting. Where is a DirectX shipped with MinGW located? How would portaudio find it? Portaudio can find a DirectX installed into the Windows system. But I actually changed the find-algorithm of Portaudio to avoid that, because people don't usually install a DirectX low enough not to break the Portaudio build. The biggest problem is, that it is quite difficult to get hold of a DirectX build the version of which is low enough to work in the MinGW build.
- did you do your working build in a subfolder of SC or in a parallel folder? If the later, I could save testing for that.

Thanks for helping patiently! It's invluable!
Best
.r.

**Comment by sonoro1234** [comment] 2016-04-21 17:53
-subfolder or paralel dont matters

**Comment by bagong** [comment] 2016-04-21 17:56
Thanks! Would you be so kind to answer my other questions as well?

**Comment by sonoro1234** [comment] 2016-04-21 17:58
direct
#include <dsound.h> in code and then link to dsound. Nothing else needed

**Comment by bagong** [comment] 2016-04-21 18:13
Could you explain with a little more detail? I am not as smart as I try to appear ;)

- So I should include `dsound.h`? In which code? Portaudio? Could you say where?
- then link to `libdsound.a`? Again that would be done in Portaudio, right? Could you explain?

Thanks!
.r.

**Comment by sonoro1234** [comment] 2016-04-21 18:19
I suppose dsound.h must already be included in portaudio so only is left to do
```
target_link_libraries(portaudio dsound)
```

**Comment by sonoro1234** [comment] 2016-04-21 18:26
So the change to CMaleList.tt would be: if it is mingw dont search it just link and if it is VS i dont know

**Comment by bagong** [comment] 2016-04-21 18:27
Yes, I am trying to understand. It would be great if that worked, I'll try. Thanks!

**Comment by sonoro1234** [comment] 2016-04-21 18:31
my build finished without the error from model.sc.

**Comment by sonoro1234** [comment] 2016-04-21 18:44
without doing nothing my devices are
```
 - MME : Asignador de sonido de Microsof - Input   (device #0 with 2 ins 0 outs)
  - MME : Line 1/2 (3- FastTrack Pro)   (device #1 with 2 ins 0 outs)
  - MME : Micrófono (Realtek High Definit   (device #2 with 2 ins 0 outs)
  - MME : Line 3/4 (3- FastTrack Pro)   (device #3 with 2 ins 0 outs)
  - MME : Asignador de sonido de Microsof - Output   (device #4 with 0 ins 2 outs)
  - MME : Line 1/2 (3- FastTrack Pro)   (device #5 with 0 ins 2 outs)
  - MME : Altavoces (Realtek High Definit   (device #6 with 0 ins 6 outs)
  - MME : S/PDIF (3- FastTrack Pro)   (device #7 with 0 ins 2 outs)
  - MME : Realtek Digital Output (Realtek   (device #8 with 0 ins 2 outs)
  - ASIO : Generic Low Latency ASIO Driver   (device #9 with 2 ins 2 outs)
  - ASIO : M-Audio USB ASIO   (device #10 with 4 ins 4 outs)
  - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #11 with 0 ins 6 outs)
  - Windows WDM-KS : Línea de entrada (Realtek HD Audio Line input)   (device #12 with 2 ins 0 outs)
  - Windows WDM-KS : Micrófono (Realtek HD Audio Mic input)   (device #13 with 2 ins 0 outs)
  - Windows WDM-KS : SPDIF Out (Realtek HDA SPDIF Out)   (device #14 with 0 ins 2 outs)
  - Windows WDM-KS : Mezcla estéreo (Realtek HD Audio Stereo input)   (device #15 with 2 ins 0 outs)
  - Windows WDM-KS : Line 1/2 (Fast Track Pro In 1/2)   (device #16 with 2 ins 0 outs)
  - Windows WDM-KS : Line 3/4 (Fast Track Pro In S/PDIF)   (device #17 with 2 ins 0 outs)
  - Windows WDM-KS : Line 1/2 (Fast Track Pro Out 1/2)   (device #18 with 0 ins 2 outs)
  - Windows WDM-KS : S/PDIF 1 (Fast Track Pro Out 3/4)   (device #19 with 0 ins 2 outs)
  - Windows WDM-KS : S/PDIF 2 (Fast Track Pro Out 3/4)   (device #20 with 0 ins 2 outs)
```
so it seems that directx is working without even linking?

**Comment by bagong** [comment] 2016-04-21 18:48
No, no dsound support ;) WDM-KS doesn't require directx.

**Comment by sonoro1234** [comment] 2016-04-21 18:53
instead of
```
IF(PA_USE_DS AND DXSDK_FOUND)
TARGET_LINK_LIBRARIES(portaudio ${DXSDK_DSOUND_LIBRARY})
ENDIF(PA_USE_DS AND DXSDK_FOUND)
```
try
```
IF(MINGW)
SET(DXSDK_DSOUND_LIBRARY dsound)
ENDIF(MINGW)
IF(PA_USE_DS AND (MINGW OR DXSDK_FOUND))
TARGET_LINK_LIBRARIES(portaudio ${DXSDK_DSOUND_LIBRARY})
ENDIF(PA_USE_DS AND DXSDK_FOUND)
```

**Comment by bagong** [comment] 2016-04-21 18:54
Yep, I was thinking in a similar direction. But I can't fully focus atm. Maybe later tonight or tomorrow. Thank you *very* much!

**Comment by sonoro1234** [comment] 2016-04-22 11:19
You are welcome. Tell me when it is ready for testing.

**Comment by bagong** [comment] 2016-05-13 23:39
@sonoro1234 , would be great if you could have a go at that PR I made, thanks!

**Comment by sonoro1234** [comment] 2016-05-14 06:32
But it is not commited. What should I test?

**Comment by bagong** [comment] 2016-05-14 06:44
Ah, you cannot use the "patch" approach here, right. Well, there are several ways you can download/fetch a PR and use it as branch to build from, or to merge into another branch. My favorite one is documented towards the end (Testing pull-requests) of this page:

    http://supercollider.github.io/development/git-cheat-sheet

Once you've made that additional line to your .git/config, pulling or fetching from the sc repo (not from your fork) will bring in all the pull requests as well. Then you can just treat them as "another" branch...

Is that useful?

**Comment by sonoro1234** [comment] 2016-05-14 07:10
```
C:\SupercolliderRepos\scorig\supercollider\build>cmake  -G"MinGW Makefiles"  -DSUPERNOVA=ON   -DSSE2=ON
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: C:/Qt/Tools/mingw482_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw482_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw482_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw482_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SuperCollider Version: 3.8dev
-- Building from branch , commit hash is
-- Build type defaulting to "RelWithDebInfo"
CMake Error at CMakeLists.txt:61 (add_subdirectory):
  The source directory

    C:/SupercolliderRepos/scorig/supercollider/external_libraries/portaudio_sc_org

  does not contain a CMakeLists.txt file.


-- Compiling with Qt GUI
-- building boost libraries manually
-- using bundled libyaml-cpp
CMake Warning (dev) at external_libraries/hidapi/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

hidapi cmakelists
===windows cmakelists===
===hidapi_parser cmakelists===
-- Found fftw3f: C:/SupercolliderRepos/scorig/x86/fftw/libfftw3f-3.dll
-- Found Sndfile: C:/Program Files/Mega-Nerd/libsndfile/lib/libsndfile-1.lib
-- Audio API: portaudio
-- Found Qt: C:/Qt/5.5/mingw492_32/bin/Qt5Core.dll
-- Building the Qt IDE
-- Configuring incomplete, errors occurred!
See also "C:/SupercolliderRepos/scorig/supercollider/build/CMakeFiles/CMakeOutput.log".
```

**Comment by bagong** [comment] 2016-05-14 07:13
Oh, maybe I should have mentioned: any time you get a new submodule, you must initialize (init) and actually download it (update). These are the two steps:

    git submodule init
    git submodule update

Currently you should see that the folder external_libraries/portaudio_sc_org is still empty. So no CmakeLists.txt and no other files either ;)

**Comment by sonoro1234** [comment] 2016-05-14 07:14
Just did it.
now building.

**Comment by bagong** [comment] 2016-05-14 07:14
Great! Thank you very much!

**Comment by sonoro1234** [comment] 2016-05-14 07:16
I guess my repo is damaged after doing this?
Shall I have to clone again?

**Comment by bagong** [comment] 2016-05-14 07:28
No not at all ;) You mean because of the additional submodule? If you stick to master, you can deinitialize the old submodule by doing (in the sc source root folder):

    submodule deinit external_libraries/portaudio

If you want to clean up more, you can delete the portaudio folder in external_libraries, and you can delete references to that folder by deleting the folder:

    .git/modules/external_libraries/portaudio

If ever you need to go to 3.7, these will be recreated when you initialize the old repo. These steps are not obligatory, it's just to get rid of warnings, and if you like it clean ;)

Sorry for the hassle, but it gives us a shared submodule with various advantages:
- it is based on the new portaudio repo which now uses git (the svn one is now frozen)
- it moves the source repo to supercollider land, which allows the org to maintain it better
- it seperates sc-specific additions into it's own branch, so that it will be easier to manage progress on either the portaudio side or the sc one.

**Comment by bagong** [comment] 2016-05-14 07:42
Btw, I forgot to test this with supernova, So if everything fundamentally works, it would be lovely if you'd have a look at how the DSound api works with it...

And if you want to make sure I did the right thing as to `model.sc`, you should try to build with `SC_QT=OFF`. But what we really want of course is that you have and use a full SC install on your system :D

**Comment by bagong** [comment] 2016-05-14 07:49
And if things look good to you it would be lovely if you'd note that in the PR so that it can be merged quickly. I would like to add more to the Windows build system. First the "server only" build, and later hopefully also a way how to avoid having to move classes and help into the build target folders.

**Comment by sonoro1234** [comment] 2016-05-14 08:04
build seems to work
```
Device options:
  - MME : Asignador de sonido de Microsof - Input   (device #0 with 2 ins 0 outs)
  - MME : Line 1/2 (3- FastTrack Pro)   (device #1 with 2 ins 0 outs)
  - MME : Micrófono (Realtek High Definit   (device #2 with 2 ins 0 outs)
  - MME : Line 3/4 (3- FastTrack Pro)   (device #3 with 2 ins 0 outs)
  - MME : Asignador de sonido de Microsof - Output   (device #4 with 0 ins 2 outs)
  - MME : Line 1/2 (3- FastTrack Pro)   (device #5 with 0 ins 2 outs)
  - MME : Altavoces (Realtek High Definit   (device #6 with 0 ins 6 outs)
  - MME : S/PDIF (3- FastTrack Pro)   (device #7 with 0 ins 2 outs)
  - MME : Realtek Digital Output (Realtek   (device #8 with 0 ins 2 outs)
  - Windows DirectSound : Controlador primario de captura de sonido   (device #9 with 2 ins 0 outs)
  - Windows DirectSound : Line 1/2 (3- FastTrack Pro)   (device #10 with 2 ins 0 outs)
  - Windows DirectSound : Micrófono (Realtek High Definition Audio)   (device #11 with 2 ins 0 outs)
  - Windows DirectSound : Line 3/4 (3- FastTrack Pro)   (device #12 with 2 ins 0 outs)
  - Windows DirectSound : Controlador primario de sonido   (device #13 with 0 ins 2 outs)
  - Windows DirectSound : Line 1/2 (3- FastTrack Pro)   (device #14 with 0 ins 2 outs)
  - Windows DirectSound : Altavoces (Realtek High Definition Audio)   (device #15 with 0 ins 6 outs)
  - Windows DirectSound : S/PDIF (3- FastTrack Pro)   (device #16 with 0 ins 2 outs)
  - Windows DirectSound : Realtek Digital Output (Realtek High Definition Audio)   (device #17 with 0 ins 2 outs)
  - ASIO : Generic Low Latency ASIO Driver   (device #18 with 2 ins 2 outs)
  - ASIO : M-Audio USB ASIO   (device #19 with 4 ins 4 outs)
  - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #20 with 0 ins 6 outs)
  - Windows WDM-KS : Línea de entrada (Realtek HD Audio Line input)   (device #21 with 2 ins 0 outs)
  - Windows WDM-KS : Micrófono (Realtek HD Audio Mic input)   (device #22 with 2 ins 0 outs)
  - Windows WDM-KS : SPDIF Out (Realtek HDA SPDIF Out)   (device #23 with 0 ins 2 outs)
  - Windows WDM-KS : Mezcla estéreo (Realtek HD Audio Stereo input)   (device #24 with 2 ins 0 outs)
  - Windows WDM-KS : Line 1/2 (Fast Track Pro In 1/2)   (device #25 with 2 ins 0 outs)
  - Windows WDM-KS : Line 3/4 (Fast Track Pro In S/PDIF)   (device #26 with 2 ins 0 outs)
  - Windows WDM-KS : Line 1/2 (Fast Track Pro Out 1/2)   (device #27 with 0 ins 2 outs)
  - Windows WDM-KS : S/PDIF 1 (Fast Track Pro Out 3/4)   (device #28 with 0 ins 2 outs)
  - Windows WDM-KS : S/PDIF 2 (Fast Track Pro Out 3/4)   (device #29 with 0 ins 2 outs)

```

**Comment by sonoro1234** [comment] 2016-05-14 08:11
now try SC_QT=OFF

**Comment by sonoro1234** [comment] 2016-05-14 08:14
I am not able to clone my fork:
I only get commits from one year ago and when I pull from remote of supercollider to master I get conflicts.
Any idea?

**Comment by sonoro1234** [comment] 2016-05-14 08:18
Can I delete my fork and do a fresh fork from supercollider?

**Comment by bagong** [comment] 2016-05-14 08:36
I am not sure why you get conflicts. I personally have a strong preference for keeping the SC repo as origin. That makes sure master is always SC...
As to delete your fork: of course it depends on which open work you have there. If you're currently done with all your stuff, it might be a good moment to switch... ;)

**Comment by sonoro1234** [comment] 2016-05-14 08:42
this are supernova audio devices

```
Supernova booting
Available Audio Devices:
0: Asignador de sonido de Microsof - Input (2 inputs, 0 outputs)
1: Line 1/2 (3- FastTrack Pro) (2 inputs, 0 outputs)
2: Micrófono (Realtek High Definit (2 inputs, 0 outputs)
3: Line 3/4 (3- FastTrack Pro) (2 inputs, 0 outputs)
4: Asignador de sonido de Microsof - Output (0 inputs, 2 outputs)
5: Line 1/2 (3- FastTrack Pro) (0 inputs, 2 outputs)
6: Altavoces (Realtek High Definit (0 inputs, 6 outputs)
7: S/PDIF (3- FastTrack Pro) (0 inputs, 2 outputs)
8: Realtek Digital Output (Realtek (0 inputs, 2 outputs)
9: Controlador primario de captura de sonido (2 inputs, 0 outputs)
10: Line 1/2 (3- FastTrack Pro) (2 inputs, 0 outputs)
11: Micrófono (Realtek High Definition Audio) (2 inputs, 0 outputs)
12: Line 3/4 (3- FastTrack Pro) (2 inputs, 0 outputs)
13: Controlador primario de sonido (0 inputs, 2 outputs)
14: Line 1/2 (3- FastTrack Pro) (0 inputs, 2 outputs)
15: Altavoces (Realtek High Definition Audio) (0 inputs, 6 outputs)
16: S/PDIF (3- FastTrack Pro) (0 inputs, 2 outputs)
17: Realtek Digital Output (Realtek High Definition Audio) (0 inputs, 2 outputs)
18: Generic Low Latency ASIO Driver (2 inputs, 2 outputs)
19: M-Audio USB ASIO (4 inputs, 4 outputs)
20: Speakers (Realtek HD Audio output) (0 inputs, 6 outputs)
21: Línea de entrada (Realtek HD Audio Line input) (2 inputs, 0 outputs)
22: Micrófono (Realtek HD Audio Mic input) (2 inputs, 0 outputs)
23: SPDIF Out (Realtek HDA SPDIF Out) (0 inputs, 2 outputs)
24: Mezcla estéreo (Realtek HD Audio Stereo input) (2 inputs, 0 outputs)
25: Line 1/2 (Fast Track Pro In 1/2) (2 inputs, 0 outputs)
26: Line 3/4 (Fast Track Pro In S/PDIF) (2 inputs, 0 outputs)
27: Line 1/2 (Fast Track Pro Out 1/2) (0 inputs, 2 outputs)
28: S/PDIF 1 (Fast Track Pro Out 3/4) (0 inputs, 2 outputs)
29: S/PDIF 2 (Fast Track Pro Out 3/4) (0 inputs, 2 outputs)
```

there is not information about audio api but works

**Comment by sonoro1234** [comment] 2016-05-14 08:43
SC_QT=OFF building works

**Comment by bagong** [comment] 2016-05-14 08:50
Ah, supernova doesn't display the API used. So let's assume it works. If it doesn't we can wait for the day somebody actually uses it. I like your idea of using MinGW DSound mainly because it makes it unnecessary to get hold of an old DirectX version where no official download is available any more.

So thanks a looot for your help, and please add a comment to the PR... Thanks!

**Comment by sonoro1234** [comment] 2016-05-14 08:53
when using directsound tcp conection with server dont works

**Comment by bagong** [comment] 2016-05-14 09:03
Hah, good find! Is that different from how it used to be in the past? Is there a reason to assume is has something to do with the switch of the DSound libs used?

**Comment by bagong** [comment] 2016-05-14 09:09
The 3.7.1 release would tell. It contains supernova and portaudio is built with DSound support. The build used the MS libs (DirectX 7).

**Comment by sonoro1234** [comment] 2016-05-14 09:26
I only use ASIO so I dont know.
Did you tried 3.7.1 release?

**Comment by sonoro1234** [comment] 2016-05-14 09:28
the issue is with directsound for scsynth and supernova

**Comment by bagong** [comment] 2016-05-14 10:31
Would you be so kind to post me test code, then I can try on 3.7.1

**Comment by sonoro1234** [comment] 2016-05-14 10:41
I did test with Lua2SC. with directsound server boot but did not comunicate by TCP in any way (s.quit for eXample)

**Comment by bagong** [comment] 2016-05-14 10:59
If it's just a matter of switching the protocol as in:

   s.options.device = "Windows DirectSound";
   s.options.protocol = \tcp

I can boot and quit the server on both 3.7.2 and master & my PR. Could it be a Lua2SC problem?

**Comment by sonoro1234** [comment] 2016-05-14 11:26
I dont think so because only happens with directsound but I will try with sc-ide later this afternoon

**Comment by bagong** [comment] 2016-05-14 11:40
Thank you!

**Comment by sonoro1234** [comment] 2016-05-14 13:57
There was not fail at all. Only slow to conect (Firewall??)

**Comment by bagong** [comment] 2016-05-14 13:59
Ah, good! Thank you very much for your help!

**Closed** 2016-05-14 14:00 UTC
