### ISSUE TITLE
ide: new document opens at end of list

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2935] opened 2017-06-09 21:03 UTC
This is just a bit inconvenient: when you create a new document, it is located at the end of the list of documents (the rightmost tab), instead of next to the document that had focus. This fragments the open documents. 

Try the same in say Firefox, you'll get the tab next to the current one (this was not always so, but has been like this now for a long time).

**Comment by brianlheim** [comment] 2017-06-09 21:10
Dupe of #2612.

**Closed by brianlheim** 2017-06-09 21:10 UTC
Labels: enhancement, env: SCIDE
