### ISSUE TITLE
Supercollider not scaling on 4K screens

### ISSUE THREAD

**Issue by Hunterwolf88** [supercollider/supercollider#4771] opened 2020-02-19 14:50 UTC
Hello there,
I run Supercollider smoothly on Windows 10 and Ubuntu 18.
Unfortunately there are some graphical issues, many things are not scaling with the system so the GUI is very tiny. This happens on my 4K desktop screen but especially on my smaller laptop screen, where many things are very hard to read.

Basically on both OS's some parts of the GUI ignore the system's scaling factor.

Is this happening only to me? Is there already a fix?

**Comment by patrickdupuis** [comment] 2020-02-19 15:13
What version of SC are you using? There was some work done for high DPI displays back in `3.9`, I believe.

**Comment by dyfer** [comment] 2020-02-19 17:45
I _think_ scaling works consistently only on macOS, and not on Windows (I haven't tried scaling on linux as at the time I tried there was no straightforward way to have non-integer scaling factors). I think this is a valid bug and I don't think there's of a fix ATM.

**Comment by Hunterwolf88** [comment] 2020-02-19 17:49
I'm running the 3.10.4, 64-bit both on Linux and Windows.
The issue is clearly visible in the help browser. You'll get also small buttons for example in the quarks GUI (Open Help, Show classes, Show extension methods, etc) where the font is ok but the button itself is too small cutting off the words.

I solved on Windows with this workaround:
right click on the application icon, "Properties", "Compatibility" tab, "Change DPI settings", check "Override high DPI scaling behavior" and then chose "System". Now everything is scaled correctly but a bit blurry somewhere.

Can't find any similar solution on Linux.

**Comment by jrsurge** [comment] 2020-02-19 19:19
I don't have access to a high dpi monitor, so I can't test this - but in case this helps anyone investigating further:
https://doc.qt.io/qt-5/highdpi.html

**Comment by dyfer** [comment] 2020-02-19 21:29
@jrsurge I don't think you need a high DPI monitor to test this. My experience is from a small (12") HD (1080) screen, that I have set to 125% or 150%. SC does not follow that scaling.

**Comment by jamshark70** [comment] 2020-02-20 00:32
This is probably a duplicate of #2442 ("Windows: Qt doesn't handle high resolution displays well"). Sometime after that, we updated Qt (#3165) but then a user reported that it didn't help (using 3.10.0 at that time).

Probably should continue this under #2442 .

**Comment by dyfer** [comment] 2020-02-20 02:10
good catch @jamshark70 I couldn't find #2442. Let's continue discussion there.

**Closed by dyfer** 2020-02-20 02:10 UTC
Labels: bug
