### ISSUE TITLE
Should all triggers be zero initialized?

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#3649] opened 2018-04-07 13:15 UTC
Shouldn't all UGens with trigger input initialize prevTrig=0 in Ctor so that an initial trig value of 1 can start the triggered action?

EnvGen does it but Poll does not for example.

**Comment by sonoro1234** [comment] 2018-04-07 13:35
Also shouldn´t TriggerControl Ctor be?
```
void TrigControl_Ctor(Unit* unit)
{
	//Print("TrigControl_Ctor\n");
	if (unit->mNumOutputs == 1) {
		SETCALC(TrigControl_next_1);
		TrigControl_next_1(unit, 1);
	} else {
		SETCALC(TrigControl_next_k);
		TrigControl_next_k(unit, 1);
	}
	//ClearUnitOutputs(unit, 1);
}
```

**Comment by sonoro1234** [comment] 2018-04-07 14:04
see:

https://github.com/supercollider/supercollider/commit/f371a5457315f6e02ac3a8714640f4ede7769617

which I cant see in my local repository (I dont know why)

**Comment by jamshark70** [comment] 2018-04-07 14:57
I've made this precise argument at least twice in the last year or two.

**Comment by brianlheim** [comment] 2018-04-07 15:42
Closing as a dupe of #2343. There's more discussion there.

**Closed by brianlheim** 2018-04-07 15:42 UTC
