### ISSUE TITLE
Plugin version mismatch gives uninformative error

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#3305] opened 2017-11-21 15:48 UTC
Just helped a user resolve an issue with a mismatched version of sc3-plugins. She got:

```
*** ERROR: dlopen '/Users/.../Library/Application Support/SuperCollider/Extensions/SC3plugins/AmbisonicUGens.scx' err 'dlopen(/Users/.../Library/Application Support/SuperCollider/Extensions/SC3plugins/AmbisonicUGens.scx, 2): no suitable image found.  Did find:
            /Users/.../Library/Application Support/SuperCollider/Extensions/SC3plugins/AmbisonicUGens.scx: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
            /Users/.../Library/Application Support/SuperCollider/Extensions/SC3plugins/AmbisonicUGens.scx: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
```

Needless to say, this is less than ideally informative. Perhaps a warning to check your plugins are the right version would be helpful for those who haven't memorised the bytes? ;-)

**Comment by brianlheim** [comment] 2017-11-21 16:02
@muellmusik is this with supernova?

**Comment by muellmusik** [comment] 2017-11-21 20:07
scsynth

**Comment by brianlheim** [comment] 2017-11-21 21:38
What OS? What version of SuperCollider? What version of the plugins?

**Comment by brianlheim** [comment] 2017-11-21 21:40
This does not seem like simply a versioning issue to me. This error message would be posted before the version is checked. Perhaps the plugins are meant for a different OS?

**Comment by brianlheim** [comment] 2017-11-21 21:41
Relevant code: 

https://github.com/supercollider/supercollider/blob/develop/server/scsynth/SC_Lib_Cintf.cpp#L348-L352

**Comment by muellmusik** [comment] 2017-11-21 22:26
3.9 beta, OSX.

Don't know version of plugins, but they ended in scx, so shouldn't have been another OS. She tried both downloaded and built from source. I downloaded the 3.9 beta plugins and then was fine.

**Comment by brianlheim** [comment] 2017-11-21 22:36
Here's a SO question related to this: https://stackoverflow.com/questions/1924452/what-can-cause-dlopen-no-suitable-image-found-cant-map

**Comment by brianlheim** [comment] 2017-11-21 22:41
here's a related SO post: https://stackoverflow.com/questions/1924452/what-can-cause-dlopen-no-suitable-image-found-cant-map

I would recommend trying out `file` like that first answer suggests. It sounds like the dylib is in the wrong format somehow.

When I try this out on my system, which is AFAICT the same (except that I don't know how our OS versions compare; I'm on 10.13 beta), I get the expected API version message. So I cannot reproduce or investigate this locally. If you have the problematic file itself somewhere, that could be useful!

**Comment by muellmusik** [comment] 2017-11-22 10:44
Here ya go. I can reproduce with this. 3.9 dev, OS 10.12.16

[AmbisonicUGens.scx.zip](https://github.com/supercollider/supercollider/files/1495590/AmbisonicUGens.scx.zip)

**Comment by muellmusik** [comment] 2017-11-22 10:54
Hmm...

```
file /Users/.../Library/Application\ Support/SuperCollider/Extensions/AmbisonicUGens.scx 
/Users/.../Library/Application Support/SuperCollider/Extensions/AmbisonicUGens.scx: PE32+ executable (DLL) (console) x86-64, for MS Windows
```

Don't know why it's named .scx rather than dll then.

**Comment by brianlheim** [comment] 2017-11-22 16:59
https://github.com/supercollider/sc3-plugins/blob/master/source/CMakeLists.txt#L140-L143

https://github.com/supercollider/supercollider/blob/develop/server/plugins/CMakeLists.txt#L55-L57

scx is used as the extension on windows and macOS. It looks like the wrong file was used by accident.

**Comment by brianlheim** [comment] 2017-11-30 05:06
Closing as user error. Feel free to reopen if you disagree or have an idea for a fix that could avoid this problem in the future.

**Closed by brianlheim** 2017-11-30 05:06 UTC
Labels: comp: scsynth, comp: server plugins
