### ISSUE TITLE
Windows: Serial port support

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2461] opened 2016-11-01 11:32 UTC
Just to have it over here among the issues...

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/SerialPort-on-Windows-td7601337.html

**Comment by brianlheim** [comment] 2017-09-22 17:52
See also report in #3200.

**Comment by brianlheim** [comment] 2017-12-05 02:34
This is close enough to be a dupe of #1008, closing.

**Closed by brianlheim** 2017-12-05 02:34 UTC
Labels: os: Windows
