### ISSUE TITLE
Help Browser keeps sending request

### ISSUE THREAD

**Issue by yavuzburuk** [supercollider/supercollider#4308] opened 2019-02-15 08:01 UTC
## Environment

* SuperCollider version: 3.10.0 and 3.9.3
* Operating system: Windows 10
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

I have downloaded first SuperCollider version 3.10.0 and then 3.9.3. I have installed it. The Help Browser windows says "Sending Request". And I can't run any single script in IDE. The SuperCollider doesn't function.

```supercollider
2+2
```

## Expected vs. actual behavior

The SuperCollider functions.

**Comment by brianlheim** [comment] 2019-02-16 12:13
Duplicate of issues in #1390 and #908.

**Closed** 2019-02-16 12:14 UTC
Labels: bug
