### ISSUE TITLE
ScIDE shortcuts under certain circumstances not working

### ISSUE THREAD

**Issue by nuss** [supercollider/supercollider#2535] opened 2016-12-05 23:19 UTC
I have some class for which I have several branches in a github repo. Just now I cherry-picked some changes from one branch to the other and had a conflict afterwards. So far, so good. After I had fixed the conflicts I recompiled the classlib and wanted to boot the server with ctrl + b (Linux) and got the following error:
```
ERROR: Message 'boot' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError   0x5e1c5b8
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x23db978
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x5e20398
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x5e38f28
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x5e299b8
		arg this = nil
		arg selector = 'boot'
		arg args = [*0]
	Process:interpretCmdLine   0x1c61c08
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'boot' not understood.
RECEIVER: nil
```
I then tried to look up ```Object``` by hitting ctrl + i. The window appeared but no class was found. I've observed this now twice, reliably after having a conflict in some class, fixing it and recompiling. As already mentioned, I'm on Linux. Currently I'm using SC 3.9dev.

**Comment by gusano** [comment] 2016-12-06 11:06
@nuss AFAICS this is not necessarily shortcut related.. What happens if you switch back to master branch and try again? Could it be that your classes introduce some kind of "mess" (Extension-wise)?

**Comment by nuss** [comment] 2016-12-06 12:46
@gusano I am on master. I don't know if my classes introduce some kind of "mess" (so far I haven't observed anything like that and my classes resp. the branches of my repo have already been around for some time...). However, I just tried to replicate that shortcuts behaviour by introducing some error, compiling, fixing the error again, then recompiling... nada. Everything fine. Possibly it's somehow related to Git resp. switching branches while the IDE is running. Usually I get a notice that an open file has changed, asking if it should be reloaded. So far I've relied on that. Maybe this doesn't always work as advertised? Don't know. I'll keep an eye on it...

**Comment by gusano** [comment] 2016-12-06 13:45
@nuss Oh I see what you mean now, the issue title is misleading.
I would expect weird behaviour when switching branches with the IDE open TBH.

**Comment by nuss** [comment] 2016-12-06 14:01
@gusano yeah, the issue title is possibly misleading. However, I haven't experienced something like this before - when switching branches while documents belonging to the repo whose branch had just been switched. To me it seems like ScIDE is (or should be) set up to react properly in those cases...

**Comment by gusano** [comment] 2016-12-06 14:03
@nuss It would be great to have a reproducer.

**Comment by brianlheim** [comment] 2017-05-15 17:36
I'm closing this due to lack of information. @nuss If you can come up with a reliable reproducer, we can reopen. :)

**Closed by brianlheim** 2017-05-15 17:36 UTC
Labels: bug, env: SCIDE
