### ISSUE TITLE
Cannot invoke `sclang &`

### ISSUE THREAD

**Issue by kalwalt** [supercollider/supercollider#1053] opened 2014-03-08 20:47 UTC
i have this script normally works well in linux64 bit>

```
# /bin/sh
# !/usr/local/bin/

sclang ecotopiaofart.scd &
# /home/odroid/Desktop/ecotopia/bin/ecotopia
```

i receive in terminal>

> SC FFT global init: cosTable initialised.
> terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::system::system_error >'
>   what():  assign: Operation not permitted

instead sclang may run successfully from terminal.

i am using ubuntu 13.10 and latest supercollider with OdroidU3., scide interface works good, no issue at all..

**Comment by vivid-synth** [comment] 2016-08-01 18:09
@kalwalt it looks like that script is only running the one line, namely:

```
sclang ecotopiaofart.scd &
```

What is the other application that you're running which communicates with SC? Do you mind sharing code?

**Comment by dvarrazzo** [comment] 2017-01-17 23:16
FYI, bug #2655 has everything needed to reproduce the problem

Is there any known workaround?

**Comment by vivid-synth** [comment] 2017-01-17 23:19
Closing, and reopening https://github.com/supercollider/supercollider/issues/2655 as it's a clearer reproducer

**Closed by vivid-synth** 2017-01-17 23:19 UTC
Labels: bug, os: Linux, waiting for information

**Comment by kalwalt** [comment] 2017-01-19 13:26
Sorry for the delay! To @vivid-synth : you can find my code here https://github.com/kalwalt/Ecotopia-of-art but that script invoking sclang serves only to start the all applications at the startup launch of the OS:  That was my thesis works for an interactive art installation, Hope that this can help... and seems  https://github.com/supercollider/supercollider/issues/2655 is similar
