### ISSUE TITLE
evaluating code in the help browser evaluates code in the document window instead

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1532] opened 2015-06-09 21:04 UTC
… that says it all. 

Reproducer: open any helpfile and evaluate code there. Instead of running the selected line, it is the current line in the currently open document.

**Comment by bagong** [comment] 2015-06-09 22:27
Yea, there is an issue for this already somewhere. Using shift-enter evaluates the code in the help-document, if I remember correctly.

**Comment by gusano** [comment] 2015-06-09 22:31
Duplicate of #1385. Closing.

**Closed by gusano** 2015-06-09 22:31 UTC
Labels: bug, comp: SCDoc, os: Mac OS X
