### ISSUE TITLE
<>> and <<> operators inside SynthDefs? 

### ISSUE THREAD

**Issue by smoge** [supercollider/supercollider#2812] opened 2017-03-23 01:32 UTC
Just an idea. Worth implementing? It looks very idiomatic to sclang...

(Sorry if that's not the right place)

```supercollider
// instead of:
{
    var snd;
    snd = PinkNoise.ar;
    snd = BPF.ar(snd, 800);
    Pan2.ar(snd, SinOsc.kr(3.2));
}.play

// this:
{ Pan2.ar(_, SinOsc.kr(3.2)) <<> BPF.ar(_, 1000) <<> PinkNoise.ar }.play

// or this:
{ PinkNoise.ar <>> BPF.ar(_, 1000) <>> Pan2.ar( _, SinOsc.kr(3.2)) }.play

// or both:
{
    var in = SoundIn.ar([0]);
    var fx = SinOsc.ar * _ <>> BPF.ar(_, 1000);
    var reverb = GVerb.ar(_);
    Out.ar(0,_!2) <<> reverb <<> fx <<> in ;
}.play

```

**Comment by snappizz** [comment] 2017-03-23 01:54
I've also had this idea, since I tend to write a lot of synthdefs that look like `snd = Saw.ar; snd = DelayN.ar(snd); snd = LPF.ar(snd); snd = snd * Env.perc.ar`, etc. I'm concerned about the `_` notation though, since it has some known design quirks that we don't really know how to deal with ([and outright bugs](https://github.com/supercollider/supercollider/issues/2800)).

**Comment by brianlheim** [comment] 2017-03-23 01:58
> (Sorry if that's not the right place)

If you want to get a lot of feedback, sending it to the mailing lists first/as well seems to do a lot of good for initial proposals. Nothing wrong with posting it here though.

**Comment by smoge** [comment] 2017-03-23 02:06
One more reason to fix it? :-) Writing it as "normal" functions would make less sense I guess.

**Comment by jamshark70** [comment] 2017-03-23 05:05
It's an interesting idea, but IMO #2295 (Qt GUI: WebView: .onLinkActivated doesn't fire) should be much, much higher priority.

But, if anyone is brave enough to tackle this -- here's a pretty common SynthDef case for me:

```
SynthDef(\summat, { |out, freq = 440, detun = 1.007, ...|
	var osc = Mix(Saw.ar(freq * [1, detun]));
	...
}).add
```

... which might turn into:

```
	[\freq.kr, \detun.kr] <>> Saw.ar(_ * [1, _]) <>> Mix()
```

Thinking through the way `_` works currently... that one line of code contains enough code that a/ if you crack it, you'll be almost all the way there, and b/ if you don't, the idea is doomed.

I'm not touching this one... my existing code libraries have enough problems already :rofl:

> One more reason to fix it?

Ah, optimism... the problem is, how do you determine, unambiguously, the scope of the closure created by a `_`? In `Saw.ar(_ * [1, _])` above, there's:

- `[1, _]` = `Array.new(2).add(1).add(theInterpreterThingForUnderscore)
- `1 * [1, _]`
- `Saw.ar(_ * [1, _])`

The compiler will have to "clump" the new-array, `*` and `ar` operations into a unit -- because the argument values from `<>>` need to go to the entire closure -- *and* understand that `<>>` should *not* be subject to this because it delimits UGen "chunks" (and we have to be totally sure that no operator could ever be ambiguous, that is, should "clump" sometimes but not at other times -- and remember, the compiler has *no* access to the types of the operands unless they are literals).

I have the feeling, when you really think through the complications, you might end up with the conclusion that it isn't fixable.

**Comment by gusano** [comment] 2017-03-23 05:15
I agree with @jamshark70 about priorities but since we're just discussing...
This might be a good candidate for sc-4! :)

**Comment by scztt** [comment] 2017-03-23 05:27
This actually works right now, only with a different operator:
```
{
	SinOsc.ar(_) <> LFNoise2.kr(10).range(400, 600)
}.play;
```
It works as a leftward function composition, returning a new function that passes the right hand side into the left hand side as the first argument. - it effectively returns `{ Saw.ar(LFSaw.ar(10).range(400, 600)) }`. Ugens are functions, so the operator works, and it's generally acceptable to use a function in place of a UGen in a SynthDef context.

It's exactly as useful for simple cases as smoge suggests, and exactly as confusing for non-simple cases as jamshark suggests. :)

**Comment by smoge** [comment] 2017-03-23 05:30
Exactly! :) Thanks

**Comment by scztt** [comment] 2017-03-23 05:30
I think the `<<>` and `<>>` operators are a marked improvement over the existing `<>`, since they indicate the direction. It's hard to remember which way you're composing functions with `<>`, even if you use it all the time.... I'd vote for adding those operators for general composition for clarity.

**Comment by smoge** [comment] 2017-03-23 05:36
I agree, if we go to the bottom of it, it's a nest of surprises. But we're just talking, no hard work is being done yet. Yea, well `<<>` still needs to be implemented. I guess function composition is trickier in the other direction in sclang, isn't it? `h = f.(g)` works in a limited way, since the `f` is never really re-evaluated.

**Comment by scztt** [comment] 2017-03-23 05:45
I think this would be all that's required 
(where `<<>` is just the existing `<>`):
```
+AbstractFunction {
	<<> { arg that;
		^{|...args| this.value(that.value(*args)) }
	}
	<>> { arg that;
		^{|...args| that.value(this.value(*args)) }
	}
}
```

**Comment by smoge** [comment] 2017-03-23 05:55
Yes, I tried something very similar here :) Works for the simple cases, I also think that's already an improvement :)

**Comment by smoge** [comment] 2017-03-23 06:19
@scztt even if one is not using ugens, that's an improvement in general, even with 'normal' functions...

```
f = (2*_+3) <>> ( _**2) 
g = (2*_+3) <<> ( _* 2)
f != g
```

**Comment by telephon** [comment] 2017-03-23 07:32
The two operators work on the supposition that you have a system of NodeProxies. You need to be careful how these interact. See http://supercollider2010.de/images/papers/signal_operators.pdf

**Comment by jamshark70** [comment] 2017-03-23 07:51
> I think this would be all that's required
> (where <<> is just the existing <>):
> 
> ```
> +AbstractFunction {
> 	<<> { arg that;
> 		^{|...args| this.value(that.value(*args)) }
> 	}
> 	<>> { arg that;
> 		^{|...args| that.value(this.value(*args)) }
> 	}
> }
> ```

But that would fail my case:

```
Saw.ar(_ * [1, _])

// you think it will do:
Saw.ar({ |a, b| a * [1, b] })

// but you have *two* partial applications, it's more like this:
Saw.ar(
    { |a| a * { |a| [1, a] } }
)
```

The problem is, there is only one arg list `*args` and nothing to distribute the first arg to the first function-operand and so on.

```
(_ * [1, _]).value(2, 3)
-> a BinaryOpFunction

(_ * [1, _]).value(2, 3).value(2, 3)
-> [2, 4]
```

But the desired result would be `[2, 6]`.

Don't underestimate how blastedly hard this is going to be.

**Comment by smoge** [comment] 2017-03-23 08:29
@jamshark70  True, it would require a  smarter compiler or some syntax change

**Comment by muellmusik** [comment] 2017-03-23 08:43
No specific comments on this, but one general one:

Over the years sclang has become almost Perl-like in its proliferation of multiple ways to do the same thing. Many of these were added despite no tangible advantages, even in terms of keystrokes, and are merely down to taste. It's thus important to carefully weigh the benefits and costs of adding and/or promoting an alternate syntax. These have costs in maintenance, complexity, and in making SC substantially harder to learn and (though it's not everyone's problem) to teach. These are real issues, though often ignored in the enthusiasm for a cool new way to express something.

That's not to say it's never worth it, but make sure it is.

**Comment by telephon** [comment] 2017-03-23 11:15
Let's first fix the partial application issues before finding more ways to use (and thereby proliferate) them.

**Comment by brianlheim** [comment] 2017-03-23 12:35
I agree with @muellmusik on the cost (learning, teaching, and maintaining) of new syntax. I spent 3 years working with supercollider before I learned about list comprehension; I still don't use it even now...

I vote to close this and focus discussion/effort on issues with existing features and syntax.

**Comment by snappizz** [comment] 2017-03-23 16:18
This idea is complex in implementation and needs more time on the drawing board before it is productive to discuss it. In the meantime, it can be developed in a quark.

**Closed by snappizz** 2017-03-23 16:18 UTC
Labels: comp: class library, enhancement

**Comment by smoge** [comment] 2017-03-23 20:31
The problem is not much with the operators. It has to do how `_` works.  It only works with one argument functions. One could enhance `_`-notation with a delimiter,  an available character used to specify the boundaries of the function. 

```
[a,b] <>> `Saw.ar(_ * [1, _])` 
```

**Comment by telephon** [comment] 2017-03-23 20:56
Yes, @smoge we have been discussing since the `_` was introduced. Back then, James McCartney deliberately kept it simple. Still, there are ways to improve this and we have  #2800.

**Comment by snappizz** [comment] 2017-03-23 21:00
I should clarify that I support this proposal and I think it would be very nice, but it's too low priority. Its utility depends on a well-designed and properly functioning `_`, which is not important to the project right now.

**Comment by jamshark70** [comment] 2017-03-24 00:14
> The problem is not much with the operators. It has to do how _ works. It only works with a one-argument function.

Not exactly. It only works to create a function containing a single method call. Multiple operands / arguments are perfectly fine: `_ + _` does what you would expect, but `_.rand * 2` does not (despite the single occurrence of `_`).

Also, as was recently discovered, it doesn't work with keyword arguments.
