### ISSUE TITLE
SoundFileView does not display selection

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#2176] opened 2016-06-11 06:47 UTC
Submitter: Martin Schuetz
Email: martin-schuetz@t-online.de
SuperCollider 3.8dev, Qt version 5.5.1
SoundFileView does not show selection, the background seems to be 'overpainted'.
it can be reproduced with the HelpFile Step by step examples.
the a.zoom(0.2) line show parts of the view correctly.

**Comment by snappizz** [comment] 2016-08-07 17:56
Can reproduce:

    (
    w = Window.new;
    a = SoundFileView(w);
    w.front;

    f = SoundFile.new;
    f.openRead(Platform.resourceDir +/+ "sounds/a11wlk01.wav");

    a.soundfile = f;
    a.read(0, f.numFrames);
    )

**Comment by snappizz** [comment] 2017-04-15 01:02
dupe of #2033

**Closed by snappizz** 2017-04-15 01:02 UTC
Labels: bug, comp: Qt GUI, gitreports
