### ISSUE TITLE
ERROR: Primitive '_ServerShmInterface_connectSharedMem' 

### ISSUE THREAD

**Issue by ericlyon** [supercollider/supercollider#3070] opened 2017-07-29 18:55 UTC
Please see the following thread for more details:
https://www.listarc.bham.ac.uk/lists/sc-users/msg56556.html

ISSUE:

The following code sporadically produces the following error, on a range of Mac hardware, for unknown reasons:

CODE:

`s.boot`

ERROR:

```
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 512
SuperCollider 3 server ready.
Receiving notification messages from server localhost
Cannot connect to shared memory: No such file or directory
ERROR: Primitive '_ServerShmInterface_connectSharedMem' failed.
Failed.
RECEIVER:
Instance of ServerShmInterface {    (0x1218c45e8, gc=60, fmt=00, flg=00, set=02)
  instance variables [2]
    ptr : nil
    finalizer : nil
}

PROTECTED CALL STACK:
	Meta_MethodError:new	0x1198be7c0
		arg this = PrimitiveFailedError
		arg what = Failed.
		arg receiver = a ServerShmInterface
	Meta_PrimitiveFailedError:new	0x1198c5d00
		arg this = PrimitiveFailedError
		arg receiver = a ServerShmInterface
	Object:primitiveFailed	0x119522e40
		arg this = a ServerShmInterface
	a FunctionDef	0x11a435300
		sourceCode = "<an open Function>"
	Routine:prStart	0x119f043c0
		arg this = a Routine
		arg inval = 728.529802017

CALL STACK:
	MethodError:reportError   0x120d72fd8
		arg this = <instance of PrimitiveFailedError>
	< closed FunctionDef >   0x119451388
		arg error = <instance of PrimitiveFailedError>
	Integer:forBy   0x12103e708
		arg this = 0
		arg endval = 0
		arg stepval = 2
		arg function = <instance of Function>
		var i = 0
		var j = 0
	SequenceableCollection:pairsDo   0x120bf0208
		arg this = [*2]
		arg function = <instance of Function>
	Scheduler:seconds_   0x120d7cd48
		arg this = <instance of Scheduler>
		arg newSeconds = 729.335527321
	Meta_AppClock:tick   0x121945668
		arg this = <instance of Meta_AppClock>
		var saveClock = <instance of Meta_SystemClock>
	Process:tick   0x12193f0c8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_ServerShmInterface_connectSharedMem' failed.
Failed.
RECEIVER: a ServerShmInterface
```

**Comment by ericlyon** [comment] 2017-07-29 18:57
This thread is different from:
https://github.com/supercollider/supercollider/issues/2488

**Comment by telephon** [comment] 2017-07-30 14:51
Which version are you using?

**Comment by telephon** [comment] 2017-07-30 15:21
ah I see, you wrote:


>Current Mac version 3.8.0, downloaded from:

>http://supercollider.github.io/download

I think this is fixed in the current master.

**Comment by telephon** [comment] 2017-07-30 15:22
Can you please try http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/master-latest.html

and see if the problem is resolved?

**Comment by ericlyon** [comment] 2017-07-30 18:12
Thanks, I shall give it a try.

Eric

On Sun, Jul 30, 2017 at 11:22 AM, Julian Rohrhuber <notifications@github.com

**Comment by telephon** [comment] 2017-07-31 16:18
holaglen wrote this reproducer:

```
s.options.sampleRate = 44100;

// Now run this line repeatedly with a pause between... it fails on lots of attempts, maybe about 5 out of 10 on average:
s.reboot;

// Now stop explicitly setting a sampleRate:
s.options.sampleRate = nil;

// Now run the same line repeatedly... for me it boots 100% of the time:
s.reboot;
```
 I can't reproduce on macos 10.11 on the latest build.

**Comment by joshpar** [comment] 2017-08-21 19:00
@ericlyon - what system are you on?

**Comment by ericlyon** [comment] 2017-08-21 19:02
macOS Sierra 10.12.6. iMac 27in late 2013.

**Comment by brianlheim** [comment] 2019-08-15 04:29
Stale, please reopen if there is more info to act on

**Closed by brianlheim** 2019-08-15 04:29 UTC
Labels: bug, comp: scsynth, os: macOS, waiting for information
