### ISSUE TITLE
~/.config/SuperCollider never created

### ISSUE THREAD

**Issue by bretgourdie** [supercollider/supercollider#2919] opened 2017-06-04 18:37 UTC
After I installed any quarks and recompiled my class library, the installed quarks would never be loaded.

It turns out that I was missing the `~/.config/SuperCollider` folder and consequently the `startup.scd` and `sclang_conf.yaml` files. Once I created the missing folder, the `sclang_conf.yaml` file was created which had the include paths pointing to my downloaded quarks. This issue is no longer a problem for me but I imagine it may pop up for someone else.

I built the Release version of SuperCollider 3.8 on Linux Mint 18 Sarah. Did the `sudo make install` and `sudo ldconfig` after installing. Wouldn't be surprised if I missed a step but I pretty much followed the `README_Linux.md` file.

**Comment by redFrik** [comment] 2018-01-30 11:43
just a ping on this.  i can confirm it's still an issue under debian and 3.9.x.  will add a `mkdir -p .config/SuperCollider` line to rpi and bbb build instructions until this is resolved.

a temporary fix for the Quarks class could be to post a warning if the directory isn't found. now it looks like it is installing fine even though the paths never are added to the yaml file...
```
sc3> Quarks.install("redSys")
Installing redSys
Installing TabbedView
Adding path: /home/debian/.local/share/SuperCollider/downloaded-quarks/TabbedView
TabbedView installed
Adding path: /home/debian/.local/share/SuperCollider/downloaded-quarks/redSys
redSys installed
-> Quark: redSys[0.5]
```

**Comment by gusano** [comment] 2018-01-30 11:58
Wasn't it been taken care of by #3469 ?

**Comment by redFrik** [comment] 2018-01-30 12:07
i believe that was for the Extensions folder - this one is for missing .config/SuperCollider. at least here on debian stretch it is still a problem. and i did build with `git checkout 3.9`.

**Comment by brianlheim** [comment] 2018-01-30 13:48
@redFrik FYI, saying what branch you built from is meaningless, the head will move as PRs are merged. I'm assuming in this instance you mean 3.9 after #3469 was merged, but to be clear you should give the SHA of the commit or a tag name.

I can look into this, I forget how the default directory layout works for SC on Linux so not sure exactly which step is going wrong. Is it possible ~/.config doesn't have user write permissions? That's the only thing I can think of at the moment but it seems ridiculous to me.

**Comment by redFrik** [comment] 2018-01-30 13:59
ok, by 3.9 branch i meant latest (current as of writing) commit in that branch. 774c809fc89a728eadbf062f494266afdaa7e07b
thanks for putting up with my git confusion.
anyways, permissions shouldn't be the problem i think.  but .config/ doesn't exist to begin with.  perhaps that's a clue.

**Comment by brianlheim** [comment] 2018-01-30 14:08
> .config/ doesn't exist to begin with. perhaps that's a clue.

Good to know, thanks!

**Comment by redFrik** [comment] 2018-01-31 20:02
figured out that `LanguageConfig.store` does not work under my debian linux. no yaml file is created when the .config/SuperCollider/ directory doesn't already exist.

one can test this by trying to write a config file to some other non-existing folder `LanguageConfig.store("/home/me/bogous/sclang.yaml")`, and compare that to giving it an existing folder (which works fine).

to fix it i propose something like this...
```
diff --git a/lang/LangSource/SC_LanguageConfig.cpp b/lang/LangSource/SC_LanguageConfig.cpp
index 6966d93a2..2710835e4 100644
--- a/lang/LangSource/SC_LanguageConfig.cpp
+++ b/lang/LangSource/SC_LanguageConfig.cpp
@@ -190,6 +190,10 @@ bool SC_LanguageConfig::writeLibraryConfigYAML(const Path& fileName)

        out << EndMap;

+       bfs::path dir(fileName.parent_path());
+       if(!(bfs::exists(dir)))
+               if (bfs::create_directories(dir))
+                       postfl("Created directory: %s\n", dir.c_str());
        bfs::ofstream fout(fileName);
        fout << out.c_str();
        return true;
```

but probably needs refinement and must be tested more under different operating systems.

**Comment by redFrik** [comment] 2018-02-01 17:03
a variant on this fix is to only post if create_directories fail.
```
bfs::path dir(fileName.parent_path());
if(!(bfs::exists(dir)))
        if(!(bfs::create_directories(dir)))
                postfl("Warning - could not create directory: %s\n", dir.c_str());
```
better i think.

**Comment by redFrik** [comment] 2018-02-10 11:58
more updates on this issue: it happens when you run sclang headless and/or never have started scide. so basically the readline interface can't install Quarks without a .config/SuperCollider/ directory while scide can. ubuntu also affected. shall i put in a PR for this?

**Comment by brianlheim** [comment] 2018-02-10 16:00
> shall i put in a PR for this?

Sure. sclang should create the config directory during startup. no warning/error messages needed IMO. Not sure where the best spot would be to put that call, startup is a little scattered. I think when I was working on #3469 I had initially tried placing that right before compilation started, I think in `compileLibrary` in `PyrLexer.cpp`

**Comment by jamshark70** [comment] 2018-02-10 21:16
Could it not simply be just before writing the language config file?

Installing quarks adds to includePaths and saves the config to disk. I think that would be the place to do it.

(Sclang doesn't have any other config files, right?)

**Comment by redFrik** [comment] 2018-02-10 22:07
i'd be happy with a simple warning or even an error for now.  both are better than to print out that the quark installed successfully.  linux users know how to `mkdir`.

also `LanguageConfig.store("/Users/me/bogous/sclang.yaml")`on macos sc3.9.1 doesn't create a directory while `123.writeArchive("/Users/me/bogous/sclang.yaml")` errors.  so just adding a warning for .store would take care of all the issues no?

things are more complicated though... what happens when you want to make a self contained standalone and always start it from a script passing in a yaml config file.  in this case i think sclang shouldn't touch ~./config and create a SuperCollider directory there.  so i'm with @jamshark70 here and the directory only needs to be written when one tries to `LanguageConfig.store` to the default location and haven't gotten a dir there already (which is exactly what Quarks.install on a fresh linux system does).

**Comment by brianlheim** [comment] 2018-02-10 22:36
> also LanguageConfig.store("/Users/me/bogous/sclang.yaml")on macos sc3.9.1 doesn't create a directory while 123.writeArchive("/Users/me/bogous/sclang.yaml") errors.

That's my point - changing the behavior of `store` to silently create directories when the file doesn't exist is inconsistent.

> so just adding a warning for .store would take care of all the issues no?

An error makes more sense to me, since the function failed to complete its only purpose.

> what happens when you want to make a self contained standalone and always start it from a script passing in a yaml config file. in this case i think sclang shouldn't touch ~./config and create a SuperCollider directory there.

Is there any problem if the directory _is_ created? Should it be named something else in that case? I'm not sure I understand, sorry. It sounds like if this is really a problem we could condition the creation of the directory based on whether or not the `-a` (standalone) flag is passed.

I think it's most natural for an application to create on startup all the directories it might need to work in. Creating the directory in `store` might make sense now, but if/when another config file asset is added, it's going to seem strange that the config directory being created depends on a method call that may or may not happen in a given run of the application. In effect we'll have to solve the same problem again.

**Comment by jamshark70** [comment] 2018-02-11 01:51
I'd be happy with creating the directory on sclang startup, except for standalone usage.

I have an aversion toward creating things in the filesystem unless we are definitely going to use them. Say I ran somebody's standalone one time, and later found that it created a config directory and the directory was empty, I'd think SC's programmers were a bit careless, creating something "just in case" and not cleaning up empty locations. But if I found that it left a file with actual content in it, that would make sense to me.

But that's not an absolute rule for me, just a preference. I won't object strenuously.

**Comment by redFrik** [comment] 2018-02-24 09:06
seems like this issue needs more discussion.  meanwhile #3535 is a stop-gap fix so that at the very least a warning is posted.

**Comment by brianlheim** [comment] 2018-02-24 15:06
@redFrik is there anything in particular you feel needs discussing? I think we've agreed on what a good solution would look like in the last couple messages, and the concerns you raised earlier re standalones were also addressed. We haven't ssettled on one exact solution, but I think a PR could be made now that would be acceptable to everyone in this conversation.

**Closed** 2018-03-16 14:26 UTC
Labels: bug, comp: class library
