### ISSUE TITLE
Server will not boot

### ISSUE THREAD

**Issue by supercollider22** [supercollider/supercollider#3644] opened 2018-04-06 23:05 UTC
Bug description:
I try to boot the server, and get this message:
Exception in World_New: boost::interprocess::intermodule_singleton initialization failed
RESULT = -1073740791

it was working great yesterday
Steps to reproduce:
1.
2.
3.

Actual result:

Expected result:

**Comment by patrickdupuis** [comment] 2018-04-06 23:07
What OS and version of SC are you using?

**Comment by brianlheim** [comment] 2018-04-06 23:34
Dupe of #2409; please add more details there if you have them, @supercollider22 !

**Closed by brianlheim** 2018-04-06 23:34 UTC
