### ISSUE TITLE
Negative quant isn't working properly

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#5949] opened 2023-01-17 05:34 UTC
Quant documentation says about the quant parameter "If negative, it indicates the number of bars in the future to schedule" and the implementation is broken because there are many values that are multiples of beatsPerBar when rounded up:

https://github.com/supercollider/supercollider/blob/2e7c222ca12237c00ef5dd6a74f22c18fd24c71c/SCClassLibrary/Common/Core/Clock.sc#L309-L311

Example:

referenceBeat = 170.0
quant = 8
roundup(referenceBeat, quant)
-> 176

referenceBeat = 170.0
quant = 16
roundup(referenceBeat, quant)
-> 176

~In fact, I think quant is broken as a whole because of that, first it says "The routine will begin on the next integer multiple of *this number* after the baseBarBeat". It will break for any multiple of quant.~

**Comment by smrg-lm** [comment] 2023-01-17 06:28
I started to look a this because someone told me that never understood how quant works. Now trying to make sense of this out loud.

"quant: Quantization granularity. The routine will begin on the next integer multiple of this number after the baseBarBeat".

that is mathematically ok, the next multiple of quant >= referenceBeat - baseBarBeat but doesn't make much sense to allow many different multiples if quant is supposed to be the size of a measure or a time unit relative to referenceBeat and/or beatsPerBar, and it gives away a bit by what it says when quant is negative. In any case I think this isn't metrically meaningful for music as is because referenceBeat - baseBarBeat is a constantly increasing number the user code doesn't know about when scheduling a routine.

**Comment by smrg-lm** [comment] 2023-01-20 08:13
Except for the -quant value as described in the documentation it's working fine.

The documentation is a bit difficult to digest, despite having possible values as examples. I don’t know if I will be able to improve it because I don't have much time and my clone is outdated and dirty. Here is something I wrote as a resume trying to make emphasis on the key concepts, but it’s still a reference based on SC documentation and implementation:

Using `Quant` routines can be scheduled to the next beat or bar of the running clock. For example, to schedule a routine to the next beat use `Quant(1)` or, to schedule it to the next bar of the running clock use `Quant(clock.beats_per_bar)`.

To schedule a routine to a specific beat or fraction within a bar use the `phase` argument. If `phase` is positive the routine will be scheduled to the specified beat of the next bar and if `phase` is negative it will be scheduled to the next specified beat within the current or next bar depending on whether the current beat is before or after the specified beat.

Setting the `quant` argument to zero avoids quantization.

To set the quantization guaranties `logical time` synchronicity between routines running in the same `TempoClock`.

Quantization rounds a reference beat to the next integer multiple of `quant`. It is related to the clock’s bar (meter) changes but isn’t clear to make a reference to `baseBarBeat` because that’s an implementation detail. It could be more clear to refer to the clock’s last meter change, it count’s the number of beats since then to make the rounding.

**Comment by jamshark70** [comment] 2023-02-09 08:37
Quant has been working fine for a long long time.

```
referenceBeat = 170.0
quant = 8
roundup(referenceBeat, quant)
-> 176

referenceBeat = 170.0
quant = 16
roundup(referenceBeat, quant)
-> 176
```

These are both correct.

**Comment by smrg-lm** [comment] 2023-02-14 00:50
I understand how it works but it doesn't seem to be meaningful for musical meter and that's the source of confusion. The problem I saw (to change the implementation is out of discussion, of course)  is that `"next multiple of x"`  starts counting from an arbitrary number not known by the user, it's zero by default but the user code misses the count and it can be changed at any time, so it's easy to change the beats per bar at a decimal part and mess up the reference/counting. Then the documentation says "If negative, it indicates the number of bars in the future to schedule (where the bar length is taken from the clock's beatsPerBar variable)", and I read that the next numbers of bars is implicitly a grouping of the current time signature as in music. A common thought might be "-1 is the next bar, -2 is the next bar plus one more bar, -3 is the next bar plus 2 more bars and so on", but it is not, it's just a multiple of a number counting from another number.

**Comment by smrg-lm** [comment] 2023-02-14 01:00
Something interesting is how Tidal uses time fractions to quantize relative to the current beat. In case someone is interested [here](https://github.com/tidalcycles/vortex/blob/main/doc/Documentation_Part_1.ipynb) is a simple explanation.

**Comment by jamshark70** [comment] 2023-02-20 10:33
> The problem I saw (to change the implementation is out of discussion, of course) is that "next multiple of x" starts counting from an arbitrary number not known by the user

It starts counting from the beat-value of the last meter change.

Consider if you set the meter to 3/4 at beat 16. Then the barlines should be 16, 19, 22, 25 etc. and *not* 15, 18, 21, 24. It's emphatically wrong to count from 0 here. The only correct behavior is to count from the moment of the last meter change.

> it's zero by default but the user code misses the count and it can be changed at any time

It should only be changed when changing meter, and only at a barline. If users are messing around with baseBarBeat arbitrarily without understanding what they're doing, I get what you're saying but that is not a reason to break meter changes. (If the documentation doesn't make the understanding clear, it's a good idea to improve the documentation -- but again, JMc's formula is well-thought-out and changing it would be almost certainly a regression.)

> so it's easy to change the beats per bar at a decimal part and mess up the reference/counting.

It is [documented](https://doc.sccode.org/Classes/TempoClock.html#-beatsPerBar): "Setting beatsPerBar also updates the barline reference (baseBarBeat). Be careful to call beatsPerBar_ only on a barline ([-nextBar](https://doc.sccode.org/Classes/TempoClock.html#-nextBar) below)." And there's an example illustrating how to do that.

`.setMeterAtBeat` should in general be avoided. That isn't documented currently but it should be.

> Something interesting is how Tidal uses time fractions to quantize relative to the current beat time unit.

It is possible to implement alternate Quant classes -- implement `asQuant` and `nextTimeOnGrid`.

**Comment by JordanHendersonMusic** [comment] 2024-05-05 16:33
Closing because this is a misunderstanding of how quant work, feel free to move this discussion to a forum, a dedicated discussion, or an RFC if you think it should be changed.

**Closed by JordanHendersonMusic** 2024-05-05 16:33 UTC
