### ISSUE TITLE
In Ubuntu Unity (16.04 or 16.10) about half of the keyboard shortcuts don't work

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2785] opened 2017-03-11 13:07 UTC
Among them ctrl-., save-, open-document and much more. Interestingly most of the language-shortcuts work. Most shortcuts defined in main_window.cpp do not work, and some defined in multi_editor.cpp don't work either.

Different observations exist if this happens on older Qt5's (below 5.5), but it definitely happens on Qt 5.5 upwards.

Trying a fix in the spirit of the tooltip-fix.

**Comment by vivid-synth** [comment] 2017-03-14 03:49
Related?: https://github.com/supercollider/supercollider/issues/1478

**Comment by bagong** [comment] 2017-03-14 04:02
ctrl-. is a special case, but generally related as it has to do with Ubuntu Unity idiosyncrasies... I will offer a solution in a few days, but I need to see first if it has side effects... Good to have the cross-link.

**Comment by bagong** [comment] 2017-04-12 09:16
Oh, I just saw this has had a priority upgrade. You know, a weird thing is that nobody even confirms this. Made me doubt whether this is actually true... 
If this is the main thing people are waiting for to go ahead with 3.9, and people want to go ahead now, please somebody else work on this, I will need another week before I can even look at it again, and no promises that I can do anything anyways.
I have a sketch of stuff I did when following up on this with Luca, who uses Ubuntu with unity, and whose system indicated that it changes with Qt5 versions. I also did a clean build on a (physical) 16.10 machine with stock Ubuntu Qt 5.6 again and can still reproduce much of if, among others ctrl-. (which will open a method lookup window rather than stop sound and ctrl-s). There is a pattern here, which gives me hope that at least some workaround like in the tooltip-case can be found:
(https://github.com/bagong/supercollider/commit/29880503517b8c88b88522194653957d6b636490). The important thing is the repetition of addAction line 517 downwards and the comment on top of it.
But if nobody has time or interest, as I said, I need to finish other stuff and won't be able to look at it before another week or so... sorry.

**Comment by scztt** [comment] 2017-04-12 18:36
Want to test this on the webengine branch? It's using qt 5.8, so it's possible it may be fixed there. 
http://supercollider.s3.amazonaws.com/builds/scztt/supercollider/osx/topic/webengine-latest.html

**Comment by bagong** [comment] 2017-04-12 18:43
@scztt, ou mean test building the branch on Ubuntu? We are talking here of keyboard problems that look particularly thorny on Ubuntu-unity-flavor, right? Not sure what Webkit would have to do with that, if not you put in some generic gems... I am eager to test your branch in general, but I won't have time before next week at best, I am sorry...

**Comment by scztt** [comment] 2017-04-12 19:59
Sorry, not specific enough, and I pointed you to a mac build. :)
That webengine branch is actually just a qt 5.8 update branch (it's labelled webengine because the only substantial work in getting to qt5.8 is the webengine work).

**Comment by bagong** [comment] 2017-04-12 20:02
Haha, ya, I was a bit confused. But that switch to webengine is pretty significant, isn't it? I thought you might consider it work in progress... Was a bit surprised that you didn't make more buzz about it yet... So it's ready for testing? Is it MacOS only, or is there a chance that other OSses can also use it?

**Comment by scztt** [comment] 2017-04-12 22:23
It's ready for testing. The unit tests aren't running on mac or linux, but it appears to be some kind of travis / readline problem? - I haven't had time to investigate. It needs a bit more documentation, and a sweep to fill in backwards compatibility where possible (WebEngine is, in general, not backwards compatible, so a lot of behavior had to change). I know of a handful of bugs too, but it's very close.
It builds on Mac and Linux. Windows will take some Cmake work (some additional install steps) that I can't do myself, but otherwise shouldn't present any problems that require code change.

**Comment by bagong** [comment] 2017-04-13 06:19
Sounds very interesting! You know that for Windows this means we cannot use the MinGW build any more, so it's a pretty significant move. We'll also have to see what this means on more conservative Linuxes that haven't even progressed to Qt 5.4 yet, from where on I think Webengine is available. But as far as I can see that's Raspbian only...  Also if it behaves as expected with Qt-versions below 5.8, which will still be around for a while on Linux. Would be nice to get people trying it. Why don't you advertise it, maybe on sc-dev? It's a very important step in many respects and must have been a lot of work for you...

**Comment by bagong** [comment] 2017-04-18 09:18
Sorry, I can't make commitments for the time being...

**Comment by patrickdupuis** [comment] 2017-05-03 21:39
It seems that Ubuntu will be dropping Unity, amongst a few other if its development initiatives, in its next version (17.10). Unity will be around for as long as version 16.04LTS is being used (~until after april 2018). It would be great for existing Ubuntu users to have this fixed. However, I wonder if it should remain a show-stopper 3.9 bug?

**Comment by snappizz** [comment] 2017-05-04 07:20
As long as Unity is still alive, I think this should stay important.

**Comment by patrickdupuis** [comment] 2017-05-04 07:24
Agreed. 16.04 will keep Unity around for a while. It's worth fixing for sure.

**Comment by snappizz** [comment] 2017-05-21 21:14
To summarize what I believe is the current state of this issue, the upgrade to Qt 5 broke a number of macros we were using to distinguish platforms, in particular `Q_WS_X11`. I believe this issue can be resolved by changing e.g. `#ifdef Q_WS_X11` to `#if defined(Q_OS_UNIX) && !defined(Q_OS_MAC)` in all shortcut-related code. The only barrier to resolving this would be to actually reproduce the issue and make sure that this proposed fix works.

**Comment by bagong** [comment] 2017-05-22 09:13
I had a look at this a few months ago and couldn't apply the "tool-tips-fix"-logic to this problem, unfortunately, no code with the relevant preprocessor macros involved. This commit actually fixes/works around? the particular issue, but I never finished it:
https://github.com/bagong/supercollider/commit/29880503517b8c88b88522194653957d6b636490
Maybe @patrickdupuis , you want to have a look? In this context one also bumps into a few keyboard-shortcut assignments that conflict with system keys on Linux (and OSX) ;) The issue can grow on you ;) Unfortunately using Ubuntu in a virtual machine adds another layer of "keyboard/key-combination management" complexity, but I actually checked, and (at least some of the) broken keys do not work on a proper "physical" install too. I think the issue is valid, but we haven't had feedback for a long time. Maybe hardly anybody uses unity-ubuntu any more...

**Comment by snappizz** [comment] 2017-05-22 17:12
> I had a look at this a few months ago and couldn't apply the "tool-tips-fix"-logic to this problem, unfortunately, no code with the relevant preprocessor macros involved.

Bummer. I do see some Qt4 macros still hanging around though:

```
$ rg Q_WS_X11
QtCollider/interface.cpp
34:#ifdef Q_WS_X11
61:#ifdef Q_WS_X11

QtCollider/QWidgetProxy.cpp
37:#ifdef Q_WS_X11
190:#ifdef Q_WS_X11
426:#ifdef Q_WS_X11

QtCollider/QcApplication.cpp
46:#ifdef Q_WS_X11
54:#ifdef Q_WS_X11

QtCollider/hacks/hacks_x11.hpp
29:#ifdef Q_WS_X11

QtCollider/hacks/hacks_x11.cpp
30:#ifdef Q_WS_X11

editors/sc-ide/widgets/code_editor/editor.cpp
43:#ifdef Q_WS_X11
658:#ifdef Q_WS_X11
```

**Comment by patrickdupuis** [comment] 2017-05-24 22:43
I'm testing this in a VM Ubuntu 17.04 (Qt 5.7.1) and I cannot reproduce. 

I went through all the default shortcuts that appear in the menus. The only ones that I found didn't work as expected were Shift-Ctrl-U (does something weird on Ubuntu, Fedora, probably all linux) and Ctlr-Alt-T (opens a new terminal window on Ubuntu). 

This issue was originally reported on Ubuntu 16.10 which is end-of-life in July 2017. The current Long Term Support version on Ubuntu is 16.04. We should check to see if the issue appears there, as it is likely that some people will be using this version until after 18.04 is released.

Please let me know if you would like me to test anything specific, or if you need more info.

**Comment by bagong** [comment] 2017-05-24 22:47
Ah, interesting, so likely they fixed something in Unity. The ctrl-u thingy is unicode related, a custom Ubuntu thing to produce unicode characters. Looking at 16.04 and/or 16.10 would be great! Just to have a confirmation if I am actually seeing gosts... (in pro issue tracker issues are not considered before they have been confirmed ;) But SC deserves to be special ;) )

**Comment by patrickdupuis** [comment] 2017-05-24 22:57
I'll try 16.04 when I have the chance. FYI - I am using Gnome Boxes for my VMs. It's very simple to use. I haven't experienced any major keyboard related complexities.

**Comment by bagong** [comment] 2017-05-24 23:02
But you're running Unity-Ubuntu inside the Gnome-box, right? ;)

ctrl-., ctrl-s, ctrl-sh-s work? That's cool!

Yea, would be lovely if you had the time to try one of the older versions.

**Comment by patrickdupuis** [comment] 2017-05-24 23:19
Yup - stock Ubuntu with Unity inside Gnome Boxes. Testing again, those shortcuts work for me 👍

**Comment by bagong** [comment] 2017-05-24 23:20
Okay, my build will finish in a few minutes, maybe it's just my hand :smile:

**Comment by bagong** [comment] 2017-05-24 23:33
Hmm, it's not my hand, in fact they work on 17.04 for me too! The more interesting it would be to confirm on 16.04/16.10. Or looking up the change log for 17.04 if there is something keyboard related in Unity or Qt...

**Comment by patrickdupuis** [comment] 2017-05-26 03:39
I can reproduce on 16.04. About half the keyboard shortcuts don't work, including Ctlr-S, Ctlr-N, and Ctlr-period. We've narrowed this problem down to 16.04 and 16.10. 17.04 does not have this behaviours.

**Comment by patrickdupuis** [comment] 2017-05-26 03:59
I installed using the Gnome desktop on 16.04 and the shortcuts work fine.

**Comment by bagong** [comment] 2017-05-26 07:06
Cool, @patrickdupuis , thanks a lot for your efforts!

**Comment by telephon** [comment] 2017-05-29 17:36
can we close?

**Comment by bagong** [comment] 2017-05-29 17:53
Depends on how important we consider 16.04 and 16.10. A workaround is likely possible, but I doubt anybody wants to work around a Unity bug.

**Comment by snappizz** [comment] 2017-05-29 18:01
let's leave this open as long as unity is around, but i'll downgrade the importance. i can't find any recent complaints about it on the list.

**Comment by muellmusik** [comment] 2018-08-30 10:57
Do we want to keep this open?

**Comment by dyfer** [comment] 2022-05-02 20:11
Feel free to reopen if the issue is still valid.

**Closed by dyfer** 2022-05-02 20:11 UTC
Labels: os: Linux, env: SCIDE, qt5
