### ISSUE TITLE
ESC-won't work with "Look up Doc. For" - Pop-Up (search for help)

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#4008] opened 2018-08-22 12:42 UTC
SuperCollider version: 3.10' [f462f096d] / macOS 10.12.6 / Qt 5.11.1 via homebrew

Expected Behavior
-----------------
In 3.9.3 the ESC-key is ending/closing the help search pop-up window. 
Should do it in 3.10 too.

Current Behavior
----------------

Only the enter-key closes the pop-up.

**Comment by snappizz** [comment] 2018-08-22 14:41
i'm sorry but what exactly is the help search pop-up window, and how do i bring it up?

**Comment by miczac** [comment] 2018-08-22 19:38
on mac it's _shft-cmd-d_
![screen shot 2018-08-22 at 14 09 08](https://user-images.githubusercontent.com/1922103/44486297-7b8af200-a653-11e8-8666-a83dbe8edd32.png)
Did I use the wrong term for that?

**Comment by snappizz** [comment] 2018-08-22 19:39
lol i actually had no idea that existed. where was it before?

**Comment by miczac** [comment] 2018-08-22 20:35
uhm ... since, like, sc-ide was introduced? 😁 

![screen shot 2018-08-22 at 22 32 24](https://user-images.githubusercontent.com/1922103/44489391-b3963300-a65b-11e8-8f21-98ad1c0357a9.png)

**Comment by miczac** [comment] 2018-08-22 23:31
uhm ... IIRC always the same - since, like, sc-ide was introduced? 😁 

![screen shot 2018-08-22 at 22 32 24](https://user-images.githubusercontent.com/1922103/44489391-b3963300-a65b-11e8-8f21-98ad1c0357a9.png)

(had to check on an old system ;)

**Comment by patrickdupuis** [comment] 2018-08-24 18:08
@miczac I can't reproduce on linux and current 3.10. This may be an window focus issue. Can you confirm that the pop-up is in focus when it first appears? ESC doesn't work if it isn't.

**Comment by miczac** [comment] 2018-08-25 12:27
just noticed: when flicking through the individual windows (I work with all IDE elements detached), the pop-up is treated like an individual window, not as part of its originating window.

**Comment by brianlheim** [comment] 2020-10-05 00:26
i can no longer reproduce this, perhaps it was fixed by a newer Qt release. if someone encounters this again, please create a new ticket with more information.

**Closed by brianlheim** 2020-10-05 00:26 UTC
Labels: bug, env: SCIDE
