### ISSUE TITLE
supercollider, SCIDE

### ISSUE THREAD

**Issue by alba21-coder** [supercollider/supercollider#5572] opened 2021-09-22 10:30 UTC
## Environment
Mac OS X El Capitan 10.11.3

* SuperCollider version: 3.12.1
* Operating system:
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

(hjh: edited to remove code tags as the description isn't code)

Simply scsynt doesn't work, so I re-install the software but when I close the interface a robot voice start to speech something about "scid-ii dot net ... Helpbroswer don't go home..." and other numbers. Very strange, cause when I open for the first time after the re-sintalling the software found the HelpBrowser and everything works but after the first time the issue comes back.
Near HelpBrowser there's written : Sending Request...

I try to open by Documents but I'm not smart for that kind of issue.

Thank you

**Comment by dyfer** [comment] 2021-09-22 16:55
Hello @alba21-coder 
`Sending Request...` is a message from the help system. This usually goes away after a moment, but if not, restarting SC usually helps...
Are you sure it's the `scsynth` that doesn't work? scsynth is the audio server, started with `Server.default.boot` or `s.boot` typically. 
Or is it the help browser that doesn't work?
Does the interpreter start properly? i.e. does it say in the post window, after starting SuperCollider: `*** Welcome to SuperCollider 3.12.1. *** For help press Cmd-D.` ?
Finally, I have no idea where does the robot voice come from - it's not from SC directly. 
Do you have any code in your startup file? (You can find it in File -> Open startup file)

**Comment by jamshark70** [comment] 2021-09-24 05:59
A couple of thoughts:

1. This may be a better question for the user forum at scsynth.org. It isn't currently known if this is a bug, or a problem with machine configuration, or something else. The bug tracker should be mainly for bug reports and enhancement requests -- at present, this is more of a technical support question. *If* it's found to be a bug, then it could be registered here.

2. Did you install the macOS legacy version of SC (for macOS 10.10-10.12)? You told us your macOS version (10.11, which needs the legacy version of SC), and the SC version *number*, but it doesn't say which download you used.

3. A robot voice might be the OS's screen reader, for vision-impaired users.

**Comment by alba21-coder** [comment] 2021-09-24 10:06
Thank you for the reply.
When I open SC in the post window don't appear " *** Welcome to SuperCollider 3.12.1. *** For help press Cmd-D" .
I can't write anything in the software, don't recognize the syntax, don't change color, doesn't work. 
I can't give any type of command.

I try to stop the interpreter and reboot and another robot voice comes to says something I can't understand.
-------------------------------------------------------------------------------------------------------------------------
compiling class library...
	Found 855 primitives.
	Compiling directory '/Applications/SuperCollider.app/Contents/Resources/SCClassLibrary'
	Compiling directory '/Users/SandroKann/Library/Application Support/SuperCollider/Extensions'
	Compiling directory '/Users/SandroKann/Library/Application Support/SuperCollider/downloaded-quarks/Vowel'
	Compiling directory '/Users/SandroKann/Library/Application Support/SuperCollider/downloaded-quarks/Dirt-Samples'
	Compiling directory '/Users/SandroKann/Library/Application Support/SuperCollider/downloaded-quarks/SuperDirt'
	Compiling directory '/Users/SandroKann/Library/Application Support/SuperCollider/downloaded-quarks/say'
	Compiling directory '/Users/SandroKann/Library/Application Support/SuperCollider/downloaded-quarks/XML'
	numentries = 1303221 / 20670688 = 0.063
	6037 method selectors, 3424 classes
	method table size 21375048 bytes, big table size 165365504
	Number of Symbols 15356
	Byte Code Size 456286
	compiled 582 files in 1.07 seconds
compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
-------------------------------------------------------------------------------------------------------------------------
Yes I install macOS legacy 10.10 - 10.12, I try previous and next version but obviusly doesn't works.

Sorry me If I made that question here but I did not know where I can, a part from here.
Thank you again.

**Comment by alba21-coder** [comment] 2021-09-24 10:07
What I write in big is what appear in the post window

**Comment by jamshark70** [comment] 2021-09-25 02:04
> Sorry me If I made that question here but I did not know where I can, a part from here.

Website https://scsynth.org = user forum

Try removing all extensions and starting with only the default class library:

1. Preferences > Interpreter and remove everything from "Include" directories.
2. Reboot interpreter (or quit/relaunch).

I suspect that an extension may be causing infinite recursion during class tree initialization.

**Comment by dyfer** [comment] 2022-02-28 00:34
I'm closing this due to lack of information. Please reopen if the issue is still valid.

**Closed by dyfer** 2022-02-28 00:34 UTC
Labels: bug
