### ISSUE TITLE
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error' could not initialize audio. Server 'localhost' exited with exit code -1073740791.

### ISSUE THREAD

**Issue by LJSCY** [supercollider/supercollider#4799] opened 2020-03-05 01:55 UTC
## Environment

* SuperCollider version: 3.10.4
* Operating system: Windows 10
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
Paste code here. Use a minimal example please.
```

## Expected vs. actual behavior

Expected behaviour: FoxDot to output audio

Actual Behaviour: No audio (Error message...)

This is the outcome:

****************************************************************************************************

-> FoxDot
Booting server 'localhost' on address 127.0.0.1:57110.

Device options:
  - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Microphone (Realtek High Defini   (device #1 with 2 ins 0 outs)
  - MME : Microsoft Sound Mapper - Output   (device #2 with 0 ins 2 outs)
  - MME : Speakers (Realtek High Definiti   (device #3 with 0 ins 2 outs)
  - Windows DirectSound : Primary Sound Capture Driver   (device #4 with 2 ins 0 outs)
  - Windows DirectSound : Microphone (Realtek High Definition Audio)   (device #5 with 2 ins 0 outs)
  - Windows DirectSound : Primary Sound Driver   (device #6 with 0 ins 2 outs)
  - Windows DirectSound : Speakers (Realtek High Definition Audio)   (device #7 with 0 ins 2 outs)
  - ASIO : ASIO4ALL v2   (device #8 with 2 ins 2 outs)
  - Windows WASAPI : Speakers (Realtek High Definition Audio)   (device #9 with 0 ins 2 outs)
  - Windows WASAPI : Microphone (Realtek High Definition Audio)   (device #10 with 2 ins 0 outs)
  - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #11 with 0 ins 2 outs)
  - Windows WDM-KS : Microphone (Realtek HD Audio Mic input)   (device #12 with 2 ins 0 outs)
  - Windows WDM-KS : Stereo Mix (Realtek HD Audio Stereo input)   (device #13 with 2 ins 0 outs)

Requested devices:
  In (matching device NOT found):
  - (null)
  Out (matching device NOT found):
  - (null)

Selecting default system input/output devices

Booting with:
  In: MME : Microphone (Realtek High Defini
  Out: MME : Speakers (Realtek High Definiti
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
could not initialize audio.
Server 'localhost' exited with exit code -1073740791.

************************************************************************************************

I have read the other tickets but am having trouble finding the issue, so a bit of help would appreciated :)

Thanks!

**Comment by LJSCY** [comment] 2020-03-05 02:14
Also when I recompile class Library it says:

Info: 2 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

**Comment by LJSCY** [comment] 2020-03-05 02:16
This is the result, not sure what to do about this:

Overwritten methods in class library:
-------------------------------------

String
------
	String:absolutePath
		C:\Program Files\SuperCollider-3.10.4\SCClassLibrary\Platform\windows\SystemOverwrites\overwrites.sc
		C:\Program Files\SuperCollider-3.10.4\SCClassLibrary\Common\Collections\String.sc

PathName
--------
	PathName:isAbsolutePath
		C:\Program Files\SuperCollider-3.10.4\SCClassLibrary\Platform\windows\SystemOverwrites\overwrites.sc
		C:\Program Files\SuperCollider-3.10.4\SCClassLibrary\Common\Files\PathName.sc

**Comment by dyfer** [comment] 2020-03-05 02:49
Hello @LJSCY 

Unfortunately SC's audio backend on Windows sometimes fails with no clear reason.
I'm closing this since it's a duplicate of https://github.com/supercollider/supercollider/issues/4718. Please see that thread for possible solutions.

Regarding the warnings:
```
Info: 2 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll
```

These are not related to the server start issue. AFAICT they are superfluous and you don't need to worry about them.

Sorry I can't offer more help ATM...

**Closed by dyfer** 2020-03-05 02:49 UTC
Labels: bug

**Comment by jamshark70** [comment] 2020-03-05 05:17
Re: the overrides -- both are related to absolute path syntax:

- Linux/Mac: `/path/to/something`
- Windows: `C:\path\to\something`

The overrides are required to cooperate with Windows, hence nothing to be alarmed about.
