### ISSUE TITLE
sclang crash when scide is launched

### ISSUE THREAD

**Issue by KRSHK** [supercollider/supercollider#3575] opened 2018-03-13 16:56 UTC
When starting scide for the first time, the sclang crash with this ERROR message:
`*** Error in '/usr/bin/sclang': free(): invalid pointer: 0x0000558888b92f00 ***`
When I try to restart scide, I got another ERROR message:
`*** Error in 'scide': unmap_chunk(): invalid pointer: 0x0000562554c210c0 ***`

**Comment by telephon** [comment] 2018-03-13 17:18
What version is it and what operating system are you on?

**Comment by KRSHK** [comment] 2018-03-13 17:25
Sorry:
SuperCollider v. 3.9.1
Operating system: void linux

**Comment by telephon** [comment] 2018-03-13 18:54
can you try to compile it on your machine? Then we'd see if it is the repository or not.

**Comment by KRSHK** [comment] 2018-03-13 20:59
Sorry, I don't have access to my computer right now, but there is a ticket opened in the voidlinux repository:
https://github.com/voidlinux/void-packages/issues/12328

**Comment by miguel-negrao** [comment] 2018-03-13 21:07
Would it be possible to run sclang from gdb

    gdb sclang 

and then get a backtrace (bt) ?

**Comment by mvf** [comment] 2018-03-14 04:30
This is probably not a Supercollider bug.  `x86_64-musl` builds of both programs work just fine. `scide` and `sclang` seem to crash only when calling `std::string` operators directly. Linking `scide` against the distribution's shared `yaml-cpp` makes its crash go away. This suggests an ABI issue, just like `sclang`'s first heap error:
```
==1122== Memcheck, a memory error detector
==1122== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1122== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==1122== Command: sclang
==1122== 
==1122== Invalid free() / delete / delete[] / realloc()
==1122==    at 0x4C2E2BB: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1122==    by 0xBC67869: std::string::_M_mutate(unsigned long, unsigned long, unsigned long) (in /usr/lib/libstdc++.so.6.0.24)
==1122==    by 0xBC67D7D: std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib/libstdc++.so.6.0.24)
==1122==    by 0x23351E: assign (basic_string.h:4314)
==1122==    by 0x23351E: operator= (basic_string.h:3637)
==1122==    by 0x23351E: SC_LanguageClient::SC_LanguageClient(char const*) (SC_LanguageClient.cpp:100)
==1122==    by 0x18111B: SC_TerminalClient::SC_TerminalClient(char const*) (SC_TerminalClient.cpp:77)
==1122==    by 0x18C2BE: QtCollider::LangClient::LangClient(char const*) (LanguageClient.cpp:38)
==1122==    by 0x17E83A: createLanguageClient(char const*) (SC_TerminalClient.cpp:719)
==1122==    by 0x16F920: main (cmdLineFuncs.cpp:25)
==1122==  Address 0x5e97a0 is 0 bytes inside data symbol "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_empty_rep_storage@@Qt_5"
```
I'd expect this to no longer occur in a fully source-bootstrapped environment. Unfortunately, just rebuilding the application doesn't help.

**Comment by brianlheim** [comment] 2018-03-24 00:56
Any updates on this?

**Comment by mvf** [comment] 2018-03-25 09:00
The root cause is still unknown, but I'm more convinced than ever it's not on your end. A rebuild of version 3.8.0, which was previously in our repos and working, now shows the same issue.

**Comment by brianlheim** [comment] 2018-03-25 14:54
Ok, I will close this then. If it turns out there is something we can do please reopen.

**Closed by brianlheim** 2018-03-25 14:54 UTC
Labels: waiting for information
