### ISSUE TITLE
s.makeGui server window broken in master

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2202] opened 2016-06-24 09:35 UTC
![broken-server-window](https://cloud.githubusercontent.com/assets/318301/16334150/e56a0ec6-3a31-11e6-813f-e3456a8fc515.png)

Server is running. IDE server panel is updating. Server window is not updating.

I guess the new server status watcher is not finished yet?

**Comment by jamshark70** [comment] 2016-06-24 09:40
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/ServerStatus.sc#L140

```
					this.updateRunningState(true);
					this.changed(\counts);
```

It's the `Server` object, not the `ServerStatusWatcher`, that should be calling `changed`.

**Comment by telephon** [comment] 2016-06-24 17:01
My refactored status watcher hasn't been merged, @crucialfelix wanted to be careful and incremental. I am now not sure, however, what is the best way to proceed.

**Comment by crucialfelix** [comment] 2016-06-28 09:48
Post a PR with a bug fix please. 

That's the whole with huge unreadable PRs - even with spending hours with it something like that gets through. I'm not sure it it was something I missed or something in the original PR.

**Comment by telephon** [comment] 2016-06-28 21:03
@crucialfelix I can try, but I don't think I can reimplement the whole recording pause-update-etc. thing in the IDE. It was already over my head, and I won't be able to do it all over. I understand that the PR was too big, but it just became that way and I had no way of simplifying it.

 I guess better to just throw it away, even if it was several day's work.

**Comment by crucialfelix** [comment] 2016-06-29 08:46
Isn't the bug reported above just one small missing change ? It isn't getting the status.

The whole recording pause-update thing is separate.  The rest of what you did is still waiting in that old PR to be cherry picked into a new smaller PR for each feature. If you (or me or somebody) starts from master now, that person can see what things are already merged in. I basically just did the first feature and then stopped.

I'll try to look at the issue above, but I'm pretty busy right now.

**Comment by telephon** [comment] 2016-06-29 10:39
OK, yes I see.

**Comment by telephon** [comment] 2016-07-01 17:11
Is this fixed? I can't reproduce on the current master.

**Comment by snappizz** [comment] 2016-07-01 17:16
I can reproduce. In particular, avg CPU, number of synths, etc. aren't displaying.

**Comment by telephon** [comment] 2016-07-01 18:56
Ah ok, I can reproduce this, too. I didn't look at them, because I misunderstood the issue description.

**Comment by jamshark70** [comment] 2016-07-01 23:02
Apologies for vagueness in the issue description. I had thought it would be clear from the screenshot that it should be inconsistent to have a server GUI showing "running" status while all the data fields are empty. Then again, I guess nobody is using the server GUI anymore so it may have been forgotten how it works.

**Comment by telephon** [comment] 2016-07-02 13:00
No problem! Yes, I also think it would be better to make a new GUI once the refactoring is done. If it is OK even with the recording quirk, this would fix it.

**Comment by gusano** [comment] 2016-07-08 16:51
@jamshark70 your change seems to fix it. Will submit a PR now.

**Closed** 2016-07-09 22:27 UTC
Labels: bug, comp: class library, severe
