### ISSUE TITLE
1. Plotter seems give different result depending OS. 2. .addKr not understood error

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6206] opened 2024-01-30 02:38 UTC
## Environment

* SuperCollider version: 3.12.x and above
* Operating system: all

## Steps to reproduce

Evaluate the code in the first post in the following forum thread:
https://scsynth.org/t/initial-trigger-with-pulsedivider/8847?u=prko

## Expected vs. actual behavior

- Expected:
  SC should plot the same result regardless of the OS where SC is running.
- Actual: 
   - Only SC3.12.0 on Raspberry Pi shows a part of the first impulse:
     - on Raspberry Pi: https://scsynth.org/t/initial-trigger-with-pulsedivider/8847/9?u=prko
     - on Windows and macOS: https://scsynth.org/t/initial-trigger-with-pulsedivider/8847/11?u=prko
  - With SC3.13.0 and above, the code has the following error: `ERROR: Message 'addKr' not understood.`
     https://scsynth.org/t/initial-trigger-with-pulsedivider/8847/9?u=prko

**Comment by mtmccrea** [comment] 2024-01-30 08:39
Interesting...this relates to the use of ControlNames for variables...
```
{ Impulse.ar(\tFreq.kr(400)) }.plot(0.01)
```

**Comment by mtmccrea** [comment] 2024-01-30 08:50
Actually, this isn't related to Plotter, it's the routine that's throwing the error:
```
{ Impulse.ar(\tFreq.ar(400)) }.fork //plot(0.01)
```
(same error as above)

**Comment by prko** [comment] 2024-01-30 09:48
The error occurs in the following line, if I am not mistaken:

https://github.com/supercollider/supercollider/blob/db7eed2a17c361503dbc7f70a557874b6001e3cd/SCClassLibrary/Common/Control/GraphBuilder.sc#L168

> ```
> { Impulse.ar(\tFreq.ar(400)) }.fork //plot(0.01)
> ```
In this case `name` is `tFreq` and its class is `Symbol`. I got this result by inserting the following code before the line168:
```
("name:" + name ++"; name.class:" + name.class).postln;
```
The problem seems to occur with `buildSynthDef.addKr(name, values.unbubble);`.
`buildSynthDef` does not understand `.addKr`...

**Comment by prko** [comment] 2024-01-30 09:59
> The problem seems to occur with `buildSynthDef.addKr(name, values.unbubble);`.
> `buildSynthDef` does not understand `.addKr`...

Hm...
`buildSynthDef` is `tFreq` and its class is `Symbol`.

**Comment by mtmccrea** [comment] 2024-01-30 10:29
I mentioned the wrong variable in my previous post, you're right that `buildSynthDef` is the problem. It should answer with the `SynthDef` that is currently being built.

**Comment by telephon** [comment] 2024-03-15 14:33
The problem is that in Function:plot, the UGen function is called directly (.value) and thus has no buildSynthDef. I'll propose a fix.

**Comment by telephon** [comment] 2024-03-15 15:12
(it was a very annoying bug …)

**Comment by telephon** [comment] 2024-03-15 20:08
@mtmccrea I just noticed that you have a similar thing in #6217, I didn't see it. Maybe you can check what is the best way to fix the collisions? Or maybe my fix is unnecessary?

**Comment by mtmccrea** [comment] 2024-03-18 13:31
@telephon, yep looks the changes in #6235 are functionally the same as #6217, though the latter adds a bit of extra documentation and cleanup. 

The exception is the nil check added to `NamedControl:-init`, and additions to docs for the `action` arg of `Function:loadToFloatArray`/`getToFloatArray` in #6235.

Could those two commits (2d3ddcb11db5ba872248ef7c11d01a274daa1bfa, 6dc6a9657985219ef3fc78e8fd00f2eabe726676) be cherry picked into #6217? Or maybe easier to just copy-paste the changes over...

**Comment by mtmccrea** [comment] 2024-03-18 13:32
Or the commit with identical changes, 4a783f1865b613436316f2b094283dc70771527e, could be scrubbed from #6235, then there's no conflict and they could just both be merged at the same time.

**Comment by telephon** [comment] 2024-03-18 14:50
> Or the commit with identical changes, [4a783f1](https://github.com/supercollider/supercollider/commit/4a783f1865b613436316f2b094283dc70771527e), could be scrubbed from #6235, then there's no conflict and they could just both be merged at the same time.

Yes, that sounds like a good idea. If you do the editing in your commit, I'd do a review, if you like.

**Comment by mtmccrea** [comment] 2024-03-20 11:34
To clarify, commit 4a783f1 in your branch has changes identical to those in mine, but the corresponding commit in my branch has additional changes.

So I'm suggesting that 4a783f1 be removed from your PR, leaving just the two commits with help doc changes and the error message when buildSynthDef is missing.

Sound ok?

**Comment by telephon** [comment] 2024-03-20 12:01
Thanks for clarifying!

It is OK if you do this. But I would propose that you could adjust your version a bit? 

```supercollider
buffer.sampleRate = if(defRate == \control) {
				server.sampleRate / server.options.blockSize
			} {
				server.sampleRate
			};

			// Unlike sampleRate, numChannels and numFrames will be sent to the server with the alloc message
			buffer.numChannels = numOutputs;
			buffer.numFrames = if(defRate == \control, {
				duration * server.sampleRate / server.options.blockSize
			}, {
				duration * server.sampleRate
			}).asInteger;
```

by writing 

```supercollider
frameRate =  if(defRate == \control) {
				server.sampleRate / server.options.blockSize
			} {
				server.sampleRate
			}
};
buffer.sampleRate = frameRate;
buffer.numFrames = (duration * frameRate).asInteger;
```

**Closed** 2024-03-21 09:41 UTC
Labels: bug
