### ISSUE TITLE
Comparison after adding rounded floats behaves unexpectedly

### ISSUE THREAD

**Issue by carlocapocasa** [supercollider/supercollider#1875] opened 2016-02-22 00:56 UTC
Floats don't stay rounded for comparison purposes after adding them together.

As expected:

a=0.1;
=> 0.1

a==0.1
=> true

a=a+0.11.round(0.1)
=> 0.2

a==0.2
=> true

Unexpected:

a=a+0.11.round(0.1)
=> 0.3

a==0.3
=> false

Unexpected

a.round(0.1)==0.3
=> false

**Comment by jamshark70** [comment] 2016-02-22 01:09
This is also normal behavior with floats. Look at classes like `Pfindur` -- they have a "tolerance" argument so that the test is not "equal," but rather "close enough."

**Comment by jamshark70** [comment] 2016-02-22 02:03
The problem here is actually the float representation of the literal 0.3.

```
e = 0.3;
[e.high32Bits, e.low32Bits];
--> [ 1070805811, 858993459 ]

e = e.round(0.1);
[e.high32Bits, e.low32Bits];
--> [ 1070805811, 858993460 ]
```

The rounding behavior is consistent in all cases I tested.

```
(
a = 0.1; b = 0.1;
"%, %\n".postf([a.high32Bits, a.low32Bits], [b.high32Bits, b.low32Bits]);
2.do {
	a = a + 0.1;
	b = b + 0.11.round(0.1);
	"%, %\n".postf([a.high32Bits, a.low32Bits], [b.high32Bits, b.low32Bits]);
};
""
)
->
[ 1069128089, -1717986918 ], [ 1069128089, -1717986918 ]
[ 1070176665, -1717986918 ], [ 1070176665, -1717986918 ]
[ 1070805811, 858993460 ], [ 1070805811, 858993460 ]
```

I.e., `+ 0.1` and `+ 0.11.round(0.1)` get exactly the same result. `0.3` as a literal float is the odd one out.

**Comment by timblechmann** [comment] 2016-02-22 03:53
none of 0.1, 0.11, 0.2 or 0.3 can be represented with binary floating point numbers ...

**Comment by jamshark70** [comment] 2016-02-22 06:18
>vnone of 0.1, 0.11, 0.2 or 0.3 can be represented with binary floating point numbers ...

Of course - the results I reported aren't surprising to *me*. I was, however, clarifying that the problem is not the round operation. It's that the sum doesn't match the literal (also not surprising).

Anyway, I'm closing this. It's not a bug, merely the IEEE making the best of an impossible situation.

**Closed** 2016-02-22 06:18 UTC

**Comment by carlocapocasa** [comment] 2016-02-22 09:29
Thanks for clearing that up guys.

Just checked out what other languages are doing. Comparison behavior is as described by you for all of them, although 0.1+0.1+0.1 is displayed as 0.30000000000000004 in Ruby and Python, which may be more obvious. PHP displays 0.30.

Wishing SC had a Decimal class.

**Comment by carlocapocasa** [comment] 2016-02-22 10:05
I think the literal value not being equal to the rounded value should be considered a bug, considering sclang is a dynamic language.

Python
round(0.1+0.1+0.1, 2)==0.3
=> true

Ruby
(0.1+0.1+0.1).round(2) == 0.3
=> true

PHP
var_dump(round(0.1+0.1+0.1,1) == 0.3);
=> bool(true)

Also, Ruby and Python display 0.1+0.1+0.1 as 0.30000000000000004, which is a convenient reminder that floats are at work.

**Comment by jamshark70** [comment] 2016-02-23 04:12
It's not that simple.

SC uses the standard C atof() function to convert strings to floats. I don't think it's wise to start adding exceptions, where SC deviates from decades of convention. You just found one odd case that doesn't work the way you expected... so we add an exception. Then, next week, you might find another one... another exception. Where does it stop?

The fact simply is: In floating-point numbers, the least significant bit or two should be considered just like sampling (quantization) noise in an ADC. '==' checks all the bits, so it is safe only if both numbers are rational, and both numbers' denominators are powers of two. That isn't usually the case, so it's always safer to use it "close enough" tests rather than "exactly equal" tests. You will always be able to find weird behavior with the latter. Do not rely on it. I mean: Do not **ever** rely on it!

Your Python and Ruby examples round to two decimal places, but your previous SC example rounds to one. So they are not the same test. In SC:

```
round(0.1+0.1+0.1, 0.01)==0.3  // matching python!
-> true

round(0.1+0.1+0.1, 0.1)==0.3
-> false
```

Also note that the Python documentation explicitly warns about funny behavior with floats:

https://docs.python.org/2/library/functions.html#round

"Note: The behavior of round() for floats can be surprising: for example, round(2.675, 2) gives 2.67 instead of the expected 2.68. This is not a bug: it’s a result of the fact that most decimal fractions can’t be represented exactly as a float. See Floating Point Arithmetic: Issues and Limitations for more information."

Also http://stackoverflow.com/questions/15732032/behavior-of-round-function-in-python

**Comment by carlocapocasa** [comment] 2016-02-23 09:08
Sorry about the decimal mismatch, that was sloppy. I stand corrected, and thanks, as always, for the detailed explaining.
