### ISSUE TITLE
Localhost error supercollider

### ISSUE THREAD

**Issue by pi-314159265** [supercollider/supercollider#6038] opened 2023-05-27 14:15 UTC
Bug description:

Steps to reproduce:
1. Error:
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
could not initialize audio.
Server 'localhost' exited with exit code -1073740791

**Comment by JordanHendersonMusic** [comment] 2024-05-05 14:08
Closing because there isn't enough information in the issue to reproduce, feel free to edit the issue with more information following the wiki's guidelines and reopen!

**Closed by JordanHendersonMusic** 2024-05-05 14:08 UTC
