### ISSUE TITLE
HelpBrowser.goTo("http://supercollider.github.io/") does not work in 3.9.1

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3574] opened 2018-03-12 00:47 UTC
Bug description:
after evaluating the following code:
HelpBrowser.goTo("http://supercollider.github.io/") 
the help browser shows just a blank page.

Steps to reproduce:
1. evaluate the following code:
HelpBrowser.goTo("http://supercollider.github.io/")
2. see the help browser

Actual result:
the help browser shows just a blank page.

Expected result:
The code above should show the typed website properly just like that evaluating the following code shows the typed website properly:
HelpBrowser.new.goTo("http://supercollider.github.io/")

**Comment by brianlheim** [comment] 2018-03-12 01:00
Do other sites work? Can you try with https? We disabled non-https connections on the main website awhile ago.

**Comment by patrickdupuis** [comment] 2018-03-12 01:00
What OS are you using? I've tested this on Linux with a current 3.9 git branch build, and could not reproduce. The help browser took some time, but eventually it did show me the SC homepage.

**Comment by prko** [comment] 2018-03-12 01:59
I have tested on Windows 10, macOS El Capitan and macOS High Sierra.
On Windows 10 and on El Capitan,
`HelpBrowser.goTo("https://....")`
works,

but on macOS High Sierra, the both of
`HelpBrowser.goTo("http://...")`
and
`HelpBrowser.goTo("https://...")`
do not work.

**Comment by brianlheim** [comment] 2018-03-12 02:51
Cannot reproduce on High Sierra. I think you may need to check that your network connection is working.

**Comment by prko** [comment] 2018-03-12 03:01
Under the same OS on the same laptop,
`HelpBrowser.new.goTo("https://...")`
works, but
`HelpBrowser.goTo("https://...")`
does not work...
It is not a problem of my network connection.

It is really strange.

**Comment by brianlheim** [comment] 2018-03-12 03:43
OK, unfortunately there is no way for me to reproduce this so you'll have to do a little more digging. Is this the case with all websites, or just this one? Is the problem present on past versions of SuperCollider?

**Comment by prko** [comment] 2018-03-12 04:05
I have tried more than four websites. The results are same.
With SC3.8, it works correctly.

**Comment by brianlheim** [comment] 2018-03-12 04:54
I'm out of ideas on this one, sorry. Hopefully someone else can help. Maybe you should ask on the mailing list.

**Comment by crucialfelix** [comment] 2018-03-12 08:22
Just guessing: help browser does not handle redirects. You should link directly to the https version so you don't have to handle redirects.

**Comment by brianlheim** [comment] 2018-04-04 04:40
Closing as unreproducible.

**Closed by brianlheim** 2018-04-04 04:40 UTC
Labels: cannot reproduce, comp: class library, comp: sclang
