### ISSUE TITLE
+___

### ISSUE THREAD

**Issue by smoge** [supercollider/supercollider#6336] opened 2024-06-04 03:24 UTC
In the night there is a violet hour unknown to others.‎

In it I meet the lover's body and we listen to the voices from the other shore.‎

There is a ghoulish pain in the bulky string instruments, cracking with the lighting sharp screams of ‎
their gentle strings. In front and from behind, there is arousal without spark, giving the strings their ‎
writhing, monstrous and scary, their defances, their happiness that is gentle and strong in the heart of ‎
this hereditary and controlling melody. Contradiction continues until the very end, faring until life ‎
triumphs in the emergence of a small green leaf on a tabla beating death ad infnitum.‎

Within it are insights flled with elegance and hope, opposing the vulgar prosaic poetry which is the ‎
other necessary contradiction... And little by little the details and fragments exhaust the task at hand. A ‎
blending has emerged which I had never reached before, although it has always stirred in my heart, ‎
and which I hope to taste in the fourth movement of the strings.‎

My attempt is to do away with the single instrument and the boredom of the Arabic poetry which is my ‎
genetic loneliness, to weld a symphony that alternates between the singular dashing blaze and the slow, ‎
and heavy, and confdent steps of history...‎

Here are two movements of the strings, while I dive into the cacophony of the fourth moment, from ‎
which an anthem of the human choir will shine with the rising of the sun in man.‎

In this hour of nightly lusts ‎
and golden thorn birds
shines the glory of the old Arab kings

Wild bushes spread their scent in the warmth of a Bedouin girl ‎
Almond milk overfows
dripping in the night

And I, beneath the two breasts ‎
a vessel.‎

In this hour when things are ‎
an utter cry
I am on a camel

immersed in the eternal stars of night ‎
greeting the spirit of the desert
Oh nomad partaking in the migrations

supplied before the great sand with a single drop of water!‎

How can I be buried in this cage ‎
locked with the scent of night?‎
How can I be buried as almond blossom ‎
in a book of Suf song?‎

How can I be buried ‎
Blind
Paranoid

Infected by a monstrous torment ‎
that writes in me
my fears and my escapes

That wipes its tears in my heart ‎
in bursts of nightly melancholy
Oh carrier of the lantern of the unseen ‎
with the darkness of your eyes!‎
Rejoice in the language of sorrow ‎
My soul is Arab.‎

Oh bird of wilderness

you took the wings of my soul to the font of this universe ‎
and you washed the sky in clay
where creation overfowed ‎
you were sad for me.‎

This clay is tired

This clay will soon depart ‎
This clay is tired.‎

Socialize with the characters of the street

they are sultans in the night ‎
Sleep in every woman
Hide in her from the heat of palm groves ‎
Oh bird of lightning I want a woman
to contaminate me for weeks with mortuary passion ‎
I want a warm woman, for I am warm
I want an able body, for I am able
Oh bird of lightning fying from the palm groves of my dreams ‎
I see the remains of my age and my delusion in you
Oh carrier of muse from the East of my dark days ‎
Go to my country, where people sleep,‎
Say hello to the Kuf calligraphy of a morning prayer in the mosque ‎
to the streets
to perseverance!‎

The bondsman of dawn does his ablutions with the sword ‎
We wash ourselves with humiliation
We wipe the edge of the sword with cloth

We make excuses of the cold and excuses of the summer heat

But the genitals of Amr Ibn Al-as1 are still here, distorting the face of history ‎
The book of God is still hanging on the Arab spear
Ibn Sufyan with his yellow beard is still inciting the tribal partisanship against Al-Lat2‎

‎1‎	Amr Ibn Al-as (585-664) was an Arab military commender most notable for the Islamic conquest of Egypt in 640.‎
‎2‎	Abu Sufyan (560-650) was the leader of the Qureish tribe of Mecca and a warrior in the early Islamic conquests. He ‎
destroyed the shrine dedicated to Al-Lat, the goddess worshiped in pre-Islamic Arabia.‎

and the Shura3 of merchants still sees Uthman as its Caliph4.‎

In the tower square

A prostitute adjusts what the night has damaged of her face ‎
appealing for her own femininity
A frustrated passerby aborts

all he has of a man who is as rude as the government.‎

But I belong to redemption ‎
and to the head of Hussein
and all of my belonging I give to the Qarmatians5!‎

I piss on the ruling police!‎

Now is the era of piss above tables and parliaments and ministers ‎
I piss on them immodestly
because they fought immodestly.‎

Oh king of lightning fying in the immortal sorrows of my soul ‎
How can I be buried as a fower of revelation
in an escapade of nightly ecstasy? ‎
It wipes its eyes in my heart
‎3‎	The Islamic principle of consultation, encouraging Muslims to decide on affairs in consultation with those who will be ‎
affected by the decision. In contemporary terms, it can refer to government, and in Egypt, for example the Upper House ‎
of Parliament is known as the Shura Council.‎
‎4‎	Uthman Ibn Affan (576-656) was the third Islamic Caliph.‎
‎5‎	The Qaramatians were a religious group combining elements of Zorastrianism and Ismaili Shia Islam that revolted
against the Abbasid Caliphate and established a religious utopian republic in 899 CE in Al-Hasa, Easterm Arabia. In 930 ‎
CE they outraged the Muslim world by sacking Mecca, stealing The Black Stone, and desecrating the well of Zam-Zam ‎
with bodies of Hajj pilgrims.‎

It writes in me... It awakens in me

What does it write in me... What does it awaken in me

Oh illuminator of the days of God with the smile in your eyes ‎
Rejoice in the language of the Quran!‎

Have you reached the pulp? ‎
There, the fre is soft
The depths of discovery will make you darker ‎
Discovery is our path to execution.‎

Muse fows in the hours of a winter night

You fnd fre there, you force yourself on words

In a chaotic moment the soul awakens to a passion ‎
A fairy
Two wells of carnal blue ‎
Sugar in her cold eyes ‎
Perfume
She drips escaping like scent ‎
I catch her
But she melts in my hand
I bury her in my nose crushed between two breasts ‎
Oh bird of lightning I love and I forget
Why... How... Who is she? ‎
I don't know anything

To love is to not know anything

Do you know what the poet is like in love? ‎
Escaping from his tears to the forest of lights ‎
Dying in the eternal meeting of the rivers, ‎
crazy and fabulous.‎

The body of wax fares Sunni

I see deep into the history of the Levant

I want to overturn the pages of the Ummayad throne ‎
but wind suffocates me
words scatter

I feel fear and aguish

The wind strains with the voice of his Companion.‎

Someone knocks on Muawiyah6's door, announcing revolution‎
He brightens the night with the sword, he kindles an ember in the heart ‎
What is sparked in the eternal absence?‎
What is sparked in his absence?‎

Apostasy killed us as the wound between the eyes killed you, my Lord ‎
The head of revolution on a dish in Yazid7's palace‎
This spot in the ground

more faithful to the rulers, to God, to the head

‎6‎	Muawiyah was the frst Caliph of the Umayyad Dynasty, one of his most controversial and enduring legacies was his ‎
decision to designate his son Yazid as his successor.‎
‎7‎	Yazid Ibn Muawiyya was the second Ummayad Caliphate. He fought in the Battle of Karbala against Muhammad's ‎
grandson, Hussein, and the ensuing massacre of Hussein's followers commenced the Sunni-Shia divide. It is told that ‎
Yazid showed Muawiyah the severed head of Hussein.‎

than the days of your captivity. ‎
And you call yourselves humans......‎
On his balcony Yazid is displaying the vanities of your nudity ‎
handing them out like lamb meat
to the army of apostasy8!‎
And you call yourselves Arabs...‎

There is doubt

from Jiddah to Baghdad ‎
Because I saw you
on sidewalks of infested streets ‎
making night into your trade. ‎
The days of famine?‎
It is apostasy that killed us!‎

Within us we carry the one who is against us.‎

My mother made me from the honey of night and the fowers of fgs

She left me on the warm soil of the garden for the green ants to grow in my heart ‎
I dreamt there, of a knife.‎
Where have you left your regrets, my love?‎

They came through the bridge of drunkenness and died ‎
One after the other
My lip trembled, I stared at the wine

I dipped my hand inside and stamped my fnger on my heart... I shall be drunk!‎
‎8‎	The Wars of Apostasy were a series of military campaigns launched by the frst Caliph Abu Bakr against rebel Arabian ‎
tribes during 632 and 633 AD. The rebels' position was that they had submitted to God but owed nothing to the Caliph.‎

Drunk... Drunk... Drunk... ‎
Because the world is full of night
How can you admonish me? How can I repent?‎

Is the gull redeemed by the weight of his broken wings?‎

Is the perfume redeemed in the dirty body of a frightened woman? ‎
Is the creator redeemed by the wine of his creation?‎
Does he wipe his hands in the burdens of the earth? ‎
Come to the secret garden and I will show you God ‎
In the smallest bud of a fower spreading perfume
on feet contaminated by the passion for riding horses ‎
In the sudden melting of the feminine suffx
As long as there is pain
Then the night is for the wolves ‎
And wine is my abode
And my body is strange and sensual.‎

My mother made me in a night of love

I dripped and asked the snow of man when it will melt ‎
She left me on the soil
For the poor to collect me

A stranger passed by, knowing the fate of a fower ‎
he handed his sins to my soul
and dropped this letter!‎

In this hour of nightly lusts my vessel hungers ‎
The words approach their seeping
On the tenth of April I cried on the doorstep of Ahvaz9‎
The fesh of my thighs broke from the water's blades in the night

I took some wild weeds packed with delicious smells and closed my wounds with them

But the mosquitos gathered around the ribbon of paradise tightened as a vow around my leg ‎
I called:‎
The gods of earth shall discover me ‎
And I will kill in the wilderness
The wind on the horizon of Basrah calls to me

The hand of clay wipes the fre of madness from my yearning forehead!‎

On the tenth of April I left my eyes on the doorstep of Ahvaz ‎
The road fies gathered around the child's mouth
I saw the Persian girls washing in the morning ‎
Their breasts rising like a cat's head in the bath
I die for a breast that rules more than a king in the night

I die for them, rising to my harsh shadow with the fear of a faithful bird in water ‎
Who is this man clothed in all the fowers of the palm?‎
Lust faring in him as he sees the pregnant palm in the night ‎
Sensual in the fesh of women as the sweet and virile sword?‎
 
‎9‎	Footnote by poet: "An Arab city raped by colonialism and left a prisoner for the Iranian Shah. It was the first city I ‎
arrived in on April 10th in the year of the massacre, having survived the massacre with my skin, and sadness and ‎
estrangement from the remains of the stone age... And my anger..." Tha reference to a massacre here is presumed to be ‎
the massacre of Communists and other dissidents during the1963 "Ramadan Revolution", a CIA backed coup d'etat in ‎
which the Iraqi Ba'ath Party overthrew Prime Minister Abd al-Karim Qassem, who in a 1958 coup had eliminated the ‎
Iraqi monarchy.‎

Who is this man, holding the reins of all the rivers leaking on the sunsets like the morning nude, ‎
evading all the familiar roads in the gardens of salt
facing the wolf of this world without a knife?‎

Oh doors of the gardens of Ahvaz ‎
I die lovingly
Oh doors of Ahvaz... I die lovingly

I left the occupied paradise as a river sadly escapes the sewers ‎
I carry the dirt of this world
The river safely keeps its course

The river keeps.. keeps.. it keeps safely ‎
Where is a woman to light all my lanterns? ‎
The night sadly rapes the soul
Oh God it is your clay that life is dying in, lighting the match of madness ‎
It is your clay stamped with fngerprints, debauched by consciousness ‎
thrown around by many roads in the rainy night of exile
It is your clay... your clay... your clay!‎
The poems pointed you to me

so how can I point to you in the embers of my poetry?‎

The tears made me soft as a wedding veil ‎
I don't hurt anyone
Take me,‎

With your lantern wipe the night spread with secrets

Don't blame the heretic in this age of heresy ‎
For hunger is the father of all heretics!‎
My ruler,‎

I am in the line of heretic hunger while the other line prostrates from the weight of all the ministers!‎

I charm you: Be angry with me!‎

My wing is wrapped around you in the dawn ‎
The god of stars of sea!‎
I have sailed to you as the last bird of wilderness ‎
They were about to hunt me down
God of sea! They will fnd me ‎
They will fnd me!‎
Your soil pulls on my swollen feet ‎
Running in my enemy's heart, screaming: ‎
They will fnd me!‎
God of sea! Can't you smell the distance of the bloody knives? ‎
Save what is absolute in man!‎
The remains of the stone age haunt me ‎
Save me from my country!‎

The spirit of the absolute looked upon my feeble body clad in hardship and narcissus and time ‎
The wind of absence carried me to a path glistening with the buds of morning
And the frst bird on the blue horizon chirped, infected: ‎
‎"Trust trust trust!"‎

The smell of bread awoke in the village ‎
I was taken by me tiredness and lust ‎
And my inherent hunger for man ‎
There was a knock on a closed door
A voice called to me ‎
The voice was a female
And estrangement when it embraced me was a female ‎
And the entrance was a female when it asked me: ‎
Who is this?‎
I answered like fre extinguished in the plains: ‎
It is me, my country.‎
Who displaced this village from my country?‎
Who put masks on the faces of people and the Iranian calendar? ‎
Who displaced the river fortifed with palms in Ahvaz?‎
Jamdanis, Buyyids, Seljuks and Mamluks, answer me! ‎
Oh strangers, my country is like smuggled crates of tea ‎
I cry for her in the laps of strangers
These laps are humiliating

My country, until when will you be an oil tanker smeared with the grime of grief and the fags of the big ‎
countries?‎

If night went mad

then the glasses clink that Jerusalem is the bride your Arabness

Ahlan, Ahlan, Ahlan!‎

But who sold Palestine if not the clerks of revolution?‎

I swear on the bottlenecks of wine and the cup of poison,‎

I swear on the revolutionary who gorged on oysters in Beirut ‎
and grew a gut so large that he lost neck
I swear on the history of hunger and the day of famine ‎
Not one of us will remain
if we remain in this state, of Hisba.‎

Jerusalem is the bride of your Arabness

So why did you usher the night's fornicators into her bedroom ‎
and listened behind doors to the screams of her virginity ‎
Gently pulling out your daggers... swelling with pride ‎
Quieting her to safeguard your image
How honorable you are! You sons of bitches... ‎
To be raped quietly?‎
You sons of bitches I am not afraid of being honest with you ‎
A pig sty is purer than the purest of you
The bed of the deceased shudders ‎
but your casbah never moves
So now I shall expose you
You killed my joy in all the capitals ‎
I saw your thugs in all the alleys
I warned the walls, I warned the telephone

I even warned the children.‎

Let us go before the desert and be judged ‎
I admit now, before the desert
That I am dull and indecent and sad ‎
That I am as vile as your defeat
Oh defeated honorables ‎
Oh defeated rulers
Oh defeated audience ‎
How dirty we are ‎

**Comment by smoge** [comment] 2024-06-04 12:37
> This looks really useful, thank you!

I'm not sure where this should go (SCDoc, wiki, other?).

**Comment by JordanHendersonMusic** [comment] 2024-06-13 12:36
> I'm not sure where this should go (SCDoc, wiki, other?).

My opinion would be for the byte code stuff to go in the source code in comments are renaming things. 

Documenting how the interpreter works and differs from the standard approach is a good idea, but I think it would be best as a developer resource, so probably here on a github wiki page — it would also make a good scsynth wiki! 
Then, the sc documentation in the help browser that speaks of developing primitives and stuff could just link to it. This way, updating it is independent from supercollider's releases.

Unpicking how the interpreter bootstraps itself with the intrinsic classes and whatnot would be really useful too.

If this became a wiki, I'd like like to contribute by writing about the calling protocol and how the stack works, with keyword args and variable arguments (and potentially variable keyword arguments) this is more complex than you might expect since it changes depending on whether you call a method in sc or a primitive.

I'd also love to write about the gc which I've spent some time digging in and was considering doing anyway.

**Comment by smoge** [comment] 2024-06-13 12:50
> I'd also love to write about the gc which I've spent some time digging in and was considering doing anyway.

That's my man. Do it.

**Comment by smoge** [comment] 2024-06-13 21:22
Is there a guideline already for the formatting of documentation comments? I wrote what I saw in other projects in a (closed) discussion. Maybe we can chat sometime to put together a proposal.

**Comment by mossheim** [comment] 2024-06-14 07:28
I guess you adapted this draft from my previous work, or perhaps a reproduction of it somewhere else? I'm disgusted that someone who talks so much about GPL and copyright doesn't bother to credit and tries to pass it off as their own. I've clarified that it's CC-BY-SA now.

https://gist.github.com/mossheim/939297a6421a4ea6c5f96cf3f1f0069e

**Comment by telephon** [comment] 2024-06-14 08:27
Yes, even without the licence it would have been polite to acknowledge the source, everybody should take care to do this adequately. 

@smoge please keep this in mind in particular. It really looks as if this had been your own draft:
>Below is an initial incomplete DRAFT:

This should not happen.

**Comment by smoge** [comment] 2024-06-14 09:51
????

**Comment by smoge** [comment] 2024-06-14 09:53
@brian, I didn't even know you were on github

**Comment by smoge** [comment] 2024-06-14 09:59
I didn't even know you were on github, it would not be possible to copy this gist. But I can give you credit, I don't care. Put please don't try to make it turn into some crazy accusation. It's all in the source code. a macro can do this easily

**Comment by smoge** [comment] 2024-06-14 10:11
The idea is not just this reference but to change the code to make it more self-documented, As the communication above reflects.

**Comment by telephon** [comment] 2024-06-14 10:41
Ah ok, I see. Thank you for the clarification. Maybe, to be just absolutely clear, could you post a link to the part of the source code that it was derived from?

And yes, of course it makes a lot of sense to make this more accessible as a proper documentation. This is a good idea!

**Comment by smoge** [comment] 2024-06-14 10:44
> Ah ok, I see. Thank you for the clarification. Maybe, to be just absolutely clear, could you post a link to the part of the source code that it was derived from?
> 
> And yes, of course, it makes a lot of sense to make this more accessible as proper documentation. This is a good idea!

I've been talking about it for a while, and those two colleagues agree with me. I talked about it with Scott Wilson 1 or 2 months ago, for example.

**Comment by capital-G** [comment] 2024-06-14 10:58
> (Also, I don't even know you, and I don't have anything against you. From my part, I don't remember a discussion even on technical things with you more than very few times in many years)

I'd think you should be familiar with Moss as their contributions were and are really important for this project, and their concerns are really valid in this case and there should be no discussion about any kind of attribution. It is really nice of them that they decided it to make it possible to share the text via CC-BY-SA. Copyright and attribution should always be respected, especially in an open source project! Please be more sensible about this topic in the future.

I'd also like to point to our code of conduct in this regard.

**Comment by smoge** [comment] 2024-06-14 11:02
```
2. Using Notes
One of the most serious difficulties in a large, long-lived project is keeping technical documentation up to date. We have no silver bullet, but we offer one low-tech mechanism that has served us particularly well: Notes.

2.1 Notes: the basic idea
When writing code, there is often a moment when a careful programmer will mentally say something like "This data type has an important invariant". She is faced with two choices, both unsatisfactory. She can add the invariant as a comment, but that can make the data type declaration too long, so that it is hard to see what the constructors are. Alternatively, she can document the invariant elsewhere, and risk it going out of date. Over twenty years, everything goes out of date!
Thus motivated, we use the following very simple convention:


Comments of any significant size are not interleaved with code, but instead set off by themselves, with a heading in standard form, thus:

    Note [Equality-constrained types]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The type   forall ab. (a ~ [b]) => blah
    is encoded like this:

       ForAllTy (a:*) $ ForAllTy (b:*) $
       FunTy (TyConApp (~) [a, [b]]) $
       blah

At the point where the comment is relevant, we add a short comment referring to the Note:

   data Type
     = FunTy Type Type -- See Note [Equality-constrained types]

     | ...
The comment highlights that something interesting is going on, and gives a precise reference to the comment that explains. It sounds trivial, but the precision is vastly better than our previous habit of saying "see the comment above", because it often was not clear which of the many comments above was intended, and after a few years the comment was not even above (it was below, or gone altogether).


Notes should be copiously illustrated with concrete examples, and should point specifically to tickets that give relevant background detail.  The extra space afforted by a Note (rather than an inline comment) makes it easy to to give such examples without breaking up the code it describes.


Not only is it possible to go from the code that refers to the Note to the Note itself, but the reverse is also possible, and that is often useful. Moreover, the same Note may be referred to from multiple points in the code.
This simple, ASCII-only technique, with no automated support, has transformed our lives: GHC's source code has thousands of Notes, and the number grows daily.
We have a lint check in CI to identify references to Notes that don't exist.

2.2 Overview Notes
Suppose you wonder "how is unsafeCoerce implemented in GHC?", or "how are
floating-point literals represented at compile time?" or "what does it mean
to say that two types are equal in GHC?".  There is often no one bit of code that will answer such questions. *But there can be one Note!"
We strongly encourage overview Notes that summarise how the compiler deals with a particular topic.
An overview Note should


Topic.  Identify its topic/problem.


Design.  Explain the overall design -- give the big picture.


Moving parts.  Point to the "moving parts"; that is, the key bits of code that implement
the feature.  These pointers should be quite specific, referring to
functions and data types by name.  (Those functions and data types should
in turn refer back to the overview Note.)


Wrinkles.  List "wrinkles"; that is, any non-obvious corners that need special treatment.
This overlaps with the previous bullet a bit; again we would typically point
to the specific code that deals with the non-obvious corner.
It is often helpful to give a name to each wrinkle, such as (W7); then you can say (elsewhere) -- See wrinkle (W7) of Note [Wombat].  Precision is so helpful!


A good example of an overview Note is Note [Implementing unsafeCoerce] in the library base:Unsafe.Coerce.
Another is Note [Quasi-quote overview] in Language.Haskell.Syntax.Expr.
Many (not all) MRs would be strengthened by adding a suitable overview Note, that
summarises the overall design.  An overview makes the MR much easier to review.

2.3 Being specific, using examples

Be specific.  Don't just say "we reject overlapping instances in situation X".  Instead point directly to the code that implements that decision.
Offer concrete examples to illustrate the point.  It can be fantastically illuminating to see how some general point plays out in a particular example.
Mention specific tickets and/or testsuite cases that further illustrate the issue.

Here's an example

Note [Put touchable variables on the left]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ticket #10009, a very nasty example:

    f :: (UnF (F b) ~ b) => F b -> ()

    g :: forall a. (UnF (F a) ~ a) => a -> ()
    g _ = f (undefined :: F a)

For g we get [G]  g1 : UnF (F a) ~ a
             [W] w1 : UnF (F beta) ~ beta
             [W] w2 : F a ~ F beta

g1 is canonical (CEqCan). It is oriented as above because a is not touchable.
See canEqTyVarFunEq.
Notice the concrete example, the pointer to [#10009 (closed)](https://github.com/ghc/ghc/-/issues/10009), and the pointer to canEqTyVarFunEq.
Caution: it is easy for these code references to get out of date. But that's a lesser evil.

2.4 Notes describe the present state, not the journey
A commit message describes a change; a comment or a Note describes a state..  That is, a Note or a comment should always describe the current state of affairs, not the journey that led to that state of affairs.
At the moment you write it, the journey is high in your consciousness; but in ten years time, it is at best a distraction, and at worst the Note becomes simply incomprehensible without knowledge of the
previous state of affairs.


Design choices.  A Note can be a good place to document the reasoning that led to a particular decision.  Lacking the reasoning, someone might change the decision later, without realising the consequences.

Historical notes.  Sometimes it can be helpful to have a clearly-signposted section called "Historical note: blah blah" that describes some previous state of affairs. But the "Historical note" signpost signals that you don't need to read it to understand the current compiler.
```

https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/coding-style

**Comment by smoge** [comment] 2024-06-14 11:04
> > 
> 
> I'd think you should be familiar with Moss as their contributions were and are really important for this project, and their concerns are really valid in this case and there should be no discussion about any kind of attribution. It is really nice of them that they decided it to make it possible to share the text via CC-BY-SA. Copyright and attribution should always be respected, especially in an open source project! Please be more sensible about this topic in the future.

When I moved to NYC around 2014, I continued to use SC in my performances and compositions, and I didn't have much time to follow the online community. I tried once around 2018, and then last year.

**Comment by smoge** [comment] 2024-06-14 11:06
> I'd also like to point to our code of conduct in this regard.

What are you saying?

**Comment by capital-G** [comment] 2024-06-14 11:18
> > I'd also like to point to our code of conduct in this regard.
> 
> What are you saying?

I think the discussion in this thread is heated and both parties are not obeying the code of conduct.

https://github.com/supercollider/supercollider/blob/1063f63526e8c6afe38d11b1b04d645138a13d07/CODE_OF_CONDUCT.md?plain=1#L33-L37

**Comment by smoge** [comment] 2024-06-14 11:20
> > > I'd also like to point to our code of conduct in this regard.
> > 
> > 
> > What are you saying?
> 
> I think the discussion in this thread is heated and both parties are not obeying the code of conduct.
> 
> https://github.com/supercollider/supercollider/blob/1063f63526e8c6afe38d11b1b04d645138a13d07/CODE_OF_CONDUCT.md?plain=1#L33-L37

Sorry, I don't understand what you're saying.

**Comment by telephon** [comment] 2024-06-14 12:16
This place here is not the right place for discussing difficult and especially personal issues. One reason for this is that it is higly surveilled.

Let's just stop right here. 

If you like, please close the issue and open a fresh one.

**Comment by mossheim** [comment] 2024-06-14 12:22
@smoge, I am going to use the original texts of your comments since you have a habit of excessively editing things and this often obscures the original intent.

https://github.com/supercollider/supercollider/issues/6336#issuecomment-2167684969

> I didn't even know you were on github, it would not be possible to copy this gist. But I can give you credit, I don't care. Put please don't try to make it turn into some crazy accusation. It's all in the source code. a macro can do this easily

Is this a joke? We have interactions on GitHub going back to at least 2017, and the linked document of mine is from 2018. I shared it on scsynth.org in 2020: https://scsynth.org/t/interpreter-bytecode-documentation/2308. You have *very clearly* plagiarized my work and tried to pass it off as your own here. The "draft" layout, organization, and many strings of words are identical. I have included some comparisons at the end of this comment.

I spent many hours on my document and much of the information was not easy to find -- I had to stitch it together from comments and reading control flow in multiple files. (This is especially true of the loop instructions under 8F which you edited out.) So I don't buy that you took it directly from the source code in some automated way.

https://github.com/supercollider/supercollider/issues/6336#issuecomment-2167704545

> The idea is not just this reference but to change the code to make it more self-documented, As the communication above reflects.

In that case, you could have just linked directly to my post or gist? I don't understand why you took the time to manually edit my work and include it here without attribution, since you said you are low on bandwidth. You are absolutely free to use my work, I just ask for proper acknowledgement.

Just a few comparisons, using the original form of the issue submission:

---

Mine:

<img width="619" alt="image" src="https://github.com/supercollider/supercollider/assets/15369640/d9921515-67f2-495e-b5f2-5a2caba361e2">

Yours:

<img width="619" alt="image" src="https://github.com/supercollider/supercollider/assets/15369640/dd262695-bbe6-42f9-9446-c9b0d5aa2643">

Note the identical ordering, terminology ("literal array types"), and how your sloppy edit made "special selectors" look as if it's a kind of intrinsic class even though it isn't. I don't believe this exact terminology ("introspective types", "stream and sound types") is present anywhere in the source code. In fact the word "introspective" itself doesn't even appear anywhere in the repository.

I don't see how we could have both arrived independently at the same ordering and grouping of names here. Looking at some of the places the list of intrinsic/special classes is given in the code, none of them match:
https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/Opcodes.h#L378
https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/PyrObject.cpp#L71
https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/PyrObject.cpp#L185
https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/PyrObject.cpp#L102
https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/PyrParseNode.cpp#L4291

---

Mine:

<img width="501" alt="image" src="https://github.com/supercollider/supercollider/assets/15369640/acb02b6f-c44a-46f9-8668-d897535982e1">

Yours:

<img width="574" alt="image" src="https://github.com/supercollider/supercollider/assets/15369640/e42bb48d-60cb-45c8-a0fa-bacd4e79969a">

It's hard to believe it's a coincidence that we came up with nearly the exact same presentation for the table, and that you included "(not asInteger)" which was a note to myself and not present in the source code.

---

Mine:

<img width="633" alt="image" src="https://github.com/supercollider/supercollider/assets/15369640/206fcf06-c8e4-4cea-bb06-d0cd5c2a019c">

Yours:

<img width="563" alt="image" src="https://github.com/supercollider/supercollider/assets/15369640/3463ee95-2200-4024-b072-0be8e3dd27d0">

These sections are nearly identical.

**Comment by telephon** [comment] 2024-06-14 12:43
Thank you for the clarification, @mossheim, and yes, @smoge I'll close it here.

**Closed by telephon** 2024-06-14 12:43 UTC
Labels: enhancement
