### ISSUE TITLE
Disappearing examples in the Scide Tutorial

### ISSUE THREAD

**Issue by jargenty** [supercollider/supercollider#4584] opened 2019-09-19 16:35 UTC
Bug description:
In the SCide Tutorial, the code examples do not appear in my configuration. Linux Lubuntu kept up to date, version 3.10 of SC. Maybe it's a bug or a problem related to an incomplete installation, I do not know. I tried an unsuccessful reinstallation and a reboot after deleting the configuration files without success either.
Steps to reproduce:
1.
2.
3.

Actual result:

Expected result:

**Comment by jargenty** [comment] 2019-09-19 19:23
If I launch SCide from the terminal, it starts but I get this:

*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 215
* source ID: "file:///home/jargenty/.local/share/SuperCollider/Help/scdoc.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: CodeMirror is not defined"
* line: 3
* source ID: "file:///home/jargenty/.local/share/SuperCollider/Help/editor.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 157
* source ID: "file:///home/jargenty/.local/share/SuperCollider/Help/scdoc.js"

**Comment by brianlheim** [comment] 2019-09-20 01:34
Duplicate of https://github.com/supercollider/supercollider/issues/4367, thanks for reporting!

**Closed by brianlheim** 2019-09-20 01:34 UTC
