### ISSUE TITLE
alwaysOnTop breaks the window's icon

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#522] opened 2012-09-21 06:57 UTC
```
w = Window.new.front;

w.alwaysOnTop = true;
```

In the above, creating the window is fine: the window takes the sccube icon. Then, setting alwaysOnTop = true reverts the icon to a generic application icon.

Ubuntu 12.04 with gnome classic. I don't know if the same happens in another OS or window manager.

**Comment by snappizz** [comment] 2016-09-29 22:34
I'm not seeing this bug on Ubuntu 16.04 with xfce.

**Comment by jamshark70** [comment] 2016-10-01 02:26
I'm not using Gnome Classic anymore, so I can't speak to the original issue. Gnome-shell 3.10.4 does not have this problem.

**Comment by patrickdupuis** [comment] 2017-05-27 00:44
I cannot reproduce this (current master) with Gnome Classic on Fedora 25 or Ubuntu 16.04.

**Comment by snappizz** [comment] 2017-05-27 00:46
closing because nobody seems to be able to reproduce it anymore.

**Closed by snappizz** 2017-05-27 00:46 UTC
Labels: bug, comp: Qt GUI, os: Linux
