### ISSUE TITLE
WebView's onLinkActivated function never executes

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2565] opened 2016-12-17 11:55 UTC
```
(
w = WebView(nil, Rect(800, 200, 500, 400)).front;
w.html = "<body><p>Here's a <a href=\"test.html\">link</a></p></body>";
w.onLinkActivated = { |view, url| url.debug("clicked") };
)
```

If you click on the link, the webview goes to an empty page and *nothing* is posted -- meaning that the `onLinkActivated` function is not executed. That's bad.

Among the user impacts: the sclang `Help.gui` interface cannot render help files on demand anymore. So, help is fundamentally broken in emacs, vim and any editor other than the IDE. That's *really* bad. See #2564.

**Comment by snappizz** [comment] 2017-01-15 01:58
Dupe of #2295.

**Closed by snappizz** 2017-01-15 01:58 UTC
Labels: bug, comp: Qt GUI
