### ISSUE TITLE
'plot' in scvim does not work: Message 'use' not understood.

### ISSUE THREAD

**Issue by yuanyelele** [supercollider/supercollider#3887] opened 2018-07-17 06:37 UTC
`{0}.plot` shows an empty window only, with the following error messages, though all is good in scide.

```
ERROR: Message 'use' not understood.
RECEIVER:
   nil
ARGS:
Instance of Function {    (0x55df148f3648, gc=CC, fmt=00, flg=00, set=02)
  instance variables [2]
    def : instance of FunctionDef in Method Plot:init
    context : Frame (0x55df14733608) of Plot:init
}
CALL STACK:
        DoesNotUnderstandError:reportError
                arg this = <instance of DoesNotUnderstandError>
        Nil:handleError
                arg this = nil
                arg error = <instance of DoesNotUnderstandError>
        Thread:handleError
                arg this = <instance of Thread>
                arg error = <instance of DoesNotUnderstandError>
        Object:throw
                arg this = <instance of DoesNotUnderstandError>
        Object:doesNotUnderstand
                arg this = nil
                arg selector = 'use'
                arg args = [*1]
        Plot:init
                arg this = <instance of Plot>
                var fontName = nil
                var gui = nil
                var skin = nil
        Plotter:makePlots
                arg this = <instance of Plotter>
                var template = nil
        Plotter:updatePlots
                arg this = <instance of Plotter>
        Plotter:setValue
                arg this = <instance of Plotter>
                arg arrays = [*1]
                arg findSpecs = true
                arg refresh = true
                arg separately = true
                arg minval = nil
                arg maxval = nil
                arg defaultRange = nil
        Plotter:value_
                arg this = <instance of Plotter>
                arg arrays = [*1]
        Function:plot
                arg this = <instance of Function>
                arg duration = 0.01
                arg server = nil
                arg bounds = nil
                arg minval = nil
                arg maxval = nil
                arg separately = false
                var name = "{0}"
                var plotter = <instance of Plotter>
        Interpreter:interpretPrintCmdLine
                arg this = <instance of Interpreter>
                var res = nil
                var func = <instance of Function>
                var code = "{0}.plot
"
                var doc = nil
                var ideClass = nil
        Process:interpretPrintCmdLine
                arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'use' not understood.
RECEIVER: nil
```

**Comment by snappizz** [comment] 2018-07-17 06:41
thanks for the report. is this in 3.9.3, or the latest git version?

**Comment by yuanyelele** [comment] 2018-07-17 07:03
This is the latest git version.

**Comment by gusano** [comment] 2018-07-17 10:40
@yuanyelele what version of `scvim` are you using? I cannot reproduce that..
Are you sure you're using the new repository? https://github.com/supercollider/scvim ?

ps: `vim` issues should go inside that repository

**Comment by yuanyelele** [comment] 2018-07-17 15:24
I am using noevim instead of vim. The problem lines in line 47 of `sc/SCVim.sc`. Everything becomes normal after changing `~/.vim` to `~/.config/nvim`.

I guess you could close this issue. Or better, make SCVim.sc more flexible. Thank you.

**Comment by brianlheim** [comment] 2018-07-17 15:43
You can submit a PR to the scvim project and someone will review it: github.com/supercollider/scvim

At any rate, this issue does not belong in this repo so I'm going to close it. Thanks!

**Closed by brianlheim** 2018-07-17 15:43 UTC
