### ISSUE TITLE
Transparent windows not working

### ISSUE THREAD

**Issue by lukiss** [supercollider/supercollider#5913] opened 2022-11-21 08:48 UTC
Bug description:

Setting the background color of a window to Color.clear does not work in version-3.13.0-rc1 

Steps to reproduce:
1.

(
w=Window("Oh, No!",Rect(
        Window.screenBounds.asArray[2]/2-150,
        Window.screenBounds.asArray[3]/2-150,
        300,
        300),false,false);
w.background_(Color.clear);
w.view.background_(Color.clear);
w.front;
)

Actual result: A gray window.

Expected result: A transparent window.

**Comment by dyfer** [comment] 2022-11-21 10:57
I can confirm this happening on macOS on both the rc1 release and the local build _that used Qt 5.15.6_. However, when I upgraded local Qt to 5.15.7 (the latest version in homebrew at the time of writing this) and re-built SC, the issue seems to have gone away. So... this might solve itself if Qt gets upgraded in the GHA runner, hopefully by the time we make another RC.

**Comment by dyfer** [comment] 2022-12-04 20:33
This seems to be resolved in the most recent builds (e.g. https://github.com/supercollider/supercollider/actions/runs/3614760272) due to upgraded Qt, so I believe this should be fixed in the upcoming 3.13.0-rc2. 
Thanks for the report!

**Closed by dyfer** 2022-12-04 20:33 UTC
Labels: bug
