### ISSUE TITLE
NRT segmentation fault with /status message

### ISSUE THREAD

**Issue by Sciss** [supercollider/supercollider#843] opened 2013-05-13 08:45 UTC
I had just terminated my NRT OSC file with a `/status` message. this seems to cause a segmentation fault (SC 3.6.2 and 3.6.5). i just changed to a dummy `/n_run` and that works, so no big deal.

**Comment by vivid-synth** [comment] 2016-08-01 18:21
@Sciss this is an old issue but can you provide code to reproduce?

**Comment by vivid-synth** [comment] 2017-01-19 04:33
Reproducer:

file "foo.scd":

```supercollider
SynthDef(\NRTsine,{ | freq = 440 |
    Out.ar(0, SinOsc.ar(freq, 0, 0.2))
}).writeDefFile;


x = [

[0.0, [ \s_new, \NRTsine, 1000, 0, 0,  \freq, 440 ]],
[0.5, [ \status ]],
[1.0, [ \s_new, \NRTsine, 1001, 0, 0,  \freq, 880 ]],

[2.0, [\c_set, 0, 0]]
];

Score.write(x, "score-test.osc");

0.exit;
```

> $ sclang foo.scd
> $ scsynth -N score-test.osc _ score-test.wav 44100 WAV int16 -o 1
> $ supernova -N score-test.osc _ score-test.wav 44100 WAV int16 -o 1

scsynth segfaults, supernova doesn't

**Comment by Sciss** [comment] 2017-01-19 18:54
Thanks, you were faster than me :)

**Comment by dyfer** [comment] 2019-09-18 19:55
Supernova similarly crashes when receiving `\d_recv` message. Example:
```supercollider
(
var g;
Server.supernova;
Score.program = Server.program;
g = [
	[0, [\d_recv, SynthDef(\nrt, {Out.ar(0, SinOsc.ar(0.5))}).asBytes]],
	[0.2, [\s_new, \nrt, 1001, 0, 0]],
    [10, [\c_set, 0, 0]] // finish
    ];
Score.recordNRT(g, nil, "~/Desktop/testNRT.wav".standardizePath); // synthesize
)
```
(tested on 3.10.3 on macOS)

**Comment by smrg-lm** [comment] 2020-11-28 13:48
> Supernova similarly crashes when receiving `\d_recv` message. Example:

Running the example here on Linux it is not a crash but that "late" thing:

Supernova booting

Performing non-rt synthesis:
late: 0.000000
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.000000000
late: 0.000000
node id 1 already in use
late: 0.000000

**Comment by smrg-lm** [comment] 2020-11-28 13:59
where is the osc parser in supernova/scsynth nrt part?

**Comment by smrg-lm** [comment] 2020-11-28 15:39
The late things is another thing, this if

https://github.com/supercollider/supercollider/blob/f441a414c42093a1508e2df095f475c4f577eec2/server/supernova/sc/sc_osc_handler.cpp#L847

seems to be wrong because there is not immediate in nrt, it starts from cero, no 1, IIRC.

**Comment by dyfer** [comment] 2020-11-28 18:47
I'm sorry, I realized I hijacked this thread with supernova issue, where the thread originally was only about scsynth. I've opened a new thread for supernova: #5270 @smrg-lm let's continue there.

**Comment by Spacechild1** [comment] 2023-12-19 21:14
This should be fixed with https://github.com/supercollider/supercollider/pull/5616

**Closed by Spacechild1** 2023-12-19 21:14 UTC
Labels: bug, comp: scsynth
