### ISSUE TITLE
Doubly declared variables in classes don't throw an error

### ISSUE THREAD

**Issue by woolgathering** [supercollider/supercollider#3747] opened 2018-05-28 04:08 UTC
Declaring variable twice within a class doesn't throw an error. 

```
DoubleVar {
  var <>myVal, <>myVal;

  *new {
    ^super.new.init;
  }

  init {
    myVal = 1;
  }
}
```

Then,
```
a = DoubleVar.new
a.myVal
```
doesn't throw an error and `a.myVal` is returned as `nil`.

I figure this might have something to do with the fact that the library is yet to be compiled but I find it strange that it can slip through, especially since an "already declared" error is thrown in other contexts _and_ the compiler throws an error if a variable is not declared at all.

SC Version:
```
~$ sclang -v
sclang 3.9.3 (Built from branch 'develop' [87d879c5c])
```

System:
```
~$ uname -a
Linux RAM 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

[edited for typo]

**Comment by brianlheim** [comment] 2018-05-28 04:33
Duplicate of #1201. Please check open issues before submitting a new ticket!

**Closed by brianlheim** 2018-05-28 04:33 UTC
