### ISSUE TITLE
support running without jack on linux

### ISSUE THREAD

**Issue by bburdette** [supercollider/supercollider#1658] opened 2015-09-17 19:29 UTC
I'm working with supercollider on the raspberry pi and similar computers, and using jack can be quite the nightmare to set up, particularly if you are running without X like I am.  On debian, you are required, among other things, to set up dbus configuration files to allow access to the audio devices from jack.  On arch, jackd cannot be automatically started from systemd because of kernel settings (at least that's my latest guess), and so I have to log in through ssh and start jack.  An instrument that requires you to use ssh in order to start it is awkward to say the least.  And even if dbus and the kernel and etc are working, jack is still complex to configure and set up, and it an extra point of failure, AND it adds latency.  

For my purposes - building an instrument that uses supercollider for sythesis - jack is a needless boondoggle that I would be 10x better off without.  How about a mode where supercollider uses portaudio instead of jack?

**Comment by telephon** [comment] 2015-09-17 20:05
Sounds like a good idea, let's see if someone can implement it.

**Comment by danstowell** [comment] 2015-09-17 20:21
Already exists. Set the cmake flag AUDIOAPI to portaudio

However, it's not been maintained for years - because no-one used it, it would be quite a surprise if it works

**Comment by bburdette** [comment] 2015-09-17 21:05
yep I compiled it and it didn't work for me.  should I file a bug to that effect?  that's what this is supposed to be.  Or don't bother because you'll just close that one?

**Comment by bburdette** [comment] 2015-09-17 21:10
actually what would be better than a compile time flag would be a runtime switch for jack/notjack.  Otherwise of course no one would use it because they'd have to compile from source.

**Comment by jamshark70** [comment] 2015-09-18 01:18
Reopening then... However, you'll need to provide more information about what doesn't work. "I compiled it and it didn't work for me" is not much for anyone to go on.

The point remains, who is going to do the work? It's easy to say we ought to have this, but a bit harder to demand someone else commit time to it.

**Comment by bburdette** [comment] 2015-09-18 01:34
I get it if you guys have a policy of not keeping 'wish list' bugs on your books.  I have a disk image from when I gave that a shot a few months ago, I'll fire it up and see what it does.  If I remember correctly it ran but no audio happened, but it didn't crash.  Anyway, will report back.

**Comment by jamshark70** [comment] 2015-09-18 04:29
There's no policy against wish list items - speaking for myself, I think you have a valid use case (so I reopened the issue). I just have no idea who is going to work on it. It's outside of my expertise :(

**Comment by danstowell** [comment] 2015-09-18 05:39
Dear @bburdette, it's fine to have an issue saying something like "fix portaudio support". The text that you put in the title and the content of this issue led me to believe that you didn't know the feature already exists. I've no intention of closing issues too soon! It doesn't matter to me if it's this issue re-titled or a new issue. It would be good to have the details from you of what happens when you try the portaudio method.

**Comment by danstowell** [comment] 2015-09-18 05:41
Regarding compile-time bs run-time: one could make a special package "supercollider-server-portaudio" or "supercollider-server-nojack" with the server compiled to use portaudio. That's a common pattern in debian packaging.

**Comment by timblechmann** [comment] 2015-09-18 07:08
fwiw, the quality of the portaudio backends is quite different on different platforms. portaudio/win or portaudio/coreaudio have a much better quality than the jack/alsa backends, which was the reason why i'm having a native jack interface in supernova.

"it didn't work" is of course not a useful bug description and it doesn't say if it doesn't work, because the portaudio configuration was invalid (wrong sample rate or the like), there is a bug in scsynth's portaudio backend or if there is a bug in portaudio ...

**Comment by sonoro1234** [comment] 2015-09-24 07:12
I am waiting for @bburdette answer as I would be able to take care of it.
I have previously done the opposite: compiling in windows with jack which lets routing audio between programs.

**Comment by sonoro1234** [comment] 2015-09-24 07:14
Another option would be implementing a RtAudio sc-driver.

**Comment by bburdette** [comment] 2015-09-26 16:24
I haven't forgotten about this!  My SD card image with the supercollider compile on it is a little larger than the actual SD cards I have, so I thought I'd try compiling it on my x86 machine, but that's nixos and is presenting some difficulties.  I'm going to give it another shot on ARM today and hopefully will have some test results for you.

**Comment by bburdette** [comment] 2015-09-26 21:21
Ok here's the normal response from scsynth when I start it with jack:

```
*** ERROR: open directory failed '/home/bananapi/.local/share/SuperCollider/synthdefs'
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 1024
SuperCollider 3 server ready.
Zeroconf: failed to create client: Daemon not running
JackDriver: max output latency 23.2 ms
FAILURE IN SERVER /g_freeAll Group 1 not found
```

So that's normal; that  FAILURE IN SERVER is how I know my program has connected.  Below is the result with the portaudio version of scsynth.  It starts normally and the latency number looks way better than 23.2ms, but it doesn't respond to commands apparently.  My program hangs when it tries to load its synths and etc.  

```
[bananapi@lemaker ~]$ ./scsynth_portaudio -u 57110 -H hw:1,0
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.front.0:CARD=0'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.sunxi-CODEC.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4260:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4739:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
*** ERROR: open directory failed '/home/bananapi/.local/share/SuperCollider/synthdefs'

Device options:
  - ALSA : sunxi-CODEC: PCM (hw:0,0)   (device #0 with 2 ins 2 outs)
  - ALSA : Sound Blaster X-Fi Go! Pro: USB Audio (hw:1,0)   (device #1 with 2 ins 2 outs)
  - ALSA : sysdefault   (device #2 with 128 ins 128 outs)
  - ALSA : default   (device #3 with 128 ins 128 outs)
  - ALSA : dmix   (device #4 with 0 ins 2 outs)
  - OSS : /dev/dsp   (device #5 with 16 ins 16 outs)
  - OSS : /dev/dsp1   (device #6 with 16 ins 16 outs)

Booting with:
  In: ALSA : Sound Blaster X-Fi Go! Pro: USB Audio (hw:1,0) 
  Out: ALSA : Sound Blaster X-Fi Go! Pro: USB Audio (hw:1,0) 
  Sample rate: 44100.000
  Latency (in/out): 0.009 / 0.009 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Zeroconf: failed to create client: Daemon not running
```

**Comment by sonoro1234** [comment] 2015-09-27 09:00
Could you try sending dumpOSC and whatever command afterwards for testing communication with server?

**Comment by bburdette** [comment] 2015-09-27 23:13
should I be getting a result from this?
    
    oscsend localhost 57110 "/dumpOSC"

**Comment by bburdette** [comment] 2015-09-28 00:49
Ok I was able to get scsynth_portaudio to emit some text to stdio like so:
```
[bananapi@lemaker bananapipro_arch]$ oscsend localhost 57110 "/dumpOSC" i 0
[bananapi@lemaker bananapipro_arch]$ oscsend localhost 57110 "/dumpOSC" i 10
[bananapi@lemaker bananapipro_arch]$ oscsend localhost 57110 "/dumpOSC" i 1
[bananapi@lemaker bananapipro_arch]$ oscsend localhost 57110 "/dumpOSC" i 1
[bananapi@lemaker bananapipro_arch]$ 
```
which results in this:

```
Device options:
  - ALSA : sunxi-CODEC: PCM (hw:0,0)   (device #0 with 2 ins 2 outs)
  - ALSA : sysdefault   (device #1 with 128 ins 128 outs)
  - ALSA : default   (device #2 with 128 ins 128 outs)
  - ALSA : dmix   (device #3 with 0 ins 2 outs)
  - OSS : /dev/dsp   (device #4 with 16 ins 16 outs)

Booting with:
  In: ALSA : sunxi-CODEC: PCM (hw:0,0) 
  Out: ALSA : sunxi-CODEC: PCM (hw:0,0) 
  Sample rate: 44100.000
  Latency (in/out): 0.070 / 0.070 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Zeroconf: failed to create client: Daemon not running
size 20
   0   2f 64 75 6d  70 4f 53 43  00 00 00 00  2c 69 00 00   |/dumpOSC....,i..|
  16   00 00 00 01                                          |....|

[ "/dumpOSC", 1 ]
```

**Comment by sonoro1234** [comment] 2015-09-29 06:46
Sorry, as an win32 ASIO-PortAudio user I cant see anything suspicious.
http://portaudio.com/docs/v19-doxydocs/compile_linux.html is the only reference for compiling.

**Comment by danstowell** [comment] 2015-10-02 22:22
Hi @bburdette - thanks for testing and reporting. I just tried it myself, on Ubuntu Linux on a standard x86_64 machine. It compiles and works fine. All I had to do was set the cmake flag "SC_AUDIOAPI=portaudio", and of course I had to have the portaudio dev libraries installed and available. (So in general, it looks like, yes we do still "support running without jack on linux". But that's not your real question.)

I've put my console output here from running a simple sclang session:
https://gist.github.com/danstowell/f47f9b9f73b713f9bb03
You'll notice that portaudio/alsa does output a little bit of blurb but none of the "snd_func_refer" stuff from your paste. Also, unlike your paste it doesn't say "Unknown PCM front" (although it does fail to find a couple of other PCMs), and then later on I can see that "front" is available and is presumably being used.

It seems rather possible that your problem is simply something to do with your alsa configuration / portaudio configuration, and if you can get it the appropriate soundcard detected then maybe it'd simply work. I'm not in a position to test on the same hardware as you so I can't be certain, but that would be my first test. In other words, @bburdette do you have other programs on that device which use portaudio *and* output sound as expected?

**Comment by bburdette** [comment] 2015-10-03 21:34
I don't have a portaudio program that works (or one at all, right now).  I have used portaudio programs in the past successfully on these ARM computers, but haven't tried on this particular setup yet.  I'm thinking of trying out csound and I think that might use portaudio so will report back with results there.  

So with scsynth I get different results depending on hw:0,0 or hw:1,0, it turns out.  hw:0,0 is closer to working, but it appears to lack some ugens that may be specific to jack.  It might be possible to modify my code to work, not sure.  

At any rate, with my program and hw:0,0 these are the results:

https://gist.github.com/bburdette/0ebefe04280d55176152

With hw:1,0 the picture is not so rosy; my program fails to progress beyond the first few commands.  

https://gist.github.com/bburdette/0ebefe04280d55176152

The native sound output is pretty horrible for the bananapi, so not having hw:1,0 working is kind of a deal breaker.  Anyway, interesting what's working... 

Kind of an aside, but sclang on that computer fails like this:

```
[bananapi@lemaker ~]$ sclang
init_OSC
empty
compiling class library...
QPixmap: Cannot create a QPixmap when no GUI is being used
QPixmap: Cannot create a QPixmap when no GUI is being used
Segmentation fault (core dumped)
[bananapi@lemaker ~]$ 
```

**Comment by danstowell** [comment] 2015-10-03 22:12
@bburdette with your log of hw:0,0, the message `exception in GraphDef_Recv: UGen 'Control' not installed` is a classic error message, which tells you that scsynth has found NONE of its ugens. The issue is not that some ugens are related to jack (as you hypothesised) - the issue is that you probably haven't built/installed the ugen DLLs, or maybe scsynth is not able to load them due to location or permission issues.

Re your log of hw:0,1 I don't see any reason the server shouldn't respond so I don't have a diagnosis. You might want to check that it's able to grab the port 57110, just in case that's causing your issue in that case (e.g. make sure no other scsynth processes are still running).

Regarding your `sclang` problem it might help to set the cmake build flag SC_QT=OFF.

**Comment by bburdette** [comment] 2015-10-03 23:23
Ok I repeated the test from above where I sent these messages:

```
[bananapi@lemaker bananapipro_arch]$ oscsend localhost 57110 "/dumpOSC" i 0
[bananapi@lemaker bananapipro_arch]$ oscsend localhost 57110 "/dumpOSC" i 10
[bananapi@lemaker bananapipro_arch]$ oscsend localhost 57110 "/dumpOSC" i 1
[bananapi@lemaker bananapipro_arch]$ oscsend localhost 57110 "/dumpOSC" i 1
[bananapi@lemaker bananapipro_arch]$ 
```

With "hw:0,0" I get some output from scsynth (as in the post up above), but with "hw:1,0" I don't.  

Re sclang, I was using the one that comes with arch rather the one that I compiled, I'm pretty sure I turned off QT when I compiled.  

Re the ugens, yeah I basically just copied the scsynth executable over to the target machine.  I don't want to install over my working scsynth on this SD image, so I'll make another SD to test with.

**Comment by bburdette** [comment] 2015-10-04 03:06
Ok great!  After making a duplicate SD and actually doing a proper install, scsynth works correctly on hw:0,0.  On hw:1,0 it still has the same problem of being unresponsive to OSC messages.  With the crappy onboard audio on the bananapi I think latency on hw:0,0 may be worse than going through jack and the hw:1,0 device.  But definitely a win to get it working at all.  I might give it a go with a few other usb audio devices I have laying around, to see if its all usb audio devices or just one in particular that gives it trouble.  For real low latency there's an i2c audio card for raspberry pi that I want to try out too, but I don't actually own one of those yet.  

So at any rate it looks like yes supercollider does work with portaudio on the ARM, albeit only on hw:0,0.  Should the hw:1,0 issue be filed as a separate bug maybe?

**Comment by bburdette** [comment] 2015-10-04 03:22
That onboard audio has pretty impressive latency numbers, impressive in a bad way.  70ms is pretty noticable.  

```
Booting with:
  In: ALSA : sunxi-CODEC: PCM (hw:0,0) 
  Out: ALSA : sunxi-CODEC: PCM (hw:0,0) 
  Sample rate: 44100.000
  Latency (in/out): 0.070 / 0.070 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Zeroconf: failed to create client: Daemon not running
```

whereas the usb audio dongle is only 9ms.  

```
Booting with:
  In: ALSA : Sound Blaster X-Fi Go! Pro: USB Audio (hw:1,0) 
  Out: ALSA : Sound Blaster X-Fi Go! Pro: USB Audio (hw:1,0) 
  Sample rate: 44100.000
  Latency (in/out): 0.009 / 0.009 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Zeroconf: failed to create client: Daemon not running
```

**Comment by danstowell** [comment] 2015-10-04 09:21
@bburdette great! congratulations.

Re the hw:1,0 issue: yes it would make sense to file a separate bug, so we can be clear about what the problem is. The most useful, I suggest, would be if you can recreate the problem on your arch machine - maybe using the same usb card(s)? If you do that it will (a) confirm whether it's a general problem rather than pi-specific; (b) make it easier for others to reproduce and fix your issue.

**Closed by danstowell** 2015-10-04 09:21 UTC
Labels: cannot reproduce, comp: build, comp: scsynth, os: Linux

**Comment by hzulla** [comment] 2015-12-02 21:58
Hi @bburdette !

Using scsynth without Jack could be a major improvement for Sonic Pi on Raspbian and other Linux desktops, for the same reasons as yours. Therefore I wanted to ask if you have made any further experiences down that road. Did you make progress / is it stable?

**Comment by bburdette** [comment] 2015-12-02 22:46
Hi Hanno!

So I did eventually get sc to compile and even make sound without jack.  
However I was unable to coax it to change from the default audio output 
device, which as you know is utter pants on the raspberry pi, 
particularly in the area of latency.  I did explore removing the default 
audio drivers and installing only the drivers for the device I wanted to 
use, making the desired device into dev 1, but it turns out that the 
audio driver is sort of baked in and you can't disable it individually, 
although I'm not sure now if that was on the banana pi or the raspberry 
pi.  In either case, a hassle and defeating the purpose of being easier 
to deal with.

On the plus side, I found out that jack 1 doesn't have the dependence on 
the dbus that jack 2 has, making it the jack of choice for headless 
audio.  I was interpreting the lack of dbus hassle on arch as something 
to do with arch itself, but it appears it was my random choice of jack 1 
rather than jack 2.  Furthermore the creator of jack 1 claims that there 
is zero added latency for connecting something straight to the audio 
outputs.  I can't verify that with any testing of my own unfortunately.

I've been working on another project for the last couple months, so I 
haven't done a lot more with SC or anything else.  I've been using 
haskell to trigger SC sounds, and I changed to rust and faust for a test 
and it was subjectively more responsive.  I'm thinking about trying out 
some soft synths too.

If you'd like more information re the SC stuff, let me know!  I filed a 
bug on supercollider re this, it may still be open.  I think I still 
have the directory where I built SC, I had to do some tweaking to get it 
to build.

Ben

**Comment by hzulla** [comment] 2015-12-03 07:11
@bburdette did you use pure Alsa or did you try with PulseAudio? The latter may be able to route the audio to your desired soundcard. (Will try that later, too.)

**Comment by bburdette** [comment] 2015-12-03 07:55
I didn't try pulseaudio - I was under the impression that pulseaudio introduced latency and my main focus has been on reducing latency.

**Comment by hzulla** [comment] 2015-12-03 08:04
Ah, OK. Latency wouldn't be a problem for Sonic Pi.

**Comment by danstowell** [comment] 2015-12-03 08:25
@bburdette @hzulla I don't use the Portaudio driver, but looking at the source code right now, it looks to me like you should be able to use any device. When the driver starts (see function `SC_PortAudioDriver::DriverSetup` in the C++ code), it asks PortAudio for the input device named in the options. Therefore what you need to do, before booting the portaudio-compiled-scsynth, is:

          s.options.device = "HERXYBOT";

where you replace HERXYBOT with the actual device name you want. I don't know exactly what string you should be using. It depends on your system. I think portaudio-compiled-scsynth will print out the available device strings as it boots.

**Comment by hzulla** [comment] 2015-12-03 09:20
@bburdette @danstowell that's really good news for what I intend to do with it. I'll have a look if it works.

**Comment by hzulla** [comment] 2015-12-03 09:24
@danstowell so there is only one AUDIOAPI compiled into scsynth, no runtime switch available and one needs to compile a separate binary to use the portaudio api?

**Comment by danstowell** [comment] 2015-12-03 09:38
@hzulla yes

**Comment by hzulla** [comment] 2015-12-03 12:38
(No success so far. I have downloaded the debian source package for supercollider 3.6.6~repack-2-1build1 and added `-DAUDIOAPI=portaudio` in debian/rules. It compiled and the binary does use portaudio, I can also tell scsynth to use different sound hardware, but there is no sound arriving in Pulseaudio on Ubuntu yet.)

**Comment by hzulla** [comment] 2015-12-03 13:36
Here's what I did on an amd64 desktop running Ubuntu 15.10.

- built a jack-less version of Debian's supercollider 3.6.6~repack-2-1build1 (see previous comment)
- removed the jackd stuff from Sonic Pi
- changed the [scsynth call in Sonic Pi](https://github.com/samaaron/sonic-pi/blob/a33adc69a9cce0486270c7780f34449cfd549bb1/app/server/sonicpi/lib/sonicpi/scsynthexternal.rb#L255) to a default `boot_and_wait("scsynth", "-u", @port.to_s)`, leaving everything but the port number to default values, including the portaudio soundcard setting
- Sonic Pi starts fine
- the scsynth called from within Sonic Pi reports this:
      ```
Found 0 LADSPA plugins
ALSA lib pcm_dsnoop.c:614:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
*** ERROR: open directory failed '/home/hanno/.local/share/SuperCollider/synthdefs'

Device options:
  - ALSA : HDA Intel PCH: CX20642 Alt Analog (hw:0,2)   (device #0 with 2 ins 0 outs)
  - ALSA : pulse   (device #1 with 32 ins 32 outs)
  - ALSA : default   (device #2 with 32 ins 32 outs)

Booting with:
  In: ALSA : default 
  Out: ALSA : default 
  Sample rate: 44100.000
  Latency (in/out): 0.009 / 0.010 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Zeroconf: registered service 'SuperCollider'
      ```
- Sonic Pi seems to play music
- but no sound
- there's an occasional `ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred` error message coming from the jackless scsynth in the logs while doing this

**Comment by danstowell** [comment] 2015-12-03 13:45
I've no real clues here, but if you want to investigate the issue I would try killing pulseaudio entirely - just as a test - so that all you have left is alsa, and see if scsynth can make sound. Remember that it's difficult to kill pulse because it tends to jump back to life.

(Also, of course you should try setting `s.options.device` to try the different devices you have available.)

The audio drivers for scsynth were written *long* before pulse was common. I personally don't have a clue how portaudio and pulse interact.

**Comment by hzulla** [comment] 2015-12-03 14:14
Tried without pulseaudio, wouldn't work.
Audacity seems to use portaudio as well and it works on the same system.
Seems to be something wrong with the portaudio driver of scsynth.

**Comment by hzulla** [comment] 2015-12-03 14:49
I'm not familiar with scsynth, only use it through Sonic Pi as a client.

Can you give me a brief guide how I can test if scsynth is running correctly and play one test sound from the command line?

**Comment by danstowell** [comment] 2015-12-03 15:06
Well the easiest way is through command-line sclang. You can invoke

      sclang

and then in the command-line interface run these, line-by-line:

      s.boot
      x = {PinkNoise.ar(0.1)}.play
      x.free

After `s.boot` the server's output will appear in the terminal.

**Comment by hzulla** [comment] 2015-12-03 21:58
Thanks. So far no luck, but I will keep on trying. :-)

Do I read it right that Portaudio is the default audio APi used by scsynth on Windows? And the code works fine on Windows? I wonder why the same code won't work when using it on Linux...

**Comment by danstowell** [comment] 2015-12-03 22:24
Look, portaudio is indeed used on windows but "the same code won't work when using it on Linux" is a false generalisation and please don't say it. Much earlier on in this thread (2nd Oct) I tried it myself and reported back my success. I just re-tried it now: I simply built SC with that single flag changed, and my code example (just above) works. I'm using Ubuntu Studio 14.04.3 on x86_64. I let portaudio choose its default driver and it says

```
Booting with:
  In: ALSA : default 
  Out: ALSA : default 
  Sample rate: 44100.000
  Latency (in/out): 0.009 / 0.010 sec
```

So I'm afraid you need to work out what's going on before blaming supercollider. I very much suspect the fault is somewhere in your own system's audio infrastructure configuration, simply because if you're not using jack then linux's audio infrastructure is a weird mess of interacting things (portaudio, pulse, etc etc)

**Comment by hzulla** [comment] 2015-12-04 06:03
Sorry, I didn't mean to blame Supercollider. I rather suspected Pulseaudio as the reason. :-) Let's see, and thanks that you just tried it yourself.

**Comment by hzulla** [comment] 2015-12-08 08:56
I have now tried on three different systems running Ubuntu and couldn't make the portaudio driver (of 3.6.6~repack-2-1build1) work. I'm not blaming SuperCollider, don't get me wrong, I just wanted to say: If the same driver works fine on Windows, there shouldn't be much missing to make it work on (my version of) Linux, too. So it's worth investigating if there are some edge cases on Linux that don't affect portaudio on Windows. Will debug and try to submit a patch for this some time later. Thanks!

**Comment by telephon** [comment] 2015-12-10 16:11
Thanks for looking into it!

**Comment by hzulla** [comment] 2016-02-17 14:08
Well, so far I only found out that portaudio works when connecting to the ALSA hardware directly. As soon as portaudio connects to the ALSA "default" device instead of the "hw:0,0", sound will stutter.

Worse, when using the pulseaudio ALSA driver as required on a standard Ubuntu desktop, it won't play anything.

```
sc3> s.options.device="pulse"
sc3> s.boot

Device options:
  - ALSA : HDA Intel PCH: CX20642 Alt Analog (hw:0,2)   (device #0 with 2 ins 0 outs)
  - ALSA : pulse   (device #1 with 32 ins 32 outs)
  - ALSA : default   (device #2 with 32 ins 32 outs)

Booting with:
  In: ALSA : pulse 
  Out: ALSA : pulse 
  Sample rate: 44100.000
  Latency (in/out): 0.009 / 0.010 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Receiving notification messages from server localhost
Shared memory server interface initialized
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred

sc3> x = {PinkNoise.ar(0.1)}.play

ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred

sc3> x.free
```

So it connects to the PulseAudio ALSA driver, but it's not clear why it remains silent.

Will debug.

**Comment by hzulla** [comment] 2016-04-01 10:22
Ha. Do you remember how I complained that scsynth remains silent on my machine using PortAudio? Turns out the reason was that PulseAudio's mixer allows muting per app and it remembered this setting. Yes, I had scsynth muted.

Now I feel dumb.

Anyway, please review my #1943 patch for a minor simplification of the PortAudio driver and see the #1944 issue, requesting help with debugging.
