### ISSUE TITLE
MIDI in/out deadlock in Windows

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1046] opened 2014-03-04 08:41 UTC
It's fairly easy to deadlock the interpreter in Windows under these conditions:

- MIDIIn is connected.
- A task, routine or pattern is sending to a MIDIOut.
- A high volume of messages are coming in.

It seems that an incoming message tries to take a lock (likely within PortMIDI), while at the same time the outgoing message has a lock.

Unfortunately, I'm not optimistic for a fix, as this reminds me of pure data's warning that "midi input is dangerous in Windows." But we should have an issue report anyway.

To reproduce the issue:

1. Run the code below. Numbers should start printing in the post window. At this point, you can bang on the MIDI keyboard to send lots of note on/off messages into SC, but you (probably?) won't be able to break it.

2. Then run `MIDIIn.connectAll` and bang on the keyboard some more. SC will probably lock up within 30 seconds.

Test code:

    (
    MIDIClient.init;
    
    // note, edit to specify a real device in your system!
    m = MIDIOut.newByName("MK-361C USB MIDI keyboard", "MK-361C USB MIDI keyboard");
    
    Tdef(\o, {
    	loop {
    		m.control(0, 7, 128.rand.postln);
    		0.25.wait;
    	}
    }).play;
    )

**Comment by llloret** [comment] 2016-05-01 19:46
I have started having a look at this, and I can indeed reproduce it using the snippet that @jamshark70 posted.

I also believe that the problem is a deadlock in the MIDI handling code, and I think it is inside the SC_PortMIDI.cpp and the interpreter.

This is what I see when running it, and the deadlock shows:

In SC_PortMidi.cpp, PMProcessMidi (this is called periodically, because of the Pt_Start call).
```
static void PMProcessMidi(PtTimestamp timestamp, void *userData)
{
	lock_guard<SC_Lock> mulo(gPmStreamMutex);
	PmEvent buffer; /* just one message at a time */

	for( int i = 0 ; i < gNumMIDIInPorts; ++i ) {
		PmStream* midi_in = gMIDIInStreams[i];
		if( midi_in ) {
			while(const PmError result = Pm_Poll(midi_in)) {
				if (result != pmGotData) {
					std::printf("errrr %s\n", Pm_GetErrorText(result));
					continue;
				}

				long Tstatus, data1, data2;
				if (Pm_Read(midi_in, &buffer, 1) == pmBufferOverflow) 
					continue;
				// unless there was overflow, we should have a message now 

				Tstatus = Pm_MessageStatus(buffer.message);
				data1 = Pm_MessageData1(buffer.message);
				data2 = Pm_MessageData2(buffer.message);

				// +---------------------------------------------+
				// | Lock the interp. mutex and dispatch message |
				// +---------------------------------------------+
                gLangMutex.lock();      <---  The thread is here
				if (compiledOK) 
				{
					VMGlobals *g = gMainVMGlobals;
...
...
```

And then in prSendMIDIOut:
```
int prSendMIDIOut(struct VMGlobals *g, int numArgsPushed)
{
	lock_guard<SC_Lock> mulo(gPmStreamMutex);  <--- Trying to acquire this lock
	//port, uid, len, hiStatus, loStatus, a, b, latency
	//PyrSlot *m = g->sp - 8;
	PyrSlot *p = g->sp - 7;
...
...
```

**So, probably the interpreter is blocked because the prSendMIDIOut cannot obtain the MIDI lock, but the MIDI lock will not be released after being taken in PMProcessMIDI, because it is waiting on the interpreter lock itself.**

Any ideas? I don't know too much about the interpreter.

**Comment by llloret** [comment] 2016-05-02 15:20
I think this is fixed by the commit I have just pushed into PR #2009.

@jamshark70, any chance that you could give it a try?

**Comment by jamshark70** [comment] 2016-05-02 15:32
If somebody makes a 32-bit build for me, I can try.

Unfortunately I have rather severe demands on my time lately and there's no way I can set up a build environment in any sort of timely fashion. Happy to test a build, not happy to make one.

**Comment by bagong** [comment] 2016-05-02 15:40
@llloret : I am currently going through the sc3-plugins step by step. Looks very good so far. One error I get is:

*** ERROR: API Version Mismatch: C:\Users\Rainer\AppData\Local\SuperCollider\Extensions\SC3plugins\Greyhole.scx
*** ERROR: API Version Mismatch: C:\Users\Rainer\AppData\Local\SuperCollider\Extensions\SC3plugins\JPverb.scx

This might somehow be Faust related.

I am having your MIDI PR as well, but it might take a day before I can test it. I suggest that we keep this workflow that I test your stuff for now, and once you decide it's done, I will provide both a VS 64-bit and a 32-bit MinGW test build in the hope that this will get some exposure before 3.7.2. @jamshark70 , at that point it would be great if you looked into it critically. I'd be particularly grateful if you also tried it on Windows XP, as it seems that not only it works there, but that the old, un-understood bugs are gone! 3.7 would be the final version to support XP, but with Louis' fixes now working better on Windows than any previous SC version.

**Comment by llloret** [comment] 2016-06-08 13:56
This should be working on 3.7.2.

**Comment by bagong** [comment] 2016-06-08 19:30
Thanks!

**Closed by bagong** 2016-06-08 19:30 UTC
Labels: bug, comp: sclang, os: Windows
