### ISSUE TITLE
interpreter crashes when cmd+q with gui window in front

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#4172] opened 2018-11-25 10:16 UTC
Environment
-----------

* Your SuperCollider version: 3.10.0-rc1
* Your operating system and version: macos 10.12.6

no extensions installed.

Steps to reproduce (for bugs)
-----------------------------

* start the app
* press cmd+m
* press cmd+q

= "Interpreter has crashed or stopped forcefully. [Exit code: 11]"

same thing with for example the scope...

* start the app
* `s.scope`
* cmd+q

and any other gui window it seems...

* start the ap
* `w= Window.new.front`
* select 'Quit SuperCollider' from the menubar

**Comment by snappizz** [comment] 2018-11-25 19:12
cmd+q closes applications in macOS. what is the expected behavior?

**Comment by redFrik** [comment] 2018-11-25 19:37
this is different from previous scide versions.  there cmd+q did nothing when a gui window was in front; which was actually a good thing so to not accidentally stop the sound.

this new behaviour can result in a lot of trouble (specially for beginners).  try this...
`s.boot`
`Pbind().play`
`s.meter`
press cmd+q
now sclang 'crashes' and you probably get a hanging note (scsynth still running)
only way is to restart scide and run `Server.killAll`

if you *don't* have a gui window in front and press cmd+q you either get a dialog asking you to save the document, or sclang+scsynth quits in a controlled manner.  no risk of hanging notes.

**Comment by snappizz** [comment] 2018-11-25 19:55
i mean, if you hit cmd+q, applications close. and if you're aware that scide and sclang are separate applications, it's not particularly unexpected behavior. you're free to disagree, but i don't necessarily think the old behavior is better than the new here.

however, i have been kicking around the idea of "performance mode" in my head where potentially dangerous actions in sclang and scide (quitting IDE, quitting server, CmdPeriod, etc.) are disabled to minimize the chances of accidentally ruining a live set. under the hood, that would entail allowing sclang users to disable cmd+q.

**Comment by redFrik** [comment] 2018-11-25 20:02
this new cmd+q feature is bad and i strongly disagree with adding it.
if you cmd+q or select quit from the menu it should...
1. not say error and that it crashed
2. it should stop scsynth and not force users to forcefully kill scsynth
most logical to me is to keep the old behaviour i.e. cmd+q was disabled when gui windows was in front.

**Comment by dyfer** [comment] 2018-11-25 21:02
The issue here is that interpreter _crashes_ on cmd+q.
We can discuss whether any action should be taken or not on cmd+q, but it definitely should not crash. IMO cmd+q should not do anything though.

**Comment by snappizz** [comment] 2018-11-25 21:47
that makes sense. sorry for misinterpreting.

**Comment by brianlheim** [comment] 2019-02-16 12:15
Duplicate of #3824.

**Closed by brianlheim** 2019-02-16 12:15 UTC
Labels: bug, comp: sclang
