### ISSUE TITLE
scdoc - can't run code from help window.

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1385] opened 2015-03-28 19:40 UTC
I think I mentioned this already somewhere: When selecting code in a help window and doing cmd-return the ide executes the code selected in the current open document.  Doing a right-click on selected code in the help window and selecting the option to run the code works.

Is this a known issue ?

**Comment by bagong** [comment] 2015-04-03 10:34
I wasn't aware of this, but I can confirm (OSX10.10/Qt5). Also shift-return works in the help window. Looks like a bug to me.

**Comment by scztt** [comment] 2015-04-12 18:33
Normally we catch that kind of keyboard shortcut by installing an eventFilter that catches QEvent::ShortcutOverride - that should allow us to short-circuit any existing shortcuts. However, for some reason Cmd+Return doesn't cause QEvent::ShortcutOverride events to be fired.... all other keyboard shortcuts do. This may be a Qt bug? This is a serious workflow blocker, so I think it's worth a hacky fix until we can figure out the Qt bug / another solutions. 

The easiest might be to detect when the help viewer gains / loses focus, and in those cases disable/enable the global cmd+return action as appropriate - unless anyone else has any ideas?

**Comment by gusano** [comment] 2015-06-09 22:34
Works on (arch) linux with a build from today (b305a24).
Could anyone test that on Windows?

**Comment by bagong** [comment] 2015-06-10 07:24
SCDoc is currently broken on Windows, a temporary side effect of a fix of the IPC problem that is in the pipe... I'll test it as soon as it works again...

**Comment by scztt** [comment] 2015-06-28 18:26
The fix for this is fairly involved. And, this was a bug in 3.6, so at least people are used to it. Anyone protest if I kick this forward?

**Comment by bagong** [comment] 2015-06-28 18:35
Hei, forgot about this. Just tried, it works as expected in Windows! So it's just OS X where it's broken...

**Comment by miczac** [comment] 2015-06-28 18:53
I just cross-checked: in 3.6.6 I select the code to be evaluated and hit cmd-enter, code is being executed. 
In 3.7a1 I select the code in the help window, hit cmd-enter which then evaluates code in the editor window (while the help window still's got the focus). If something is selected in the editor this portion gets evaluated or if the doc is empty it's just linefeed is executed.
What bug in 3.6.6 you are referring to, Scott?

**Comment by scztt** [comment] 2015-06-28 19:26
@miczac - Ah! So this must have snuck in with qt5. Damn, maybe we do need to fix....

Here's a proposal for a fix, if anyone wants to attempt it... connect the application-level Cmd+Return action (search for EvaluateRegion or editor-eval-smart) to a function on MainWindow that detects whether a code editor or the helpview has focus, and redirects to the appropriate HelpBrowser::evaluateSelection or ScCodeEditor::evaluateRegion as is appropriate.

**Comment by telephon** [comment] 2015-09-13 20:06
I set the milestone to 3.7.0, because I think it is a big problems for workshops and beginners. If it is hard to fix, we can move to 3.7.x

**Comment by telephon** [comment] 2015-09-13 20:10
Connected: hitting ````shift-enter```` , the interpreter gets sent a wrong string, e.g.:

````
ERROR: syntax error, unexpected INTEGER, expecting ELLIPSIS
  in file 'selected text'
  line 2 char 1:

  0; SinOsc.ar(LastValue.ar(freq, 20), 0, 0.2) }.play; 
  ^
-----------------------------------
ERROR: Command line parse failed
-> nil
````

This comes from a wrong linebreak, copy and paste returns this:

````
d = { arg freq=44
0; SinOsc.ar(LastValue.ar(freq, 20), 0, 0.2) }.play;
````

**Comment by adcxyz** [comment] 2015-09-14 11:51
more tests - on my pretty current build and OSX 10.10.5, 
normal code doc: 
   shift-return, cmd-return, alt-return evaluate code
help window:  
  shift-return works, 
  alt-return clears the line in the help window, 
  cmd-return evaluates selected code in code window
TextViews like :
```TextView().front.string_("1 + 2");```
  shift-return works, 
  cmd-return works 
  alt-return does nothing

So telling people to use shift-return seems to be a good option for now, 
but still the others should be more consistent across all three forms.

**Comment by telephon** [comment] 2015-09-14 13:25
Actually it is very interesting that *shift return works* (which will just run the selection or the line), but cmd-return not. This means that one can probably adjust the code from the one to the other.

**Comment by telephon** [comment] 2015-09-14 13:40
As it seems, the help browser has only an  ````evaluateSelection()```` function implemented, but no corresponding ````evaluateRegion()```` (as defined in sc_editor.cpp). The help browser is programmed in java script, so that in order for it to work here, we need to re-implement region finding in javascript. 

**Note**

I always found it would have been better if the standard code window were a ````QTextDocument````, in rich text, and we could open help pages here, and even html web pages. We could skip the help widget and have one window less.

**Comment by miczac** [comment] 2015-09-14 14:34
@adcxyz what's your editor settings regarding evaluation of code?
mine is *cmd-return*
so, on 10.8.5 / latest build [b3ef8f6] here your tests would look like this:

normal code doc:
*shift-return* inserts line break at the current cursor position
*cmd-return* evaluates selected code or line
*alt-return* inserts line break and indent at the current cursor position

help window:
*shift-return* inserts line break at current cursor position
*alt-return* clears the line in the help window if selected or does nothing if not
*cmd-return* evaluates selected code in code window or the current region

TextViews like : TextView().front.string_("1 + 2");
*shift-return* works,
*cmd-return* works
*alt-return* does nothing

**Comment by adcxyz** [comment] 2015-09-14 16:11
hi, 

> On 14/09/2015, at 16:34 , Michael Zacherl <notifications@github.com> wrote:
> 
> @adcxyz <https://github.com/adcxyz> what's your editor settings regarding evaluation of code?
> 
in sc prefs, I have 
shift-return -> evaluate current selection/line
cmd-return ->  evaluate current selection/line or region
alt-return is not assigned to anything.

**Comment by telephon** [comment] 2015-09-14 17:19
@miczac The problem (if I am correct) was introduced with a new QT version – if you are on OSX 10.8, you may not have that?

````cmd-return evaluates selected code or line````should be: ````cmd-return evaluates selected code or line, or region```` – is it?

**Comment by adcxyz** [comment] 2015-09-14 20:19
> On 14/09/2015, at 19:19 , Julian Rohrhuber <notifications@github.com> wrote:
> 
> @miczac <https://github.com/miczac> The problem (if I am correct) was introduced with a new QT version – if you are on OSX 10.8, you may not have that?
> 
> cmd-return evaluates selected code or lineshould be: cmd-return evaluates selected code or line, or region – is it?
> 
strangelythe two are different: 
cmd-return evaluates selected code or line, or region 

shift-return evaluates selected code or line

**Comment by telephon** [comment] 2015-09-14 21:08
>strangelythe two are different: cmd-return evaluates selected code or line, or region 
>
> shift-return evaluates selected code or line

Yes, as far as I know, this is intended behaviour (though a little over-complicated). If ````cmd-return```` were working for both help and editor, I'd say skip the other. It may be useful if you want to evaluate lines in a region without selection.

But the scheme is *a little bit* broken anyhow, because you can't have nested regions (which was very common practice in sc3.5).

**Comment by adcxyz** [comment] 2015-09-14 21:13
actually I find the automatic region evaluation in help docs rather annoying at times, 
because it somehow infers what I want to evaulate, and code in helpfiles is often 
not formatted according to region-recognition by the IDE’s logic for that. 

maybe that is why I got used to using shift-return.

**Comment by telephon** [comment] 2015-09-15 17:06
````cmd-return```` has a big advantage: you don't have to do anything preparatory to run the code you are just editing. With a document organized in regions, it seems much better than the "old" behavior.

But whatever: code in the help files should behave like code in the editor. The closer, the better.

**Comment by telephon** [comment] 2015-09-30 18:06
OK, so here is a possible simplification. I'm opening a new issue.

**Comment by telephon** [comment] 2015-09-30 18:12
For clarity, I've moved the issue: #1676.

**Closed by telephon** 2015-09-30 18:12 UTC
Labels: bug, comp: help, comp: SCDoc, env: Qt IDE, os: Mac OS X
