### ISSUE TITLE
When we close the Help menu, the next time SuperCollider is loaded it is open but empty

### ISSUE THREAD

**Issue by bernardgeyer** [supercollider/supercollider#3758] opened 2018-06-04 16:55 UTC
This is not the case when the help menu was docked and we select the “close” widget. 
This bug and the previous one are clearly related, it happens only on Mac OS X on versions after 3.6

**Comment by patrickdupuis** [comment] 2018-06-04 17:15
Possible duplicate of #908?

**Comment by bernardgeyer** [comment] 2018-06-04 20:37
Yes, effectively. Should I delete it here ?  I'm convinced that the previous issue I sent is related, both happened only since 3.7

**Comment by patrickdupuis** [comment] 2018-06-04 22:21
You should contribute to that issue thread. I'll close this one.

**Closed by patrickdupuis** 2018-06-04 22:21 UTC

**Comment by jamshark70** [comment] 2018-06-04 22:50
Also, I just posted at 908: "See also #3660 and a more complete problem description at #3287. It might be fixed in 3.10."
