### ISSUE TITLE
Server loses SHM after computer sleep

### ISSUE THREAD

**Issue by jpburstrom** [supercollider/supercollider#774] opened 2013-03-15 09:12 UTC
When I leave the server running while computer is sleeping, the server seems to lose its SHM interface:

s = Server.local.boot;
s.hasShmInterface; // true
//Put the computer to sleep, and wake it up again, leaving the server running
s.hasShmInterface;  // false
s.reboot;
s.hasShmInterface; // true

I'm on a MacBook running OSX 10.6.8.

**Comment by scztt** [comment] 2015-03-15 01:10
I think this should be at least looked at. I completely disagree that it's acceptable that the server would crash / fail in a sleep case.... plenty of audio applications behave just fine after sleeping. I'll poke around and see if I can at least improve things slightly.

**Comment by telephon** [comment] 2015-06-14 18:11
Just for reference, the problem is that ````thisProcess.platform.isSleeping```` returns true even though it is sleeping.

**Comment by telephon** [comment] 2015-06-14 18:14
So if there is a reliable way to tell if the OS is sleeping on all platforms, this would solve the issue.

**Comment by telephon** [comment] 2015-06-14 18:46
So here is a little bit more complete description of the problem.

Currently, the shared memory interface is explicitly released in ````Server.serverRunning_```` which is called regularly in sclang to see if the server application is still up and fine. When setting the computer to sleep, the task that does this runs much longer than the server is responsive (on OS X 10.10, the task runs 24 s into the sleep mode). Normally, the grace time (````reallyDeadCount````) should catch this, but would need to be excessively long (around 30 s).

What is really missing is a reliable way to know:
1. whether the server is running (this might be untraceable in some conditions of course)
2. whether the system has been set to sleep.

If this can't be done until 3.7, we should think of a band-aid of some sort. I am not qualified to say which is acceptable:

1. just leave the ShmInterface open, even when the server has crashed, and don't notify of the crash. Basically ignore that state. Manually ````reboot```` will do those notifications.
2. Extend the grace time to 30 s. You will know only then that the server has crashed. But if you load buffers that take longer than that to read, the server will have the same (wrong) behavior, and disconnect the shared memory interface.

Actually, as we can't be 100% sure if a non-responsive program is dead or just working really really hard (the halting problem, essentially), it may be much cleaner to mark the server as ```non-responsive```(yellow), letting the user decide whether to reboot it explicitly or not. This seems to be the way it is done in operating systems. Additionally, there may be a way to check if the app has really crashed, and then properly clean up.

Opinions?

**Comment by telephon** [comment] 2015-06-14 20:49
Here is a quick first implementation, without GUI yet:
https://github.com/supercollider/supercollider/tree/topic/unresponsive-server

**Comment by vivid-synth** [comment] 2016-11-18 15:16
Pleasantly surprised to see the server not die on sleep in a recent build! Was it @telephon 's work that fixed it? I'm running without sclang or IDE at all, and I don't see any server changes in that PR...

**Comment by telephon** [comment] 2016-11-18 19:52
yes, I fixed this. It isn't connected to the IDE, it was the sclang implementation of the SHM interface which didn't take sleep into account.

**Comment by vivid-synth** [comment] 2016-11-18 20:08
Awesome, thanks @telephon !

**Closed by vivid-synth** 2016-11-18 20:08 UTC
Labels: bug, comp: scsynth, crash, fix proposed
