### ISSUE TITLE
scsynth OSC packet size in NRT mode

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#61] opened 2012-05-06 05:45 UTC
[Issue migrated from SourceForge | ID: 1970340 | Submitted by 'sciss']
[http://sourceforge.net/support/tracker.php?aid=1970340]

scsynth's OSC packet size differs from realtime and NRT mode, in realtime i think it's 64K(?) and in NRT just 8K(?). that produces problems in porting realtime code to NRT equivalents, particularly with using /d_recv to transfer synthdefs. The packet size should be increased in NRT to match the realtime size.

**Comment by scztt** [comment] 2015-04-17 02:45
Someone want to look and see if this is an easy issue (meaning - changing a constant somewhere :) ) to fix for 3.7?

**Comment by davidgranstrom** [comment] 2015-05-28 17:42
Maybe this issue is obsolete now since #714 was merged?

**Comment by vivid-synth** [comment] 2016-05-05 22:21
Yup, this looks like a duplicate of https://github.com/supercollider/supercollider/issues/714

**Comment by vivid-synth** [comment] 2016-08-01 18:36
As this looks like a duplicate of https://github.com/supercollider/supercollider/issues/714 , can we close?

**Closed** 2016-08-01 22:40 UTC
Labels: bug, retest
