### ISSUE TITLE
Scheduling based on audio hardware clock

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#280] opened 2012-05-06 17:39 UTC
[Issue migrated from SourceForge | ID: 2829289 | Submitted by 'sciss']
[http://sourceforge.net/support/tracker.php?aid=2829289]

The OSC protocol defines bundle times in terms of an Internet NTP timestamp, however without giving details of implementation, and addressing the real world issue of different computer clocks running independantly. A bigger problem is that audio is computed based on the sample rate and sample clock of some audio hardware. This sample clock again is independant of the CPU clock.

Currently, scsynth relates OSC bundle times to the CPU clock. This implies that when audio is computed, CPU clock state needs to be translated to audio clock state, resulting in extra jitter. For example, in the current implementation it is impossible to schedule two bundles appart and achieve a delay of an exact number of samples. This is a very sad situation, and I believe that in 99t% of the cases the user will want all scheduling based on the audio clock instead of the (CPU) SystemClock. This can be seen for example by the existance of the OffsetOut UGen that in the current scheduling model is completely useless, as it does not guarantee sample accuracy at all.

There have been some hacking attempts by blackrain, making special scheduling UGens that translate forth and back between CPU and audio time, but the only real solution is to add an option to run scsynth with OSC bundles measured against audio clock. This implies that on the client side (sclang) a corresponding AudioClock class is created, so that logical time on the client and on the server side are in sync. The disadvantage is that sclang will need to deal with the audio driver layer. However, looking at Meta_ServerOptions:devices, it already connects to this layer.

This topic has been discussed a couple of times, the last time here: http://www.listarc.bham.ac.uk/lists/sc-users/msg47465.html

**Comment by vivid-synth** [comment] 2016-08-03 04:34
Supernova does this, right?

**Comment by LFSaw** [comment] 2017-07-06 21:46
duplicate of the (newer, more elaborate) #2939

**Closed by LFSaw** 2017-07-06 21:46 UTC
Labels: comp: scsynth, enhancement
