### ISSUE TITLE
SCIDE is stuck. All I can see is "Sending request..." where dots at the end keep changing quantity.

### ISSUE THREAD

**Issue by kasravi** [supercollider/supercollider#4135] opened 2018-10-23 12:10 UTC
So I know there is a problem with my environment, As this had never happened anywhere before and I have tried bunch of previous versions as well as cutting edge nightly builds and the problem is consistent and also nobody is getting this error. I need to figure out what is the problem with my system.

I'm running Windows 10 64-bit, recently updated on a 2.7 Core-i5 6400 and 8 GB of RAM.

The problem always existed from the freshest installation on this machine, so no extension or quarks is involved. when I open scide I can see the class library is being compiled, and I can see the *** welcome ... message. however the help browser is blank with "Sending request" message moving. I can type and execute lines in the document panel but nothing would happen. I cannot start the server nor with s.boot or ctrl-B. So I guess it is not responsive. when I try to close the window it closes but when I look at the processes sometimes sclang.exe and sometimes scide.exe is still there and I need to end task them.

what I have tried:
I tried to close the help panel and restart.
I tried to run scsynth alone -> seems successful
I tried to run sclang alone -> seems successful. it lets me write although I can not execute anything 
I tried compatibility modes and running as administrator on each.
I tried previous versions randomly from 3.7 till 3.10.
I checked the firewall and check everything related to scsynth and sclang.
I checked the code a bit and it seems that something is going wrong on a line like this `Main::scProcess()->evaluateCode( code, true );` but I have no idea what next.
I tried to check if it is successfully opening port with `netstat -b` but nothing is shown there. I might be wrong to even check there but still, I'm out of ideas.

Where should I check next?

**Comment by brianlheim** [comment] 2018-10-23 15:07
Duplicate of issues in #1390 and #908. Other people are getting this behavior, it's been reported here and on the mailing list. Sorry, but this is a known issue and there is currently no fix in progress. If you would like to help I can point you in the right direction; both of the linked threads also contain more relevant information.

**Closed by brianlheim** 2018-10-23 15:07 UTC

**Comment by kasravi** [comment] 2018-10-26 08:15
I had seen those two threads but they were seeing it occasionally, problem is I cannot use it at all. This is why I opened another.
>  If you would like to help ...

Of course. Do you have any idea about the source of problem? Even if you (or anyone) can only guess. I no longer have a place to look at. Any help is appreciated.

**Comment by yavuzburuk** [comment] 2019-02-16 08:43
Hello Kasravi,

Have you found a solution to this problem? I am facing the same problem and no matter what I do, the IDE doesn't function.

**Comment by kasravi** [comment] 2019-02-16 12:39
Hey yavuzburuk
No I didn't find an answer. I'd upgraded my pc so I cannot reproduce the bug to find the cause either
