### ISSUE TITLE
syntax error in documentation example (or parser bug?)

### ISSUE THREAD

**Issue by Aeva** [supercollider/supercollider#5367] opened 2021-02-21 03:50 UTC
## Environment

* SuperCollider version: `SuperCollider 3.11.2 Built from branch 'HEAD' [9a34118]` (the current Windows 64bit release downloaded from the webpage)
* Operating system: Windows 10
* Other details (Qt version, audio driver, etc.):  A USB midi controller is connected to the computer.

## Steps to reproduce

Literally copy and paste the midi input example from [the docs](https://doc.sccode.org/Guides/UsingMIDI.html), and attempt to run it via `Evaluate File`:

```
s.boot;

(
var notes, on, off;

MIDIClient.init;
MIDIIn.connectAll;

notes = Array.newClear(128);    // array has one slot per possible MIDI note

on = MIDIFunc.noteOn({ |veloc, num, chan, src|
    notes[num] = Synth(\default, [\freq, num.midicps,
        \amp, veloc * 0.00315]);
});

off = MIDIFunc.noteOff({ |veloc, num, chan, src|
    notes[num].release;
});

q = { on.free; off.free; };
)

// when done:
q.value;
```

## Expected vs. actual behavior

**Expected behavior**
Documentation example contains valid code that runs to learn from.  I'm unfamiliar with the language, and just want to try out something fun before diving in.

**Actual behavior**
```
ERROR: syntax error, unexpected VAR, expecting ')'
  in interpreted text
  line 4 char 3:

  var notes, on, off;
  ^^^
```

**Comment by Aeva** [comment] 2021-02-21 04:30
Huh, running it via ctrl-enter works fine for some reason?

**Comment by jamshark70** [comment] 2021-02-21 04:58
Not a bug.

There are 3 blocks here.

1. `s.boot` -- run this and wait for it to complete, *then* move on to...
2. The parenthesized block.
3. After you've heard enough, `q.value` to clean up.

Running this example all at once by evaluate file *should not* work, in fact.

Admittedly this is a tricky point in learning SC. But this convention of separate code blocks to run in sequence is common throughout the documentation.

As this is a usage question, I'll close this. Feel free to raise further questions at scsynth.org.

**Closed by jamshark70** 2021-02-21 04:58 UTC
Labels: bug
