### ISSUE TITLE
help search misses results

### ISSUE THREAD

**Issue by aspiers** [supercollider/supercollider#3578] opened 2018-03-15 12:20 UTC
If I search the help for `classvar`, `Writing Classes` is not shown as a match despite that being the only place I can find where `classvar` is really explained.

**Comment by telephon** [comment] 2018-03-15 15:06
yes, it is unfortunately not a full text search. I'm often tricked by this.

**Comment by brianlheim** [comment] 2018-03-16 14:29
This is a dupe of #3030.

**Closed by brianlheim** 2018-03-16 14:29 UTC

**Comment by aspiers** [comment] 2018-03-16 15:39
Oops missed that, sorry for the noise!
