### ISSUE TITLE
Built crach on debian 

### ISSUE THREAD

**Issue by Axxon** [supercollider/supercollider#1082] opened 2014-04-13 17:44 UTC
Hello, here my crash i think the problem come from qt4-qmake. 

-- SuperCollide Version: 3.7alpha0
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- building boost libraries manually
-- using fftw3f
-- Found jack: /usr/lib/x86_64-linux-gnu/libjack.so
-- Audio API: jack
-- Found GNU Readline version 6.2: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.2", required is "4.7") 
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.2", required is "4.7") 
-- Compiling with Readline support
-- Compiling with ALSA midi support
-- Building the Qt IDE
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.2", required is "4.7") 
-- Building with Sced for gedit 3 (UNIX)
-- Will copy HelpSource to /usr/local/share/SuperCollider
-- Configuring done
-- Generating done
-- Build files have been written to: /home/axxon/SoftSrc/supercollider/build
 version

Here the complete crash return message:

https://gist.github.com/Axxon/10625285

Thanks for help, best regard.

**Comment by scztt** [comment] 2015-04-19 17:01
Oops, this is not a crash after all - moving this to future and keeping it open pending discussion.

**Comment by vivid-synth** [comment] 2016-08-16 23:44
This is about a build crash that's quite old now, and builds are working fine. Close?

**Comment by danstowell** [comment] 2016-08-17 07:08
Yes thanks. I'm afraid the problem seems to relate to boost which is beyond our current expertise, and also the boost code in question has been updated since so the issue is outdated. @Axxon if you are still (!) able to reproduce the issue then please reopen the issue...

**Closed by danstowell** 2016-08-17 07:08 UTC
Labels: bug, comp: build
