### ISSUE TITLE
2 Errors: "Message 'prSetEdited' not understood." & "Message 'closed' not understood."

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6119] opened 2023-10-24 10:06 UTC
## Environment

* SuperCollider version: 3.13.0
* Operating system: Windows 11 Pro
* System Locale Language: Korean

## Steps to reproduce

1. Start SuperCollider
2. type something in the IDE editor
3. close the SCD document

## Expected vs. actual behaviour
- Expected:
  - Typing without error messages and warnings.
  - Close without error
- Actual behaviour:
https://www.dropbox.com/scl/fi/izhbkciqc3xmzrvyyndx5/Screen-Recording-2023-10-24-at-18.53.31.mov?rlkey=kfxz4duxbcy0yzlla9sh8awqv&dl=0

Not always, but often.

**Comment by prko** [comment] 2023-10-24 12:20
Selecting "Beta: Use Unicode UTF-8 for worldwide language support" in the following window seems to solve the problem, but it is not certain:

<img width="520" alt="Screenshot 2023-10-24 at 20 43 11" src="https://github.com/supercollider/supercollider/assets/416281/ad42b052-d522-4940-8632-5a7a62296f58">

**Comment by prko** [comment] 2023-10-24 14:42
There are some similar cases:
- https://scsynth.org/t/general-copied-pasted-code-errors/8402/16
- https://scsynth.org/t/ide-throwing-prsetedited-errors/3577
- https://scsynth.org/t/setactivedocbyquuid-error-msg/4596/2

**Comment by prko** [comment] 2023-10-24 23:46
I tested it after changing the system locale to English. However, the same problem persists. So the system locale language does not seem to be causing this problem.

**Comment by SimonDeplat** [comment] 2023-10-25 10:02
This issue is mentioned in several other issues. The deepest discussion about this is #4413 , that proposes a temporarily fix. But we need to keep tracking it.

I'd like to mention that even if I'm on Linux (Ubuntu 22.04), I got affected by the 'broken mirror' warning recently, that seems related, although I didn't pay much attention. It fixed itself somehow, and I can't reproduce it. I think it was after recompiling, and my document history was empty.

**Comment by JordanHendersonMusic** [comment] 2024-05-05 14:03
Closing because this is a duplicate of #4812 and #4413

**Closed by JordanHendersonMusic** 2024-05-05 14:03 UTC
Labels: bug
