### ISSUE TITLE
IDE - collapse lines of code

### ISSUE THREAD

**Issue by paum3** [supercollider/supercollider#2264] opened 2016-08-05 08:22 UTC
Hi.   Due to my (little) experience with sc, it will be helpful and code more readable - to collapse SynthDefs etc.

**Comment by crucialfelix** [comment] 2016-08-09 10:34
The IDE isn't intended to become a full professional level code editor. That would suck up precious developer time that needs to be spent on the core feature (music). It's pretty complicated to do cold folding correctly.

You might be interested in using atom: https://atom.io/packages/supercollider (disclaimer: I wrote that one)

also emacs and vim and sublime text have supercollider packages for them.

With atom you can also navigate by folds and quickly toggle them, auto fold etc. There are quite a few packages for that.

**Comment by brianlheim** [comment] 2017-01-27 15:50
Closing - probably won't implement anytime soon, plus this is a dupe of #731.

**Closed by brianlheim** 2017-01-27 15:50 UTC
Labels: enhancement, env: Qt IDE
