### ISSUE TITLE
gitreports.com submitted bug

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#4307] opened 2019-02-15 05:49 UTC
Submitter: Yavuz Buruk
Email: yavuzburuk@gmail.com
Hello,

I have downloaded and installed SuperCollider 3.10.0 and afterwards 3.9.3 on Windows. I don't get any error message during installation. After I run it, the IDE doesn't function. The Help Browser window says "sending request". I can't do anything at all.

**Comment by snappizz** [comment] 2019-02-15 08:55
closing as duplicate of #4308

**Closed by snappizz** 2019-02-15 08:55 UTC
Labels: bug, gitreports
