### ISSUE TITLE
nil check with empty function crashes interpreter

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#5375] opened 2021-02-26 23:02 UTC
## Environment

* SuperCollider version: 3.11.2
* Operating system: macOS 10.14
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
1 !? {};
```

## Expected vs. actual behavior

Expected: empty function is evaluated (i.e. nothing happens).
Actual: interpreter crashes: `Interpreter has crashed or stopped forcefully. [Exit code: 11]`

**Comment by telephon** [comment] 2021-02-27 08:32
The inlined function is defined here: https://github.com/supercollider/supercollider/blob/0017e14868a5d0bccec2c63eaba1377332e35b63/lang/LangSource/PyrParseNode.cpp#L2341

These look reasonable:

```
{ {} !? 1 }.def.dumpByteCodes

BYTECODES: (7)
  0   04 00    PushLiteralX instance of FunctionDef - closed
  2   64       PushSpecialValue 1
  3   B0       TailCallReturnFromFunction
  4   C2 48    SendSpecialMsg '!?'
  6   F2       BlockReturn
```

```
{}.def.dumpByteCodes
  0   6E       PushSpecialValue nil
  1   F2       BlockReturn
```

**Comment by brianlheim** [comment] 2021-02-27 09:42
duplicate of #4924

**Closed by brianlheim** 2021-02-27 09:42 UTC
Labels: bug, comp: sclang

**Comment by brianlheim** [comment] 2021-02-27 09:44
there is some useful info in that ticket btw, i think this should be relatively straightforward to fix for anyone interested in delving into the interpreter code

**Comment by dyfer** [comment] 2021-02-27 19:21
Ah thanks! I tried to check if this is a duplicated, but I missed that other ticket.
