### ISSUE TITLE
sclang fails to start in background in a script

### ISSUE THREAD

**Issue by dvarrazzo** [supercollider/supercollider#2655] opened 2017-01-17 04:35 UTC
Reproducible with this simple script:

```sh
#!/bin/bash
sclang &
```

running it produces:

```
$ ./test.sh 
pi@raspberrypi:~/hitomi-2017-01 $ terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  assign: Operation not permitted
```

running `sclang &` from command line works as expected.

This was tested on a raspberry pi using master at 72ff009a88cb25b32b8b3b5faf5465af8b329f6f

The issue happens trying to run sclang from a systemd unit. It was [reported here too](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/start-sclang-with-systemctl-td7610429.html)

**Comment by brianlheim** [comment] 2017-01-17 15:54
Thanks! Closing as dupe of #1053.

**Comment by dvarrazzo** [comment] 2017-01-17 23:14
Is there any workaround for the issue?

**Comment by vivid-synth** [comment] 2017-01-17 23:19
I can repro this

**Comment by vivid-synth** [comment] 2017-01-17 23:21
@dvarrazzo there may be a workaround in your particular case - what are you trying to achieve?

**Comment by dvarrazzo** [comment] 2017-01-17 23:35
Just having a sclang script to run in background when a raspberry starts, for an artistic performance. As mentioned the same problem happens when sclang is run by systemd. In particular I've prepared these two scripts:

```
# /etc/systemd/system/jackd.service

[Unit]
Description=Jack Server

[Service]
ExecStart=/usr/local/bin/jackd -P75 -dalsa  -p1024 -n3 -s -r44100

[Install]
WantedBy=multi-user.target
```

```
# /etc/systemd/system/performance.service 

[Unit]
Description=Hitomi January 2017 Performance
Requires=jackd.service

[Service]
ExecStart=/usr/local/bin/sclang /home/pi/hitomi-2017-01/performance.scd

[Install]
WantedBy=multi-user.target
```

you don't need any `.scd` file at all to reproduce the bug. Even removing the script name from the above, trying to run sclang interactively results in:

```
pi@raspberrypi:~/hitomi-2017-01/systemd $ sudo systemctl start performance
pi@raspberrypi:~/hitomi-2017-01/systemd $ sudo systemctl status performance
● performance.service - Hitomi January 2017 Performance
   Loaded: loaded (/etc/systemd/system/performance.service; enabled)
   Active: failed (Result: signal) since Tue 2017-01-17 23:33:54 UTC; 2s ago
  Process: 1144 ExecStart=/usr/local/bin/sclang (code=killed, signal=ABRT)
 Main PID: 1144 (code=killed, signal=ABRT)

Jan 17 23:33:53 raspberrypi systemd[1]: Started Hitomi January 2017 Performance.
Jan 17 23:33:54 raspberrypi sclang[1144]: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
Jan 17 23:33:54 raspberrypi sclang[1144]: what():  assign: Operation not permitted
Jan 17 23:33:54 raspberrypi systemd[1]: performance.service: main process exited, code=killed, status=6/ABRT
Jan 17 23:33:54 raspberrypi systemd[1]: Unit performance.service entered failed state.
```

**Comment by vivid-synth** [comment] 2017-01-17 23:47
@dvarrazzo this definitely is a bug. In the meantime, if you're trying to get something working for an imminent piece, maybe use tmux or screen?:

e.g.:

> $ tmux new-session -d -s my_performance 'sclang foo.scd'

Then, to attach to it:

> $ tmux attach -t my_performance

To detach again , hit ```ctrl-b d```

In screen:

>  $ screen -S my_performance2 -m -d 'sclang'

To attach:

> $ screen -r my_performance

To detach again: ```ctrl-a d```

**Comment by gusano** [comment] 2017-02-20 20:39
This one is really annoying

**Comment by simonvanderveldt** [comment] 2018-03-11 17:46
Has anyone been able to look into this?

It seems real issue is that `sclang` has no proper means of running in the background. It has a `-D Enter daemon mode (no input)` flag, but that doesn't do much apart from not taking input, which is not really what daemon mode means to most people ;)

If it would run as a normal daemon in the background no workarounds with backgrounding via shell scripts would be necessary.

**Comment by yaxu** [comment] 2018-04-02 10:59
I'm also seeing this error, but not when putting it in the background. I want to run sclang via daemontools, so that if sclang crashes, daemontools restarts it. Daemontools runs sclang in the foreground, and runs it again if/when it terminates.

I'm seeing the same error `Operation not permitted terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'   what():  assign: Operation not permitted` etc

So I'm guessing that the problem isn't with running sclang in the background, but running it without a terminal?

**Comment by vivid-synth** [comment] 2018-05-14 03:05
@yaxu does the `tmux`/`screen` kludgy workaround fix it in your case?

**Comment by yaxu** [comment] 2018-05-14 06:41
That wouldn't work with the daemontools approach @vivid-synth.

**Comment by gogobd** [comment] 2018-06-13 08:39
Thanks to @mzero on Slack I got a workaround for this:

#!/bin/bash
echo | sclang &

**Comment by diegodorado** [comment] 2019-06-12 03:56
Is there a less hacky workaround to this? I am not able to start sclang with non-proxy ( from non session manager)

**Comment by snappizz** [comment] 2019-06-12 05:10
@diegodorado hmm, i can't repro this on the latest 3.10 branch on ubuntu, tested both with and without Qt. could you share what version you're using?

**Comment by diegodorado** [comment] 2019-06-12 13:34
> @diegodorado hmm, i can't repro this on the latest 3.10 branch on ubuntu, tested both with and without Qt. could you share what version you're using?

Sorry, my bad. I was running version 3.9
Updated the repo and reinstalled and it worked. Thanx!

**Comment by snappizz** [comment] 2019-06-13 02:59
thanks for the update! glad it's fixed.

**Closed by snappizz** 2019-06-13 02:59 UTC
Labels: bug, comp: sclang, retest
