### ISSUE TITLE
focusColor

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#297] opened 2012-05-06 17:40 UTC
[Issue migrated from SourceForge | ID: 3385815 | Submitted by 'jamshark70']
[http://sourceforge.net/support/tracker.php?aid=3385815]

Crucial library's GUI classes use focusColor throughout, leading to a lot of

QNumberBox: focusColor_ is not implemented yet
QSlider: focusColor_ is not implemented yet

for every NumberEditorGui that gets created (e.g.). Might be worth silencing that warning, and keeping this tracker item open until focusColor is really implemented.

(For that matter, SwingOSC doesn't implement it either, but focusColor_ is a no-op and doesn't clutter the post window.)

Thanks :)

// to reproduce (assumes cruciallib is installed):
NumberEditor.new.gui;

**Comment by JordanHendersonMusic** [comment] 2024-04-24 15:38
Closing because I can't reproduce.
```
NumberEditor.new.gui;
```
prints nothing to post window.

**Closed by JordanHendersonMusic** 2024-04-24 15:38 UTC
Labels: enhancement, comp: Qt GUI
