### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by pluto-bell** [supercollider/supercollider#6259] opened 2024-04-21 03:54 UTC
## Environment

* SuperCollider version: 3.13.0
* Operating system: macOS 14.4.1 
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce
```
cd SuperCollider
mkdir -p build
cd build
cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt5`  ..
cmake --build . --target install --config RelWithDebInfo
```

_**spot of failure**_
```supercollider
plutobell@plutos-computer build % cmake --build . --target install --config RelWithDebInfo
```

## Expected vs. actual behavior
expected: sc build
actual: build failure

Error Messages:
```
The following build commands failed:
	PhaseScriptExecution CMake\ PostBuild\ Rules /Users/plutobell/SuperCollider/build/build/UnpackFFTUGens.build/RelWithDebInfo/Script-957DED8BEED535BDE11472B3.sh (in target 'UnpackFFTUGens' from project 'SuperCollider')
	PhaseScriptExecution CMake\ PostBuild\ Rules /Users/plutobell/SuperCollider/build/build/UnaryOpUGens.build/RelWithDebInfo/Script-D1D5FFFE5B1EB73817D4A4FD.sh (in target 'UnaryOpUGens' from project 'SuperCollider')
(2 failures)
```

**Comment by capital-G** [comment] 2024-05-30 12:57
Seeing that this is a macOS 14 build, it is most likely a duplicate of https://github.com/supercollider/supercollider/issues/6224

What do you think @JordanHendersonMusic  should this be closed therefore?

Or at least we would need more information what went wrong exactly.

**Comment by JordanHendersonMusic** [comment] 2024-05-30 13:16
@pluto-bell the error message isn't actually present in your issue, just which command failed. Could post the entirety of the output... I know it's gonna be huge so perhaps upload it as a gist and link to it?

**Comment by telephon** [comment] 2024-06-26 06:51
please reopen if necessary!

**Closed by telephon** 2024-06-26 06:51 UTC
Labels: bug
