### ISSUE TITLE
IDE enhancement: folding lines  

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3757] opened 2018-06-03 07:50 UTC
Hi,

I remember that there was folding code feature in the windows version of SuperCollider. I cannot find a screenshot, but the following links show it.
https://blog.codepen.io/2015/02/23/code-folding-settings-customize-editor/
https://notepad-plus-plus.org/

I think this feature might be useful when writing a long document...
How do you think about it?

My Memory is faint...
If  I suggested it before already, I'm sorry for the duplicated request, but I cannot find it in the threads.

**Comment by snappizz** [comment] 2018-06-03 07:56
closing as duplicate of #731 and #2264.

**Closed by snappizz** 2018-06-03 07:56 UTC

**Comment by brianlheim** [comment] 2018-06-03 14:36
@prko Please check open issies before submitting a ticket!

**Comment by prko** [comment] 2018-06-03 15:08
sorry for it.
I, of course, checked open issues, but only with the combination of "folding" and "lines".
However, my thought did not reach to search with "collapsible" and "collapse"...
In future, I will check open issues more carefully.

**Comment by telephon** [comment] 2018-06-03 16:38
no problem!
